/**
 * Curated disposable / temporary email domains used to block free-trial abuse.
 * Keep this list focused on well-known throwaway providers; update as needed.
 */
const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "0-mail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "guerrillamail.info",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailinater.com",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempmailo.com",
  "tempail.com",
  "throwaway.email",
  "throwawaymail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "cool.fr.nf",
  "jetable.org",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "trash-mail.com",
  "maildrop.cc",
  "discard.email",
  "discardmail.com",
  "dispostable.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "getnada.com",
  "nada.email",
  "emailondeck.com",
  "mailnesia.com",
  "moakt.com",
  "mohmal.com",
  "mytemp.email",
  "tempinbox.com",
  "tmpmail.net",
  "tmpmail.org",
  "tmpeml.com",
  "mailcatch.com",
  "mailnull.com",
  "spamgourmet.com",
  "spamhole.com",
  "spamex.com",
  "spamobox.com",
  "spamfree24.org",
  "spamfree.eu",
  "mintemail.com",
  "mailscrap.com",
  "getairmail.com",
  "emailfake.com",
  "generator.email",
  "inboxkitten.com",
  "harakirimail.com",
  "mailforspam.com",
  "mailimate.com",
  "meltmail.com",
  "mt2015.com",
  "mt2014.com",
  "thankyou2010.com",
  "trashymail.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "einrot.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.de",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "bugmenot.com",
  "mailtemp.net",
  "tempmailaddress.com",
  "temporary-mail.net",
  "temporarymail.com",
  "tmpbox.net",
  "crazymailing.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emltmp.com",
  "emlpro.com",
  "fakemail.net",
  "incognitomail.org",
  "mailzilla.com",
  "safetymail.info",
  "sogetthis.com",
  "spamherelots.com",
  "thisisnotmyrealemail.com",
  "veryrealemail.com",
  "mailpoof.com",
  "burnermail.io",
  "guerrillamail.biz",
  "pokemail.net",
  "spam4.me",
  "bccto.me",
  "chacuo.net",
  "dropmail.me",
  "emailna.co",
  "fakernet.com",
  "mail-temp.com",
  "tempmail.dev",
  "tempmail.us",
  "1secmail.com",
  "1secmail.org",
  "1secmail.net",
  "wwjmp.com",
  "esiix.com",
  "oosln.com",
  "vddaz.com",
]);

function emailDomain(email: string): string | null {
  const at = email.lastIndexOf("@");
  if (at < 0 || at === email.length - 1) return null;
  return email.slice(at + 1).trim().toLowerCase();
}

/** True when the address uses a known disposable / temporary mail domain. */
export function isDisposableEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  const domain = emailDomain(email);
  if (!domain) return false;
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) return true;
  // Match subdomains of listed providers (e.g. foo.mailinator.com).
  for (const blocked of DISPOSABLE_EMAIL_DOMAINS) {
    if (domain.endsWith(`.${blocked}`)) return true;
  }
  return false;
}
