import type { MemoryCard } from "../types";

/** Static Memory Card library — seed to DB later if needed. */
export const MEMORY_CARDS: MemoryCard[] = [
  // —— NAPLEX / Heart Failure ——
  {
    id: "naplex-hf-four-pillars",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "HFrEF Four Pillars (GDMT)",
    teaser: "Mortality-reducing drug classes every pharmacist must know.",
    kind: "table",
    tags: ["GDMT", "HFrEF", "mortality"],
    body: "Start low, go slow. Diuretics treat congestion but are not a mortality pillar.",
    table: {
      headers: ["Pillar", "Examples", "Monitor"],
      rows: [
        ["RAAS inhibitor", "ACEi / ARB / ARNI", "BP, Cr, K⁺"],
        ["Beta-blocker", "Carvedilol, metoprolol succinate, bisoprolol", "HR, BP"],
        ["MRA", "Spironolactone, eplerenone", "K⁺, Cr"],
        ["SGLT2i", "Dapagliflozin, empagliflozin", "Volume, infections"],
      ],
    },
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 1,
  },
  {
    id: "naplex-arni-washout",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "ARNI Switch Rule",
    teaser: "Sacubitril/valsartan requires ACEi washout.",
    kind: "mistake",
    tags: ["ARNI", "ACEi", "angioedema"],
    body: "Stop ACE inhibitor → wait 36 hours → start sacubitril/valsartan. Never combine ACEi + ARNI.",
    bullets: [
      "Do not combine ACEi + ARB + ARNI",
      "Elevated BNP on ARNI is expected (neprilysin inhibition)",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 2,
  },
  {
    id: "naplex-loop-diuretics",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Diuretics",
    title: "Loop Diuretic Equivalents",
    teaser: "Bioavailability matters when furosemide fails.",
    kind: "conversion",
    tags: ["diuretics", "furosemide", "bumetanide"],
    body: "Approximate oral conversions (varies by patient):",
    table: {
      headers: ["Drug", "Oral dose", "Notes"],
      rows: [
        ["Furosemide", "40 mg", "Variable absorption (~50%)"],
        ["Bumetanide", "1 mg", "≈ 40 mg furosemide"],
        ["Torsemide", "20 mg", "Better bioavailability"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 3,
  },
  // —— NAPLEX / Anticoagulation ——
  {
    id: "naplex-reversal-chart",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Anticoagulant Reversal",
    teaser: "Match the reversal agent to the drug on board.",
    kind: "table",
    tags: ["reversal", "DOAC", "warfarin"],
    body: "Life-threatening bleeding — stop drug first, then reverse.",
    table: {
      headers: ["Anticoagulant", "Reversal"],
      rows: [
        ["Warfarin", "4-factor PCC + vitamin K"],
        ["Dabigatran", "Idarucizumab (or PCC)"],
        ["Rivaroxaban / Apixaban", "Andexanet alfa or PCC"],
        ["Heparin / LMWH", "Protamine (partial for LMWH)"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 4,
  },
  {
    id: "naplex-hit-rule",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "HIT Type 2",
    teaser: "Thrombocytopenia + thrombosis — stop all heparin.",
    kind: "mistake",
    tags: ["HIT", "heparin", "argatroban"],
    body: "Immune-mediated HIT: stop heparin (including flushes) → non-heparin anticoagulant (argatroban, bivalirudin, fondaparinux). Do not start warfarin alone.",
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 5,
  },
  // —— NCLEX / Sepsis ——
  {
    id: "nclex-sepsis-bundle",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Hour-1 Sepsis Priorities",
    teaser: "What to do first when infection + organ dysfunction.",
    kind: "pearl",
    tags: ["sepsis", "bundle", "prioritization"],
    body: "Recognize early → cultures → antibiotics → fluids → measure lactate → vasopressors if needed.",
    bullets: [
      "Do not delay antibiotics for minor tasks",
      "30 mL/kg crystalloid if hypotensive (adjust for HF/ESRD)",
      "Norepinephrine first-line if MAP still low after fluids",
      "Lactate clearance tracks resuscitation success",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 1,
  },
  {
    id: "nclex-shock-types",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Shock",
    title: "Shock Type Clues",
    teaser: "Hypovolemic vs cardiogenic vs distributive vs obstructive.",
    kind: "table",
    tags: ["shock", "prioritization", "ABC"],
    body: "NCLEX loves matching intervention to shock physiology.",
    table: {
      headers: ["Type", "Clue", "First move"],
      rows: [
        ["Hypovolemic", "Low CVP, dry", "Volume"],
        ["Cardiogenic", "Crackles, ↑ JVP", "Inotropes / treat cause"],
        ["Distributive (sepsis)", "Warm skin early, ↓ BP", "Fluids + abx + pressors"],
        ["Obstructive", "↑ JVP, muffled heart sounds", "Relieve obstruction"],
      ],
    },
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 2,
  },
  // —— USMLE / ACS ——
  {
    id: "usmle-stemi-path",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "STEMI: Do Not Wait",
    teaser: "ECG drives reperfusion — not troponin.",
    kind: "fact",
    tags: ["STEMI", "PCI", "reperfusion"],
    body: "ASA + anticoagulation + P2Y12 → primary PCI if available within 120 min; fibrinolysis if PCI unavailable.",
    bullets: [
      "New LBBB + symptoms = STEMI equivalent",
      "Inferior MI + hypotension → think RV infarct → fluids, avoid nitrates",
      "Hold beta-blocker if acute decompensation or cocaine MI",
    ],
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 1,
  },
  {
    id: "usmle-acs-spectrum",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "UA vs NSTEMI vs STEMI",
    teaser: "Troponin + ECG pattern defines the pathway.",
    kind: "table",
    tags: ["ACS", "troponin", "ECG"],
    body: "Use ECG for immediate reperfusion decisions; troponin confirms myocardial injury.",
    table: {
      headers: ["Diagnosis", "Troponin", "ECG"],
      rows: [
        ["Unstable angina", "Normal", "May have ST depression / T-wave changes"],
        ["NSTEMI", "Elevated", "ST depression or normal"],
        ["STEMI", "Usually elevated", "ST elevation or new LBBB"],
      ],
    },
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 2,
  },
  {
    id: "usmle-acs-antithrombotics",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "ACS Antithrombotic Stack",
    teaser: "Dual antiplatelet + anticoagulation for NSTEMI/STEMI.",
    kind: "table",
    tags: ["ACS", "aspirin", "heparin", "P2Y12"],
    body: "Give aspirin immediately unless contraindicated; add P2Y12 and parenteral anticoagulant per pathway.",
    table: {
      headers: ["Phase", "Typical agents", "Pearl"],
      rows: [
        ["All ACS", "Aspirin 325 mg then 81 mg daily", "Start ASAP — do not wait for cath lab"],
        ["NSTEMI/STEMI", "P2Y12 (ticagrelor, prasugrel, clopidogrel)", "Prasugrel CI if prior stroke/TIA"],
        ["NSTEMI/STEMI", "UFH, enoxaparin, or bivalirudin", "Match to PCI plan and bleeding risk"],
        ["Post-PCI", "DAPT 12 months typical", "Balance stent thrombosis vs bleeding"],
      ],
    },
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 3,
  },
  {
    id: "usmle-stroke-tpa",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "Acute Ischemic Stroke — tPA Window",
    teaser: "Time last known well → CT → treat eligible patients fast.",
    kind: "pearl",
    tags: ["stroke", "tPA", "CT"],
    body: "Non-contrast CT excludes hemorrhage; IV alteplase within 4.5 h for eligible patients.",
    bullets: [
      "Last known well defines clock — wake-up stroke often ineligible unless advanced imaging",
      "BP >185/110 must be lowered before tPA",
      "Major exclusions: recent surgery, active bleeding, prior ICH",
      "Endovascular thrombectomy up to 24 h in select large-vessel occlusion",
    ],
    practiceTopicSlug: "neurology-stroke",
    sortOrder: 4,
  },
  {
    id: "usmle-hyperkalemia",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "Electrolytes",
    title: "Hyperkalemia Emergency",
    teaser: "Stabilize myocardium → shift K⁺ → remove K⁺.",
    kind: "table",
    tags: ["potassium", "ECG", "dialysis"],
    body: "Peaked T waves → widened QRS → sine wave. Treat ECG changes urgently.",
    table: {
      headers: ["Step", "Agent", "Onset"],
      rows: [
        ["Stabilize", "Calcium gluconate/chloride", "Minutes"],
        ["Shift intracellular", "Insulin + dextrose", "~30 min"],
        ["Shift intracellular", "Albuterol, bicarbonate if acidemic", "Adjunct"],
        ["Remove", "Diuretics, patiromer, dialysis", "Hours"],
      ],
    },
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 5,
  },
  {
    id: "usmle-aki-fena",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "AKI",
    title: "Prerenal vs ATN (FeNa)",
    teaser: "BUN:Cr ratio and urine studies narrow AKI type.",
    kind: "fact",
    tags: ["AKI", "FeNa", "ATN"],
    body: "FeNa <1% favors prerenal; FeNa >2% favors ATN (unreliable on diuretics — use FEUrea).",
    bullets: [
      "Prerenal: dry mucosa, ↓ urine Na, responds to fluid bolus",
      "ATN: muddy brown casts, ischemic or nephrotoxic insult",
      "Postrenal: hydronephrosis — relieve obstruction (Foley, stent)",
      "Dialysis indications: AEIOU (Acidosis, Electrolytes, Ingestion, Overload, Uremia)",
    ],
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 6,
  },
  // —— MPJE ——
  {
    id: "mpje-cii-rules",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Controlled Substances",
    title: "Schedule II Essentials",
    teaser: "No refills. Strict Rx validity.",
    kind: "fact",
    tags: ["CII", "CSA", "prescribing"],
    body: "Written or compliant e-Rx; quantity must be written — no 'dispense as directed.'",
    bullets: [
      "No refills on CII",
      "Partial fills highly restricted (except qualifying scenarios)",
      "Emergency oral supply: narrow criteria + written follow-up within 7 days",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 1,
  },
  {
    id: "mpje-schedules",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Controlled Substances",
    title: "CSA Schedules at a Glance",
    teaser: "Abuse potential vs accepted medical use.",
    kind: "table",
    tags: ["CSA", "schedules", "MPJE"],
    body: "State law may be stricter — always apply the tighter standard on MPJE.",
    table: {
      headers: ["Schedule", "Refills (general)", "Example"],
      rows: [
        ["CII", "None", "Oxycodone, amphetamine"],
        ["CIII", "≤5 in 6 months", "Codeine/APAP combos"],
        ["CIV", "≤5 in 6 months", "Benzodiazepines"],
        ["CV", "Varies", "Low-abuse preparations"],
      ],
    },
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 2,
  },
  {
    id: "naplex-k-hyperkalemia",
    examSlug: "naplex",
    subject: "Electrolytes",
    topic: "Hyperkalemia",
    title: "Hyperkalemia Emergency",
    teaser: "Stabilize the myocardium, then shift and remove K⁺.",
    kind: "pearl",
    tags: ["potassium", "ECG", "emergency"],
    body: "Severe hyperkalemia is a pharmacy and nursing emergency — treat ECG changes before waiting for repeat labs.",
    bullets: [
      "Calcium gluconate/chloride: membrane stabilization (does not lower K⁺)",
      "Insulin + dextrose: shifts K⁺ intracellularly",
      "Albuterol, sodium bicarbonate (if acidemic): adjuncts",
      "Kayexalate/patiromer/diuretics/dialysis: remove K⁺ from body",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 12,
  },
  // —— NCLEX / Delegation (extra) ——
  {
    id: "nclex-five-rights",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Five Rights of Delegation",
    teaser: "NCLEX checklist before assigning any task.",
    kind: "fact",
    tags: ["delegation", "five-rights", "scope"],
    body: "All five must be satisfied — if one is missing, the RN keeps the task.",
    bullets: [
      "Right task — appropriate for delegatee scope",
      "Right circumstance — stable patient, adequate resources",
      "Right person — competent, trained, within scope",
      "Right direction — clear instructions and limits",
      "Right supervision — RN evaluates outcome",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 3,
  },
  {
    id: "nclex-never-delegate",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Never Delegate to UAP",
    teaser: "High-risk tasks that stay with the RN on NCLEX.",
    kind: "mistake",
    tags: ["delegation", "UAP", "insulin"],
    body: "When an answer assigns these to UAP, eliminate it.",
    bullets: [
      "Initial admission assessment",
      "Insulin administration",
      "Unstable vital signs or new acute changes",
      "Patient/family teaching",
      "Sterile procedures requiring nursing judgment",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 4,
  },
  // —— USMLE extras ——
  {
    id: "usmle-dka-orders",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA",
    title: "DKA Management Order",
    teaser: "Fluids before insulin if K⁺ is low.",
    kind: "pearl",
    tags: ["DKA", "insulin", "potassium"],
    body: "Start IV fluids → check K⁺ → insulin drip only if K⁺ ≥3.3 mEq/L.",
    bullets: [
      "Add dextrose when glucose ~200 to continue insulin until gap closes",
      "Gap closes when bicarbonate normalizes, not when glucose normalizes",
      "Search for trigger: infection, missed insulin, new-onset DM",
    ],
    practiceTopicSlug: "endocrine-dm",
    sortOrder: 7,
  },
  {
    id: "usmle-hhs-vs-dka",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA / HHS",
    title: "DKA vs HHS",
    teaser: "Ketones and gap distinguish emergencies in hyperglycemia.",
    kind: "table",
    tags: ["DKA", "HHS", "hyperglycemia"],
    body: "Both need aggressive fluids; HHS has higher mortality and slower correction targets.",
    table: {
      headers: ["Feature", "DKA", "HHS"],
      rows: [
        ["Glucose", "Often >250", "Often >600"],
        ["Ketones / gap", "Present", "Minimal ketones, mild or no gap"],
        ["Dehydration", "Significant", "Profound"],
        ["Insulin", "Required once K⁺ safe", "Often lower doses; fluids first"],
      ],
    },
    practiceTopicSlug: "endocrine-dm",
    sortOrder: 8,
  },
  {
    id: "usmle-cap-antibiotics",
    examSlug: "usmle",
    subject: "Pulmonary",
    topic: "Pneumonia",
    title: "CAP Antibiotic Choices",
    teaser: "Outpatient vs inpatient; cover atypicals when indicated.",
    kind: "table",
    tags: ["CAP", "pneumonia", "antibiotics"],
    body: "CURB-65 or PSI guides disposition; tailor to local resistance and comorbidities.",
    table: {
      headers: ["Setting", "Typical regimen", "Add pseudomonas if"],
      rows: [
        ["Healthy outpatient", "Amoxicillin or doxy/macrolide", "N/A"],
        ["Comorbid outpatient", "Amox-clav + macrolide or resp fluoroquinolone", "Recent abx/hospitalization"],
        ["Inpatient non-ICU", "Beta-lactam + macrolide or FQ monotherapy", "Risk factors for resistant orgs"],
        ["ICU", "Beta-lactam + macrolide or FQ (+ MRSA/Pseudomonas if risk)", "Structural lung disease, HCAP risk"],
      ],
    },
    practiceTopicSlug: "pulmonary",
    sortOrder: 9,
  },
  {
    id: "usmle-meningitis-emergency",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Meningitis",
    title: "Bacterial Meningitis — Do Not Delay Abx",
    teaser: "Blood cultures then empiric antibiotics; add dexamethasone when indicated.",
    kind: "pearl",
    tags: ["meningitis", "ceftriaxone", "LP"],
    body: "If LP delayed, give empiric antibiotics after blood cultures — do not wait for CT/LP if unstable.",
    bullets: [
      "Adults: ceftriaxone + vancomycin (+ ampicillin if Listeria risk >50 or immunocompromised)",
      "Dexamethasone before or with first abx dose if suspected pneumococcal",
      "Petechiae + fever → treat as meningococcemia; isolate and prophylax contacts",
    ],
    practiceTopicSlug: "infectious-disease",
    sortOrder: 10,
  },
  {
    id: "usmle-tpa-exclusions",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "tPA — High-Yield Exclusions",
    teaser: "Eliminate wrong answers on stroke timing and bleeding risk.",
    kind: "mistake",
    tags: ["stroke", "tPA", "contraindications"],
    body: "When in doubt on Step 2 CK: recent intracranial surgery, active internal bleeding, or INR >1.7 excludes tPA.",
    bullets: [
      "Symptom onset >4.5 h (without advanced imaging protocol)",
      "Evidence of hemorrhage on CT",
      "Recent major surgery or GI/GU bleed",
      "Platelets <100k, glucose <50 (correct first)",
    ],
    practiceTopicSlug: "neurology-stroke",
    sortOrder: 11,
  },
  // —— MPJE extras ——
  {
    id: "mpje-recordkeeping",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Recordkeeping",
    title: "Controlled Substance Records",
    teaser: "Perpetual inventory and DEA Form 222 for CII.",
    kind: "fact",
    tags: ["DEA", "inventory", "CII"],
    body: "Two-year minimum retention; reconcile physical count to perpetual inventory.",
    bullets: [
      "DEA Form 222 for Schedule II orders (electronic CSOS in practice)",
      "Biennial inventory required",
      "Theft/loss: DEA Form 106 within one business day",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 3,
  },
  // —— Cross-exam utilities ——
  {
    id: "all-creatinine-clearance",
    examSlug: "naplex",
    subject: "Calculations",
    topic: "Renal dosing",
    title: "Cockcroft-Gault (CrCl)",
    teaser: "Estimate creatinine clearance for drug dosing.",
    kind: "equation",
    tags: ["calculation", "renal", "dosing"],
    body: "CrCl (mL/min) = [(140 − age) × weight (kg)] / [72 × SCr (mg/dL)] × 0.85 if female",
    bullets: [
      "Use ideal body weight if obese (often tested conceptually)",
      "Many renally cleared drugs use CrCl, not eGFR",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 10,
  },
  {
    id: "all-anion-gap",
    examSlug: "usmle",
    subject: "Laboratory",
    topic: "Acid-base",
    title: "Anion Gap",
    teaser: "MUDPILES for elevated gap metabolic acidosis.",
    kind: "equation",
    tags: ["ABG", "acid-base", "MUDPILES"],
    body: "AG = Na⁺ − (Cl⁻ + HCO₃⁻). Normal ≈ 8–12 mEq/L.",
    bullets: ["MUDPILES: Methanol, Uremia, DKA, Propylene glycol, INH/Iron, Lactic acidosis, Ethylene glycol, Salicylates"],
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 12,
  },
  {
    id: "nclex-delegation",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "RN Accountability",
    teaser: "What you can and cannot delegate.",
    kind: "mistake",
    tags: ["delegation", "UAP", "scope"],
    body: "The RN remains accountable for all care. Never delegate assessment, teaching, or unstable clients inappropriately.",
    bullets: [
      "UAP: stable tasks (hygiene, ambulation with plan)",
      "LPN: stable predictable care per scope",
      "RN: assessment, triage, unstable patients",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 10,
  },
];
