import type { MemoryCard } from "../types";

/** Static Memory Card library — seed to DB later if needed. */
export const MEMORY_CARDS: MemoryCard[] = [
  // —— NAPLEX / Heart Failure ——
  {
    id: "naplex-hf-four-pillars",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "HFrEF Four Pillars (GDMT)",
    teaser: "Mortality-reducing drug classes every pharmacist must know.",
    kind: "table",
    tags: ["GDMT", "HFrEF", "mortality"],
    body: "Start low, go slow. Diuretics treat congestion but are not a mortality pillar.",
    table: {
      headers: ["Pillar", "Examples", "Monitor"],
      rows: [
        ["RAAS inhibitor", "ACEi / ARB / ARNI", "BP, Cr, K⁺"],
        ["Beta-blocker", "Carvedilol, metoprolol succinate, bisoprolol", "HR, BP"],
        ["MRA", "Spironolactone, eplerenone", "K⁺, Cr"],
        ["SGLT2i", "Dapagliflozin, empagliflozin", "Volume, infections"],
      ],
    },
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 1,
  },
  {
    id: "naplex-arni-washout",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "ARNI Switch Rule",
    teaser: "Sacubitril/valsartan requires ACEi washout.",
    kind: "mistake",
    tags: ["ARNI", "ACEi", "angioedema"],
    body: "Stop ACE inhibitor → wait 36 hours → start sacubitril/valsartan. Never combine ACEi + ARNI.",
    bullets: [
      "Do not combine ACEi + ARB + ARNI",
      "Elevated BNP on ARNI is expected (neprilysin inhibition)",
      "Washout prevents bradykinin-mediated angioedema when switching from ACEi",
      "If angioedema history on ACEi — ARNI is generally contraindicated",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 2,
  },
  {
    id: "naplex-loop-diuretics",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Diuretics",
    title: "Loop Diuretic Equivalents",
    teaser: "Bioavailability matters when furosemide fails.",
    kind: "conversion",
    tags: ["diuretics", "furosemide", "bumetanide"],
    body: "Approximate oral conversions (varies by patient):",
    table: {
      headers: ["Drug", "Oral dose", "Notes"],
      rows: [
        ["Furosemide", "40 mg", "Variable absorption (~50%)"],
        ["Bumetanide", "1 mg", "≈ 40 mg furosemide"],
        ["Torsemide", "20 mg", "Better bioavailability"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 3,
  },
  {
    id: "naplex-bb-start-rule",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "Beta-Blocker Start Rule (HFrEF)",
    teaser: "Euvolemic first — only the three proven agents.",
    kind: "pearl",
    tags: ["GDMT", "beta-blocker", "HFrEF"],
    body: "Initiate beta-blocker only when the patient is euvolemic — not during acute decompensation. Uptitrate slowly to target dose.",
    bullets: [
      "Mortality-proven agents only: carvedilol, metoprolol succinate (NOT tartrate), bisoprolol",
      "Hold or do not uptitrate during active pulmonary edema or cardiogenic shock",
      "Metoprolol tartrate lacks HFrEF mortality data — succinate ER is the evidence-based formulation",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 4,
  },
  {
    id: "naplex-k-hyperkalemia",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "MRA + ACEi Hyperkalemia Management",
    teaser: "Expected on GDMT — treat without abandoning pillars.",
    kind: "pearl",
    tags: ["potassium", "MRA", "ACEi", "GDMT"],
    body: "Combining RAAS inhibitor with MRA raises hyperkalemia risk — monitor K⁺ and manage without unnecessary GDMT discontinuation.",
    bullets: [
      "Check K⁺ and Cr within 1 week of starting or dose-changing MRA + ACEi/ARB",
      "Mild hyperkalemia (5.0–5.5): dietary K⁺ restriction, reduce MRA dose, consider patiromer/SPS",
      "Avoid triple RAAS blockade (ACEi + ARB + MRA) — no benefit, high K⁺ risk",
      "Severe hyperkalemia with ECG changes: calcium stabilization, insulin + dextrose, then remove K⁺",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 5,
  },
  {
    id: "naplex-sglt2i-periop-dka",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "SGLT2i Perioperative Hold",
    teaser: "Hold before surgery; watch for euglycemic DKA.",
    kind: "mistake",
    tags: ["SGLT2i", "DKA", "perioperative"],
    body: "SGLT2 inhibitors reduce HF hospitalization but require perioperative management and patient counseling on rare euglycemic DKA.",
    bullets: [
      "Hold dapagliflozin/empagliflozin 3–4 days before elective surgery",
      "Euglycemic DKA: normal or mildly elevated glucose + ketosis — suspect on SGLT2i, especially peri-op/fasting",
      "Resume when eating and clinically stable; counsel on genital mycotic infections",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 6,
  },
  {
    id: "naplex-digoxin-toxicity",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "Digoxin Toxicity Triggers",
    teaser: "Hypokalemia lowers the therapeutic threshold.",
    kind: "fact",
    tags: ["digoxin", "toxicity", "hypokalemia"],
    body: "Digoxin has a narrow therapeutic index; toxicity risk rises when potassium is low or renal clearance falls.",
    bullets: [
      "Hypokalemia potentiates digoxin toxicity — common with loop diuretics + MRA/ACEi",
      "Renal impairment reduces clearance — reduce dose and monitor levels",
      "Toxicity signs: nausea, vision changes (yellow halos), arrhythmias (PVCs, AV block)",
      "Hold digoxin; treat hyperkalemia if present; digoxin Fab for life-threatening toxicity",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 7,
  },
  // —— NAPLEX / Anticoagulation ——
  {
    id: "naplex-reversal-chart",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Anticoagulant Reversal",
    teaser: "Match the reversal agent to the drug on board.",
    kind: "table",
    tags: ["reversal", "DOAC", "warfarin"],
    body: "Life-threatening bleeding — stop drug first, then reverse.",
    bullets: [
      "Hold anticoagulant immediately; support ABCs and source control",
      "PCC preferred over FFP for warfarin reversal when available",
      "Andexanet is agent-specific for factor Xa inhibitors — costly but targeted",
      "Document time of last dose — guides urgency and agent choice",
    ],
    table: {
      headers: ["Anticoagulant", "Reversal"],
      rows: [
        ["Warfarin", "4-factor PCC + vitamin K"],
        ["Dabigatran", "Idarucizumab (or PCC)"],
        ["Rivaroxaban / Apixaban", "Andexanet alfa or PCC"],
        ["Heparin / LMWH", "Protamine (partial for LMWH)"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 9,
  },
  {
    id: "naplex-hit-rule",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "HIT Type 2",
    teaser: "Thrombocytopenia + thrombosis — stop all heparin.",
    kind: "mistake",
    tags: ["HIT", "heparin", "argatroban"],
    body: "Immune-mediated HIT: stop heparin (including flushes) → non-heparin anticoagulant (argatroban, bivalirudin, fondaparinux). Do not start warfarin alone.",
    bullets: [
      "4T score helps probability: Thrombocytopenia, Timing, Thrombosis, oTher causes",
      "Stop all heparin — including line flushes and heparin-coated catheters",
      "Start direct thrombin inhibitor or fondaparinux — never warfarin alone (limb gangrene risk)",
      "Platelets often fall 5–10 days after heparin exposure; thrombosis may precede severe drop",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 10,
  },
  {
    id: "naplex-doac-renal-dose",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "DOAC Renal Dose Adjustment",
    teaser: "CrCl thresholds differ by agent — know the cutoffs.",
    kind: "table",
    tags: ["DOAC", "renal", "dosing"],
    body: "Renally cleared DOACs need dose reduction or avoidance at low CrCl. Apixaban uses the 2-of-3 rule.",
    table: {
      headers: ["Agent", "CrCl threshold", "Action"],
      rows: [
        ["Apixaban", "≤50 mL/min (standard dose)", "Reduce to 2.5 mg BID if 2 of 3: age ≥80, weight ≤60 kg, SCr ≥1.5"],
        ["Rivaroxaban", "≤50 mL/min (VTE/AF)", "Reduce dose per indication; avoid if CrCl <15"],
        ["Dabigatran", "≤50 mL/min", "Reduce dose; avoid if CrCl <15–30 (per labeling/indication)"],
        ["Edoxaban", "≤50 mL/min", "Reduce to 30 mg daily; avoid if CrCl >95 (reduced efficacy)"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 11,
  },
  {
    id: "naplex-warfarin-vs-doac",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Warfarin vs DOAC Selection",
    teaser: "Mechanical mitral valve stays on warfarin.",
    kind: "pearl",
    tags: ["warfarin", "DOAC", "selection"],
    body: "DOACs offer fixed dosing and fewer interactions for most VTE/AF patients; warfarin remains mandatory in select scenarios.",
    bullets: [
      "Warfarin required: mechanical mitral valve, moderate-severe mitral stenosis",
      "DOACs preferred for most AF and VTE when renal function allows — no routine monitoring",
      "Warfarin needs INR monitoring; many drug/food interactions; established reversal (PCC + vitamin K)",
      "Severe renal impairment: warfarin often usable; dabigatran most renally cleared — highest caution",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 12,
  },
  {
    id: "naplex-ufh-lmwh-monitor",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "UFH vs LMWH Monitoring",
    teaser: "aPTT for UFH; anti-Xa for LMWH when indicated.",
    kind: "table",
    tags: ["heparin", "enoxaparin", "monitoring"],
    body: "LMWH has predictable kinetics; routine monitoring is not needed except in renal impairment, obesity, or pregnancy.",
    table: {
      headers: ["Agent", "Monitor", "Goal / Pearl"],
      rows: [
        ["UFH IV", "aPTT (or anti-Xa)", "Per institutional nomogram; anti-Xa if aPTT unreliable"],
        ["UFH SC", "aPTT if therapeutic intent", "Less common than IV monitoring"],
        ["LMWH (enoxaparin)", "Anti-Xa (peak)", "Consider if CrCl <30, obesity, pregnancy"],
        ["LMWH reversal", "Protamine", "Partial (~60%) anti-Xa neutralization"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 13,
  },
  {
    id: "naplex-bridge-therapy",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Bridge Therapy Basics",
    teaser: "Bridge high thrombotic risk — not low risk.",
    kind: "fact",
    tags: ["bridge", "warfarin", "perioperative"],
    body: "Perioperative bridging with LMWH/UFH is reserved for patients at high thrombotic risk when warfarin is held.",
    bullets: [
      "Bridge when high risk: mechanical mitral valve, recent VTE (<3 mo), CHA₂DS₂-VASc with recent stroke",
      "Do NOT bridge most AF patients — bleeding risk outweighs benefit in moderate-risk AF",
      "Hold warfarin ~5 days pre-op; last LMWH dose ~24 h before (high bleeding) or ~12 h (moderate)",
      "Resume warfarin post-op when hemostasis achieved; overlap parenteral agent until INR therapeutic",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 14,
  },
  // —— NAPLEX / Diabetes ——
  {
    id: "naplex-insulin-kinetics",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Insulin Onset / Peak / Duration",
    teaser: "Match insulin type to meal timing and basal needs.",
    kind: "table",
    tags: ["insulin", "kinetics", "basal-bolus"],
    body: "Rapid analogs cover meals; basal analogs provide background coverage without pronounced peak.",
    table: {
      headers: ["Type", "Examples", "Onset", "Peak", "Duration"],
      rows: [
        ["Rapid", "Lispro, aspart, glulisine", "~15 min", "~1–2 h", "~3–5 h"],
        ["Regular", "Regular human", "~30 min", "2–4 h", "5–8 h"],
        ["NPH", "NPH", "1–2 h", "4–12 h", "12–18 h"],
        ["Basal", "Glargine, detemir, degludec", "1–4 h", "Minimal", "Up to 24–42 h"],
      ],
    },
    practiceTopicSlug: "insulin-diabetes-management",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 15,
  },
  {
    id: "naplex-metformin-hold",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Metformin Hold Rules",
    teaser: "Renal function and contrast dictate hold timing.",
    kind: "mistake",
    tags: ["metformin", "eGFR", "contrast"],
    body: "Metformin is first-line for T2DM but must be held or dose-reduced as renal function declines.",
    bullets: [
      "eGFR ≥45: continue with routine monitoring",
      "eGFR 30–44: reduce dose; reassess benefits/risks",
      "eGFR <30: contraindicated — discontinue",
      "Iodinated contrast: hold at time of procedure if eGFR 30–60 or AKI risk; restart after 48 h if stable",
    ],
    practiceTopicSlug: "insulin-diabetes-management",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 16,
  },
  {
    id: "naplex-hypoglycemia-15-15",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Hypoglycemia 15-15 Rule",
    teaser: "15 grams of carb, recheck in 15 minutes.",
    kind: "pearl",
    tags: ["hypoglycemia", "counseling", "insulin"],
    body: "Treat hypoglycemia (<70 mg/dL) with fast-acting carbohydrate; repeat until glucose ≥70 mg/dL.",
    bullets: [
      "15 g fast-acting carb: 4 glucose tabs, 4 oz juice, or hard candy",
      "Recheck glucose in 15 minutes; repeat if still <70",
      "Once ≥70: small snack if next meal >1 hour away",
      "Severe/unconscious: glucagon IM/SC or intranasal; call emergency services",
    ],
    practiceTopicSlug: "insulin-diabetes-management",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 17,
  },
  {
    id: "naplex-sglt2i-counseling",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "SGLT2i Patient Counseling",
    teaser: "Infections, surgery hold, and euglycemic DKA warning.",
    kind: "pearl",
    tags: ["SGLT2i", "counseling", "DKA"],
    body: "SGLT2 inhibitors offer glycemic, CV, and renal benefits but require proactive patient education.",
    bullets: [
      "Genital mycotic infections (yeast/UTI-like symptoms) — maintain hygiene, seek treatment early",
      "Hold 3–4 days before elective surgery; resume when eating and stable",
      "Euglycemic DKA: report nausea, vomiting, abdominal pain even if glucose is normal",
      "Stay hydrated; sick-day rules apply — do not stop insulin without provider guidance",
    ],
    practiceTopicSlug: "insulin-diabetes-management",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 18,
  },
  // —— NCLEX / Sepsis ——
  {
    id: "nclex-sepsis-bundle",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Hour-1 Sepsis Priorities",
    teaser: "What to do first when infection + organ dysfunction.",
    kind: "pearl",
    tags: ["sepsis", "bundle", "prioritization"],
    body: "Recognize early → cultures → antibiotics → fluids → measure lactate → vasopressors if needed.",
    bullets: [
      "Do not delay antibiotics for minor tasks",
      "30 mL/kg crystalloid if hypotensive (adjust for HF/ESRD)",
      "Norepinephrine first-line if MAP still low after fluids",
      "Lactate clearance tracks resuscitation success",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 1,
  },
  {
    id: "nclex-shock-types",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Shock",
    title: "Shock Type Clues",
    teaser: "Hypovolemic vs cardiogenic vs distributive vs obstructive.",
    kind: "table",
    tags: ["shock", "prioritization", "ABC"],
    body: "NCLEX loves matching intervention to shock physiology.",
    table: {
      headers: ["Type", "Clue", "First move"],
      rows: [
        ["Hypovolemic", "Low CVP, dry", "Volume"],
        ["Cardiogenic", "Crackles, ↑ JVP", "Inotropes / treat cause"],
        ["Distributive (sepsis)", "Warm skin early, ↓ BP", "Fluids + abx + pressors"],
        ["Obstructive", "↑ JVP, muffled heart sounds", "Relieve obstruction"],
      ],
    },
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 2,
  },
  {
    id: "nclex-lactate-four",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Lactate ≥4 = Fluid Bolus",
    teaser: "Elevated lactate mandates resuscitation even if BP looks stable.",
    kind: "mistake",
    tags: ["sepsis", "lactate", "fluids"],
    body: "Lactate ≥4 mmol/L signals severe sepsis — give 30 mL/kg crystalloid and reassess, even when blood pressure is still compensating.",
    bullets: [
      "Normal BP does not exclude sepsis — watch lactate, mentation, urine output",
      "Trend lactate clearance to assess resuscitation success",
      "Reassess after each bolus for fluid overload (crackles, JVD, hypoxia)",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 3,
  },
  {
    id: "nclex-norepinephrine-first",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Septic Shock",
    title: "First-Line Vasopressor",
    teaser: "Norepinephrine for MAP ≥65 after fluids.",
    kind: "fact",
    tags: ["sepsis", "vasopressor", "norepinephrine"],
    body: "Septic shock persists when MAP stays below 65 mmHg despite adequate crystalloid — start norepinephrine; do not delay for central line in an emergency.",
    bullets: [
      "MAP goal ≥65 mmHg: DBP + ⅓(SBP − DBP)",
      "Add vasopressin or epinephrine as second-line if refractory",
      "Avoid dopamine as first-line — more arrhythmias vs norepinephrine",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 4,
  },
  {
    id: "nclex-qsofa-screen",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "qSOFA Bedside Screen",
    teaser: "Two or more criteria → suspect sepsis outside the ICU.",
    kind: "table",
    tags: ["sepsis", "qSOFA", "screening"],
    body: "qSOFA is a quick bedside screen — not diagnostic alone, but triggers escalation and workup.",
    table: {
      headers: ["Criterion", "Threshold"],
      rows: [
        ["Respiratory rate", "≥22/min"],
        ["Altered mentation", "GCS <15"],
        ["Systolic BP", "≤100 mmHg"],
      ],
    },
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 5,
  },
  {
    id: "nclex-abx-one-hour",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Antibiotics Within 1 Hour",
    teaser: "Cultures first — but never delay antibiotics for imaging.",
    kind: "mistake",
    tags: ["sepsis", "antibiotics", "prioritization"],
    body: "Obtain blood cultures before antibiotics when feasible, then give broad-spectrum coverage within 1 hour of recognition. Each hour of delay increases mortality.",
    bullets: [
      "Do not wait for CT scan, line placement, or culture results to start abx",
      "Match empiric coverage to likely source (lung, abdomen, line, skin)",
      "Source control (drain, debride, remove line) within 6–12 h when feasible",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 6,
  },
  {
    id: "nclex-sepsis-vs-shock",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Sepsis vs Septic Shock",
    teaser: "When vasopressors and lactate define shock.",
    kind: "table",
    tags: ["sepsis", "septic-shock", "SOFA"],
    body: "Sepsis-3: infection + organ dysfunction (SOFA ≥2). Septic shock adds pressor-dependent hypotension plus lactate >2 despite fluids.",
    table: {
      headers: ["Feature", "Sepsis", "Septic Shock"],
      rows: [
        ["Organ dysfunction", "SOFA score ↑ ≥2", "Same"],
        ["Blood pressure", "May be normal early", "Hypotension despite fluids"],
        ["Vasopressors", "Not required", "Required for MAP ≥65"],
        ["Lactate", "May be elevated", ">2 mmol/L despite fluids"],
      ],
    },
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 7,
  },
  {
    id: "nclex-perfusion-endpoints",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Perfusion Endpoints",
    teaser: "Urine output and mentation track resuscitation.",
    kind: "pearl",
    tags: ["sepsis", "urine-output", "monitoring"],
    body: "After initial resuscitation, nursing reassessment confirms adequate perfusion — not just a single BP reading.",
    bullets: [
      "Urine output goal ≥0.5 mL/kg/h — oliguria for 2 h suggests inadequate perfusion",
      "Track mental status, capillary refill, and lactate clearance",
      "Notify provider if perfusion markers fail to improve after fluids and pressors",
      "Document hourly urine output and trend MAP — single normal BP can mask shock",
    ],
    practiceTopicSlug: "critical-care",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 8,
  },
  // —— USMLE / ACS ——
  {
    id: "usmle-stemi-path",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "STEMI: Do Not Wait",
    teaser: "ECG drives reperfusion — not troponin.",
    kind: "fact",
    tags: ["STEMI", "PCI", "reperfusion"],
    body: "ASA + anticoagulation + P2Y12 → primary PCI if available within 120 min; fibrinolysis if PCI unavailable.",
    bullets: [
      "New LBBB + symptoms = STEMI equivalent",
      "Inferior MI + hypotension → think RV infarct → fluids, avoid nitrates",
      "Hold beta-blocker if acute decompensation or cocaine MI",
    ],
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 1,
  },
  {
    id: "usmle-acs-spectrum",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "UA vs NSTEMI vs STEMI",
    teaser: "Troponin + ECG pattern defines the pathway.",
    kind: "table",
    tags: ["ACS", "troponin", "ECG"],
    body: "Use ECG for immediate reperfusion decisions; troponin confirms myocardial injury.",
    table: {
      headers: ["Diagnosis", "Troponin", "ECG"],
      rows: [
        ["Unstable angina", "Normal", "May have ST depression / T-wave changes"],
        ["NSTEMI", "Elevated", "ST depression or normal"],
        ["STEMI", "Usually elevated", "ST elevation or new LBBB"],
      ],
    },
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 2,
  },
  {
    id: "usmle-acs-antithrombotics",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "ACS Antithrombotic Stack",
    teaser: "Dual antiplatelet + anticoagulation for NSTEMI/STEMI.",
    kind: "table",
    tags: ["ACS", "aspirin", "heparin", "P2Y12"],
    body: "Give aspirin immediately unless contraindicated; add P2Y12 and parenteral anticoagulant per pathway.",
    table: {
      headers: ["Phase", "Typical agents", "Pearl"],
      rows: [
        ["All ACS", "Aspirin 325 mg then 81 mg daily", "Start ASAP — do not wait for cath lab"],
        ["NSTEMI/STEMI", "P2Y12 (ticagrelor, prasugrel, clopidogrel)", "Prasugrel CI if prior stroke/TIA"],
        ["NSTEMI/STEMI", "UFH, enoxaparin, or bivalirudin", "Match to PCI plan and bleeding risk"],
        ["Post-PCI", "DAPT 12 months typical", "Balance stent thrombosis vs bleeding"],
      ],
    },
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 3,
  },
  {
    id: "usmle-stroke-tpa",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "Acute Ischemic Stroke — tPA Window",
    teaser: "Time last known well → CT → treat eligible patients fast.",
    kind: "pearl",
    tags: ["stroke", "tPA", "CT"],
    body: "Non-contrast CT excludes hemorrhage; IV alteplase within 4.5 h for eligible patients.",
    bullets: [
      "Last known well defines clock — wake-up stroke often ineligible unless advanced imaging",
      "BP >185/110 must be lowered before tPA",
      "Major exclusions: recent surgery, active bleeding, prior ICH",
      "Endovascular thrombectomy up to 24 h in select large-vessel occlusion",
    ],
    practiceTopicSlug: "neurology-stroke",
    sortOrder: 4,
  },
  {
    id: "usmle-hyperkalemia",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "Electrolytes",
    title: "Hyperkalemia Emergency",
    teaser: "Stabilize myocardium → shift K⁺ → remove K⁺.",
    kind: "table",
    tags: ["potassium", "ECG", "dialysis"],
    body: "Peaked T waves → widened QRS → sine wave. Treat ECG changes urgently.",
    table: {
      headers: ["Step", "Agent", "Onset"],
      rows: [
        ["Stabilize", "Calcium gluconate/chloride", "Minutes"],
        ["Shift intracellular", "Insulin + dextrose", "~30 min"],
        ["Shift intracellular", "Albuterol, bicarbonate if acidemic", "Adjunct"],
        ["Remove", "Diuretics, patiromer, dialysis", "Hours"],
      ],
    },
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 5,
  },
  {
    id: "usmle-aki-fena",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "AKI",
    title: "Prerenal vs ATN (FeNa)",
    teaser: "BUN:Cr ratio and urine studies narrow AKI type.",
    kind: "fact",
    tags: ["AKI", "FeNa", "ATN"],
    body: "FeNa <1% favors prerenal; FeNa >2% favors ATN (unreliable on diuretics — use FEUrea).",
    bullets: [
      "Prerenal: dry mucosa, ↓ urine Na, responds to fluid bolus",
      "ATN: muddy brown casts, ischemic or nephrotoxic insult",
      "Postrenal: hydronephrosis — relieve obstruction (Foley, stent)",
      "Dialysis indications: AEIOU (Acidosis, Electrolytes, Ingestion, Overload, Uremia)",
    ],
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 6,
  },
  // —— MPJE ——
  {
    id: "mpje-cii-rules",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Controlled Substances",
    title: "Schedule II Essentials",
    teaser: "No refills. Strict Rx validity.",
    kind: "fact",
    tags: ["CII", "CSA", "prescribing"],
    body: "Written or compliant e-Rx; quantity must be written — no 'dispense as directed.'",
    bullets: [
      "No refills on CII",
      "Partial fills highly restricted (except qualifying scenarios)",
      "Emergency oral supply: narrow criteria + written follow-up within 7 days",
      "Quantity must be written in words and numbers — no 'dispense as directed'",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 1,
  },
  {
    id: "mpje-schedules",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Controlled Substances",
    title: "CSA Schedules at a Glance",
    teaser: "Abuse potential vs accepted medical use.",
    kind: "table",
    tags: ["CSA", "schedules", "MPJE"],
    body: "State law may be stricter — always apply the tighter standard on MPJE.",
    table: {
      headers: ["Schedule", "Refills (general)", "Example"],
      rows: [
        ["CII", "None", "Oxycodone, amphetamine"],
        ["CIII", "≤5 in 6 months", "Codeine/APAP combos"],
        ["CIV", "≤5 in 6 months", "Benzodiazepines"],
        ["CV", "Varies", "Low-abuse preparations"],
      ],
    },
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 2,
  },
  // —— NCLEX / Delegation (extra) ——
  {
    id: "nclex-five-rights",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Five Rights of Delegation",
    teaser: "NCLEX checklist before assigning any task.",
    kind: "fact",
    tags: ["delegation", "five-rights", "scope"],
    body: "All five must be satisfied — if one is missing, the RN keeps the task.",
    bullets: [
      "Right task — appropriate for delegatee scope",
      "Right circumstance — stable patient, adequate resources",
      "Right person — competent, trained, within scope",
      "Right direction — clear instructions and limits",
      "Right supervision — RN evaluates outcome",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 3,
  },
  {
    id: "nclex-never-delegate",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Never Delegate to UAP",
    teaser: "High-risk tasks that stay with the RN on NCLEX.",
    kind: "mistake",
    tags: ["delegation", "UAP", "insulin"],
    body: "When an answer assigns these to UAP, eliminate it.",
    bullets: [
      "Initial admission assessment",
      "Insulin administration",
      "Unstable vital signs or new acute changes",
      "Patient/family teaching",
      "Sterile procedures requiring nursing judgment",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 4,
  },
  {
    id: "nclex-scope-rn-lpn-uap",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "RN vs LPN vs UAP Scope",
    teaser: "Who can do what on NCLEX — stable vs unstable framing.",
    kind: "table",
    tags: ["delegation", "scope", "LPN", "UAP"],
    body: "When unsure, choose the most restrictive safe option — state nurse practice act always wins.",
    table: {
      headers: ["Activity", "RN", "LPN/LVN", "UAP"],
      rows: [
        ["Initial admission assessment", "Yes", "No", "No"],
        ["Medication administration", "Yes", "Per license", "No"],
        ["Insulin administration", "Yes", "Varies by state", "Never on NCLEX"],
        ["Patient/family teaching", "Yes", "Reinforce plan", "No"],
        ["ADLs on stable patient", "Yes", "Yes", "Yes"],
        ["Vital signs — unstable/post-op complication", "Yes", "No", "No"],
      ],
    },
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 5,
  },
  {
    id: "nclex-stable-unstable",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Stable vs Unstable — Delegate?",
    teaser: "Unpredictable outcomes stay with the RN.",
    kind: "table",
    tags: ["delegation", "stable", "unstable"],
    body: "Read the stem for unstable cues first — if present, pick the RN action.",
    table: {
      headers: ["Patient picture", "Delegate?", "Why"],
      rows: [
        ["Chronic HF, baseline VS, PT ambulation plan", "Often yes (ADL/VS)", "Predictable, stable"],
        ["Fresh post-op, oozing dressing, HR 118", "No", "Unstable — RN owns assessment"],
        ["New fever + rigors on chemo unit", "No", "Unpredictable — assess first"],
        ["LTC stable adult, routine I&O", "Often yes", "Stable, protocol-driven"],
      ],
    },
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 6,
  },
  {
    id: "nclex-supervision-eval",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Right Supervision & Evaluation",
    teaser: "Delegation is not handoff — the RN follows up.",
    kind: "pearl",
    tags: ["delegation", "supervision", "five-rights"],
    body: "Provide clear directions, confirm understanding, define when to report back, and evaluate the outcome. If the patient condition changes, reassess and reassign.",
    bullets: [
      "Specify what to do, parameters for escalation, and when to notify the RN",
      "If delegatee refuses or lacks competency — RN finds another solution",
      "Attractive NCLEX distractors assign tasks without supervision built in",
      "Re-delegate only after reassessing patient stability and delegatee competency",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 7,
  },
  {
    id: "nclex-delegation-decision-tree",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Delegation Decision Tree",
    teaser: "Four yes/no gates before assigning a task.",
    kind: "fact",
    tags: ["delegation", "five-rights", "NCLEX"],
    body: "Walk the stem through each gate — one failure means the RN keeps the task.",
    bullets: [
      "Is the patient stable with a predictable outcome?",
      "Is the task within the delegatee's scope and competency?",
      "Are circumstances appropriate (staffing, setting, resources)?",
      "Can you give clear direction and supervise/evaluate the result?",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 8,
  },
  // —— USMLE extras ——
  {
    id: "usmle-dka-orders",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA",
    title: "DKA Management Order",
    teaser: "Fluids before insulin if K⁺ is low.",
    kind: "pearl",
    tags: ["DKA", "insulin", "potassium"],
    body: "Start IV fluids → check K⁺ → insulin drip only if K⁺ ≥3.3 mEq/L.",
    bullets: [
      "Add dextrose when glucose ~200 to continue insulin until gap closes",
      "Gap closes when bicarbonate normalizes, not when glucose normalizes",
      "Search for trigger: infection, missed insulin, new-onset DM",
    ],
    practiceTopicSlug: "endocrine-dm",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 7,
  },
  {
    id: "usmle-hhs-vs-dka",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA / HHS",
    title: "DKA vs HHS",
    teaser: "Ketones and gap distinguish emergencies in hyperglycemia.",
    kind: "table",
    tags: ["DKA", "HHS", "hyperglycemia"],
    body: "Both need aggressive fluids; HHS has higher mortality and slower correction targets.",
    bullets: [
      "HHS: extreme hyperosmolarity, minimal ketosis, profound dehydration — correct sodium/glucose slowly",
      "DKA: insulin required once K⁺ ≥3.3; continue until anion gap closes",
      "Both: search for infection as trigger; monitor K⁺ closely during treatment",
    ],
    table: {
      headers: ["Feature", "DKA", "HHS"],
      rows: [
        ["Glucose", "Often >250", "Often >600"],
        ["Ketones / gap", "Present", "Minimal ketones, mild or no gap"],
        ["Dehydration", "Significant", "Profound"],
        ["Insulin", "Required once K⁺ safe", "Often lower doses; fluids first"],
      ],
    },
    practiceTopicSlug: "endocrine-dm",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 8,
  },
  {
    id: "usmle-cap-antibiotics",
    examSlug: "usmle",
    subject: "Pulmonary",
    topic: "Pneumonia",
    title: "CAP Antibiotic Choices",
    teaser: "Outpatient vs inpatient; cover atypicals when indicated.",
    kind: "table",
    tags: ["CAP", "pneumonia", "antibiotics"],
    body: "CURB-65 or PSI guides disposition; tailor to local resistance and comorbidities.",
    bullets: [
      "Outpatient: healthy + no comorbidities → amoxicillin or doxycycline/macrolide",
      "Inpatient non-ICU: beta-lactam + macrolide OR respiratory fluoroquinolone monotherapy",
      "Add pseudomonal coverage if structural lung disease, recent IV abx, or HCAP risk",
    ],
    table: {
      headers: ["Setting", "Typical regimen", "Add pseudomonas if"],
      rows: [
        ["Healthy outpatient", "Amoxicillin or doxy/macrolide", "N/A"],
        ["Comorbid outpatient", "Amox-clav + macrolide or resp fluoroquinolone", "Recent abx/hospitalization"],
        ["Inpatient non-ICU", "Beta-lactam + macrolide or FQ monotherapy", "Risk factors for resistant orgs"],
        ["ICU", "Beta-lactam + macrolide or FQ (+ MRSA/Pseudomonas if risk)", "Structural lung disease, HCAP risk"],
      ],
    },
    practiceTopicSlug: "pulmonary",
    sortOrder: 9,
  },
  {
    id: "usmle-meningitis-emergency",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Meningitis",
    title: "Bacterial Meningitis — Do Not Delay Abx",
    teaser: "Blood cultures then empiric antibiotics; add dexamethasone when indicated.",
    kind: "pearl",
    tags: ["meningitis", "ceftriaxone", "LP"],
    body: "If LP delayed, give empiric antibiotics after blood cultures — do not wait for CT/LP if unstable.",
    bullets: [
      "Adults: ceftriaxone + vancomycin (+ ampicillin if Listeria risk >50 or immunocompromised)",
      "Dexamethasone before or with first abx dose if suspected pneumococcal",
      "Petechiae + fever → treat as meningococcemia; isolate and prophylax contacts",
      "Immunocompromised or age >50: add ampicillin for Listeria coverage",
    ],
    practiceTopicSlug: "infectious-disease",
    sortOrder: 10,
  },
  {
    id: "usmle-tpa-exclusions",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "tPA — High-Yield Exclusions",
    teaser: "Eliminate wrong answers on stroke timing and bleeding risk.",
    kind: "mistake",
    tags: ["stroke", "tPA", "contraindications"],
    body: "When in doubt on Step 2 CK: recent intracranial surgery, active internal bleeding, or INR >1.7 excludes tPA.",
    bullets: [
      "Symptom onset >4.5 h (without advanced imaging protocol)",
      "Evidence of hemorrhage on CT",
      "Recent major surgery or GI/GU bleed",
      "Platelets <100k, glucose <50 (correct first)",
    ],
    practiceTopicSlug: "neurology-stroke",
    sortOrder: 11,
  },
  // —— MPJE extras ——
  {
    id: "mpje-recordkeeping",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Recordkeeping",
    title: "Controlled Substance Records",
    teaser: "Perpetual inventory and DEA Form 222 for CII.",
    kind: "fact",
    tags: ["DEA", "inventory", "CII"],
    body: "Two-year minimum retention; reconcile physical count to perpetual inventory.",
    bullets: [
      "DEA Form 222 for Schedule II orders (electronic CSOS in practice)",
      "Biennial inventory required",
      "Theft/loss: DEA Form 106 within one business day",
      "Biennial inventory reconciles perpetual book to physical count",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 3,
  },
  {
    id: "mpje-transfer-rules",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Transfers",
    title: "Rx Transfer Between Pharmacies",
    teaser: "One-time transfer rules differ by schedule.",
    kind: "mistake",
    tags: ["transfer", "CII", "refill"],
    body: "CII prescriptions generally cannot be transferred. CIII–CV may transfer once if remaining refills exist and both pharmacies document.",
    bullets: [
      "Verify patient identity and remaining refills before transfer",
      "Document transfer in both pharmacy records",
      "State law may prohibit transfer — apply stricter rule on MPJE",
      "One-time transfer only for CIII–CV when refills remain on the original Rx",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 4,
  },
  {
    id: "mpje-partial-fill-ciii",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Partial fills",
    title: "Partial Fills — CIII–CV vs CII",
    teaser: "Schedule determines whether partial dispensing is allowed.",
    kind: "table",
    tags: ["partial-fill", "CII", "CIII"],
    body: "MPJE loves schedule-specific partial fill traps.",
    bullets: [
      "Document quantity dispensed and balance remaining on the prescription",
      "CII partial fills limited to emergency supply scenarios — not routine",
      "Patient counseling required when balance remains for future fills",
    ],
    table: {
      headers: ["Schedule", "Partial fill", "Notes"],
      rows: [
        ["CII", "Highly restricted", "Emergency supply rules only — no routine partials"],
        ["CIII–CV", "Allowed if remaining balance documented", "Patient request or prescriber direction"],
        ["Non-controlled", "Per state/professional judgment", "Document quantity dispensed"],
      ],
    },
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 5,
  },
  {
    id: "mpje-expired-rx",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "Prescription validity",
    title: "Prescription Expiration Windows",
    teaser: "How long is an unfilled Rx valid?",
    kind: "fact",
    tags: ["validity", "expiration", "CII"],
    body: "Federal baseline — state law may shorten the window.",
    bullets: [
      "Schedule II: no refills; must be filled within 7 days of written date (eRx timing rules apply)",
      "Schedule III–V: valid up to 6 months from issue if refills authorized",
      "Do not dispense expired or altered prescriptions — verify with prescriber",
      "CII written date: typically must fill within 7 days (verify state/eRx rules)",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 6,
  },
  {
    id: "mpje-otp-basics",
    examSlug: "mpje",
    subject: "Pharmacy Law",
    topic: "OTP / methadone",
    title: "OTP Take-Home Dosing Basics",
    teaser: "Federal OTP rules for methadone maintenance.",
    kind: "pearl",
    tags: ["OTP", "methadone", "DEA"],
    body: "Only SAMHSA-certified OTPs dispense methadone for opioid use disorder maintenance.",
    bullets: [
      "Take-home doses require stability assessments and documented criteria",
      "Diversion control: bottle counts, callbacks, lock boxes when required",
      "State + federal OTP regulations apply — stricter standard wins",
      "Initial dosing observed in clinic; take-homes earned by stability and compliance",
    ],
    practiceTopicSlug: "federal-law",
    reviewModuleSlug: "controlled-substances",
    sortOrder: 7,
  },
  // —— Cross-exam utilities ——
  {
    id: "all-creatinine-clearance",
    examSlug: "naplex",
    subject: "Calculations",
    topic: "Renal dosing",
    title: "Cockcroft-Gault (CrCl)",
    teaser: "Estimate creatinine clearance for drug dosing.",
    kind: "equation",
    tags: ["calculation", "renal", "dosing"],
    body: "CrCl (mL/min) = [(140 − age) × weight (kg)] / [72 × SCr (mg/dL)] × 0.85 if female",
    bullets: [
      "Use ideal body weight if obese (often tested conceptually)",
      "Many renally cleared drugs use CrCl, not eGFR",
      "Round to one decimal for exam calculations; verify units (mg/dL for SCr)",
      "Adjust aminoglycosides, DOACs, metformin, and many antimicrobials at low CrCl",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 8,
  },
  {
    id: "all-anion-gap",
    examSlug: "usmle",
    subject: "Laboratory",
    topic: "Acid-base",
    title: "Anion Gap",
    teaser: "MUDPILES for elevated gap metabolic acidosis.",
    kind: "equation",
    tags: ["ABG", "acid-base", "MUDPILES"],
    body: "AG = Na⁺ − (Cl⁻ + HCO₃⁻). Normal ≈ 8–12 mEq/L.",
    bullets: [
      "MUDPILES: Methanol, Uremia, DKA, Propylene glycol, INH/Iron, Lactic acidosis, Ethylene glycol, Salicylates",
      "Normal anion gap acidosis: diarrhea (HCO₃⁻ loss), RTA, saline infusion",
      "Calculate delta gap to detect mixed disorders (ΔAG + ΔHCO₃⁻)",
      "Treat underlying cause — bicarbonate only if severe acidemia with caution",
    ],
    practiceTopicSlug: "renal-electrolytes",
    sortOrder: 12,
  },
  {
    id: "nclex-delegation",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "RN Accountability",
    teaser: "What you can and cannot delegate.",
    kind: "mistake",
    tags: ["delegation", "UAP", "scope"],
    body: "The RN remains accountable for all care. Never delegate assessment, teaching, or unstable clients inappropriately.",
    bullets: [
      "UAP: stable tasks (hygiene, ambulation with plan)",
      "LPN: stable predictable care per scope",
      "RN: assessment, triage, unstable patients",
      "Delegating does not transfer accountability — the RN owns the outcome",
    ],
    practiceTopicSlug: "delegation",
    reviewModuleSlug: "delegation",
    sortOrder: 9,
  },
];
