import type { MemoryCard } from "../types";

/** NPTE-PT memory cards — linked to deep-dive review modules and FSBPT subjects. */
export const NPTE_PT_MEMORY_CARDS: MemoryCard[] = [
  {
    id: "npte-rotator-cuff-testing",
    examSlug: "npte-pt",
    subject: "Musculoskeletal",
    topic: "Shoulder",
    title: "Rotator Cuff Special Tests",
    teaser: "Impingement vs cuff tear clusters.",
    kind: "fact",
    tags: ["shoulder", "msk", "examination"],
    body: "Combine painful arc, empty can weakness, and Hawkins-Kennedy for impingement; weakness with positive drop arm suggests full-thickness tear.",
    bullets: [
      "Painful arc 60–120° suggests subacromial impingement",
      "Empty can (Jobe) tests supraspinatus — less provocative than full can",
      "Drop arm test suggests large rotator cuff tear",
      "Scapular dyskinesis contributes to impingement — assess together",
    ],
    practiceTopicSlug: "musculoskeletal",
    reviewModuleSlug: "msk-rehabilitation",
    sortOrder: 1,
  },
  {
    id: "npte-lumbar-red-flags",
    examSlug: "npte-pt",
    subject: "Musculoskeletal",
    topic: "Spine",
    title: "Lumbar Red Flags",
    teaser: "Refer before aggressive treatment.",
    kind: "mistake",
    tags: ["spine", "msk", "safety"],
    body: "Cauda equina, progressive neuro deficit, fever with back pain, history of cancer, and unexplained weight loss require medical referral.",
    bullets: [
      "Saddle anesthesia + urinary retention → cauda equina emergency",
      "Peripheralization with repeated movements → stop directional preference trial",
      "Night pain unrelieved by position in older adults → consider malignancy workup",
    ],
    practiceTopicSlug: "musculoskeletal",
    reviewModuleSlug: "msk-rehabilitation",
    sortOrder: 2,
  },
  {
    id: "npte-tka-precautions",
    examSlug: "npte-pt",
    subject: "Musculoskeletal",
    topic: "Knee",
    title: "Post-TKA Early Rehab",
    teaser: "ROM, quad activation, swelling control.",
    kind: "fact",
    tags: ["knee", "post-op", "msk"],
    body: "Early goals: extension lag minimization, patellar mobility, quad activation, and ROM per surgeon protocol.",
    bullets: [
      "Quad sets and SLR when extensor lag controlled",
      "Ice and elevation for swelling management",
      "Avoid excessive flexion early per protocol",
      "Gait training with appropriate assistive device",
    ],
    practiceTopicSlug: "musculoskeletal",
    reviewModuleSlug: "msk-rehabilitation",
    sortOrder: 3,
  },
  {
    id: "npte-stroke-gait",
    examSlug: "npte-pt",
    subject: "Neuromuscular",
    topic: "Stroke",
    title: "Hemiplegic Gait Training",
    teaser: "Weight shift and terminal knee extension.",
    kind: "fact",
    tags: ["stroke", "gait", "neuro"],
    body: "Address hip extension in stance, adequate knee control, and arm swing as tolerated — high-repetition task practice.",
    bullets: [
      "Weight shift to paretic side in stance",
      "Terminal knee extension for stability",
      "Avoid circumduction-only strategy without proximal control",
      "Community ambulation needs curbs, distance, dual-task practice",
    ],
    practiceTopicSlug: "neuromuscular-nervous",
    reviewModuleSlug: "stroke-rehabilitation",
    sortOrder: 4,
  },
  {
    id: "npte-sci-autonomic",
    examSlug: "npte-pt",
    subject: "Neuromuscular",
    topic: "SCI",
    title: "Autonomic Dysreflexia",
    teaser: "T6 and above — hypertensive emergency.",
    kind: "mistake",
    tags: ["sci", "neuro", "safety"],
    body: "Noxious stimulus below lesion → severe headache and hypertension. Sit upright, loosen clothing, remove stimulus, monitor BP.",
    bullets: [
      "Common triggers: full bladder, bowel impaction, tight clothing",
      "Blood pressure can rise dangerously high",
      "Refer/activate emergency protocol if not resolving",
      "Teach patients and caregivers recognition",
    ],
    practiceTopicSlug: "neuromuscular-nervous",
    reviewModuleSlug: "stroke-rehabilitation",
    sortOrder: 5,
  },
  {
    id: "npte-parkinson-cues",
    examSlug: "npte-pt",
    subject: "Neuromuscular",
    topic: "Parkinson",
    title: "External Cueing",
    teaser: "Combat bradykinesia and freezing.",
    kind: "fact",
    tags: ["parkinson", "neuro", "gait"],
    body: "Auditory metronome, visual lines on floor, and rhythmic counting improve step length and reduce freezing episodes.",
    bullets: [
      "Large amplitude exercises (LSVT BIG principles)",
      "Dual-task training progresses after single-task mastery",
      "Freezing at doorways — use visual or verbal cues",
      "Medication timing affects best training window",
    ],
    practiceTopicSlug: "neuromuscular-nervous",
    reviewModuleSlug: "stroke-rehabilitation",
    sortOrder: 6,
  },
  {
    id: "npte-copd-breathing",
    examSlug: "npte-pt",
    subject: "Cardiopulmonary",
    topic: "COPD",
    title: "Pursed-Lip Breathing",
    teaser: "Reduce dynamic hyperinflation.",
    kind: "fact",
    tags: ["copd", "pulmonary", "breathing"],
    body: "Prolonged expiration through pursed lips reduces air trapping and dyspnea during exertion.",
    bullets: [
      "Inhale through nose, exhale 2–3× longer through pursed lips",
      "Use before and during functional activities",
      "Paced activities with planned rest breaks",
      "Bronchodilator timing before airway clearance",
    ],
    practiceTopicSlug: "cardiovascular-pulmonary",
    reviewModuleSlug: "cardiopulmonary-rehab",
    sortOrder: 7,
  },
  {
    id: "npte-copd-oxygen",
    examSlug: "npte-pt",
    subject: "Cardiopulmonary",
    topic: "Oxygen",
    title: "Oxygen Titration in COPD",
    teaser: "Avoid hyperoxia in retainers.",
    kind: "mistake",
    tags: ["copd", "oxygen", "pulmonary"],
    body: "Titrate supplemental oxygen to target SpO₂ per physician order; chronic retainers risk hypercapnia with excessive O₂.",
    bullets: [
      "Typical target 88–92% in chronic CO₂ retainers when ordered",
      "Monitor dyspnea and mental status during exercise",
      "RPE supplements pulse oximetry when HR blunted",
    ],
    practiceTopicSlug: "cardiovascular-pulmonary",
    reviewModuleSlug: "cardiopulmonary-rehab",
    sortOrder: 8,
  },
  {
    id: "npte-us-contraindications",
    examSlug: "npte-pt",
    subject: "Modalities",
    topic: "Ultrasound",
    title: "US Contraindications",
    teaser: "Screen before every application.",
    kind: "mistake",
    tags: ["ultrasound", "modalities", "safety"],
    body: "Avoid ultrasound over malignancy, pregnancy, acute infection, vascular insufficiency, and impaired sensation without monitoring.",
    bullets: [
      "Continuous US heats tissue — thermal risk in vulnerable areas",
      "Pulsed US for acute/subacute inflammation",
      "Never over epiphyseal plates in children unless prescribed",
    ],
    practiceTopicSlug: "therapeutic-modalities",
    reviewModuleSlug: "therapeutic-modalities",
    sortOrder: 9,
  },
  {
    id: "npte-cane-side",
    examSlug: "npte-pt",
    subject: "Equipment",
    topic: "Ambulatory Aids",
    title: "Cane Placement",
    teaser: "Contralateral to involved LE.",
    kind: "fact",
    tags: ["equipment", "gait", "assistive-device"],
    body: "Standard cane is used on the strong/uninvolved side to widen BOS and unload the involved limb.",
    bullets: [
      "Cane height: wrist crease with arm at side",
      "Advance cane with involved LE in gait cycle",
      "Walker provides maximal stability; assess cognition and UE strength",
    ],
    practiceTopicSlug: "equipment-devices",
    sortOrder: 10,
  },
  {
    id: "npte-fall-risk-tug",
    examSlug: "npte-pt",
    subject: "Safety",
    topic: "Falls",
    title: "Timed Up and Go",
    teaser: "Screen community fall risk.",
    kind: "fact",
    tags: ["falls", "safety", "outcome-measure"],
    body: "TUG >12 seconds suggests increased fall risk; combine with Berg Balance Scale and history.",
    bullets: [
      "Observe rise, walk 3 meters, turn, return, sit",
      "≥13.5 seconds linked to higher fall risk in many populations",
      "Environmental modification follows positive screen",
    ],
    practiceTopicSlug: "safety-protection",
    sortOrder: 11,
  },
  {
    id: "npte-referral-scope",
    examSlug: "npte-pt",
    subject: "Professional",
    topic: "Scope",
    title: "When to Refer",
    teaser: "Findings outside PT scope.",
    kind: "fact",
    tags: ["professional", "ethics", "referral"],
    body: "Refer when presentation suggests medical pathology beyond PT scope, non-response to skilled intervention, or need for diagnostic workup.",
    bullets: [
      "Unexplained neuro deficit, fever, unexplained weight loss",
      "Chest pain, signs of DVT/PE during rehab",
      "Document rationale and communicate with physician",
    ],
    practiceTopicSlug: "professional-responsibilities",
    sortOrder: 12,
  },
];
