import type { MemoryCard } from "../types";

/** Static Memory Card library — seed to DB later if needed. */
export const MEMORY_CARDS: MemoryCard[] = [
  // —— NAPLEX / Heart Failure ——
  {
    id: "naplex-hf-four-pillars",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "HFrEF Four Pillars (GDMT)",
    teaser: "Mortality-reducing drug classes every pharmacist must know.",
    kind: "table",
    tags: ["GDMT", "HFrEF", "mortality"],
    body: "Start low, go slow. Diuretics treat congestion but are not a mortality pillar.",
    table: {
      headers: ["Pillar", "Examples", "Monitor"],
      rows: [
        ["RAAS inhibitor", "ACEi / ARB / ARNI", "BP, Cr, K⁺"],
        ["Beta-blocker", "Carvedilol, metoprolol succinate, bisoprolol", "HR, BP"],
        ["MRA", "Spironolactone, eplerenone", "K⁺, Cr"],
        ["SGLT2i", "Dapagliflozin, empagliflozin", "Volume, infections"],
      ],
    },
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 1,
  },
  {
    id: "naplex-arni-washout",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "ARNI Switch Rule",
    teaser: "Sacubitril/valsartan requires ACEi washout.",
    kind: "mistake",
    tags: ["ARNI", "ACEi", "angioedema"],
    body: "Stop ACE inhibitor → wait 36 hours → start sacubitril/valsartan. Never combine ACEi + ARNI.",
    bullets: [
      "Do not combine ACEi + ARB + ARNI",
      "Elevated BNP on ARNI is expected (neprilysin inhibition)",
      "Washout prevents bradykinin-mediated angioedema when switching from ACEi",
      "If angioedema history on ACEi — ARNI is generally contraindicated",
    ],
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 2,
  },
  {
    id: "naplex-loop-diuretics",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Diuretics",
    title: "Loop Diuretic Equivalents",
    teaser: "Bioavailability matters when furosemide fails.",
    kind: "conversion",
    tags: ["diuretics", "furosemide", "bumetanide"],
    body: "Approximate oral conversions (varies by patient):",
    table: {
      headers: ["Drug", "Oral dose", "Notes"],
      rows: [
        ["Furosemide", "40 mg", "Variable absorption (~50%)"],
        ["Bumetanide", "1 mg", "≈ 40 mg furosemide"],
        ["Torsemide", "20 mg", "Better bioavailability"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 3,
  },
  {
    id: "naplex-bb-start-rule",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "Beta-Blocker Start Rule (HFrEF)",
    teaser: "Euvolemic first — only the three proven agents.",
    kind: "pearl",
    tags: ["GDMT", "beta-blocker", "HFrEF"],
    body: "Initiate beta-blocker only when the patient is euvolemic — not during acute decompensation. Uptitrate slowly to target dose.",
    bullets: [
      "Mortality-proven agents only: carvedilol, metoprolol succinate (NOT tartrate), bisoprolol",
      "Hold or do not uptitrate during active pulmonary edema or cardiogenic shock",
      "Metoprolol tartrate lacks HFrEF mortality data — succinate ER is the evidence-based formulation",
    ],
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 4,
  },
  {
    id: "naplex-k-hyperkalemia",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "MRA + ACEi Hyperkalemia Management",
    teaser: "Expected on GDMT — treat without abandoning pillars.",
    kind: "pearl",
    tags: ["potassium", "MRA", "ACEi", "GDMT"],
    body: "Combining RAAS inhibitor with MRA raises hyperkalemia risk — monitor K⁺ and manage without unnecessary GDMT discontinuation.",
    bullets: [
      "Check K⁺ and Cr within 1 week of starting or dose-changing MRA + ACEi/ARB",
      "Mild hyperkalemia (5.0–5.5): dietary K⁺ restriction, reduce MRA dose, consider patiromer/SPS",
      "Avoid triple RAAS blockade (ACEi + ARB + MRA) — no benefit, high K⁺ risk",
      "Severe hyperkalemia with ECG changes: calcium stabilization, insulin + dextrose, then remove K⁺",
    ],
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 5,
  },
  {
    id: "naplex-sglt2i-periop-dka",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "SGLT2i Perioperative Hold",
    teaser: "Hold before surgery; watch for euglycemic DKA.",
    kind: "mistake",
    tags: ["SGLT2i", "DKA", "perioperative"],
    body: "SGLT2 inhibitors reduce HF hospitalization but require perioperative management and patient counseling on rare euglycemic DKA.",
    bullets: [
      "Hold dapagliflozin/empagliflozin 3–4 days before elective surgery",
      "Euglycemic DKA: normal or mildly elevated glucose + ketosis — suspect on SGLT2i, especially peri-op/fasting",
      "Resume when eating and clinically stable; counsel on genital mycotic infections",
    ],
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 6,
  },
  {
    id: "naplex-digoxin-toxicity",
    examSlug: "naplex",
    subject: "Cardiology",
    topic: "Heart Failure",
    title: "Digoxin Toxicity Triggers",
    teaser: "Hypokalemia lowers the therapeutic threshold.",
    kind: "fact",
    tags: ["digoxin", "toxicity", "hypokalemia"],
    body: "Digoxin has a narrow therapeutic index; toxicity risk rises when potassium is low or renal clearance falls.",
    bullets: [
      "Hypokalemia potentiates digoxin toxicity — common with loop diuretics + MRA/ACEi",
      "Renal impairment reduces clearance — reduce dose and monitor levels",
      "Toxicity signs: nausea, vision changes (yellow halos), arrhythmias (PVCs, AV block)",
      "Hold digoxin; treat hyperkalemia if present; digoxin Fab for life-threatening toxicity",
    ],
    practiceTopicSlug: "cardiovascular-rx",
    reviewModuleSlug: "heart-failure-gdmt",
    sortOrder: 7,
  },
  // —— NAPLEX / Anticoagulation ——
  {
    id: "naplex-reversal-chart",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Anticoagulant Reversal",
    teaser: "Match the reversal agent to the drug on board.",
    kind: "table",
    tags: ["reversal", "DOAC", "warfarin"],
    body: "Life-threatening bleeding — stop drug first, then reverse.",
    bullets: [
      "Hold anticoagulant immediately; support ABCs and source control",
      "PCC preferred over FFP for warfarin reversal when available",
      "Andexanet is agent-specific for factor Xa inhibitors — costly but targeted",
      "Document time of last dose — guides urgency and agent choice",
    ],
    table: {
      headers: ["Anticoagulant", "Reversal"],
      rows: [
        ["Warfarin", "4-factor PCC + vitamin K"],
        ["Dabigatran", "Idarucizumab (or PCC)"],
        ["Rivaroxaban / Apixaban", "Andexanet alfa or PCC"],
        ["Heparin / LMWH", "Protamine (partial for LMWH)"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 9,
  },
  {
    id: "naplex-hit-rule",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "HIT Type 2",
    teaser: "Thrombocytopenia + thrombosis — stop all heparin.",
    kind: "mistake",
    tags: ["HIT", "heparin", "argatroban"],
    body: "Immune-mediated HIT: stop heparin (including flushes) → non-heparin anticoagulant (argatroban, bivalirudin, fondaparinux). Do not start warfarin alone.",
    bullets: [
      "4T score helps probability: Thrombocytopenia, Timing, Thrombosis, oTher causes",
      "Stop all heparin — including line flushes and heparin-coated catheters",
      "Start direct thrombin inhibitor or fondaparinux — never warfarin alone (limb gangrene risk)",
      "Platelets often fall 5–10 days after heparin exposure; thrombosis may precede severe drop",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 10,
  },
  {
    id: "naplex-doac-renal-dose",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "DOAC Renal Dose Adjustment",
    teaser: "CrCl thresholds differ by agent — know the cutoffs.",
    kind: "table",
    tags: ["DOAC", "renal", "dosing"],
    body: "Renally cleared DOACs need dose reduction or avoidance at low CrCl. Apixaban uses the 2-of-3 rule.",
    table: {
      headers: ["Agent", "CrCl threshold", "Action"],
      rows: [
        ["Apixaban", "≤50 mL/min (standard dose)", "Reduce to 2.5 mg BID if 2 of 3: age ≥80, weight ≤60 kg, SCr ≥1.5"],
        ["Rivaroxaban", "≤50 mL/min (VTE/AF)", "Reduce dose per indication; avoid if CrCl <15"],
        ["Dabigatran", "≤50 mL/min", "Reduce dose; avoid if CrCl <15–30 (per labeling/indication)"],
        ["Edoxaban", "≤50 mL/min", "Reduce to 30 mg daily; avoid if CrCl >95 (reduced efficacy)"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 11,
  },
  {
    id: "naplex-warfarin-vs-doac",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Warfarin vs DOAC Selection",
    teaser: "Mechanical mitral valve stays on warfarin.",
    kind: "pearl",
    tags: ["warfarin", "DOAC", "selection"],
    body: "DOACs offer fixed dosing and fewer interactions for most VTE/AF patients; warfarin remains mandatory in select scenarios.",
    bullets: [
      "Warfarin required: mechanical mitral valve, moderate-severe mitral stenosis",
      "DOACs preferred for most AF and VTE when renal function allows — no routine monitoring",
      "Warfarin needs INR monitoring; many drug/food interactions; established reversal (PCC + vitamin K)",
      "Severe renal impairment: warfarin often usable; dabigatran most renally cleared — highest caution",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 12,
  },
  {
    id: "naplex-ufh-lmwh-monitor",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "UFH vs LMWH Monitoring",
    teaser: "aPTT for UFH; anti-Xa for LMWH when indicated.",
    kind: "table",
    tags: ["heparin", "enoxaparin", "monitoring"],
    body: "LMWH has predictable kinetics; routine monitoring is not needed except in renal impairment, obesity, or pregnancy.",
    table: {
      headers: ["Agent", "Monitor", "Goal / Pearl"],
      rows: [
        ["UFH IV", "aPTT (or anti-Xa)", "Per institutional nomogram; anti-Xa if aPTT unreliable"],
        ["UFH SC", "aPTT if therapeutic intent", "Less common than IV monitoring"],
        ["LMWH (enoxaparin)", "Anti-Xa (peak)", "Consider if CrCl <30, obesity, pregnancy"],
        ["LMWH reversal", "Protamine", "Partial (~60%) anti-Xa neutralization"],
      ],
    },
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 13,
  },
  {
    id: "naplex-bridge-therapy",
    examSlug: "naplex",
    subject: "Pharmacology",
    topic: "Anticoagulation",
    title: "Bridge Therapy Basics",
    teaser: "Bridge high thrombotic risk — not low risk.",
    kind: "fact",
    tags: ["bridge", "warfarin", "perioperative"],
    body: "Perioperative bridging with LMWH/UFH is reserved for patients at high thrombotic risk when warfarin is held.",
    bullets: [
      "Bridge when high risk: mechanical mitral valve, recent VTE (<3 mo), CHA₂DS₂-VASc with recent stroke",
      "Do NOT bridge most AF patients — bleeding risk outweighs benefit in moderate-risk AF",
      "Hold warfarin ~5 days pre-op; last LMWH dose ~24 h before (high bleeding) or ~12 h (moderate)",
      "Resume warfarin post-op when hemostasis achieved; overlap parenteral agent until INR therapeutic",
    ],
    practiceTopicSlug: "pharmacology",
    reviewModuleSlug: "anticoagulation-reversal",
    sortOrder: 14,
  },
  // —— NAPLEX / Diabetes ——
  {
    id: "naplex-insulin-kinetics",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Insulin Onset / Peak / Duration",
    teaser: "Match insulin type to meal timing and basal needs.",
    kind: "table",
    tags: ["insulin", "kinetics", "basal-bolus"],
    body: "Rapid analogs cover meals; basal analogs provide background coverage without pronounced peak.",
    table: {
      headers: ["Type", "Examples", "Onset", "Peak", "Duration"],
      rows: [
        ["Rapid", "Lispro, aspart, glulisine", "~15 min", "~1–2 h", "~3–5 h"],
        ["Regular", "Regular human", "~30 min", "2–4 h", "5–8 h"],
        ["NPH", "NPH", "1–2 h", "4–12 h", "12–18 h"],
        ["Basal", "Glargine, detemir, degludec", "1–4 h", "Minimal", "Up to 24–42 h"],
      ],
    },
    practiceTopicSlug: "endocrine-rx",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 15,
  },
  {
    id: "naplex-metformin-hold",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Metformin Hold Rules",
    teaser: "Renal function and contrast dictate hold timing.",
    kind: "mistake",
    tags: ["metformin", "eGFR", "contrast"],
    body: "Metformin is first-line for T2DM but must be held or dose-reduced as renal function declines.",
    bullets: [
      "eGFR ≥45: continue with routine monitoring",
      "eGFR 30–44: reduce dose; reassess benefits/risks",
      "eGFR <30: contraindicated — discontinue",
      "Iodinated contrast: hold at time of procedure if eGFR 30–60 or AKI risk; restart after 48 h if stable",
    ],
    practiceTopicSlug: "endocrine-rx",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 16,
  },
  {
    id: "naplex-hypoglycemia-15-15",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Hypoglycemia 15-15 Rule",
    teaser: "15 grams of carb, recheck in 15 minutes.",
    kind: "pearl",
    tags: ["hypoglycemia", "counseling", "insulin"],
    body: "Treat hypoglycemia (<70 mg/dL) with fast-acting carbohydrate; repeat until glucose ≥70 mg/dL.",
    bullets: [
      "15 g fast-acting carb: 4 glucose tabs, 4 oz juice, or hard candy",
      "Recheck glucose in 15 minutes; repeat if still <70",
      "Once ≥70: small snack if next meal >1 hour away",
      "Severe/unconscious: glucagon IM/SC or intranasal; call emergency services",
    ],
    practiceTopicSlug: "endocrine-rx",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 17,
  },
  {
    id: "naplex-sglt2i-counseling",
    examSlug: "naplex",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "SGLT2i Patient Counseling",
    teaser: "Infections, surgery hold, and euglycemic DKA warning.",
    kind: "pearl",
    tags: ["SGLT2i", "counseling", "DKA"],
    body: "SGLT2 inhibitors offer glycemic, CV, and renal benefits but require proactive patient education.",
    bullets: [
      "Genital mycotic infections (yeast/UTI-like symptoms) — maintain hygiene, seek treatment early",
      "Hold 3–4 days before elective surgery; resume when eating and stable",
      "Euglycemic DKA: report nausea, vomiting, abdominal pain even if glucose is normal",
      "Stay hydrated; sick-day rules apply — do not stop insulin without provider guidance",
    ],
    practiceTopicSlug: "endocrine-rx",
    reviewModuleSlug: "insulin-diabetes-management",
    sortOrder: 18,
  },
  // —— NAPLEX / Infectious Disease ——
  {
    id: "naplex-abx-spectrum-ladder",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Antimicrobial Coverage",
    title: "Beta-Lactam Spectrum Ladder",
    teaser: "1-2-3-4-5: generations climb as gram-negative coverage expands.",
    kind: "table",
    tags: ["beta-lactam", "cephalosporin", "spectrum", "ceftriaxone", "cefazolin"],
    body: "Match spectrum to the bug, not habit. Penicillins excel at streptococci; cephalosporin generation predicts gram-negative reach; carbapenems are the nuclear option.",
    table: {
      headers: ["Class / Gen", "Key agents", "Covers well", "Misses / gaps"],
      rows: [
        ["Natural penicillins", "Penicillin G/V", "Strep, syphilis", "Staph (most), gram-neg rods"],
        ["Aminopenicillins", "Ampicillin, amox", "+ Listeria, Enterococcus", "MRSA, Pseudomonas"],
        ["Antistaph penicillins", "Nafcillin, oxacillin", "MSSA", "Gram-neg, MRSA"],
        ["1st-gen ceph", "Cefazolin", "MSSA, strep", "Enterococcus, anaerobes (B. frag)"],
        ["3rd-gen ceph", "Ceftriaxone, ceftazidime", "Strep, many GNR; ceftazidime = Pseudomonas", "MRSA, ESBL (variable)"],
        ["4th-gen ceph", "Cefepime", "Broad GNR + Pseudomonas", "MRSA, ESBL (better than 3rd gen)"],
        ["Carbapenems", "Meropenem, ertapenem", "ESBL, anaerobes, broad GNR", "MRSA; ertapenem lacks Pseudomonas/Acinetobacter"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 19,
  },
  {
    id: "naplex-cap-empiric",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Community-Acquired Pneumonia",
    title: "CAP Empiric Regimens",
    teaser: "Outpatient = macrolide or doxy; inpatient adds beta-lactam backbone.",
    kind: "table",
    tags: ["CAP", "pneumonia", "azithromycin", "ceftriaxone", "levofloxacin"],
    body: "CAP therapy hinges on severity, comorbidities, and local resistance. Always cover typical + atypical pathogens; add MRSA/Pseudomonas only when risk factors exist.",
    table: {
      headers: ["Setting", "Regimen", "Mnemonic / pearl"],
      rows: [
        ["Healthy outpatient", "Amoxicillin 1 g TID or doxycycline or macrolide", "Macrolide only if local resistance <25%"],
        ["Outpatient + comorbidity", "Amox-clav or cephalosporin + macrolide OR respiratory FQ monotherapy", "Dual therapy covers atypicals"],
        ["Inpatient non-ICU", "Beta-lactam (ceftriaxone/amp-sulb) + macrolide OR respiratory FQ", "Add MRSA only if risk factors"],
        ["ICU", "Beta-lactam + macrolide OR beta-lactam + FQ; add vanc/linezolid if MRSA risk", "Pseudomonas coverage if structural lung disease"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 20,
  },
  {
    id: "naplex-mrsa-agents",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "MRSA",
    title: "MRSA Agent Selection",
    teaser: "VAN-CO in blood; LINE for lungs; DAP-TOM for skin — never DAP in pneumonia.",
    kind: "table",
    tags: ["MRSA", "vancomycin", "daptomycin", "linezolid", "ceftaroline"],
    body: "Vancomycin remains first-line for most serious MRSA, but tissue penetration and MIC creep matter. Match the agent to infection site and resistance pattern.",
    table: {
      headers: ["Agent", "Best use", "Key trap"],
      rows: [
        ["Vancomycin", "Bacteremia, most serious infections", "Monitor AUC/MIC; nephrotoxicity; slow response if MIC ≥2"],
        ["Daptomycin", "Bacteremia, endocarditis, skin/soft tissue", "INACTIVATED by pulmonary surfactant — not for pneumonia"],
        ["Linezolid", "Pneumonia, skin, oral step-down", "Weak MAOI — serotonin syndrome with SSRIs; myelosuppression with prolonged use"],
        ["Ceftaroline", "MRSA pneumonia, complicated skin", "Broad but reserved; C. diff risk like other beta-lactams"],
        ["TMP-SMX", "Mild skin, step-down if susceptible", "Hyperkalemia, sulfa allergy, inadequate for bacteremia as monotherapy"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 21,
  },
  {
    id: "naplex-daptomycin-lung-trap",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "MRSA",
    title: "Daptomycin Pneumonia Trap",
    teaser: "DAP-TOM dissolves in surfactant — use LINE or VAN for MRSA pneumonia.",
    kind: "mistake",
    tags: ["daptomycin", "MRSA", "pneumonia", "linezolid"],
    body: "Daptomycin binds pulmonary surfactant and cannot achieve therapeutic concentrations in alveolar lining fluid — it will fail for pneumonia despite in-vitro susceptibility.",
    bullets: [
      "MRSA pneumonia: vancomycin or linezolid (or ceftaroline) — not daptomycin",
      "Daptomycin excels for bacteremia, right-sided endocarditis, and skin/soft tissue",
      "Check CPK weekly on daptomycin — myopathy risk, hold if CPK >5× ULN with symptoms",
      "If pneumonia + bacteremia: treat pneumonia with vanc/linezolid; daptomycin alone is insufficient for the lung source",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 22,
  },
  {
    id: "naplex-pseudomonas-coverage",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Antimicrobial Coverage",
    title: "Pseudomonas Coverage Ladder",
    teaser: "PIP-TAZO → FEP → CIP — double-cover only when severe or prior MDR.",
    kind: "table",
    tags: ["Pseudomonas", "piperacillin-tazobactam", "cefepime", "ciprofloxacin", "meropenem"],
    body: "Pseudomonas aeruginosa drives empiric broadening in HAP/VAP, febrile neutropenia, and structural lung disease. De-escalate once cultures return.",
    table: {
      headers: ["Agent", "Route", "Pearl"],
      rows: [
        ["Piperacillin-tazobactam", "IV", "Workhorse empiric; adjust for renal function"],
        ["Cefepime", "IV", "Anti-pseudomonal cephalosporin; neurotoxicity at high doses/renal failure"],
        ["Ceftazidime", "IV", "3rd-gen anti-pseudomonal; less ESBL stability than cefepime"],
        ["Ciprofloxacin / levofloxacin", "IV/PO", "Oral step-down when susceptible; resistance common"],
        ["Meropenem", "IV", "Carbapenem reserve; covers ESBL + Pseudomonas (check local resistance)"],
        ["Aztreonam", "IV", "Monobactam — gram-neg only; safe in penicillin allergy (no cross-reactivity)"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 23,
  },
  {
    id: "naplex-uti-pyelonephritis",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Urinary Tract Infections",
    title: "UTI & Pyelonephritis Therapy",
    teaser: "Uncomplicated cystitis = narrow PO; pyelo = fluoroquinolone or ceftriaxone.",
    kind: "table",
    tags: ["UTI", "pyelonephritis", "nitrofurantoin", "TMP-SMX", "ceftriaxone"],
    body: "Match drug to syndrome and local resistance. Nitrofurantoin and fosfomycin do not achieve renal tissue levels — never use for pyelonephritis.",
    table: {
      headers: ["Syndrome", "First-line (if susceptible)", "Avoid / trap"],
      rows: [
        ["Uncomplicated cystitis (women)", "Nitrofurantoin ×5 d, TMP-SMX ×3 d, or fosfomycin ×1", "Fluoroquinolones reserved — resistance + harm"],
        ["Pyelonephritis outpatient", "Oral fluoroquinolone (if local resistance low) or ceftriaxone IM/IV then PO step-down", "Nitrofurantoin, fosfomycin — inadequate tissue levels"],
        ["Pyelonephritis inpatient", "Ceftriaxone or fluoroquinolone ± ampicillin if Enterococcus concern", "Adjust for renal function; culture-directed de-escalation"],
        ["Complicated UTI / catheter", "Culture-guided; often pip-tazo or ceftriaxone empirically", "Treat bacteriuria without symptoms only in pregnancy or pre-urologic procedure"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 24,
  },
  {
    id: "naplex-cdiff-treatment",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "C. difficile",
    title: "C. diff Treatment by Severity",
    teaser: "PO vanc for all severities; fidaxomicin if recurrent; avoid metronidazole first-line.",
    kind: "table",
    tags: ["C. diff", "vancomycin", "fidaxomicin", "metronidazole", "stewardship"],
    body: "Oral vancomycin or fidaxomicin are first-line for initial and recurrent C. diff. IV metronidazole does not reach colonic lumen — PO/IV vanc for fulminant with ileus (PO + rectal).",
    table: {
      headers: ["Severity", "Regimen", "Pearl"],
      rows: [
        ["Initial, non-severe", "Oral vancomycin 125 mg QID ×10 d OR fidaxomicin BID", "Stop inciting antibiotic when possible"],
        ["Initial, severe", "Oral vancomycin 125 mg QID", "Metronidazole no longer preferred first-line"],
        ["Fulminant / shock", "Oral/rectal vancomycin 500 mg QID + IV metronidazole 500 mg q8h", "Surgery consult if megacolon, perforation"],
        ["First recurrence", "Fidaxomicin or tapered/pulsed oral vancomycin", "Bezlotoxumab for high recurrence risk (optional adjunct)"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 25,
  },
  {
    id: "naplex-penicillin-allergy",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Drug Allergy",
    title: "Penicillin Allergy Cross-Reactivity",
    teaser: "True anaphylaxis → 1–2% cephalosporin cross-reactivity; most 'allergies' are not IgE.",
    kind: "pearl",
    tags: ["penicillin", "allergy", "cephalosporin", "cross-reactivity"],
    body: "Up to 10% of patients carry a penicillin allergy label, but >90% are not truly IgE-mediated. Mislabeling drives unnecessary broad-spectrum use and worse outcomes.",
    bullets: [
      "Low-risk history (rash only, childhood, remote): many patients tolerate beta-lactams; consider allergy delabeling or graded challenge",
      "Confirmed anaphylaxis: ~1–2% cross-reactivity with cephalosporins (shared R1 side chain matters more than class)",
      "Carbapenems: <1% cross-reactivity even with penicillin anaphylaxis — often safe with monitoring",
      "Aztreonam has no cross-reactivity with penicillins — safe in penicillin allergy for gram-neg coverage",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 26,
  },
  {
    id: "naplex-aminoglycoside-pae",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Aminoglycosides",
    title: "Aminoglycoside Once-Daily & PAE",
    teaser: "Peak kills; PAE lets you dose high once — monitor trough + renal.",
    kind: "pearl",
    tags: ["aminoglycoside", "gentamicin", "PAE", "pharmacokinetics"],
    body: "Aminoglycosides are concentration-dependent bactericidal agents with a post-antibiotic effect (PAE): bacterial suppression continues after levels fall below MIC.",
    bullets: [
      "Once-daily (extended-interval) dosing maximizes peak:MIC ratio and minimizes nephrotoxicity vs traditional q8h",
      "Monitor trough (target <1 for gentamicin/tobramycin) and SCr — adjust or hold if rising creatinine",
      "Synergy with beta-lactams for enterococcal endocarditis — low-dose gentamicin short course",
      "Avoid with other nephrotoxins (vancomycin, contrast, NSAIDs); once-daily does not eliminate ototoxicity risk",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 27,
  },
  {
    id: "naplex-fq-boxed-warnings",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Fluoroquinolones",
    title: "Fluoroquinolone Boxed Warnings",
    teaser: "CIPRO = CIP tendon ROPture; reserve FQs for when alternatives fail.",
    kind: "mistake",
    tags: ["fluoroquinolone", "ciprofloxacin", "levofloxacin", "tendon", "QT"],
    body: "FDA boxed warnings: tendinitis/tendon rupture, peripheral neuropathy, CNS effects, QT prolongation, aortic aneurysm, and glucose dysregulation. Reserve for situations without safer alternatives.",
    bullets: [
      "Mnemonic: CIPRO = CIP (central nervous system, glucose, QT) tendon ROP (rupture, neuropathy, aortic)",
      "Highest tendon risk: age >60, corticosteroids, renal failure, solid organ transplant",
      "Do not use for uncomplicated cystitis or acute bronchitis when alternatives exist (stewardship)",
      "Drug interactions: QT prolongation with macrolides, azoles, antiarrhythmics; chelate with cations (separate by 2 h)",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 28,
  },
  {
    id: "naplex-vanc-auc",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Vancomycin",
    title: "Vancomycin Dosing & AUC Monitoring",
    teaser: "Load 25–30 mg/kg → AUC/MIC 400–600; never trough-only for serious MRSA.",
    kind: "table",
    tags: ["vancomycin", "AUC", "loading dose", "MRSA", "nephrotoxicity"],
    body: "Vancomycin requires loading dose, renal-based interval adjustment, and AUC/MIC-guided monitoring for serious MRSA. Red man syndrome is prevented by infusing ≥60 minutes.",
    table: {
      headers: ["Step", "Guideline", "NAPLEX pearl"],
      rows: [
        ["Loading dose", "25–30 mg/kg IV (max 3 g) for serious MRSA", "Calculate mg/kg first; cap at 3,000 mg"],
        ["Maintenance", "Start q12 h if CrCl ≥50; extend as CrCl falls", "Use Cockcroft-Gault CrCl — not eGFR alone"],
        ["Monitoring", "AUC/MIC 400–600 mg·h/L (MIC=1)", "Bayesian or two-level sampling preferred"],
        ["Trough surrogate", "15–20 mg/L only if AUC unavailable", "Single trough × 12 ≈ rough AUC estimate"],
        ["Toxicity", "Nephrotoxicity + red man syndrome", "Slow infusion; avoid pip-tazo + vanc combo when possible"],
      ],
    },
    bullets: [
      "Mnemonic: 'LOAD then AUC' — Loading dose → Adjust for CrCl → Observe levels → De-escalate duration",
      "Check steady-state level around the 4th dose (before 5th dose)",
      "Oral vancomycin for C. diff does NOT apply these IV kinetics — different indication entirely",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 29,
  },
  {
    id: "naplex-hiv-oi-prophylaxis",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "HIV",
    title: "HIV OI Prophylaxis (CD4 Thresholds)",
    teaser: "Below 200 = PCP; below 100 = toxo + MAC; below 50 = MAC + crypto screen.",
    kind: "table",
    tags: ["HIV", "PCP", "toxoplasmosis", "MAC", "TMP-SMX"],
    body: "Opportunistic infection prophylaxis depends on CD4 count. TMP-SMX double-strength daily covers PCP and toxoplasmosis — the workhorse prophylactic.",
    table: {
      headers: ["CD4 threshold", "Prophylaxis", "Agent"],
      rows: [
        ["<200 cells/µL", "PCP", "TMP-SMX DS daily (preferred); alt: dapsone, atovaquone"],
        ["<100 cells/µL", "Toxoplasmosis (if IgG+)", "TMP-SMX covers both PCP + toxo"],
        ["<100 cells/µL", "MAC", "Azithromycin weekly (after PCP prophylaxis established)"],
        ["<50 cells/µL", "MAC + crypto screening", "Azithromycin; check CrAg; fluconazole if CrAg+"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 30,
  },
  {
    id: "naplex-art-first-line",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "HIV",
    title: "HIV ART First-Line & Rifampin Trap",
    teaser: "INSTI + 2 NRTIs; rifampin slashes INSTI levels — boost or switch.",
    kind: "pearl",
    tags: ["HIV", "ART", "bictegravir", "dolutegravir", "rifampin"],
    body: "Modern first-line ART uses integrase strand transfer inhibitors (INSTIs) plus two NRTIs. Drug interactions with rifampin for TB co-infection are a classic NAPLEX trap.",
    bullets: [
      "Common first-line: bictegravir/TAF/FTC (Biktarvy) or dolutegravir + TAF/FTC — single-tablet regimens",
      "Rifampin potent CYP3A4 inducer: reduces dolutegravir/bictegravir levels — double INSTI dose or use alternative",
      "TAF preferred over TDF when CKD or osteoporosis risk; check HBV status before stopping TAF/FTC (hepatitis flare)",
      "Pharmacist role: adherence counseling, interaction checks, resistance testing before switch",
    ],
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 31,
  },
  {
    id: "naplex-abx-renal-dosing",
    examSlug: "naplex",
    subject: "Infectious Disease",
    topic: "Renal Dosing",
    title: "Antimicrobial Renal Adjustments",
    teaser: "Vanc, aminoglycosides, FQs, and most beta-lactams need CrCl review.",
    kind: "table",
    tags: ["renal", "dosing", "vancomycin", "gentamicin", "CrCl"],
    body: "Renal impairment demands dose or interval adjustment for many antimicrobials. Always calculate CrCl before confirming renally cleared regimens.",
    table: {
      headers: ["Drug", "Adjustment trigger", "Action"],
      rows: [
        ["Vancomycin", "Any renal impairment", "Extend interval; AUC-guided; monitor trough/AUC"],
        ["Aminoglycosides", "CrCl decline", "Extend interval; monitor trough; avoid if prolonged AKI"],
        ["Fluoroquinolones", "CrCl thresholds per agent", "Reduce dose (levofloxacin, ciprofloxacin) or avoid (moxifloxacin minimal renal)"],
        ["Nitrofurantoin", "CrCl <30", "Avoid — inadequate urine concentration + toxicity risk"],
        ["Metformin of note", "eGFR <30", "Contraindicated — not an abx but co-tested on boards"],
      ],
    },
    practiceTopicSlug: "infectious-disease-rx",
    reviewModuleSlug: "antibiotics-stewardship",
    sortOrder: 32,
  },
  // —— NCLEX / Infection Control ——
  {
    id: "nclex-precaution-types",
    examSlug: "nclex",
    subject: "Safety",
    topic: "Infection Control",
    title: "Transmission-Based Precautions",
    teaser: "Contact, droplet, airborne — match PPE to route.",
    kind: "table",
    tags: ["PPE", "precautions", "isolation"],
    body: "Standard precautions for all patients; add transmission-based precautions by organism route.",
    table: {
      headers: ["Type", "Examples", "PPE / Room"],
      rows: [
        ["Contact", "C. diff, MRSA, VRE", "Gown + gloves; private/cohort room"],
        ["Droplet", "Influenza, pertussis, meningococcus", "Surgical mask within 3–6 ft"],
        ["Airborne", "TB, measles, varicella", "N95; negative-pressure room"],
      ],
    },
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 1,
  },
  {
    id: "nclex-cdiff-soap",
    examSlug: "nclex",
    subject: "Safety",
    topic: "C. difficile",
    title: "C. diff: Soap Not Gel",
    teaser: "Spores resist alcohol — contact precautions + bleach cleaning.",
    kind: "mistake",
    tags: ["C-diff", "hand-hygiene", "contact"],
    body: "After caring for a patient with C. diff, wash hands with soap and water — alcohol-based hand rub does not kill spores.",
    bullets: [
      "Contact precautions: gown + gloves for every room entry",
      "Environmental cleaning with bleach (sporicidal)",
      "Treatment: oral vancomycin or fidaxomicin; stop inciting antibiotic",
    ],
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 2,
  },
  {
    id: "nclex-mrsa-contact",
    examSlug: "nclex",
    subject: "Safety",
    topic: "MRSA",
    title: "MRSA = Contact Precautions",
    teaser: "Gown and gloves — not airborne isolation.",
    kind: "fact",
    tags: ["MRSA", "contact", "PPE"],
    body: "MRSA requires contact precautions (gown + gloves on every entry). ABHR is acceptable unless hands are soiled. MRSA is not routine airborne isolation.",
    bullets: [
      "Private room or cohort per policy",
      "Dedicated equipment when possible",
      "Distinguish colonization vs infection for treatment decisions",
    ],
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 3,
  },
  {
    id: "nclex-vanc-red-man",
    examSlug: "nclex",
    subject: "Pharmacology",
    topic: "Vancomycin",
    title: "Red Man Syndrome",
    teaser: "Slow infusion ≥60 min — rate-related, not allergy.",
    kind: "pearl",
    tags: ["vancomycin", "red-man", "infusion"],
    body: "Red man syndrome is a rate-related histamine flush during rapid vancomycin infusion — flushing, pruritus, hypotension. Infuse over ≥60 minutes.",
    bullets: [
      "Stop infusion and notify provider if reaction occurs",
      "Not a true IgE-mediated allergy — different management",
      "Monitor creatinine for nephrotoxicity during therapy",
    ],
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 4,
  },
  {
    id: "nclex-vanc-trough",
    examSlug: "nclex",
    subject: "Pharmacology",
    topic: "Vancomycin",
    title: "Vancomycin Trough Timing",
    teaser: "Draw immediately before dose at steady state.",
    kind: "fact",
    tags: ["vancomycin", "trough", "labs"],
    body: "Draw vancomycin trough immediately before the scheduled dose once at steady state (typically before the 4th–5th dose). Too-early trough misleads dosing.",
    bullets: [
      "Document exact draw time on the lab requisition",
      "Verify renal function before starting therapy",
      "Report rising creatinine — nephrotoxicity risk",
    ],
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 5,
  },
  {
    id: "nclex-neutropenic-precautions",
    examSlug: "nclex",
    subject: "Safety",
    topic: "Neutropenia",
    title: "Neutropenic Precautions",
    teaser: "Protect the patient — reverse isolation.",
    kind: "pearl",
    tags: ["neutropenia", "oncology", "reverse-isolation"],
    body: "Neutropenic precautions protect the immunocompromised patient (ANC <500). Private room, no plants/flowers, no raw foods, meticulous hand hygiene.",
    bullets: [
      "Fever ≥38.3°C once or ≥38.0°C sustained = medical emergency",
      "No rectal temps or enemas",
      "Report fever immediately — cultures and broad-spectrum antibiotics stat",
    ],
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 6,
  },
  {
    id: "nclex-peak-trough-labs",
    examSlug: "nclex",
    subject: "Pharmacology",
    topic: "Antimicrobial Monitoring",
    title: "Peak vs Trough Labs",
    teaser: "When to draw levels for aminoglycosides and vancomycin.",
    kind: "table",
    tags: ["peak", "trough", "aminoglycoside", "vancomycin"],
    body: "Trough = immediately before next dose at steady state. Peak (aminoglycosides) = ~30 min after infusion ends.",
    bullets: [
      "Vancomycin trough: draw immediately pre-dose at steady state (~4th–5th dose)",
      "Aminoglycoside peak: ~30 min after infusion ends; trough immediately before next dose",
      "Document exact draw time on the lab requisition — wrong timing invalidates results",
    ],
    table: {
      headers: ["Lab", "Timing", "Agent"],
      rows: [
        ["Trough", "Immediately pre-dose at steady state", "Vancomycin, aminoglycosides"],
        ["Peak", "~30 min post-infusion", "Aminoglycosides"],
      ],
    },
    practiceTopicSlug: "safety-infection",
    reviewModuleSlug: "infection-control",
    sortOrder: 7,
  },
  // —— NCLEX / Sepsis ——
  {
    id: "nclex-sepsis-bundle",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Hour-1 Sepsis Priorities",
    teaser: "What to do first when infection + organ dysfunction.",
    kind: "pearl",
    tags: ["sepsis", "bundle", "prioritization"],
    body: "Recognize early → cultures → antibiotics → fluids → measure lactate → vasopressors if needed.",
    bullets: [
      "Do not delay antibiotics for minor tasks",
      "30 mL/kg crystalloid if hypotensive (adjust for HF/ESRD)",
      "Norepinephrine first-line if MAP still low after fluids",
      "Lactate clearance tracks resuscitation success",
    ],
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 1,
  },
  {
    id: "nclex-shock-types",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Shock",
    title: "Shock Type Clues",
    teaser: "Hypovolemic vs cardiogenic vs distributive vs obstructive.",
    kind: "table",
    tags: ["shock", "prioritization", "ABC"],
    body: "NCLEX loves matching intervention to shock physiology.",
    table: {
      headers: ["Type", "Clue", "First move"],
      rows: [
        ["Hypovolemic", "Low CVP, dry", "Volume"],
        ["Cardiogenic", "Crackles, ↑ JVP", "Inotropes / treat cause"],
        ["Distributive (sepsis)", "Warm skin early, ↓ BP", "Fluids + abx + pressors"],
        ["Obstructive", "↑ JVP, muffled heart sounds", "Relieve obstruction"],
      ],
    },
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 2,
  },
  {
    id: "nclex-lactate-four",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Lactate ≥4 = Fluid Bolus",
    teaser: "Elevated lactate mandates resuscitation even if BP looks stable.",
    kind: "mistake",
    tags: ["sepsis", "lactate", "fluids"],
    body: "Lactate ≥4 mmol/L signals severe sepsis — give 30 mL/kg crystalloid and reassess, even when blood pressure is still compensating.",
    bullets: [
      "Normal BP does not exclude sepsis — watch lactate, mentation, urine output",
      "Trend lactate clearance to assess resuscitation success",
      "Reassess after each bolus for fluid overload (crackles, JVD, hypoxia)",
    ],
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 3,
  },
  {
    id: "nclex-norepinephrine-first",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Septic Shock",
    title: "First-Line Vasopressor",
    teaser: "Norepinephrine for MAP ≥65 after fluids.",
    kind: "fact",
    tags: ["sepsis", "vasopressor", "norepinephrine"],
    body: "Septic shock persists when MAP stays below 65 mmHg despite adequate crystalloid — start norepinephrine; do not delay for central line in an emergency.",
    bullets: [
      "MAP goal ≥65 mmHg: DBP + ⅓(SBP − DBP)",
      "Add vasopressin or epinephrine as second-line if refractory",
      "Avoid dopamine as first-line — more arrhythmias vs norepinephrine",
    ],
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 4,
  },
  {
    id: "nclex-qsofa-screen",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "qSOFA Bedside Screen",
    teaser: "Two or more criteria → suspect sepsis outside the ICU.",
    kind: "table",
    tags: ["sepsis", "qSOFA", "screening"],
    body: "qSOFA is a quick bedside screen — not diagnostic alone, but triggers escalation and workup.",
    table: {
      headers: ["Criterion", "Threshold"],
      rows: [
        ["Respiratory rate", "≥22/min"],
        ["Altered mentation", "GCS <15"],
        ["Systolic BP", "≤100 mmHg"],
      ],
    },
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 5,
  },
  {
    id: "nclex-abx-one-hour",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Antibiotics Within 1 Hour",
    teaser: "Cultures first — but never delay antibiotics for imaging.",
    kind: "mistake",
    tags: ["sepsis", "antibiotics", "prioritization"],
    body: "Obtain blood cultures before antibiotics when feasible, then give broad-spectrum coverage within 1 hour of recognition. Each hour of delay increases mortality.",
    bullets: [
      "Do not wait for CT scan, line placement, or culture results to start abx",
      "Match empiric coverage to likely source (lung, abdomen, line, skin)",
      "Source control (drain, debride, remove line) within 6–12 h when feasible",
    ],
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 6,
  },
  {
    id: "nclex-sepsis-vs-shock",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Sepsis vs Septic Shock",
    teaser: "When vasopressors and lactate define shock.",
    kind: "table",
    tags: ["sepsis", "septic-shock", "SOFA"],
    body: "Sepsis-3: infection + organ dysfunction (SOFA ≥2). Septic shock adds pressor-dependent hypotension plus lactate >2 despite fluids.",
    table: {
      headers: ["Feature", "Sepsis", "Septic Shock"],
      rows: [
        ["Organ dysfunction", "SOFA score ↑ ≥2", "Same"],
        ["Blood pressure", "May be normal early", "Hypotension despite fluids"],
        ["Vasopressors", "Not required", "Required for MAP ≥65"],
        ["Lactate", "May be elevated", ">2 mmol/L despite fluids"],
      ],
    },
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 7,
  },
  {
    id: "nclex-perfusion-endpoints",
    examSlug: "nclex",
    subject: "Critical Care",
    topic: "Sepsis",
    title: "Perfusion Endpoints",
    teaser: "Urine output and mentation track resuscitation.",
    kind: "pearl",
    tags: ["sepsis", "urine-output", "monitoring"],
    body: "After initial resuscitation, nursing reassessment confirms adequate perfusion — not just a single BP reading.",
    bullets: [
      "Urine output goal ≥0.5 mL/kg/h — oliguria for 2 h suggests inadequate perfusion",
      "Track mental status, capillary refill, and lactate clearance",
      "Notify provider if perfusion markers fail to improve after fluids and pressors",
      "Document hourly urine output and trend MAP — single normal BP can mask shock",
    ],
    practiceTopicSlug: "physiological-adaptation",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 8,
  },
  // —— USMLE / ACS ——
  {
    id: "usmle-stemi-path",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "STEMI: Do Not Wait",
    teaser: "ECG drives reperfusion — not troponin.",
    kind: "fact",
    tags: ["STEMI", "PCI", "reperfusion"],
    body: "ASA + anticoagulation + P2Y12 → primary PCI if available within 120 min; fibrinolysis if PCI unavailable.",
    bullets: [
      "New LBBB + symptoms = STEMI equivalent",
      "Inferior MI + hypotension → think RV infarct → fluids, avoid nitrates",
      "Hold beta-blocker if acute decompensation or cocaine MI",
    ],
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 1,
  },
  {
    id: "usmle-acs-spectrum",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "UA vs NSTEMI vs STEMI",
    teaser: "Troponin + ECG pattern defines the pathway.",
    kind: "table",
    tags: ["ACS", "troponin", "ECG"],
    body: "Use ECG for immediate reperfusion decisions; troponin confirms myocardial injury.",
    table: {
      headers: ["Diagnosis", "Troponin", "ECG"],
      rows: [
        ["Unstable angina", "Normal", "May have ST depression / T-wave changes"],
        ["NSTEMI", "Elevated", "ST depression or normal"],
        ["STEMI", "Usually elevated", "ST elevation or new LBBB"],
      ],
    },
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 2,
  },
  {
    id: "usmle-acs-antithrombotics",
    examSlug: "usmle",
    subject: "Cardiology",
    topic: "ACS",
    title: "ACS Antithrombotic Stack",
    teaser: "Dual antiplatelet + anticoagulation for NSTEMI/STEMI.",
    kind: "table",
    tags: ["ACS", "aspirin", "heparin", "P2Y12"],
    body: "Give aspirin immediately unless contraindicated; add P2Y12 and parenteral anticoagulant per pathway.",
    table: {
      headers: ["Phase", "Typical agents", "Pearl"],
      rows: [
        ["All ACS", "Aspirin 325 mg then 81 mg daily", "Start ASAP — do not wait for cath lab"],
        ["NSTEMI/STEMI", "P2Y12 (ticagrelor, prasugrel, clopidogrel)", "Prasugrel CI if prior stroke/TIA"],
        ["NSTEMI/STEMI", "UFH, enoxaparin, or bivalirudin", "Match to PCI plan and bleeding risk"],
        ["Post-PCI", "DAPT 12 months typical", "Balance stent thrombosis vs bleeding"],
      ],
    },
    practiceTopicSlug: "cardiology",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 3,
  },
  {
    id: "usmle-stroke-tpa",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "Acute Ischemic Stroke — tPA Window",
    teaser: "Time last known well → CT → treat eligible patients fast.",
    kind: "pearl",
    tags: ["stroke", "tPA", "CT"],
    body: "Non-contrast CT excludes hemorrhage; IV alteplase within 4.5 h for eligible patients.",
    bullets: [
      "Last known well defines clock — wake-up stroke often ineligible unless advanced imaging",
      "BP >185/110 must be lowered before tPA",
      "Major exclusions: recent surgery, active bleeding, prior ICH",
      "Endovascular thrombectomy up to 24 h in select large-vessel occlusion",
    ],
    practiceTopicSlug: "neurology",
    sortOrder: 4,
  },
  {
    id: "usmle-hyperkalemia",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "Electrolytes",
    title: "Hyperkalemia Emergency",
    teaser: "Stabilize myocardium → shift K⁺ → remove K⁺.",
    kind: "table",
    tags: ["potassium", "ECG", "dialysis"],
    body: "Peaked T waves → widened QRS → sine wave. Treat ECG changes urgently.",
    table: {
      headers: ["Step", "Agent", "Onset"],
      rows: [
        ["Stabilize", "Calcium gluconate/chloride", "Minutes"],
        ["Shift intracellular", "Insulin + dextrose", "~30 min"],
        ["Shift intracellular", "Albuterol, bicarbonate if acidemic", "Adjunct"],
        ["Remove", "Diuretics, patiromer, dialysis", "Hours"],
      ],
    },
    practiceTopicSlug: "nephrology",
    sortOrder: 5,
  },
  {
    id: "usmle-aki-fena",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "AKI",
    title: "Prerenal vs ATN (FeNa)",
    teaser: "BUN:Cr ratio and urine studies narrow AKI type.",
    kind: "fact",
    tags: ["AKI", "FeNa", "ATN"],
    body: "FeNa <1% favors prerenal; FeNa >2% favors ATN (unreliable on diuretics — use FEUrea).",
    bullets: [
      "Prerenal: dry mucosa, ↓ urine Na, responds to fluid bolus",
      "ATN: muddy brown casts, ischemic or nephrotoxic insult",
      "Postrenal: hydronephrosis — relieve obstruction (Foley, stent)",
      "Dialysis indications: AEIOU (Acidosis, Electrolytes, Ingestion, Overload, Uremia)",
    ],
    practiceTopicSlug: "nephrology",
    sortOrder: 6,
  },
  // —— PANCE (NCCPA clinical reference) ——
  {
    id: "pance-hypertension-first-line",
    examSlug: "pance",
    subject: "Cardiovascular",
    topic: "Hypertension",
    title: "First-Line HTN Therapy",
    teaser: "JNC/ACC approach for uncomplicated hypertension.",
    kind: "fact",
    tags: ["hypertension", "cardiovascular", "pharmacotherapy"],
    body: "Start with lifestyle + thiazide-like diuretic, CCB, or ACEi/ARB for most adults with HTN.",
    bullets: [
      "Target <130/80 for most adults with CVD risk per ACC/AHA",
      "ACEi/ARB preferred with diabetes, CKD, or HF",
      "Avoid ACEi/ARB in pregnancy — use methyldopa, labetalol, or nifedipine XL",
      "Reassess BP in 2–4 weeks; add second agent if not at goal",
    ],
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 1,
  },
  {
    id: "pance-acs-reperfusion",
    examSlug: "pance",
    subject: "Cardiovascular",
    topic: "ACS",
    title: "STEMI: Reperfusion Windows",
    teaser: "ECG drives reperfusion — not troponin alone.",
    kind: "fact",
    tags: ["STEMI", "ACS", "PCI"],
    body: "ASA + anticoagulation + P2Y12 → primary PCI if available within 120 min; fibrinolysis if PCI unavailable.",
    bullets: [
      "New LBBB + symptoms = STEMI equivalent",
      "Inferior MI + hypotension → think RV infarct → fluids, avoid nitrates",
      "Hold beta-blocker if acute decompensation",
    ],
    practiceTopicSlug: "cardiovascular",
    reviewModuleSlug: "acute-coronary-syndrome",
    sortOrder: 2,
  },
  {
    id: "pance-diabetes-a1c-targets",
    examSlug: "pance",
    subject: "Endocrine",
    topic: "Diabetes",
    title: "Type 2 DM — A1c Goals & Monitoring",
    teaser: "Individualize targets; screen complications annually.",
    kind: "fact",
    tags: ["diabetes", "A1c", "endocrine"],
    body: "General A1c <7% if achievable without hypoglycemia; less strict for frail elderly or limited life expectancy.",
    bullets: [
      "Metformin first-line unless contraindicated (eGFR <30)",
      "Check A1c q3–6 months when not at goal; annual eye, foot, urine albumin, lipids",
      "SGLT2i or GLP-1 RA with ASCVD/HF/CKD benefits per guidelines",
      "Hypoglycemia counseling — 15 g fast carb, recheck in 15 min",
    ],
    practiceTopicSlug: "endocrine",
    sortOrder: 3,
  },
  {
    id: "pance-sepsis-bundle",
    examSlug: "pance",
    subject: "Infectious Diseases",
    topic: "Sepsis",
    title: "Hour-1 Sepsis Bundle",
    teaser: "Antibiotics and fluids without delay.",
    kind: "pearl",
    tags: ["sepsis", "bundle", "critical care"],
    body: "Recognize early → cultures → antibiotics → fluids → measure lactate → vasopressors if needed.",
    bullets: [
      "Do not delay antibiotics for minor tasks",
      "30 mL/kg crystalloid if hypotensive (adjust for HF/ESRD)",
      "Norepinephrine first-line if MAP still low after fluids",
      "Lactate clearance tracks resuscitation success",
    ],
    practiceTopicSlug: "infectious-diseases",
    reviewModuleSlug: "sepsis-shock",
    sortOrder: 4,
  },
  {
    id: "pance-febrile-infant-workup",
    examSlug: "pance",
    subject: "Infectious Diseases",
    topic: "Pediatrics",
    title: "Febrile Infant ≤60 Days",
    teaser: "High-risk age — low threshold for full sepsis workup.",
    kind: "mistake",
    tags: ["pediatrics", "fever", "sepsis"],
    body: "Neonates and young infants with fever require careful assessment — low threshold for LP, blood/urine culture, and admission.",
    bullets: [
      "≤28 days with T≥38°C — admit, full sepsis evaluation, empiric antibiotics",
      "29–60 days: risk stratify per local protocol/PECARN",
      "Always consider UTI — catheter or suprapubic preferred over bag urine",
      "Parent counseling on return precautions",
    ],
    practiceTopicSlug: "infectious-diseases",
    sortOrder: 5,
  },
  {
    id: "pance-copd-exacerbation",
    examSlug: "pance",
    subject: "Pulmonary",
    topic: "COPD",
    title: "COPD Exacerbation Management",
    teaser: "Bronchodilators, steroids, antibiotics when indicated.",
    kind: "fact",
    tags: ["COPD", "pulmonary", "exacerbation"],
    body: "Short-acting bronchodilator first; systemic steroids if moderate-severe; antibiotics if increased sputum purulence.",
    bullets: [
      "Assess for NIPPV if hypercapnic respiratory failure",
      "Avoid over-oxygenation in chronic retainers",
      "Discharge with action plan and inhaler technique check",
    ],
    practiceTopicSlug: "pulmonary",
    sortOrder: 6,
  },
  {
    id: "pance-depression-screening",
    examSlug: "pance",
    subject: "Psychiatry",
    topic: "Depression",
    title: "Major Depression — PHQ-9 & Safety",
    teaser: "Screen, diagnose, and assess suicide risk at every behavioral visit.",
    kind: "fact",
    tags: ["depression", "PHQ-9", "psychiatry"],
    body: "PHQ-9 ≥10 suggests moderate depression; always ask about suicidal ideation, plan, and means.",
    bullets: [
      "First-line SSRI (sertraline, escitalopram) for most adults",
      "Reassess in 2–4 weeks; full response may take 6–8 weeks",
      "Refer urgently if active SI with plan, psychosis, or bipolar features",
    ],
    practiceTopicSlug: "psychiatry",
    sortOrder: 7,
  },
  {
    id: "pance-prenatal-initial-visit",
    examSlug: "pance",
    subject: "Reproductive",
    topic: "Prenatal care",
    title: "First Prenatal Visit Essentials",
    teaser: "Dating, baseline labs, and risk counseling.",
    kind: "fact",
    tags: ["OB", "prenatal", "reproductive"],
    body: "Confirm EDC by LMP vs early ultrasound; complete prenatal panel and screen for infections and anemia.",
    bullets: [
      "Labs: CBC, blood type/Rh, antibody screen, rubella, hepatitis B, HIV, syphilis, UA culture",
      "Start prenatal vitamins with folic acid; counsel on teratogens",
      "BP baseline, weight, mental health and domestic violence screen",
    ],
    practiceTopicSlug: "reproductive",
    sortOrder: 8,
  },
  {
    id: "pance-informed-consent",
    examSlug: "pance",
    subject: "Professional Practice",
    topic: "Ethics",
    title: "Informed Consent Essentials",
    teaser: "Capacity, disclosure, comprehension, voluntariness.",
    kind: "fact",
    tags: ["ethics", "consent", "professional practice"],
    body: "Valid consent requires disclosure of risks, benefits, and alternatives in language the patient understands.",
    bullets: [
      "Assess decision-making capacity before high-risk procedures",
      "Document who explained the procedure and answered questions",
      "Emergent treatment without consent when patient lacks capacity and delay risks harm",
      "Minors generally require parent/guardian consent with narrow exceptions",
    ],
    practiceTopicSlug: "professional-practice",
    sortOrder: 9,
  },
  // —— NCLEX / Delegation (extra) ——
  {
    id: "nclex-five-rights",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Five Rights of Delegation",
    teaser: "NCLEX checklist before assigning any task.",
    kind: "fact",
    tags: ["delegation", "five-rights", "scope"],
    body: "All five must be satisfied — if one is missing, the RN keeps the task.",
    bullets: [
      "Right task — appropriate for delegatee scope",
      "Right circumstance — stable patient, adequate resources",
      "Right person — competent, trained, within scope",
      "Right direction — clear instructions and limits",
      "Right supervision — RN evaluates outcome",
    ],
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 3,
  },
  {
    id: "nclex-never-delegate",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Never Delegate to UAP",
    teaser: "High-risk tasks that stay with the RN on NCLEX.",
    kind: "mistake",
    tags: ["delegation", "UAP", "insulin"],
    body: "When an answer assigns these to UAP, eliminate it.",
    bullets: [
      "Initial admission assessment",
      "Insulin administration",
      "Unstable vital signs or new acute changes",
      "Patient/family teaching",
      "Sterile procedures requiring nursing judgment",
    ],
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 4,
  },
  {
    id: "nclex-scope-rn-lpn-uap",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "RN vs LPN vs UAP Scope",
    teaser: "Who can do what on NCLEX — stable vs unstable framing.",
    kind: "table",
    tags: ["delegation", "scope", "LPN", "UAP"],
    body: "When unsure, choose the most restrictive safe option — state nurse practice act always wins.",
    table: {
      headers: ["Activity", "RN", "LPN/LVN", "UAP"],
      rows: [
        ["Initial admission assessment", "Yes", "No", "No"],
        ["Medication administration", "Yes", "Per license", "No"],
        ["Insulin administration", "Yes", "Varies by state", "Never on NCLEX"],
        ["Patient/family teaching", "Yes", "Reinforce plan", "No"],
        ["ADLs on stable patient", "Yes", "Yes", "Yes"],
        ["Vital signs — unstable/post-op complication", "Yes", "No", "No"],
      ],
    },
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 5,
  },
  {
    id: "nclex-stable-unstable",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Stable vs Unstable — Delegate?",
    teaser: "Unpredictable outcomes stay with the RN.",
    kind: "table",
    tags: ["delegation", "stable", "unstable"],
    body: "Read the stem for unstable cues first — if present, pick the RN action.",
    table: {
      headers: ["Patient picture", "Delegate?", "Why"],
      rows: [
        ["Chronic HF, baseline VS, PT ambulation plan", "Often yes (ADL/VS)", "Predictable, stable"],
        ["Fresh post-op, oozing dressing, HR 118", "No", "Unstable — RN owns assessment"],
        ["New fever + rigors on chemo unit", "No", "Unpredictable — assess first"],
        ["LTC stable adult, routine I&O", "Often yes", "Stable, protocol-driven"],
      ],
    },
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 6,
  },
  {
    id: "nclex-supervision-eval",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Right Supervision & Evaluation",
    teaser: "Delegation is not handoff — the RN follows up.",
    kind: "pearl",
    tags: ["delegation", "supervision", "five-rights"],
    body: "Provide clear directions, confirm understanding, define when to report back, and evaluate the outcome. If the patient condition changes, reassess and reassign.",
    bullets: [
      "Specify what to do, parameters for escalation, and when to notify the RN",
      "If delegatee refuses or lacks competency — RN finds another solution",
      "Attractive NCLEX distractors assign tasks without supervision built in",
      "Re-delegate only after reassessing patient stability and delegatee competency",
    ],
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 7,
  },
  {
    id: "nclex-delegation-decision-tree",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "Delegation Decision Tree",
    teaser: "Four yes/no gates before assigning a task.",
    kind: "fact",
    tags: ["delegation", "five-rights", "NCLEX"],
    body: "Walk the stem through each gate — one failure means the RN keeps the task.",
    bullets: [
      "Is the patient stable with a predictable outcome?",
      "Is the task within the delegatee's scope and competency?",
      "Are circumstances appropriate (staffing, setting, resources)?",
      "Can you give clear direction and supervise/evaluate the result?",
    ],
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 8,
  },
  // —— USMLE extras ——
  {
    id: "usmle-dka-orders",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA",
    title: "DKA Management Order",
    teaser: "Fluids before insulin if K⁺ is low.",
    kind: "pearl",
    tags: ["DKA", "insulin", "potassium"],
    body: "Start IV fluids → check K⁺ → insulin drip only if K⁺ ≥3.3 mEq/L.",
    bullets: [
      "Add dextrose when glucose ~200 to continue insulin until gap closes",
      "Gap closes when bicarbonate normalizes, not when glucose normalizes",
      "Search for trigger: infection, missed insulin, new-onset DM",
    ],
    practiceTopicSlug: "internal-medicine",
    sortOrder: 7,
  },
  {
    id: "usmle-hhs-vs-dka",
    examSlug: "usmle",
    subject: "Endocrine",
    topic: "DKA / HHS",
    title: "DKA vs HHS",
    teaser: "Ketones and gap distinguish emergencies in hyperglycemia.",
    kind: "table",
    tags: ["DKA", "HHS", "hyperglycemia"],
    body: "Both need aggressive fluids; HHS has higher mortality and slower correction targets.",
    bullets: [
      "HHS: extreme hyperosmolarity, minimal ketosis, profound dehydration — correct sodium/glucose slowly",
      "DKA: insulin required once K⁺ ≥3.3; continue until anion gap closes",
      "Both: search for infection as trigger; monitor K⁺ closely during treatment",
    ],
    table: {
      headers: ["Feature", "DKA", "HHS"],
      rows: [
        ["Glucose", "Often >250", "Often >600"],
        ["Ketones / gap", "Present", "Minimal ketones, mild or no gap"],
        ["Dehydration", "Significant", "Profound"],
        ["Insulin", "Required once K⁺ safe", "Often lower doses; fluids first"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    sortOrder: 8,
  },
  {
    id: "usmle-cap-antibiotics",
    examSlug: "usmle",
    subject: "Pulmonary",
    topic: "Pneumonia",
    title: "CAP Antibiotic Choices",
    teaser: "Outpatient vs inpatient; cover atypicals when indicated.",
    kind: "table",
    tags: ["CAP", "pneumonia", "antibiotics"],
    body: "CURB-65 or PSI guides disposition; tailor to local resistance and comorbidities.",
    bullets: [
      "Outpatient: healthy + no comorbidities → amoxicillin or doxycycline/macrolide",
      "Inpatient non-ICU: beta-lactam + macrolide OR respiratory fluoroquinolone monotherapy",
      "Add pseudomonal coverage if structural lung disease, recent IV abx, or HCAP risk",
    ],
    table: {
      headers: ["Setting", "Typical regimen", "Add pseudomonas if"],
      rows: [
        ["Healthy outpatient", "Amoxicillin or doxy/macrolide", "N/A"],
        ["Comorbid outpatient", "Amox-clav + macrolide or resp fluoroquinolone", "Recent abx/hospitalization"],
        ["Inpatient non-ICU", "Beta-lactam + macrolide or FQ monotherapy", "Risk factors for resistant orgs"],
        ["ICU", "Beta-lactam + macrolide or FQ (+ MRSA/Pseudomonas if risk)", "Structural lung disease, HCAP risk"],
      ],
    },
    practiceTopicSlug: "pulmonology",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 9,
  },
  {
    id: "usmle-meningitis-emergency",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Meningitis",
    title: "Bacterial Meningitis — Do Not Delay Abx",
    teaser: "Blood cultures then empiric antibiotics; add dexamethasone when indicated.",
    kind: "pearl",
    tags: ["meningitis", "ceftriaxone", "LP"],
    body: "If LP delayed, give empiric antibiotics after blood cultures — do not wait for CT/LP if unstable.",
    bullets: [
      "Adults: ceftriaxone + vancomycin (+ ampicillin if Listeria risk >50 or immunocompromised)",
      "Dexamethasone before or with first abx dose if suspected pneumococcal",
      "Petechiae + fever → treat as meningococcemia; isolate and prophylax contacts",
      "Immunocompromised or age >50: add ampicillin for Listeria coverage",
    ],
    practiceTopicSlug: "emergency-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 10,
  },
  // —— USMLE / Infectious Disease ——
  {
    id: "usmle-mrsa-agents",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "MRSA",
    title: "MRSA Agent Selection",
    teaser: "VAN-CO in blood; LINE for lungs; DAP-TOM for skin — never DAP in pneumonia.",
    kind: "table",
    tags: ["MRSA", "vancomycin", "daptomycin", "linezolid"],
    body: "Step 2 CK tests infection site when choosing MRSA therapy — daptomycin fails in pneumonia due to surfactant inactivation.",
    table: {
      headers: ["Agent", "Best use", "Trap"],
      rows: [
        ["Vancomycin", "Bacteremia, most serious infections", "AUC/MIC 400–600; nephrotoxicity"],
        ["Daptomycin", "Bacteremia, endocarditis, skin", "Not for pneumonia — surfactant inactivation"],
        ["Linezolid", "Pneumonia, oral step-down", "Weak MAOI; myelosuppression with prolonged use"],
        ["Ceftaroline", "MRSA pneumonia", "Reserved; beta-lactam class"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 11,
  },
  {
    id: "usmle-daptomycin-lung-trap",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "MRSA",
    title: "Daptomycin Pneumonia Trap",
    teaser: "DAP-TOM dissolves in surfactant — use vanc or linezolid for MRSA pneumonia.",
    kind: "mistake",
    tags: ["daptomycin", "MRSA", "pneumonia"],
    body: "Daptomycin binds pulmonary surfactant and cannot achieve therapeutic alveolar concentrations — a classic Step 2 CK distractor.",
    bullets: [
      "MRSA pneumonia: vancomycin, linezolid, or ceftaroline",
      "Daptomycin for bacteremia and skin/soft tissue when susceptible",
      "Check CPK weekly — myopathy risk",
    ],
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 12,
  },
  {
    id: "usmle-vanc-dosing",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Vancomycin",
    title: "Vancomycin Dosing & AUC",
    teaser: "Load 25–30 mg/kg → AUC/MIC 400–600 for serious MRSA.",
    kind: "table",
    tags: ["vancomycin", "AUC", "MRSA", "loading dose"],
    body: "Vancomycin requires loading dose, CrCl-based interval adjustment, and AUC-guided monitoring for serious MRSA bacteremia and endocarditis.",
    table: {
      headers: ["Step", "Guideline", "Board pearl"],
      rows: [
        ["Loading", "25–30 mg/kg IV (max 3 g)", "Calculate mg/kg before cap"],
        ["CrCl ≥50", "q8–12 h maintenance", "Cockcroft-Gault for interval"],
        ["Monitoring", "AUC/MIC 400–600", "Preferred over trough-only"],
        ["Steady state", "Level before 4th–5th dose", "Too-early trough misleads"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 13,
  },
  {
    id: "usmle-cdiff-treatment",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "C. difficile",
    title: "C. diff Treatment",
    teaser: "Oral vanc or fidaxomicin — not IV vanc for colonic infection.",
    kind: "table",
    tags: ["C-diff", "vancomycin", "fidaxomicin"],
    body: "Oral vancomycin or fidaxomicin are first-line for C. diff; IV vancomycin does not reach the colon.",
    table: {
      headers: ["Severity", "Regimen", "Pearl"],
      rows: [
        ["Initial non-severe", "Oral vancomycin 125 mg QID or fidaxomicin", "Stop inciting antibiotic"],
        ["Severe", "Oral vancomycin 125 mg QID", "Metronidazole no longer preferred first-line"],
        ["Fulminant", "Oral/rectal vanc 500 mg QID + IV metronidazole", "Surgery if megacolon"],
        ["Recurrence", "Fidaxomicin or tapered oral vanc", "Bezlotoxumab if high recurrence risk"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 14,
  },
  {
    id: "usmle-hiv-oi-prophylaxis",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "HIV",
    title: "HIV OI Prophylaxis Thresholds",
    teaser: "CD4 <200 = PCP; <100 = toxo/MAC; <50 = MAC + crypto screen.",
    kind: "table",
    tags: ["HIV", "PCP", "TMP-SMX", "MAC"],
    body: "Opportunistic infection prophylaxis is driven by CD4 count — TMP-SMX DS daily is the workhorse when CD4 <200.",
    table: {
      headers: ["CD4", "Prophylaxis", "Agent"],
      rows: [
        ["<200", "PCP", "TMP-SMX DS daily"],
        ["<100 + toxo IgG+", "Toxoplasmosis", "TMP-SMX covers PCP + toxo"],
        ["<100", "MAC", "Azithromycin weekly"],
        ["<50", "MAC + crypto", "Azithromycin; CrAg screen; fluconazole if CrAg+"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 15,
  },
  {
    id: "usmle-abx-spectrum",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Antimicrobial Coverage",
    title: "Beta-Lactam Spectrum (High-Yield)",
    teaser: "1st gen = MSSA; 3rd = ceftriaxone; 4th/5th = Pseudomonas / MRSA niche.",
    kind: "table",
    tags: ["cephalosporin", "beta-lactam", "spectrum"],
    body: "Cephalosporin generation predicts gram-negative reach; carbapenems cover ESBL but reserve for resistance.",
    table: {
      headers: ["Gen / class", "Examples", "Covers"],
      rows: [
        ["1st-gen ceph", "Cefazolin", "MSSA, strep"],
        ["3rd-gen ceph", "Ceftriaxone, ceftazidime", "GNR; ceftazidime = Pseudomonas"],
        ["4th-gen ceph", "Cefepime", "Broad GNR + Pseudomonas"],
        ["5th-gen ceph", "Ceftaroline", "MRSA pneumonia"],
        ["Carbapenem", "Meropenem", "ESBL, anaerobes, broad GNR"],
      ],
    },
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 16,
  },
  {
    id: "usmle-febrile-neutropenia",
    examSlug: "usmle",
    subject: "Infectious Disease",
    topic: "Oncology",
    title: "Febrile Neutropenia",
    teaser: "ANC <500 + fever → cultures then anti-pseudomonal abx within 60 min.",
    kind: "pearl",
    tags: ["neutropenia", "cefepime", "meropenem", "oncology"],
    body: "Febrile neutropenia is an emergency — empiric anti-pseudomonal beta-lactam after blood cultures; add vancomycin only for line/skin source.",
    bullets: [
      "First-line: cefepime, meropenem, or pip-tazo — per local protocol",
      "Do not wait for culture results to start antibiotics",
      "Add vancomycin for catheter-related infection, skin infection, or hemodynamic instability",
      "G-CSF may be considered per oncology guidelines — not a substitute for antibiotics",
    ],
    practiceTopicSlug: "internal-medicine",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 17,
  },
  {
    id: "usmle-crcl-dosing",
    examSlug: "usmle",
    subject: "Nephrology",
    topic: "Renal dosing",
    title: "Cockcroft-Gault (CrCl)",
    teaser: "Estimate CrCl for vancomycin, aminoglycosides, and DOAC adjustments.",
    kind: "equation",
    tags: ["CrCl", "renal", "calculation", "vancomycin"],
    body: "CrCl (mL/min) = [(140 − age) × weight (kg)] / [72 × SCr (mg/dL)] × 0.85 if female",
    bullets: [
      "Use ABW if >30% above IBW; actual weight if below IBW",
      "Low CrCl extends vancomycin interval and raises toxicity risk",
      "Use Reference hub calculators for step-by-step CrCl and vanc loading",
    ],
    practiceTopicSlug: "nephrology",
    reviewModuleSlug: "infectious-disease",
    sortOrder: 18,
  },
  {
    id: "usmle-tpa-exclusions",
    examSlug: "usmle",
    subject: "Neurology",
    topic: "Stroke",
    title: "tPA — High-Yield Exclusions",
    teaser: "Eliminate wrong answers on stroke timing and bleeding risk.",
    kind: "mistake",
    tags: ["stroke", "tPA", "contraindications"],
    body: "When in doubt on Step 2 CK: recent intracranial surgery, active internal bleeding, or INR >1.7 excludes tPA.",
    bullets: [
      "Symptom onset >4.5 h (without advanced imaging protocol)",
      "Evidence of hemorrhage on CT",
      "Recent major surgery or GI/GU bleed",
      "Platelets <100k, glucose <50 (correct first)",
    ],
    practiceTopicSlug: "neurology",
    sortOrder: 11,
  },
  // —— Cross-exam utilities ——
  {
    id: "all-creatinine-clearance",
    examSlug: "naplex",
    subject: "Calculations",
    topic: "Renal dosing",
    title: "Cockcroft-Gault (CrCl)",
    teaser: "Estimate creatinine clearance for drug dosing.",
    kind: "equation",
    tags: ["calculation", "renal", "dosing"],
    body: "CrCl (mL/min) = [(140 − age) × weight (kg)] / [72 × SCr (mg/dL)] × 0.85 if female",
    bullets: [
      "Use actual weight unless below IBW; use ABW = IBW + 0.4 × (actual − IBW) if >30% above IBW",
      "Many renally cleared drugs (vancomycin, aminoglycosides, DOACs) use CrCl — not eGFR",
      "Round to nearest whole number on NAPLEX (e.g. 70 y/o, 75 kg, SCr 2.4 → CrCl ≈ 30 mL/min)",
      "Use the Reference hub calculators for step-by-step CrCl and vancomycin loading checks",
    ],
    practiceTopicSlug: "pharmacology",
    sortOrder: 8,
  },
  {
    id: "all-anion-gap",
    examSlug: "usmle",
    subject: "Laboratory",
    topic: "Acid-base",
    title: "Anion Gap",
    teaser: "MUDPILES for elevated gap metabolic acidosis.",
    kind: "equation",
    tags: ["ABG", "acid-base", "MUDPILES"],
    body: "AG = Na⁺ − (Cl⁻ + HCO₃⁻). Normal ≈ 8–12 mEq/L.",
    bullets: [
      "MUDPILES: Methanol, Uremia, DKA, Propylene glycol, INH/Iron, Lactic acidosis, Ethylene glycol, Salicylates",
      "Normal anion gap acidosis: diarrhea (HCO₃⁻ loss), RTA, saline infusion",
      "Calculate delta gap to detect mixed disorders (ΔAG + ΔHCO₃⁻)",
      "Treat underlying cause — bicarbonate only if severe acidemia with caution",
    ],
    practiceTopicSlug: "nephrology",
    sortOrder: 12,
  },
  {
    id: "nclex-delegation",
    examSlug: "nclex",
    subject: "Management of Care",
    topic: "Delegation",
    title: "RN Accountability",
    teaser: "What you can and cannot delegate.",
    kind: "mistake",
    tags: ["delegation", "UAP", "scope"],
    body: "The RN remains accountable for all care. Never delegate assessment, teaching, or unstable clients inappropriately.",
    bullets: [
      "UAP: stable tasks (hygiene, ambulation with plan)",
      "LPN: stable predictable care per scope",
      "RN: assessment, triage, unstable patients",
      "Delegating does not transfer accountability — the RN owns the outcome",
    ],
    practiceTopicSlug: "management-of-care",
    reviewModuleSlug: "delegation",
    sortOrder: 9,
  },
];
