import type { SubjectArea } from "../types";

/** FSBPT NPTE-PT body-system and non-system content areas (2024 outline). */
export const NPTE_PT_SUBJECTS: SubjectArea[] = [
  {
    id: "musculoskeletal",
    label: "Musculoskeletal System",
    contentArea: "Musculoskeletal (44–54 items)",
    textbookRefs: "APTA Orthopaedic Section, O'Sullivan Physical Rehabilitation",
    examHints: "orthopedic eval, manual therapy, post-op rehab, exercise prescription, joint mobilization",
    keywords: ["MSK", "orthopedic", "manual therapy", "ROM", "strength", "gait"],
    focusPlaceholder: "e.g. rotator cuff, ACL rehab, low back pain",
    difficultyLevel: 3,
  },
  {
    id: "neuromuscular-nervous",
    label: "Neuromuscular & Nervous Systems",
    contentArea: "Neuromuscular & Nervous (39–48 items)",
    textbookRefs: "APTA Neurology Section, stroke/SCI/TBI guidelines",
    examHints: "stroke, TBI, SCI, Parkinson, MS, peripheral neuropathy, gait/balance, neuroplasticity",
    keywords: ["neuro", "stroke", "SCI", "TBI", "gait", "balance", "PNF"],
    focusPlaceholder: "e.g. CVA gait training, SCI mobility",
    difficultyLevel: 4,
  },
  {
    id: "cardiovascular-pulmonary",
    label: "Cardiovascular & Pulmonary Systems",
    contentArea: "Cardiovascular & Pulmonary (22–27 items)",
    textbookRefs: "APTA Cardiovascular & Pulmonary Section, AACVPR",
    examHints: "COPD, CHF, post-MI rehab, oxygen titration, airway clearance, ventilator weaning",
    keywords: ["cardiopulmonary", "COPD", "CHF", "aerobic", "SpO2", "percussion"],
    focusPlaceholder: "e.g. COPD exercise prescription, post-CABG",
    difficultyLevel: 3,
  },
  {
    id: "integumentary",
    label: "Integumentary System",
    contentArea: "Integumentary (8–11 items)",
    textbookRefs: "Wound care guidelines, pressure injury prevention",
    examHints: "pressure injuries, wound dressings, burns, lymphedema skin care",
    keywords: ["wound", "pressure ulcer", "burn", "skin"],
    focusPlaceholder: "e.g. Stage III pressure injury management",
    difficultyLevel: 3,
  },
  {
    id: "metabolic-endocrine",
    label: "Metabolic & Endocrine Systems",
    contentArea: "Metabolic & Endocrine (4–6 items)",
    textbookRefs: "Diabetes exercise guidelines, osteoporosis",
    examHints: "diabetes exercise precautions, osteoporosis, obesity, metabolic syndrome",
    keywords: ["diabetes", "osteoporosis", "obesity", "exercise tolerance"],
    focusPlaceholder: "e.g. DM exercise monitoring",
    difficultyLevel: 3,
  },
  {
    id: "gastrointestinal",
    label: "Gastrointestinal System",
    contentArea: "Gastrointestinal (3–6 items)",
    textbookRefs: "GI surgery rehab, pelvic floor basics",
    examHints: "post-abdominal surgery mobility, constipation, pelvic floor dysfunction",
    keywords: ["GI", "pelvic floor", "abdominal surgery"],
    focusPlaceholder: "e.g. post-colectomy mobilization",
    difficultyLevel: 2,
  },
  {
    id: "genitourinary",
    label: "Genitourinary System",
    contentArea: "Genitourinary (2–5 items)",
    textbookRefs: "Pelvic health, incontinence management",
    examHints: "urinary incontinence, pelvic floor training, prostate post-op",
    keywords: ["incontinence", "pelvic floor", "GU"],
    focusPlaceholder: "e.g. stress incontinence intervention",
    difficultyLevel: 3,
  },
  {
    id: "lymphatic",
    label: "Lymphatic System",
    contentArea: "Lymphatic (4–7 items)",
    textbookRefs: "Lymphedema management, CDT",
    examHints: "lymphedema, complete decongestive therapy, compression",
    keywords: ["lymphedema", "CDT", "compression"],
    focusPlaceholder: "e.g. post-mastectomy lymphedema",
    difficultyLevel: 3,
  },
  {
    id: "system-interactions",
    label: "System Interactions",
    contentArea: "System Interactions (8–10 items)",
    textbookRefs: "Multi-system case management",
    examHints: "comorbidities, polypharmacy, frailty, multi-system deconditioning",
    keywords: ["comorbidity", "frailty", "multi-system"],
    focusPlaceholder: "e.g. COPD + HF exercise planning",
    difficultyLevel: 4,
  },
  {
    id: "equipment-devices",
    label: "Equipment, Devices & Technologies",
    contentArea: "Non-Systems — Equipment (5–6 items)",
    textbookRefs: "Assistive technology, orthotics/prosthetics basics",
    examHints: "wheelchair fitting, ambulatory aids, orthotics, prosthetic gait training",
    keywords: ["wheelchair", "crutches", "prosthetic", "orthotic", "AD"],
    focusPlaceholder: "e.g. wheelchair prescription",
    difficultyLevel: 3,
  },
  {
    id: "therapeutic-modalities",
    label: "Therapeutic Modalities",
    contentArea: "Non-Systems — Modalities (4–6 items)",
    textbookRefs: "Therapeutic modalities textbook, electrotherapy safety",
    examHints: "ultrasound, e-stim, cryotherapy, heat, contraindications, dosage",
    keywords: ["ultrasound", "TENS", "NMES", "cryotherapy", "phonophoresis"],
    focusPlaceholder: "e.g. US parameters for tendinopathy",
    difficultyLevel: 3,
  },
  {
    id: "safety-protection",
    label: "Safety & Protection",
    contentArea: "Non-Systems — Safety (5–7 items)",
    textbookRefs: "OSHA, bloodborne pathogens, fall prevention",
    examHints: "body mechanics, fall prevention, infection control, emergency response",
    keywords: ["safety", "falls", "infection control", "body mechanics"],
    focusPlaceholder: "e.g. transfer safety, BBP exposure",
    difficultyLevel: 2,
  },
  {
    id: "professional-responsibilities",
    label: "Professional Responsibilities",
    contentArea: "Non-Systems — Professional (4–5 items)",
    textbookRefs: "APTA Code of Ethics, jurisdiction practice acts",
    examHints: "ethics, supervision, documentation, informed consent, scope of practice",
    keywords: ["ethics", "documentation", "supervision", "scope"],
    focusPlaceholder: "e.g. PTA supervision requirements",
    difficultyLevel: 2,
  },
  {
    id: "research-evidence",
    label: "Research & Evidence-Based Practice",
    contentArea: "Non-Systems — EBP (3–5 items)",
    textbookRefs: "EBP frameworks, statistics for clinicians",
    examHints: "study design, sensitivity/specificity, outcome measures, clinical prediction rules",
    keywords: ["EBP", "sensitivity", "specificity", "outcome measure"],
    focusPlaceholder: "e.g. interpreting RCT for intervention",
    difficultyLevel: 3,
  },
];
