import type { AnatomyStructure } from "./types";
import { generateBoneStructures } from "./bones/structures";
import { ANATOMY_SUBREGION_STRUCTURES } from "./subregions/structures";

/** Curated high-yield anatomical structures for board exam prep. */
const CORE_ANATOMY_STRUCTURES: AnatomyStructure[] = [
  {
    id: "heart",
    name: "Heart",
    system: "cardiovascular",
    layer: "organ",
    description:
      "Four-chamber muscular pump. Right side receives deoxygenated blood; left side pumps oxygenated blood systemically.",
    clinicalFacts: [
      "SA node (60–100 bpm) is the primary pacemaker; AV node delays impulse ~120 ms",
      "Left coronary artery supplies most of the left ventricle — dominant in ~85%",
      "Auscultation: Aortic (2nd R ICS), Pulmonic (2nd L ICS), Tricuspid (4th L), Mitral (5th L midclavicular)",
    ],
    pathologies: ["STEMI", "Heart failure", "Pericardial tamponade", "Endocarditis"],
    highYield: true,
    memoryCardIds: ["usmle-stemi-path", "usmle-acs-spectrum", "naplex-hf-four-pillars"],
    practiceTopicSlug: "cardiovascular",
    highYieldTopicSlug: "cardiovascular",
    biodigitalId: "production/maleAdult/male_respiratory_heart_01",
    meshId: "heart",
    keywords: ["cardiac", "myocardium", "chambers", "valves"],
  },
  {
    id: "aorta",
    name: "Aorta",
    system: "cardiovascular",
    layer: "vascular",
    description:
      "Largest artery; ascends from LV, arches, descends through thorax and abdomen. Branches supply head, neck, and viscera.",
    clinicalFacts: [
      "Aortic dissection: tearing chest pain radiating to back — type A needs surgery",
      "Coarctation: upper extremity HTN, weak femoral pulses, rib notching on CXR",
      "Ligamentum arteriosum connects aortic arch to pulmonary trunk (ductus arteriosus remnant)",
    ],
    pathologies: ["Aortic dissection", "Coarctation", "Aortic aneurysm"],
    highYield: true,
    memoryCardIds: ["usmle-acs-spectrum"],
    practiceTopicSlug: "cardiovascular",
    highYieldTopicSlug: "cardiovascular",
    meshId: "aorta",
    keywords: ["artery", "arch", "descending"],
  },
  {
    id: "carotid-artery",
    name: "Carotid Arteries",
    system: "cardiovascular",
    layer: "vascular",
    description:
      "Common carotid bifurcates at C4 into internal (intracranial) and external (face/scalp) branches. Pulse palpated at anterior border of sternocleidomastoid.",
    clinicalFacts: [
      "Carotid sinus hypersensitivity → bradycardia/hypotension with neck massage or tight collar",
      "Internal carotid supplies anterior circulation (MCA/ACA); external carotid → face/scalp",
      "Carotid bruit may indicate stenosis — correlate with stroke risk and need for imaging",
    ],
    pathologies: ["Carotid stenosis", "Dissection", "Stroke"],
    highYield: true,
    memoryCardIds: ["usmle-stroke-tpa", "usmle-tpa-exclusions"],
    practiceTopicSlug: "neurology-stroke",
    highYieldTopicSlug: "neurology-stroke",
    meshId: "carotid-artery",
    keywords: ["carotid", "stroke", "neck", "pulse"],
  },
  {
    id: "lungs",
    name: "Lungs",
    system: "respiratory",
    layer: "organ",
    description:
      "Paired organs for gas exchange. Right lung has 3 lobes; left has 2 (cardiac notch). Hilum contains bronchi, vessels, nerves.",
    clinicalFacts: [
      "Right main bronchus is wider, shorter, more vertical — aspiration favors right lower lobe",
      "Surfactant (type II pneumocytes) reduces surface tension; deficiency → RDS in neonates",
      "V/Q mismatch: apex high V/Q, base low V/Q — affects PAO2 and shunt physiology",
    ],
    pathologies: ["Pneumonia", "PE", "COPD", "Pneumothorax"],
    highYield: true,
    memoryCardIds: ["nclex-shock-types", "usmle-cap-antibiotics", "pance-copd-exacerbation", "nclex-sepsis-bundle"],
    practiceTopicSlug: "respiratory",
    highYieldTopicSlug: "respiratory",
    meshId: "lungs",
    keywords: ["pulmonary", "alveoli", "bronchi"],
  },
  {
    id: "trachea",
    name: "Trachea",
    system: "respiratory",
    layer: "organ",
    description:
      "Cartilaginous airway from larynx to carina (T4–T5), where it bifurcates into main bronchi. C-shaped hyaline rings open posteriorly toward esophagus.",
    clinicalFacts: [
      "Endotracheal tube tip should sit ~3–5 cm above carina on CXR — avoid mainstem intubation",
      "Tracheostomy sits below cricoid cartilage — surgical airway when upper airway obstructed",
      "Tracheal deviation suggests tension pneumothorax or large pleural mass",
    ],
    pathologies: ["Stridor", "Tracheomalacia", "Mainstem intubation"],
    highYield: true,
    memoryCardIds: ["nclex-shock-types"],
    practiceTopicSlug: "respiratory",
    highYieldTopicSlug: "respiratory",
    meshId: "trachea",
    keywords: ["airway", "carina", "bronchi", "intubation"],
  },
  {
    id: "spinal-cord",
    name: "Spinal Cord",
    system: "nervous",
    layer: "nerve",
    description:
      "Cylindrical extension of CNS from foramen magnum to ~L1–L2 (conus medullaris). Gray matter H-shaped; white matter tracts.",
    clinicalFacts: [
      "Complete cord transection: loss of all function below lesion (two-point discrimination, motor, autonomic)",
      "Brown-Séquard: ipsilateral motor/proprioception loss, contralateral pain/temp loss",
      "C5–T1 roots → upper limb; L2–S2 → lower limb dermatome/myotome patterns",
    ],
    pathologies: ["Transverse myelitis", "Epidural abscess", "Cord compression"],
    highYield: true,
    memoryCardIds: ["usmle-stroke-tpa"],
    practiceTopicSlug: "anatomy",
    highYieldTopicSlug: "neurology-stroke",
    meshId: "spinal-cord",
    keywords: ["spine", "vertebral", "tracts", "reflex"],
  },
  {
    id: "liver",
    name: "Liver",
    system: "digestive",
    layer: "organ",
    description:
      "Largest visceral organ in right upper quadrant. Dual blood supply: hepatic artery (~20%) and portal vein (~80%).",
    clinicalFacts: [
      "Porta hepatis: proper hepatic artery, portal vein, common bile duct (free edge of lesser omentum)",
      "Cirrhosis → portal HTN → varices, ascites, caput medusae, splenomegaly",
      "Couinaud segments (I–VIII) guide surgical resection and embolization",
    ],
    pathologies: ["Cirrhosis", "Hepatitis", "HCC", "Budd-Chiari"],
    highYield: true,
    memoryCardIds: ["naplex-abx-spectrum-ladder", "usmle-cap-antibiotics"],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "liver",
    keywords: ["hepatic", "portal", "RUQ"],
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    system: "digestive",
    layer: "organ",
    description:
      "Pear-shaped reservoir on visceral surface of liver storing bile. Cystic duct joins common hepatic duct to form common bile duct.",
    clinicalFacts: [
      "Murphy sign: inspiratory arrest with palpation in RUQ during acute cholecystitis",
      "Courvoisier sign: painless palpable gallbladder + jaundice suggests malignant obstruction (pancreatic head)",
      "Cystic artery usually branches from right hepatic artery in Calot triangle",
    ],
    pathologies: ["Cholelithiasis", "Cholecystitis", "Choledocholithiasis"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "gallbladder",
    keywords: ["bile", "cystic duct", "RUQ", "Murphy"],
  },
  {
    id: "pancreas",
    name: "Pancreas",
    system: "digestive",
    layer: "organ",
    description:
      "Retroperitoneal gland with exocrine (digestive enzymes) and endocrine (islets) functions. Head nestled in C-loop of duodenum.",
    clinicalFacts: [
      "Pancreatic head cancer → painless jaundice, Courvoisier gallbladder, weight loss",
      "Acute pancreatitis: epigastric pain radiating to back; check triglycerides and gallstones",
      "Main pancreatic duct joins common bile duct at ampulla of Vater (major duodenal papilla)",
    ],
    pathologies: ["Pancreatitis", "Pancreatic cancer", "Insulinoma"],
    highYield: true,
    memoryCardIds: ["usmle-dka-orders", "usmle-hhs-vs-dka"],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "pancreas",
    keywords: ["pancreatic", "islets", "ampulla", "epigastric"],
  },
  {
    id: "stomach",
    name: "Stomach",
    system: "digestive",
    layer: "organ",
    description:
      "J-shaped reservoir in left upper quadrant. Cardia, fundus, body, antrum, pylorus. Rich parasympathetic (vagus) innervation.",
    clinicalFacts: [
      "Left gastric artery (celiac trunk) along lesser curvature — peptic ulcer bleeding source",
      "Vagotomy reduces acid but can cause dumping syndrome and delayed gastric emptying",
      "Pyloric stenosis in infants: projectile non-bilious vomiting, olive-shaped mass",
    ],
    pathologies: ["Peptic ulcer", "Gastric cancer", "Pyloric stenosis"],
    highYield: false,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "stomach",
    keywords: ["gastric", "pylorus", "fundus"],
  },
  {
    id: "appendix",
    name: "Appendix",
    system: "digestive",
    layer: "organ",
    description:
      "Blind-ended pouch off cecum in right lower quadrant. Variable position (retrocecal common) affects clinical presentation.",
    clinicalFacts: [
      "McBurney point: one-third from ASIS to umbilicus — classic appendicitis tenderness",
      "Retrocecal appendix may lack peritoneal signs; consider pelvic or RUQ pain patterns",
      "Perforation → peritonitis; initial management includes fluids, antibiotics, and surgical consult",
    ],
    pathologies: ["Appendicitis", "Perforation", "Abscess"],
    highYield: true,
    memoryCardIds: ["nclex-abx-one-hour"],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "appendix",
    keywords: ["RLQ", "McBurney", "cecum", "appendicitis"],
  },
  {
    id: "kidneys",
    name: "Kidneys",
    system: "urinary",
    layer: "organ",
    description:
      "Retroperitoneal paired organs filtering blood. Nephrons perform filtration, reabsorption, secretion. Ureters drain to bladder.",
    clinicalFacts: [
      "Renal artery → segmental → interlobar → arcuate → interlobular → afferent arteriole",
      "Ureter passes under gonadal vessels, over iliac bifurcation — stone pain radiates to groin",
      "Horseshoe kidney fused at lower poles; trapped below IMA — increased UTI/stone risk",
    ],
    pathologies: ["AKI", "Nephrolithiasis", "Polycystic kidney disease"],
    highYield: true,
    memoryCardIds: ["usmle-hyperkalemia", "usmle-aki-fena", "all-creatinine-clearance", "pance-sepsis-bundle", "nclex-sepsis-bundle"],
    practiceTopicSlug: "renal-electrolytes",
    highYieldTopicSlug: "renal-electrolytes",
    meshId: "kidneys",
    keywords: ["renal", "nephron", "ureter"],
  },
  {
    id: "bladder",
    name: "Urinary Bladder",
    system: "urinary",
    layer: "organ",
    description:
      "Muscular reservoir in pelvis when full. Trigone receives ureteric orifices and urethral opening. Sympathetic (hypogastric) and parasympathetic (pelvic splanchnic) innervation.",
    clinicalFacts: [
      "Acute urinary retention: painful distended bladder — catheterize; check medications (anticholinergics)",
      "Interstitial cystitis: suprapubic pain relieved by voiding; exclude UTI",
      "Bladder cancer classic presentation: painless gross hematuria",
    ],
    pathologies: ["UTI", "Urinary retention", "Bladder cancer"],
    highYield: true,
    memoryCardIds: ["usmle-aki-fena"],
    practiceTopicSlug: "renal-electrolytes",
    highYieldTopicSlug: "renal-electrolytes",
    meshId: "bladder",
    keywords: ["urinary", "trigone", "retention", "hematuria"],
  },
  {
    id: "pelvis",
    name: "Pelvis",
    system: "skeletal",
    layer: "bone",
    description:
      "Bony ring formed by the two hip bones (innominates), sacrum, and coccyx. Supports the trunk and transmits weight to the lower limbs.",
    clinicalFacts: [
      "Open-book pelvic fracture can cause life-threatening hemorrhage — bind and resuscitate early",
      "Acetabulum articulates with femoral head — posterior hip dislocation risks sciatic nerve injury",
      "Pubic symphysis and sacroiliac joints allow limited motion during childbirth and gait",
    ],
    pathologies: ["Pelvic fracture", "Hip dislocation", "Osteitis pubis"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "pelvis",
    keywords: ["hip", "innominate", "acetabulum", "sacrum"],
  },
  {
    id: "femur",
    name: "Femur",
    system: "skeletal",
    layer: "bone",
    description:
      "Longest, strongest bone. Head articulates with acetabulum; neck is common fracture site in elderly (osteoporosis).",
    clinicalFacts: [
      "Femoral neck fracture: leg shortened, externally rotated; avascular necrosis risk (reticular artery)",
      "Intertrochanteric vs femoral neck fracture — different fixation and AVN risk profiles",
      "Femoral artery in femoral triangle — access site for cardiac catheterization",
    ],
    pathologies: ["Hip fracture", "Avascular necrosis", "Slipped capital femoral epiphysis"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "femur",
    keywords: ["hip", "thigh", "trochanter"],
  },
  {
    id: "humerus",
    name: "Humerus",
    system: "skeletal",
    layer: "bone",
    description:
      "Upper arm bone articulating with scapula proximally and radius/ulna distally. Surgical neck is fracture site affecting axillary nerve.",
    clinicalFacts: [
      "Axillary nerve injury (surgical neck fracture): flattened deltoid, loss of arm abduction",
      "Radial nerve in spiral groove: wrist drop with mid-shaft humerus fracture",
      "Supracondylar fracture in children — check distal neurovascular status (brachial artery, median nerve)",
    ],
    pathologies: ["Fracture", "Radial nerve palsy", "Axillary nerve injury"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "humerus",
    keywords: ["arm", "axillary", "radial", "fracture"],
  },
  {
    id: "tibia",
    name: "Tibia",
    system: "skeletal",
    layer: "bone",
    description:
      "Weight-bearing shin bone medial to fibula. Proximal plateau articulates with femur; malleolus forms medial ankle.",
    clinicalFacts: [
      "Tibial plateau fracture: think ACL/MCL injury and compartment syndrome risk",
      "Open tibia fracture high infection risk — urgent ortho/antibiotic management",
      "Anterior compartment syndrome: pain with passive toe extension, tense compartment",
    ],
    pathologies: ["Fracture", "Compartment syndrome", "Shin splints"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "tibia",
    keywords: ["leg", "shin", "ankle", "compartment"],
  },
  {
    id: "skull",
    name: "Skull",
    system: "skeletal",
    layer: "bone",
    description:
      "Cranium protects brain. Sutures (coronal, sagittal, lambdoid). Foramen magnum transmits spinal cord; jugular foramen CN IX–XI.",
    clinicalFacts: [
      "Epidural hematoma: middle meningeal artery — lucid interval, biconvex (lentiform) on CT",
      "Basilar skull fracture: Battle sign, raccoon eyes, CSF otorrhea/rhinorrhea",
      "Cavernous sinus: CN III, IV, V1, V2, VI; ICA; infection can spread from face",
    ],
    pathologies: ["Skull fracture", "Epidural hematoma", "Cavernous sinus thrombosis"],
    highYield: true,
    memoryCardIds: ["usmle-meningitis-emergency", "usmle-tpa-exclusions"],
    practiceTopicSlug: "anatomy",
    highYieldTopicSlug: "neurology-stroke",
    meshId: "skull",
    keywords: ["cranium", "foramen", "suture"],
  },
  {
    id: "sternum",
    name: "Sternum",
    system: "skeletal",
    layer: "bone",
    description:
      "Flat midline chest bone: manubrium, body, xiphoid process. Ribs articulate at costal cartilages; landmark for CPR and sternal IO access.",
    clinicalFacts: [
      "Sternal angle (of Louis) at T4–T5: second rib landmark; aortic arch begins/ends near this level",
      "CPR compressions target lower half of sternum — allow full recoil, minimize interruptions",
      "Sternal fracture from blunt trauma — evaluate for associated cardiac contusion and rib injuries",
    ],
    pathologies: ["Fracture", "Cardiac contusion", "Sternal IO access"],
    highYield: true,
    memoryCardIds: ["usmle-stemi-path"],
    practiceTopicSlug: "cardiovascular",
    highYieldTopicSlug: "cardiovascular",
    meshId: "sternum",
    keywords: ["chest", "CPR", "ribs", "manubrium"],
  },
  {
    id: "diaphragm",
    name: "Diaphragm",
    system: "muscular",
    layer: "muscle",
    description:
      "Primary muscle of respiration separating thoracic and abdominal cavities. Phrenic nerve (C3–C5) motor innervation.",
    clinicalFacts: [
      "C3, 4, 5 keep the diaphragm alive — phrenic nerve injury → hemidiaphragm paralysis",
      "Esophageal hiatus (T10), aortic hiatus (T12), caval opening (T8) — hiatal hernia at esophageal",
      "Referred shoulder pain with subdiaphragmatic irritation (splenic rupture, ectopic pregnancy)",
    ],
    pathologies: ["Hiatal hernia", "Diaphragmatic rupture", "Eventration"],
    highYield: true,
    memoryCardIds: ["nclex-shock-types"],
    practiceTopicSlug: "respiratory",
    highYieldTopicSlug: "respiratory",
    meshId: "diaphragm",
    keywords: ["respiration", "phrenic", "hiatus"],
  },
  {
    id: "biceps-brachii",
    name: "Biceps Brachii",
    system: "muscular",
    layer: "muscle",
    description:
      "Two-headed flexor of elbow and supinator of forearm. Long head origin from supraglenoid tubercle; short head from coracoid.",
    clinicalFacts: [
      "Musculocutaneous nerve (C5–C7) — weakness of elbow flexion and forearm supination",
      "Biceps tendon rupture: sudden pop, Popeye deformity; often long head at groove",
      "Deep tendon reflex tests C5–C6 via biceps reflex",
    ],
    pathologies: ["Tendon rupture", "Bicipital tendinitis"],
    highYield: false,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "biceps",
    keywords: ["arm", "flexion", "musculocutaneous"],
  },
  {
    id: "spleen",
    name: "Spleen",
    system: "lymphatic",
    layer: "organ",
    description:
      "Largest lymphoid organ in left upper quadrant, protected by ribs 9–11. Filters blood, removes senescent RBCs, immune function.",
    clinicalFacts: [
      "Kehr sign: left shoulder pain from diaphragmatic irritation in splenic rupture",
      "Howell-Jolly bodies after splenectomy — loss of pitted cell removal",
      "Risk of OPSI (overwhelming post-splenectomy infection) — pneumococcal vaccination essential",
    ],
    pathologies: ["Splenic rupture", "Hypersplenism", "Splenic infarct"],
    highYield: true,
    memoryCardIds: ["nclex-sepsis-bundle"],
    practiceTopicSlug: "critical-care",
    highYieldTopicSlug: "prioritization",
    meshId: "spleen",
    keywords: ["lymphoid", "LUQ", "rupture"],
  },
  {
    id: "thyroid",
    name: "Thyroid Gland",
    system: "endocrine",
    layer: "organ",
    description:
      "Butterfly-shaped endocrine gland anterior to trachea. Produces T3/T4; calcitonin from parafollicular (C) cells.",
    clinicalFacts: [
      "Recurrent laryngeal nerve (branch of vagus) loops under aortic arch (left) — injury → hoarseness",
      "Superior thyroid artery (external carotid) and inferior thyroid artery (thyrocervical trunk)",
      "Graves: exophthalmos, pretibial myxedema; Hashimoto: goiter with hypothyroidism",
    ],
    pathologies: ["Graves disease", "Hashimoto thyroiditis", "Thyroid cancer"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "endocrine-dm",
    highYieldTopicSlug: "endocrine-dm",
    meshId: "thyroid",
    keywords: ["T3", "T4", "goiter", "RLN"],
  },
  {
    id: "esophagus",
    name: "Esophagus",
    system: "digestive",
    layer: "organ",
    description:
      "Muscular tube from pharynx to stomach passing through the thoracic cavity and esophageal hiatus (T10). Upper third striated, lower two-thirds smooth muscle.",
    clinicalFacts: [
      "Achalasia: failure of LES relaxation — bird-beak on barium swallow, risk of aspiration",
      "Boerhaave syndrome: transmural esophageal rupture post-vomiting — surgical emergency",
      "Varices at gastroesophageal junction in portal hypertension — life-threatening bleed risk",
    ],
    pathologies: ["Achalasia", "Esophageal varices", "GERD", "Mallory-Weiss tear"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "esophagus",
    keywords: ["esophageal", "swallow", "hiatus", "GERD"],
  },
  {
    id: "duodenum",
    name: "Duodenum",
    system: "digestive",
    layer: "organ",
    description:
      "First segment of small intestine forming a C-loop around the pancreatic head. Receives gastric chyme, bile, and pancreatic enzymes.",
    clinicalFacts: [
      "Duodenal ulcers often related to H. pylori or NSAIDs — pain improves with food (vs gastric ulcer)",
      "Superior mesenteric artery syndrome: duodenum compressed between SMA and aorta",
      "Ampulla of Vater drains bile and pancreatic juice into the duodenal lumen",
    ],
    pathologies: ["Peptic ulcer", "SMA syndrome", "Obstruction"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "duodenum",
    keywords: ["small intestine", "ampulla", "ulcer", "SMA"],
  },
  {
    id: "small-intestine",
    name: "Small Intestine",
    system: "digestive",
    layer: "organ",
    description:
      "Long coiled tube (duodenum, jejunum, ileum) where most digestion and nutrient absorption occur. Jejunum in upper abdomen; ileum in lower abdomen and pelvis.",
    clinicalFacts: [
      "Celiac disease: villous atrophy in duodenum/jejunum — iron, B12, folate malabsorption",
      "Crohn disease can affect any segment; skip lesions and transmural inflammation are classic",
      "Superior mesenteric artery supplies midgut — ischemia causes pain out of proportion after eating",
    ],
    pathologies: ["Celiac disease", "Crohn disease", "SMA syndrome", "Obstruction"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "small-intestine",
    keywords: ["jejunum", "ileum", "absorption", "SMA", "coiled"],
  },
  {
    id: "colon",
    name: "Colon (Large Intestine)",
    system: "digestive",
    layer: "organ",
    description:
      "Frames the small intestine: ascending (right), transverse, descending (left), and sigmoid colon. Absorbs water and electrolytes; houses most gut flora.",
    clinicalFacts: [
      "Diverticulosis common in sigmoid colon — left lower quadrant pain suggests diverticulitis",
      "Colon cancer screening: colonoscopy; FIT for average-risk adults per guidelines",
      "Ulcerative colitis limited to colon and rectum; continuous inflammation from rectum proximally",
    ],
    pathologies: ["Diverticulitis", "Colorectal cancer", "Ulcerative colitis", "Volvulus"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "gastrointestinal",
    highYieldTopicSlug: "gastroenterology",
    meshId: "colon",
    keywords: ["large intestine", "sigmoid", "ascending", "transverse", "diverticulitis"],
  },
  {
    id: "clavicle",
    name: "Clavicle",
    system: "skeletal",
    layer: "bone",
    description:
      "S-shaped bone linking sternum to scapula. Common fracture from fall on outstretched hand or direct trauma.",
    clinicalFacts: [
      "Midshaft clavicle fracture is most common — figure-of-eight sling vs operative fixation by displacement",
      "Subclavian vessels and brachial plexus run posterior to clavicle — high-energy fractures need neurovascular exam",
      "Landmark for subclavian central line and brachial plexus blocks",
    ],
    pathologies: ["Fracture", "Nonunion", "Brachial plexus injury"],
    highYield: false,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "clavicle",
    keywords: ["collarbone", "shoulder", "fracture"],
  },
  {
    id: "scapula",
    name: "Scapula",
    system: "skeletal",
    layer: "bone",
    description:
      "Triangular flat bone of posterior thorax. Articulates with humerus at glenoid fossa; anchor for rotator cuff muscles.",
    clinicalFacts: [
      "Winged scapula: long thoracic nerve (CN XI) injury → serratus anterior weakness",
      "Scapular fracture often high-energy trauma — evaluate for chest and spine injuries",
      "Rotator cuff tears affect supraspinatus most often — painful arc on abduction",
    ],
    pathologies: ["Fracture", "Winged scapula", "Rotator cuff tear"],
    highYield: false,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    meshId: "scapula",
    keywords: ["shoulder", "glenoid", "rotator cuff"],
  },
  {
    id: "prostate",
    name: "Prostate",
    system: "urinary",
    layer: "organ",
    description:
      "Male accessory gland encircling the urethra below the bladder. Produces fluid component of semen; palpable on digital rectal exam.",
    clinicalFacts: [
      "BPH causes urinary frequency, weak stream, nocturia — alpha-blockers and 5-alpha reductase inhibitors",
      "Prostate cancer screening controversial — PSA, DRE, shared decision-making",
      "Acute bacterial prostatitis: fever, tender boggy prostate — avoid vigorous DRE if sepsis suspected",
    ],
    pathologies: ["BPH", "Prostatitis", "Prostate cancer"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "renal-electrolytes",
    highYieldTopicSlug: "renal-electrolytes",
    meshId: "prostate",
    keywords: ["BPH", "PSA", "DRE", "male"],
  },
  {
    id: "adrenal-glands",
    name: "Adrenal Glands",
    system: "endocrine",
    layer: "organ",
    description:
      "Paired suprarenal glands atop kidneys. Cortex (steroids) and medulla (catecholamines) with distinct embryologic origins.",
    clinicalFacts: [
      "Cushing syndrome: cortisol excess — moon facies, striae, hypertension, hyperglycemia",
      "Primary hyperaldosteronism: HTN + hypokalemia — screen with aldosterone/renin ratio",
      "Pheochromocytoma: episodic HTN, headache, sweating — rule out before anesthesia",
    ],
    pathologies: ["Cushing syndrome", "Addison disease", "Pheochromocytoma", "Conn syndrome"],
    highYield: true,
    memoryCardIds: ["usmle-hyperkalemia"],
    practiceTopicSlug: "endocrine-dm",
    highYieldTopicSlug: "endocrine-dm",
    meshId: "adrenal-glands",
    keywords: ["cortex", "medulla", "cortisol", "aldosterone"],
  },
  {
    id: "vertebral-column",
    name: "Vertebral Column",
    system: "skeletal",
    layer: "bone",
    description:
      "33 vertebrae: 7 cervical, 12 thoracic, 5 lumbar, 5 fused sacral, 4 coccygeal. Protects spinal cord; intervertebral discs allow motion.",
    clinicalFacts: [
      "C6–C7 common levels for central line insertion (internal jugular) — know vertebral landmarks",
      "L4–L5 disc herniation compresses L5 root — foot drop, dorsum foot numbness",
      "Cauda equina syndrome: saddle anesthesia, bowel/bladder dysfunction — surgical emergency",
    ],
    pathologies: ["Disc herniation", "Spinal stenosis", "Cauda equina syndrome", "Compression fracture"],
    highYield: true,
    memoryCardIds: [],
    practiceTopicSlug: "anatomy",
    highYieldTopicSlug: "neurology-stroke",
    meshId: "vertebral-column",
    keywords: ["spine", "vertebrae", "disc", "cervical", "lumbar"],
  },
];

/** Core organs + sub-regions + legacy bone summaries + all 206 individually named bones. */
export const ANATOMY_STRUCTURES: AnatomyStructure[] = [
  ...CORE_ANATOMY_STRUCTURES,
  ...ANATOMY_SUBREGION_STRUCTURES,
  ...generateBoneStructures(),
];
