import type { AnatomyDiseaseLink } from "./types";

/** Curated threads for remaining core-structure pathologies (organs 2–32). */
export const CURATED_DISEASE_LINKS_EXTENDED: AnatomyDiseaseLink[] = [
  // ── Cardiovascular ──
  {
    id: "infective-endocarditis",
    name: "Infective endocarditis",
    structureIds: ["heart"],
    pathologyLabel: "Endocarditis",
    pathophysiology: "Microbial colonization of endocardium/valves → vegetation, emboli, valve destruction.",
    presentation: ["Fever, new murmur, peripheral stigmata", "Blood cultures before antibiotics"],
    firstLineDrugIds: ["nafcillin", "oxacillin"],
    adjunctDrugIds: ["gentamicin", "vancomycin"],
    diagnosticEndpoints: [{ label: "Blood cultures", target: "≥2 sets before abx" }],
    monitoringEndpoints: [{ label: "Cr", target: "Aminoglycoside/vancomycin levels" }],
    treatmentGoals: ["Sterilize infection", "Prevent embolic complications"],
    examPearl: "MSSA → nafcillin/oxacillin + gentamicin synergy; MRSA → vancomycin.",
    highYield: true,
  },
  {
    id: "pericardial-tamponade",
    name: "Cardiac tamponade",
    structureIds: ["heart"],
    pathologyLabel: "Pericardial tamponade",
    pathophysiology: "Pericardial fluid ↑ intrapericardial pressure → impaired diastolic filling → shock.",
    presentation: ["Beck triad: hypotension, JVD, muffled heart sounds", "Pulsus paradoxus"],
    firstLineDrugIds: ["furosemide"],
    adjunctDrugIds: ["phenylephrine"],
    diagnosticEndpoints: [{ label: "Echo", target: "Pericardial effusion + RA collapse" }],
    treatmentGoals: ["Pericardiocentesis / drain", "Hemodynamic support"],
    examPearl: "Definitive treatment is drainage — fluids cautiously if tamponade.",
    highYield: true,
  },
  {
    id: "aortic-dissection",
    name: "Aortic dissection",
    structureIds: ["aorta"],
    pathologyLabel: "Aortic dissection",
    pathophysiology: "Intimal tear → blood in media → propagation along aortic wall.",
    presentation: ["Tearing chest pain radiating to back", "BP differential between arms"],
    firstLineDrugIds: ["esmolol", "labetalol"],
    adjunctDrugIds: ["morphine"],
    diagnosticEndpoints: [{ label: "CT angiography", target: "Dissection flap" }],
    monitoringEndpoints: [{ label: "HR, BP", target: "SBP <120, HR <60" }],
    treatmentGoals: ["↓ shear stress", "Type A → surgery; Type B → medical unless complicated"],
    highYield: true,
  },
  {
    id: "aortic-coarctation",
    name: "Coarctation of the aorta",
    structureIds: ["aorta"],
    pathologyLabel: "Coarctation",
    pathophysiology: "Congenital narrowing near ductus → upper-body HTN, lower-body hypoperfusion.",
    presentation: ["Upper extremity HTN, weak femoral pulses", "Rib notching on CXR"],
    firstLineDrugIds: ["amlodipine", "hydralazine"],
    diagnosticEndpoints: [{ label: "BP gradient", target: "Arms > legs" }],
    treatmentGoals: ["BP control", "Definitive repair (surgical/percutaneous)"],
    highYield: true,
  },
  {
    id: "aortic-aneurysm",
    name: "Abdominal aortic aneurysm",
    structureIds: ["aorta"],
    pathologyLabel: "Aortic aneurysm",
    pathophysiology: "Degenerative wall weakening → focal dilation with rupture risk.",
    presentation: ["Often asymptomatic until rupture", "Pulsatile abdominal mass"],
    firstLineDrugIds: ["amlodipine", "atorvastatin"],
    monitoringEndpoints: [{ label: "US/CT surveillance", target: "Repair if ≥5.5 cm" }],
    treatmentGoals: ["BP/smoking control", "Elective repair when size threshold met"],
    highYield: true,
  },
  {
    id: "carotid-stenosis",
    name: "Carotid stenosis",
    structureIds: ["carotid-artery"],
    pathologyLabel: "Carotid stenosis",
    pathophysiology: "Atherosclerotic plaque narrows carotid lumen → embolic stroke risk.",
    presentation: ["Bruit on exam", "TIA/stroke in anterior circulation"],
    firstLineDrugIds: ["atorvastatin", "aspirin"],
    adjunctDrugIds: ["clopidogrel"],
    diagnosticEndpoints: [{ label: "Carotid duplex", target: "Stenosis grade" }],
    treatmentGoals: ["ASCVD risk reduction", "Revascularization if symptomatic/high-grade"],
    highYield: true,
  },
  {
    id: "carotid-dissection",
    name: "Carotid artery dissection",
    structureIds: ["carotid-artery"],
    pathologyLabel: "Dissection",
    pathophysiology: "Intimal tear in carotid → stroke from hemodynamic compromise or thrombus.",
    presentation: ["Neck pain, Horner syndrome, headache", "Young patient with stroke"],
    firstLineDrugIds: ["aspirin"],
    adjunctDrugIds: ["clopidogrel"],
    treatmentGoals: ["Prevent thromboembolism", "Pain control"],
    highYield: true,
  },

  // ── Respiratory ──
  {
    id: "pneumothorax",
    name: "Pneumothorax",
    structureIds: ["lungs"],
    pathologyLabel: "Pneumothorax",
    pathophysiology: "Air in pleural space → lung collapse, V/Q mismatch.",
    presentation: ["Sudden pleuritic pain, dyspnea", "Absent breath sounds, hyperresonance"],
    firstLineDrugIds: ["morphine"],
    diagnosticEndpoints: [{ label: "CXR / US", target: "Visceral line" }],
    treatmentGoals: ["Needle decompression if tension", "Chest tube if large/symptomatic"],
    examPearl: "Tension PTX → needle 2nd ICS midclavicular before tube.",
    highYield: true,
  },
  {
    id: "asthma-bronchospasm",
    name: "Acute bronchospasm / asthma",
    structureIds: ["lungs", "trachea"],
    pathologyLabel: "Stridor",
    pathophysiology: "Bronchial smooth muscle constriction + inflammation → airflow obstruction.",
    presentation: ["Wheeze, dyspnea, cough", "↓ Peak flows in asthma"],
    firstLineDrugIds: ["albuterol"],
    adjunctDrugIds: ["prednisone", "ipratropium"],
    diagnosticEndpoints: [{ label: "Peak flow / spirometry" }],
    treatmentGoals: ["Bronchodilation", "↓ inflammation in exacerbation"],
    highYield: true,
  },

  // ── Nervous ──
  {
    id: "bacterial-meningitis",
    name: "Bacterial meningitis",
    structureIds: ["brain"],
    pathologyLabel: "Meningitis",
    pathophysiology: "Bacterial invasion of meninges → inflammation, ↑ ICP, sepsis.",
    presentation: ["Fever, headache, neck stiffness, altered mental status"],
    firstLineDrugIds: ["vancomycin", "cefuroxime"],
    adjunctDrugIds: ["dexamethasone"],
    diagnosticEndpoints: [{ label: "LP", target: "CSF pleocytosis, low glucose" }],
    treatmentGoals: [
      "Empiric antibiotics immediately (IDSA) — vancomycin + ceftriaxone preferred (ceftriaxone not in Top 500; cefuroxime shown as catalog proxy)",
      "Adjunct dexamethasone when indicated",
    ],
    examPearl:
      "Do not delay antibiotics for CT/LP if unstable. Boards: vancomycin + ceftriaxone (± ampicillin for Listeria).",
    highYield: true,
  },
  {
    id: "subdural-hematoma",
    name: "Subdural hematoma",
    structureIds: ["brain", "skull"],
    pathologyLabel: "Subdural hematoma",
    pathophysiology: "Bridging vein rupture → blood between dura and arachnoid.",
    presentation: ["Headache, confusion, focal deficits", "Crescent on CT (acute/subacute)"],
    firstLineDrugIds: ["mannitol"],
    adjunctDrugIds: ["dexamethasone"],
    diagnosticEndpoints: [{ label: "Non-contrast CT", target: "Crescent collection" }],
    treatmentGoals: ["ICP control", "Neurosurgical evacuation if indicated"],
    highYield: true,
  },
  {
    id: "uncal-herniation",
    name: "Brain herniation",
    structureIds: ["brain"],
    pathologyLabel: "Raised ICP",
    pathophysiology: "↑ ICP displaces brain tissue → brainstem compression.",
    presentation: ["↓ LOC, blown pupil (uncal), Cushing reflex"],
    firstLineDrugIds: ["mannitol"],
    adjunctDrugIds: ["dexamethasone"],
    treatmentGoals: ["↓ ICP emergently", "Neurosurgery"],
    examPearl: "CN III palsy + blown pupil → uncal herniation until proven otherwise.",
    highYield: true,
  },
  {
    id: "epidural-hematoma",
    name: "Epidural hematoma",
    structureIds: ["skull", "brain"],
    pathologyLabel: "Epidural hematoma",
    pathophysiology: "Middle meningeal artery bleed → lentiform hematoma, rapid expansion.",
    presentation: ["Lucid interval classic", "Head trauma, lateralizing signs"],
    firstLineDrugIds: ["mannitol"],
    diagnosticEndpoints: [{ label: "CT", target: "Biconvex hyperdensity" }],
    treatmentGoals: ["Emergent neurosurgical evacuation"],
    highYield: true,
  },
  {
    id: "spinal-epidural-abscess",
    name: "Spinal epidural abscess",
    structureIds: ["spinal-cord", "vertebral-column"],
    pathologyLabel: "Epidural abscess",
    pathophysiology: "Infection in epidural space → cord compression + sepsis.",
    presentation: ["Back pain, fever, progressive neuro deficit"],
    firstLineDrugIds: ["vancomycin", "piperacillin-tazobactam"],
    diagnosticEndpoints: [{ label: "MRI spine", target: "Epidural collection" }],
    treatmentGoals: ["Antibiotics + surgical decompression"],
    highYield: true,
  },
  {
    id: "cord-compression",
    name: "Spinal cord compression",
    structureIds: ["spinal-cord", "vertebral-column"],
    pathologyLabel: "Cord compression",
    pathophysiology: "Mass effect on cord (tumor, abscess, disc) → motor/sensory/autonomic loss.",
    presentation: ["Progressive weakness, sensory level, bowel/bladder dysfunction"],
    firstLineDrugIds: ["dexamethasone"],
    adjunctDrugIds: ["morphine"],
    treatmentGoals: ["Urgent decompression", "Treat underlying cause"],
    highYield: true,
  },
  {
    id: "disc-herniation",
    name: "Lumbar disc herniation",
    structureIds: ["vertebral-column"],
    pathologyLabel: "Disc herniation",
    pathophysiology: "Nucleus protrudes → nerve root compression (e.g., L5 → foot drop).",
    presentation: ["Radicular pain, dermatomal numbness", "Positive straight-leg raise"],
    firstLineDrugIds: ["ibuprofen", "gabapentin"],
    adjunctDrugIds: ["prednisone", "pregabalin"],
    diagnosticEndpoints: [{ label: "MRI", target: "Disc-nerve contact" }],
    treatmentGoals: ["Pain control", "Surgery if cauda equina or refractory"],
    highYield: true,
  },
  {
    id: "cauda-equina-syndrome",
    name: "Cauda equina syndrome",
    structureIds: ["vertebral-column", "spinal-cord"],
    pathologyLabel: "Cauda equina syndrome",
    pathophysiology: "Compression of lumbosacral nerve roots → saddle anesthesia, retention.",
    presentation: ["Saddle anesthesia", "Urinary retention, bowel incontinence"],
    firstLineDrugIds: ["dexamethasone"],
    treatmentGoals: ["Emergent surgical decompression"],
    examPearl: "Surgical emergency — do not delay MRI when suspected.",
    highYield: true,
  },

  // ── GI / hepatobiliary ──
  {
    id: "liver-cirrhosis",
    name: "Cirrhosis / portal hypertension",
    structureIds: ["liver", "esophagus", "spleen"],
    pathologyLabel: "Cirrhosis",
    pathophysiology: "Chronic hepatocyte injury → fibrosis, portal HTN, decompensation.",
    presentation: ["Ascites, varices, jaundice, encephalopathy"],
    firstLineDrugIds: ["lactulose", "spironolactone"],
    adjunctDrugIds: ["furosemide", "propranolol"],
    diagnosticEndpoints: [
      { label: "Albumin, INR", target: "Synthetic dysfunction" },
      { label: "Ammonia", target: "Encephalopathy workup" },
    ],
    monitoringEndpoints: [{ label: "Na, K", target: "Diuretic therapy" }],
    treatmentGoals: ["Treat complications", "HCC surveillance"],
    highYield: true,
  },
  {
    id: "acute-cholecystitis",
    name: "Acute cholecystitis",
    structureIds: ["gallbladder"],
    pathologyLabel: "Cholecystitis",
    pathophysiology: "Cystic duct obstruction → inflammation/infection of gallbladder.",
    presentation: ["RUQ pain, fever, Murphy sign positive"],
    firstLineDrugIds: ["piperacillin-tazobactam"],
    adjunctDrugIds: ["ciprofloxacin", "metronidazole"],
    diagnosticEndpoints: [{ label: "RUQ US", target: "Stones, wall thickening" }],
    treatmentGoals: ["Antibiotics + cholecystectomy"],
    highYield: true,
  },
  {
    id: "choledocholithiasis",
    name: "Choledocholithiasis / cholangitis",
    structureIds: ["gallbladder", "liver", "duodenum"],
    pathologyLabel: "Choledocholithiasis",
    pathophysiology: "CBD stone → biliary obstruction ± ascending infection.",
    presentation: ["Charcot triad: fever, jaundice, RUQ pain"],
    firstLineDrugIds: ["piperacillin-tazobactam"],
    adjunctDrugIds: ["ciprofloxacin"],
    treatmentGoals: ["ERCP for stone removal", "Antibiotics if cholangitis"],
    examPearl: "Reynolds pentad adds hypotension + AMS — severe cholangitis.",
    highYield: true,
  },
  {
    id: "acute-pancreatitis",
    name: "Acute pancreatitis",
    structureIds: ["pancreas"],
    pathologyLabel: "Pancreatitis",
    pathophysiology: "Premature enzyme activation → autodigestion, inflammation, third-spacing.",
    presentation: ["Epigastric pain radiating to back", "↑ lipase/amylase"],
    firstLineDrugIds: ["morphine"],
    adjunctDrugIds: ["ondansetron"],
    diagnosticEndpoints: [{ label: "Lipase", target: "≥3× ULN" }],
    treatmentGoals: ["Aggressive IV fluids", "Treat gallstone/ETOH cause"],
    highYield: true,
  },
  {
    id: "peptic-ulcer-disease",
    name: "Peptic ulcer disease",
    structureIds: ["stomach", "duodenum"],
    pathologyLabel: "Peptic ulcer",
    pathophysiology: "H. pylori and/or NSAIDs → mucosal break in stomach/duodenum.",
    presentation: ["Epigastric pain", "Duodenal ulcer improves with food"],
    firstLineDrugIds: ["omeprazole", "amoxicillin"],
    adjunctDrugIds: ["metronidazole", "sucralfate"],
    diagnosticEndpoints: [{ label: "EGD", target: "Ulcer visualization" }],
    treatmentGoals: ["H. pylori eradication if positive", "PPI therapy"],
    highYield: true,
  },
  {
    id: "acute-appendicitis",
    name: "Acute appendicitis",
    structureIds: ["appendix"],
    pathologyLabel: "Appendicitis",
    pathophysiology: "Luminal obstruction → inflammation, perforation risk.",
    presentation: ["Periumbilical pain → RLQ, McBurney tenderness"],
    firstLineDrugIds: ["piperacillin-tazobactam"],
    adjunctDrugIds: ["metronidazole", "ciprofloxacin"],
    treatmentGoals: ["Appendectomy", "Antibiotics if perforation"],
    highYield: true,
  },
  {
    id: "esophageal-varices",
    name: "Esophageal varices bleed",
    structureIds: ["esophagus", "liver"],
    pathologyLabel: "Esophageal varices",
    pathophysiology: "Portal HTN → dilated submucosal veins at GE junction.",
    presentation: ["Hematemesis, melena", "History of cirrhosis"],
    firstLineDrugIds: ["octreotide", "propranolol"],
    adjunctDrugIds: ["pantoprazole"],
    treatmentGoals: ["Hemostasis (banding)", "Non-selective β-blocker for prophylaxis"],
    highYield: true,
  },
  {
    id: "crohn-disease",
    name: "Crohn disease",
    structureIds: ["small-intestine", "colon"],
    pathologyLabel: "Crohn disease",
    pathophysiology: "Transmural granulomatous inflammation — any GI segment, skip lesions.",
    presentation: ["Crampy pain, diarrhea, weight loss", "Fistulas, abscesses"],
    firstLineDrugIds: ["mesalamine"],
    adjunctDrugIds: ["infliximab", "prednisone"],
    treatmentGoals: ["Induce/maintain remission", "Nutrition support"],
    highYield: true,
  },
  {
    id: "ulcerative-colitis",
    name: "Ulcerative colitis",
    structureIds: ["colon"],
    pathologyLabel: "Ulcerative colitis",
    pathophysiology: "Continuous mucosal inflammation from rectum proximally.",
    presentation: ["Bloody diarrhea, urgency", "Toxic megacolon risk"],
    firstLineDrugIds: ["mesalamine"],
    adjunctDrugIds: ["infliximab", "prednisone"],
    treatmentGoals: ["Induce remission", "Colon cancer surveillance"],
    highYield: true,
  },
  {
    id: "diverticulitis",
    name: "Acute diverticulitis",
    structureIds: ["colon"],
    pathologyLabel: "Diverticulitis",
    pathophysiology: "Microperforation of diverticulum → localized infection (often sigmoid).",
    presentation: ["LLQ pain, fever", "Localized tenderness"],
    firstLineDrugIds: ["ciprofloxacin", "metronidazole"],
    adjunctDrugIds: ["sulfamethoxazole-trimethoprim"],
    treatmentGoals: ["Antibiotics (uncomplicated)", "Drain/surgery if complicated"],
    highYield: true,
  },

  // ── Renal / GU ──
  {
    id: "nephrolithiasis",
    name: "Nephrolithiasis",
    structureIds: ["kidneys"],
    pathologyLabel: "Nephrolithiasis",
    pathophysiology: "Crystal aggregation in urinary tract → colic, obstruction.",
    presentation: ["Flank pain radiating to groin", "Hematuria"],
    firstLineDrugIds: ["ibuprofen", "tamsulosin"],
    adjunctDrugIds: ["acetazolamide", "allopurinol"],
    diagnosticEndpoints: [{ label: "CT KUB", target: "Stone burden" }],
    treatmentGoals: ["Pain control", "Facilitate passage / urology if obstructing"],
    highYield: true,
  },
  {
    id: "acute-urinary-retention",
    name: "Acute urinary retention",
    structureIds: ["bladder", "prostate"],
    pathologyLabel: "Urinary retention",
    pathophysiology: "Outlet obstruction or detrusor failure → painful bladder distension.",
    presentation: ["Suprapubic pain, inability to void", "Palpable bladder"],
    firstLineDrugIds: ["tamsulosin"],
    adjunctDrugIds: ["bethanechol"],
    treatmentGoals: ["Catheter decompression", "Treat underlying cause"],
    highYield: true,
  },
  {
    id: "acute-bacterial-prostatitis",
    name: "Acute bacterial prostatitis",
    structureIds: ["prostate"],
    pathologyLabel: "Prostatitis",
    pathophysiology: "Bacterial infection of prostate → fever, dysuria, tender prostate.",
    presentation: ["Fever, chills, perineal pain", "Tender boggy prostate"],
    firstLineDrugIds: ["ciprofloxacin"],
    adjunctDrugIds: ["sulfamethoxazole-trimethoprim"],
    treatmentGoals: ["Prolonged antibiotic course", "Avoid vigorous DRE if septic"],
    highYield: true,
  },

  // ── Endocrine ──
  {
    id: "thyroid-cancer-suppression",
    name: "Differentiated thyroid cancer",
    structureIds: ["thyroid"],
    pathologyLabel: "Thyroid cancer",
    pathophysiology: "Thyroid malignancy — papillary/follicular most common; TSH suppression therapy post-thyroidectomy.",
    presentation: ["Thyroid nodule, cervical nodes", "FNA guides management"],
    firstLineDrugIds: ["levothyroxine"],
    monitoringEndpoints: [{ label: "TSH", target: "Suppressed per risk stratification" }],
    treatmentGoals: ["Surgical resection", "TSH suppression", "RAI if indicated"],
    highYield: true,
  },
  {
    id: "cushing-syndrome",
    name: "Cushing syndrome",
    structureIds: ["adrenal-glands"],
    pathologyLabel: "Cushing syndrome",
    pathophysiology: "Chronic glucocorticoid excess → central obesity, hyperglycemia, HTN.",
    presentation: ["Moon facies, striae, proximal weakness"],
    firstLineDrugIds: ["ketoconazole"],
    adjunctDrugIds: ["metformin", "amlodipine"],
    diagnosticEndpoints: [
      { label: "Dexamethasone suppression", target: "Localization workup" },
      { label: "Late-night salivary cortisol" },
    ],
    treatmentGoals: ["Treat underlying source", "Glucose/BP management"],
    highYield: true,
  },
  {
    id: "pheochromocytoma",
    name: "Pheochromocytoma",
    structureIds: ["adrenal-glands"],
    pathologyLabel: "Pheochromocytoma",
    pathophysiology: "Catecholamine-secreting tumor → episodic HTN, tachycardia, sweating.",
    presentation: ["Paroxysmal headache, palpitations, diaphoresis"],
    firstLineDrugIds: ["labetalol"],
    adjunctDrugIds: ["doxazosin"],
    diagnosticEndpoints: [
      { label: "Plasma/urine metanephrines", target: "Elevated" },
    ],
    treatmentGoals: ["α-blockade before β-blockade", "Surgical resection"],
    examPearl: "Never give β-blocker alone — unopposed α worsens HTN.",
    highYield: true,
  },
  {
    id: "primary-hyperaldosteronism",
    name: "Primary hyperaldosteronism (Conn)",
    structureIds: ["adrenal-glands"],
    pathologyLabel: "Conn syndrome",
    pathophysiology: "Autonomous aldosterone → HTN, hypokalemia, metabolic alkalosis.",
    presentation: ["Resistant HTN, muscle cramps", "Hypokalemia"],
    firstLineDrugIds: ["spironolactone"],
    diagnosticEndpoints: [{ label: "Aldosterone/renin ratio", target: "Screening test" }],
    treatmentGoals: ["Confirm lateralization", "Surgery or MRA therapy"],
    highYield: true,
  },

  // ── Musculoskeletal / trauma (symptom-focused pharmacotherapy) ──
  {
    id: "hip-fracture-pain",
    name: "Hip fracture",
    structureIds: ["femur"],
    pathologyLabel: "Hip fracture",
    pathophysiology: "Femoral neck/intertrochanteric fracture — AVN risk at neck.",
    presentation: ["Shortened, externally rotated leg", "Inability to bear weight"],
    firstLineDrugIds: ["acetaminophen", "morphine"],
    treatmentGoals: ["Analgesia", "Early orthopedic fixation", "DVT prophylaxis"],
    highYield: true,
  },
  {
    id: "open-fracture-infection",
    name: "Open fracture / infection prophylaxis",
    structureIds: ["tibia", "humerus", "femur", "clavicle", "scapula", "sternum"],
    pathologyLabel: "Fracture",
    pathophysiology: "Open fracture exposes bone to contamination — osteomyelitis risk.",
    presentation: ["Visible bone, wound contamination", "Compartment syndrome signs in tibia"],
    firstLineDrugIds: ["nafcillin", "ciprofloxacin"],
    adjunctDrugIds: ["morphine", "acetaminophen"],
    treatmentGoals: ["Urgent debridement", "Antibiotics + stabilization"],
    highYield: true,
  },
  {
    id: "splenic-rupture",
    name: "Splenic rupture",
    structureIds: ["spleen", "diaphragm"],
    pathologyLabel: "Splenic rupture",
    pathophysiology: "Capsular tear → intraperitoneal hemorrhage; Kehr referred shoulder pain.",
    presentation: ["LUQ pain, hypotension", "Left shoulder pain (Kehr)"],
    firstLineDrugIds: ["morphine"],
    treatmentGoals: ["Hemodynamic resuscitation", "Splenectomy or embolization"],
    examPearl: "Post-splenectomy → pneumococcal vaccination, OPSI risk counseling.",
    highYield: true,
  },
  {
    id: "hiatal-hernia-gerd",
    name: "Hiatal hernia",
    structureIds: ["diaphragm", "esophagus", "stomach"],
    pathologyLabel: "Hiatal hernia",
    pathophysiology: "Stomach herniates through esophageal hiatus → reflux symptoms.",
    presentation: ["Heartburn, regurgitation", "Worse supine"],
    firstLineDrugIds: ["omeprazole"],
    treatmentGoals: ["Acid suppression", "Lifestyle modification"],
    highYield: true,
  },
  {
    id: "musculoskeletal-pain-nsaid",
    name: "Musculoskeletal pain / tendinitis",
    structureIds: ["biceps-brachii", "scapula", "clavicle"],
    pathologyLabel: "Bicipital tendinitis",
    pathophysiology: "Overuse inflammation of tendon/muscle insertions.",
    presentation: ["Localized pain with movement", "Tenderness over tendon"],
    firstLineDrugIds: ["ibuprofen", "naproxen"],
    adjunctDrugIds: ["acetaminophen"],
    treatmentGoals: ["NSAIDs + rest", "Physical therapy"],
    highYield: false,
  },
];
