import type { AnatomyDiseaseLink } from "./types";
import { applyClinicalDepth } from "./clinical-depth";
import { CURATED_DISEASE_LINKS_EXTENDED } from "./diseases-curated-extended";
import { CURATED_DISEASE_LINKS_LONGTAIL } from "./diseases-curated-longtail";

/** Hand-curated high-yield structure → disease → drug threads with clinical endpoints. */
export const CURATED_DISEASE_LINKS: AnatomyDiseaseLink[] = [
  {
    id: "primary-hypothyroidism",
    name: "Primary hypothyroidism",
    structureIds: ["thyroid"],
    pathologyLabel: "Hashimoto thyroiditis",
    pathophysiology:
      "Autoimmune thyroid destruction → decreased T4/T3 → loss of negative feedback → elevated TSH.",
    presentation: [
      "Fatigue, weight gain, cold intolerance, constipation",
      "Dry skin, bradycardia, delayed reflex relaxation",
      "↑ TSH with low free T4",
    ],
    bestDiagnosis: "↑ TSH + low free T4; anti-TPO supports Hashimoto thyroiditis.",
    treatmentRationale:
      "Replace missing thyroid hormone to restore euthyroidism and normalize TSH feedback.",
    drugRationales: {
      levothyroxine: {
        whyUsed:
          "Standard T4 replacement that converts peripherally to active T3 and is titrated to TSH.",
        briefMoa: "Synthetic T4; deiodinated to T3 → nuclear thyroid receptor activation.",
      },
      liothyronine: {
        whyUsed:
          "Direct T3 when rapid effect or myxedema adjunct is needed — not routine first-line monotherapy.",
        briefMoa: "Synthetic T3 binds thyroid receptors directly (short half-life).",
      },
    },
    firstLineDrugIds: ["levothyroxine"],
    adjunctDrugIds: ["liothyronine"],
    diagnosticEndpoints: [
      { label: "TSH", target: "Elevated" },
      { label: "Free T4", target: "Low" },
    ],
    monitoringEndpoints: [
      { label: "TSH recheck", target: "6–8 weeks after dose change", frequency: "Per titration" },
      { label: "Heart rate / symptoms", target: "Avoid overtreatment" },
    ],
    treatmentGoals: ["Normalize TSH", "Resolve hypothyroid symptoms"],
    counselingPearl:
      "Levothyroxine (Synthroid) on empty stomach 30–60 min before breakfast; separate from calcium, iron, PPIs.",
    examPearl: "Myxedema coma → IV T4 ± T3 + hydrocortisone (cover adrenal insufficiency).",
    highYield: true,
  },
  {
    id: "hyperthyroidism-graves",
    name: "Graves disease (hyperthyroidism)",
    structureIds: ["thyroid"],
    pathologyLabel: "Graves disease",
    pathophysiology: "TSH-receptor stimulating antibodies → excess thyroid hormone synthesis/release.",
    presentation: [
      "Weight loss, heat intolerance, tachycardia, tremor",
      "Exophthalmos, pretibial myxedema",
      "Suppressed TSH with ↑ free T4/T3",
    ],
    // ATDs (methimazole/PTU) are disease-modifying first-line per ATA but not in Top 500;
    // catalog agents support symptomatic control while definitive therapy is planned.
    firstLineDrugIds: [],
    adjunctDrugIds: ["propranolol"],
    diagnosticEndpoints: [
      { label: "TSH", target: "Suppressed" },
      { label: "TSH receptor antibodies", target: "Positive (Graves)" },
    ],
    monitoringEndpoints: [
      { label: "HR, BP", target: "Symptom control on β-blocker" },
      { label: "Free T4/T3", target: "Guide ATD titration (clinic)" },
    ],
    treatmentGoals: [
      "Start antithyroid drug (methimazole preferred; PTU in 1st trimester/storm) — not in Top 500 catalog",
      "β-blocker for adrenergic symptoms only",
      "Plan definitive therapy (ATD course, RAI, or surgery)",
    ],
    counselingPearl:
      "Propranolol treats symptoms only (ATA). Definitive therapy is methimazole/PTU, RAI, or surgery — coordinate endocrinology; do not call β-blocker disease-modifying first-line.",
    examPearl: "Thyroid storm: PTU + β-blocker + iodine (after ATD) + glucocorticoids.",
    highYield: true,
  },
  {
    id: "type-2-diabetes",
    name: "Type 2 diabetes mellitus",
    structureIds: ["pancreas"],
    pathophysiology: "Insulin resistance + progressive β-cell failure → hyperglycemia and ASCVD risk.",
    presentation: ["Polyuria, polydipsia when markedly elevated", "Often asymptomatic early"],
    firstLineDrugIds: ["metformin"],
    adjunctDrugIds: ["semaglutide", "empagliflozin", "glipizide"],
    diagnosticEndpoints: [
      { label: "A1c", target: "≥6.5% diagnostic" },
      { label: "Fasting glucose", target: "≥126 mg/dL" },
    ],
    monitoringEndpoints: [
      { label: "A1c", target: "<7% individualized", frequency: "Every 3–6 mo" },
      { label: "eGFR", target: "Before metformin / dose adjust if low" },
    ],
    treatmentGoals: [
      "Glycemic control",
      "ASCVD / HF / CKD risk reduction with GLP-1 RA or SGLT2i when indicated (ADA)",
    ],
    counselingPearl:
      "Metformin with meals; hold before contrast per protocol; monitor B12. Prefer GLP-1 RA / SGLT2i when ASCVD, HF, or CKD drives therapy choice.",
    highYield: true,
  },
  {
    id: "type-1-diabetes",
    name: "Type 1 diabetes mellitus",
    structureIds: ["pancreas"],
    pathophysiology: "Autoimmune β-cell destruction → absolute insulin deficiency.",
    presentation: ["Polyuria, polydipsia, weight loss", "DKA at presentation common in youth"],
    firstLineDrugIds: ["insulin-regular"],
    adjunctDrugIds: ["insulin-glargine"],
    diagnosticEndpoints: [
      { label: "Glucose", target: "Elevated" },
      { label: "Autoantibodies (GAD, IA-2)", target: "Support T1DM" },
    ],
    monitoringEndpoints: [
      { label: "A1c", target: "Age-adjusted goals" },
      { label: "Blood glucose", target: "SMBG or CGM per plan" },
    ],
    treatmentGoals: ["Insulin replacement", "Prevent DKA"],
    examPearl: "DKA: fluids + insulin only after K⁺ ≥3.3; add dextrose when glucose ~200.",
    highYield: true,
  },
  {
    id: "heart-failure-hfref",
    name: "Heart failure with reduced EF",
    structureIds: ["heart"],
    pathologyLabel: "Heart failure",
    pathophysiology: "Systolic dysfunction → neurohormonal activation, congestion, low forward flow.",
    presentation: ["Dyspnea, orthopnea, PND, edema", "S3, elevated JVP, crackles"],
    firstLineDrugIds: ["lisinopril", "metoprolol", "furosemide"],
    adjunctDrugIds: ["spironolactone", "carvedilol"],
    diagnosticEndpoints: [{ label: "BNP/NT-proBNP", target: "Elevated supports HF" }],
    monitoringEndpoints: [
      { label: "Daily weight", target: "Report ↑2–3 lb in 48 h" },
      { label: "K⁺, Cr", target: "On ACEi/ARB/MRA/diuretic" },
    ],
    treatmentGoals: ["↓ mortality (GDMT)", "Euvolemia", "Symptom relief"],
    counselingPearl: "Never stop β-blocker abruptly; low sodium diet.",
    highYield: true,
  },
  {
    id: "stemi-acs",
    name: "STEMI / acute coronary syndrome",
    structureIds: ["heart"],
    pathologyLabel: "STEMI",
    pathophysiology: "Plaque rupture → thrombotic coronary occlusion → transmural ischemia.",
    presentation: ["Crushing chest pain radiating to arm/jaw", "ST elevation on ECG in territory"],
    firstLineDrugIds: ["aspirin", "clopidogrel"],
    adjunctDrugIds: ["metoprolol", "atorvastatin"],
    diagnosticEndpoints: [
      { label: "ECG", target: "ST elevation" },
      { label: "Troponin", target: "Rising/falling" },
    ],
    monitoringEndpoints: [{ label: "Rhythm, BP", target: "Post-reperfusion" }],
    treatmentGoals: ["Reperfusion ASAP", "Dual antiplatelet therapy", "Secondary prevention"],
    examPearl: "Door-to-balloon / fibrinolysis — aspirin + P2Y12 + anticoagulation per protocol.",
    highYield: true,
  },
  {
    id: "hypertension-essential",
    name: "Essential hypertension",
    structureIds: ["heart", "aorta"],
    pathophysiology: "↑ SVR and/or volume → end-organ damage (heart, kidney, brain, retina).",
    presentation: ["Usually asymptomatic", "BP ≥130/80 on repeated measures"],
    firstLineDrugIds: ["amlodipine", "lisinopril", "hydrochlorothiazide"],
    diagnosticEndpoints: [{ label: "BP", target: "<130/80 goal (individualized)" }],
    monitoringEndpoints: [
      { label: "BP", frequency: "Each visit / home logs" },
      { label: "Cr, K⁺", target: "On ACEi/ARB/diuretic" },
    ],
    treatmentGoals: ["BP control", "ASCVD risk reduction"],
    highYield: true,
  },
  {
    id: "atrial-fibrillation-stroke",
    name: "Atrial fibrillation / stroke prevention",
    structureIds: ["heart", "carotid-artery", "brain"],
    pathologyLabel: "Cardioembolic stroke risk",
    pathophysiology: "Left atrial thrombus embolizes → anterior circulation stroke.",
    presentation: ["Sudden focal neuro deficit", "AF on ECG increases cardioembolic risk"],
    firstLineDrugIds: ["apixaban", "warfarin"],
    adjunctDrugIds: ["aspirin"],
    diagnosticEndpoints: [{ label: "CT head", target: "Rule hemorrhage before tPA" }],
    monitoringEndpoints: [{ label: "INR", target: "2–3 on warfarin", frequency: "Routine" }],
    treatmentGoals: ["Restore perfusion if eligible", "Anticoagulation for AF"],
    examPearl: "tPA window + exclusions; anticoagulate AF unless contraindicated.",
    highYield: true,
  },
  {
    id: "copd-chronic",
    name: "COPD (chronic bronchitis/emphysema)",
    structureIds: ["lungs"],
    pathologyLabel: "COPD",
    pathophysiology: "Small-airway inflammation + parenchymal destruction → chronic airflow limitation.",
    presentation: ["Chronic productive cough, dyspnea", "FEV1/FVC <0.70 post-bronchodilator"],
    firstLineDrugIds: ["albuterol", "ipratropium"],
    adjunctDrugIds: ["fluticasone-salmeterol"],
    diagnosticEndpoints: [{ label: "Spirometry", target: "FEV1/FVC <0.70" }],
    monitoringEndpoints: [{ label: "Symptoms, exacerbation frequency" }],
    treatmentGoals: ["Relieve dyspnea", "Prevent exacerbations", "Smoking cessation"],
    counselingPearl: "Rescue inhaler technique + smoking cessation are core therapy.",
    highYield: true,
  },
  {
    id: "community-pneumonia",
    name: "Community-acquired pneumonia",
    structureIds: ["lungs"],
    pathologyLabel: "Pneumonia",
    pathophysiology: "Alveolar infection → consolidation, impaired gas exchange.",
    presentation: ["Fever, productive cough, pleuritic chest pain", "Crackles, infiltrate on CXR"],
    firstLineDrugIds: ["amoxicillin", "azithromycin"],
    adjunctDrugIds: ["levofloxacin"],
    diagnosticEndpoints: [
      { label: "CXR", target: "Infiltrate" },
      { label: "Procalcitonin", target: "Supports bacterial etiology" },
    ],
    monitoringEndpoints: [{ label: "O₂ sat, RR", target: "Admission criteria" }],
    treatmentGoals: ["Appropriate empiric antibiotics", "Supportive care"],
    highYield: true,
  },
  {
    id: "pulmonary-embolism",
    name: "Pulmonary embolism",
    structureIds: ["lungs"],
    pathologyLabel: "PE",
    pathophysiology: "Venous thrombus lodges in pulmonary artery → V/Q mismatch, RV strain.",
    presentation: ["Sudden dyspnea, pleuritic pain", "Tachycardia, hypoxemia"],
    firstLineDrugIds: ["enoxaparin", "heparin-unfractionated"],
    adjunctDrugIds: ["warfarin", "apixaban"],
    diagnosticEndpoints: [{ label: "CT pulmonary angiography", target: "PE diagnosis" }],
    monitoringEndpoints: [{ label: "Hemodynamics, O₂", target: "Stability" }],
    treatmentGoals: ["Anticoagulation", "Hemodynamic support if massive PE"],
    examPearl: "Hemodynamically unstable PE → thrombolysis consideration.",
    highYield: true,
  },
  {
    id: "aki-prerenal",
    name: "Acute kidney injury (prerenal)",
    structureIds: ["kidneys"],
    pathologyLabel: "AKI",
    pathophysiology: "↓ Renal perfusion → reversible azotemia if perfusion restored.",
    presentation: ["↑ Cr/BUN, oliguria", "BUN:Cr >20:1 classic prerenal"],
    firstLineDrugIds: ["furosemide"],
    diagnosticEndpoints: [
      { label: "Serum creatinine", target: "↑ from baseline" },
      { label: "Urine Na", target: "<20 mEq/L prerenal" },
    ],
    monitoringEndpoints: [
      { label: "I/O, daily weight" },
      { label: "K⁺, acid-base", target: "Avoid hyperkalemia" },
    ],
    treatmentGoals: ["Restore perfusion", "Avoid nephrotoxins"],
    counselingPearl: "Hold NSAIDs, ACEi/ARB when AKI suspected.",
    highYield: true,
  },
  {
    id: "uti-uncomplicated",
    name: "Urinary tract infection",
    structureIds: ["bladder", "kidneys"],
    pathologyLabel: "UTI",
    pathophysiology: "Ascension of uropathogens → cystitis; pyelonephritis if upper tract involved.",
    presentation: ["Dysuria, frequency, urgency", "Flank pain/fever if pyelonephritis"],
    firstLineDrugIds: ["nitrofurantoin"],
    adjunctDrugIds: ["levofloxacin"],
    diagnosticEndpoints: [{ label: "Urinalysis", target: "Pyuria, bacteriuria" }],
    monitoringEndpoints: [{ label: "Symptom resolution", target: "48–72 h" }],
    treatmentGoals: ["Eradicate infection", "Shortest effective course"],
    highYield: true,
  },
  {
    id: "gerd-reflux",
    name: "GERD",
    structureIds: ["esophagus", "stomach"],
    pathologyLabel: "GERD",
    pathophysiology: "↓ LES tone / transient relaxations → acid injury to esophageal mucosa.",
    presentation: ["Heartburn, regurgitation", "Worse supine / post-prandial"],
    firstLineDrugIds: ["omeprazole", "pantoprazole"],
    diagnosticEndpoints: [{ label: "Clinical diagnosis", target: "Response to PPI trial" }],
    monitoringEndpoints: [{ label: "Alarm symptoms", target: "Dysphagia, weight loss → scope" }],
    treatmentGoals: ["Symptom control", "Heal esophagitis if present"],
    counselingPearl: "PPI 30–60 min before breakfast; lifestyle: elevate HOB, avoid late meals.",
    highYield: true,
  },
  {
    id: "bph-lut",
    name: "Benign prostatic hyperplasia",
    structureIds: ["prostate", "bladder"],
    pathologyLabel: "BPH",
    pathophysiology: "Prostatic enlargement → bladder outlet obstruction.",
    presentation: ["Weak stream, nocturia, incomplete emptying"],
    firstLineDrugIds: ["tamsulosin"],
    diagnosticEndpoints: [{ label: "IPSS symptom score" }],
    monitoringEndpoints: [{ label: "Post-void residual", target: "If retention suspected" }],
    treatmentGoals: ["Improve urinary flow", "Prevent retention"],
    highYield: true,
  },
  {
    id: "hyperlipidemia-ascvd",
    name: "Hyperlipidemia / ASCVD prevention",
    structureIds: ["heart", "aorta", "carotid-artery"],
    pathophysiology: "↑ Atherogenic lipoproteins → arterial plaque.",
    presentation: ["Often asymptomatic until event"],
    firstLineDrugIds: ["atorvastatin"],
    diagnosticEndpoints: [
      { label: "LDL-C", target: "Risk-based goal" },
      { label: "ASCVD risk calculator" },
    ],
    monitoringEndpoints: [
      { label: "LFTs", target: "Baseline and PRN" },
      { label: "Muscle symptoms / CK", target: "If myopathy suspected" },
    ],
    treatmentGoals: ["LDL reduction per risk", "Primary/secondary prevention"],
    counselingPearl: "Report unexplained muscle pain on statins.",
    highYield: true,
  },
  {
    id: "adrenal-insufficiency",
    name: "Adrenal insufficiency (Addison)",
    structureIds: ["adrenal-glands"],
    pathologyLabel: "Addison disease",
    pathophysiology: "Cortisol (± aldosterone) deficiency → hypotension, hyperkalemia, hypoglycemia.",
    presentation: ["Fatigue, hyperpigmentation, orthostasis", "Hyponatremia, hyperkalemia"],
    firstLineDrugIds: ["hydrocortisone"],
    adjunctDrugIds: ["prednisone"],
    diagnosticEndpoints: [
      { label: "AM cortisol", target: "Low" },
      { label: "ACTH stimulation test", target: "Non-responder in primary" },
    ],
    monitoringEndpoints: [{ label: "Stress-dose steroids", target: "Sick-day rules" }],
    treatmentGoals: ["Glucocorticoid replacement", "Fludrocortisone if mineralocorticoid deficient"],
    examPearl: "Adrenal crisis → hydrocortisone IV + fluids + glucose.",
    highYield: true,
  },
  {
    id: "seizure-epilepsy",
    name: "Seizure / epilepsy",
    structureIds: ["brain"],
    pathologyLabel: "Seizure",
    pathophysiology:
      "Abnormal hypersynchronous neuronal firing → clinical seizure; status = continuous/recurrent without recovery.",
    presentation: ["Convulsive or non-convulsive episodes", "Post-ictal confusion", "Status epilepticus medical emergency"],
    firstLineDrugIds: ["levetiracetam", "lorazepam"],
    adjunctDrugIds: ["phenytoin", "fosphenytoin"],
    diagnosticEndpoints: [
      { label: "Glucose / Na⁺ / imaging", target: "Rule out reversible causes" },
      { label: "EEG", target: "Support epilepsy diagnosis when indicated" },
    ],
    monitoringEndpoints: [
      { label: "Drug levels (phenytoin)", target: "Narrow therapeutic index" },
      { label: "Mood / behavior (levetiracetam)", target: "Counsel irritability risk" },
    ],
    treatmentGoals: ["Stop acute seizure / status", "Prevent recurrence with ASM"],
    counselingPearl:
      "Lorazepam first for status; then load ASM. Keppra preferred for many new-onset seizures (fewer interactions).",
    examPearl: "Status epilepticus: ABCs → benzos → fosphenytoin/levetiracetam/valproate load.",
    highYield: true,
  },
  {
    id: "ischemic-stroke-brain",
    name: "Ischemic stroke",
    structureIds: ["brain", "carotid-artery"],
    pathologyLabel: "Stroke",
    pathophysiology: "Arterial occlusion → focal brain ischemia in vascular territory.",
    presentation: ["Sudden unilateral weakness, speech change, visual loss"],
    firstLineDrugIds: ["aspirin"],
    adjunctDrugIds: ["clopidogrel", "atorvastatin"],
    diagnosticEndpoints: [{ label: "Non-contrast CT", target: "Exclude hemorrhage" }],
    monitoringEndpoints: [{ label: "NIHSS", target: "Serial neuro checks" }],
    treatmentGoals: ["Reperfusion if eligible (AHA/ASA)", "Secondary prevention"],
    counselingPearl:
      "Last-known-well drives tPA/thrombectomy eligibility; aspirin for non-cardioembolic secondary prevention after ICH excluded.",
    examPearl: "tPA exclusions matter — blood pressure, glucose, recent surgery, active bleed.",
    highYield: true,
  },
  ...CURATED_DISEASE_LINKS_EXTENDED,
  ...CURATED_DISEASE_LINKS_LONGTAIL,
].map(applyClinicalDepth);
