import type { AnatomyDiseaseLink } from "./types";

/** Curated threads for pathologies that indication-matching cannot reliably cover. */
export const CURATED_DISEASE_LINKS_LONGTAIL: AnatomyDiseaseLink[] = [
  {
    id: "appendiceal-perforation",
    name: "Appendiceal perforation",
    structureIds: ["appendix"],
    pathologyLabel: "Perforation",
    pathophysiology: "Appendiceal wall necrosis → intraperitoneal contamination and peritonitis.",
    presentation: ["Diffuse abdominal pain, fever", "Peritoneal signs"],
    firstLineDrugIds: ["piperacillin-tazobactam"],
    adjunctDrugIds: ["metronidazole", "ciprofloxacin"],
    treatmentGoals: ["Source control + antibiotics", "Resuscitation"],
    examPearl: "Perforated appendicitis → broad-spectrum coverage + urgent surgery.",
    highYield: true,
  },
  {
    id: "intra-abdominal-abscess",
    name: "Intra-abdominal abscess",
    structureIds: ["appendix"],
    pathologyLabel: "Abscess",
    pathophysiology: "Localized infection with walled-off pus after perforation or post-op complication.",
    presentation: ["Persistent fever, localized pain", "Leukocytosis"],
    firstLineDrugIds: ["piperacillin-tazobactam"],
    adjunctDrugIds: ["metronidazole"],
    treatmentGoals: ["Drainage + antibiotics", "Source control"],
    highYield: true,
  },
  {
    id: "tendon-rupture",
    name: "Tendon rupture",
    structureIds: ["biceps-brachii"],
    pathologyLabel: "Tendon rupture",
    pathophysiology: "Acute tendon fiber disruption → loss of function at insertion.",
    presentation: ["Pop sensation, ecchymosis", "Weakness against resisted motion"],
    firstLineDrugIds: ["ibuprofen", "acetaminophen"],
    adjunctDrugIds: ["cyclobenzaprine"],
    treatmentGoals: ["Pain control", "Orthopedic repair/rehab"],
    highYield: false,
  },
  {
    id: "bone-nonunion",
    name: "Fracture nonunion",
    structureIds: ["clavicle"],
    pathologyLabel: "Nonunion",
    pathophysiology: "Fracture fails to heal → persistent pain and instability.",
    presentation: ["Chronic pain at fracture site", "Abnormal motion at fracture"],
    firstLineDrugIds: ["acetaminophen", "tramadol"],
    adjunctDrugIds: ["alendronate"],
    treatmentGoals: ["Analgesia", "Surgical revision if indicated"],
    highYield: false,
  },
  {
    id: "sigmoid-volvulus",
    name: "Sigmoid volvulus",
    structureIds: ["colon"],
    pathologyLabel: "Volvulus",
    pathophysiology: "Twisted bowel loop → obstruction and ischemia risk.",
    presentation: ["Distension, obstipation", "Coffee-bean sign on XR"],
    firstLineDrugIds: ["morphine"],
    adjunctDrugIds: ["ondansetron"],
    treatmentGoals: ["Decompression (sigmoidoscopy)", "Surgical fixation if recurrent"],
    examPearl: "Sigmoid volvulus in elderly — detorsion then elective repair.",
    highYield: true,
  },
  {
    id: "diaphragmatic-rupture",
    name: "Diaphragmatic rupture",
    structureIds: ["diaphragm"],
    pathologyLabel: "Diaphragmatic rupture",
    pathophysiology: "Traumatic diaphragm tear → herniation of abdominal viscera into thorax.",
    presentation: ["Post-blunt trauma dyspnea", "Absent breath sounds, bowel sounds in chest"],
    firstLineDrugIds: ["morphine", "furosemide"],
    treatmentGoals: ["Surgical repair", "Respiratory support"],
    highYield: true,
  },
  {
    id: "diaphragmatic-eventration",
    name: "Diaphragmatic eventration",
    structureIds: ["diaphragm"],
    pathologyLabel: "Eventration",
    pathophysiology: "Abnormal elevation of diaphragm → restrictive physiology.",
    presentation: ["Dyspnea on exertion", "Elevated hemidiaphragm on imaging"],
    firstLineDrugIds: ["albuterol"],
    adjunctDrugIds: ["prednisone"],
    treatmentGoals: ["Optimize pulmonary function", "Plication if severe"],
    highYield: false,
  },
  {
    id: "small-bowel-obstruction",
    name: "Small bowel obstruction",
    structureIds: ["duodenum", "small-intestine"],
    pathologyLabel: "Obstruction",
    pathophysiology: "Mechanical or functional block → fluid sequestration, emesis, ischemia risk.",
    presentation: ["Colicky pain, vomiting, distension", "High-pitched bowel sounds early"],
    firstLineDrugIds: ["ondansetron", "morphine"],
    adjunctDrugIds: ["metoclopramide"],
    treatmentGoals: ["NG decompression", "Surgery if strangulation/perforation"],
    examPearl: "Complete obstruction — avoid promotility agents until obstruction ruled out.",
    highYield: true,
  },
  {
    id: "sma-syndrome",
    name: "Superior mesenteric artery syndrome",
    structureIds: ["duodenum", "small-intestine"],
    pathologyLabel: "SMA syndrome",
    pathophysiology: "Duodenum compressed between SMA and aorta → postprandial obstruction symptoms.",
    presentation: ["Postprandial pain, vomiting", "Weight loss"],
    firstLineDrugIds: ["metoclopramide", "omeprazole"],
    treatmentGoals: ["Nutritional support", "Postural therapy / surgery if refractory"],
    highYield: false,
  },
  {
    id: "achalasia",
    name: "Achalasia",
    structureIds: ["esophagus"],
    pathologyLabel: "Achalasia",
    pathophysiology: "LES fails to relax + aperistalsis → progressive dysphagia.",
    presentation: ["Dysphagia to solids and liquids", "Regurgitation, weight loss"],
    firstLineDrugIds: ["nifedipine"],
    adjunctDrugIds: ["metoclopramide"],
    treatmentGoals: ["LES relaxation", "Definitive: pneumatic dilation / myotomy"],
    highYield: true,
  },
  {
    id: "mallory-weiss-tear",
    name: "Mallory-Weiss tear",
    structureIds: ["esophagus", "stomach"],
    pathologyLabel: "Mallory-Weiss tear",
    pathophysiology: "Mucosal tear at GE junction after forceful retching → upper GI bleed.",
    presentation: ["Hematemesis after vomiting/retching", "Often self-limited"],
    firstLineDrugIds: ["pantoprazole"],
    adjunctDrugIds: ["ondansetron"],
    treatmentGoals: ["Hemostasis if ongoing", "Acid suppression"],
    highYield: true,
  },
  {
    id: "femoral-avn",
    name: "Avascular necrosis of femoral head",
    structureIds: ["femur"],
    pathologyLabel: "Avascular necrosis",
    pathophysiology: "Interrupted femoral head blood supply → subchondral collapse.",
    presentation: ["Groin pain, weight-bearing limitation", "MRI changes before X-ray"],
    firstLineDrugIds: ["acetaminophen", "ibuprofen"],
    adjunctDrugIds: ["alendronate"],
    treatmentGoals: ["Pain control", "Core decompression / arthroplasty"],
    highYield: true,
  },
  {
    id: "scfe",
    name: "Slipped capital femoral epiphysis",
    structureIds: ["femur"],
    pathologyLabel: "Slipped capital femoral epiphysis",
    pathophysiology: "Femoral head slips on physis — adolescent orthopedic emergency.",
    presentation: ["Hip/knee pain, antalgic gait", "Limited internal rotation"],
    firstLineDrugIds: ["morphine", "acetaminophen"],
    treatmentGoals: ["Non-weight-bearing", "Urgent pinning"],
    examPearl: "Bilateral in 20% — evaluate both hips.",
    highYield: true,
  },
  {
    id: "cholelithiasis",
    name: "Cholelithiasis",
    structureIds: ["gallbladder"],
    pathologyLabel: "Cholelithiasis",
    pathophysiology: "Gallstones in gallbladder → biliary colic when cystic duct obstructed.",
    presentation: ["RUQ pain after fatty meals", "Normal labs between attacks"],
    firstLineDrugIds: ["acetaminophen", "morphine"],
    treatmentGoals: ["Analgesia during colic", "Elective cholecystectomy for recurrent symptoms"],
    highYield: true,
  },
  {
    id: "radial-nerve-palsy",
    name: "Radial nerve palsy",
    structureIds: ["humerus"],
    pathologyLabel: "Radial nerve palsy",
    pathophysiology: "Radial nerve injury (often mid-shaft humerus fracture) → wrist drop.",
    presentation: ["Wrist/finger extension weakness", "Sensory loss dorsum hand"],
    firstLineDrugIds: ["gabapentin", "pregabalin"],
    adjunctDrugIds: ["acetaminophen"],
    treatmentGoals: ["Neuropathic pain control", "Splinting + nerve recovery monitoring"],
    highYield: true,
  },
  {
    id: "viral-hepatitis",
    name: "Viral hepatitis",
    structureIds: ["liver"],
    pathologyLabel: "Hepatitis",
    pathophysiology: "Hepatocyte inflammation from viral or autoimmune injury → transaminitis.",
    presentation: ["Jaundice, fatigue, RUQ discomfort", "↑ AST/ALT"],
    firstLineDrugIds: ["tenofovir-disoproxil"],
    adjunctDrugIds: ["elbasvir", "azathioprine"],
    treatmentGoals: ["Treat specific etiology (HBV/HCV/autoimmune)", "Avoid hepatotoxins"],
    examPearl: "HBV → tenofovir; HCV → direct-acting antivirals; autoimmune → azathioprine.",
    highYield: true,
  },
  {
    id: "hepatocellular-carcinoma",
    name: "Hepatocellular carcinoma",
    structureIds: ["liver"],
    pathologyLabel: "HCC",
    pathophysiology: "Primary liver malignancy, often on cirrhotic background.",
    presentation: ["Weight loss, ascites, variceal bleed", "AFP elevation"],
    firstLineDrugIds: ["cisplatin"],
    adjunctDrugIds: ["fluorouracil"],
    treatmentGoals: ["Staging and transplant candidacy", "Systemic therapy if advanced"],
    highYield: true,
  },
  {
    id: "budd-chiari",
    name: "Budd-Chiari syndrome",
    structureIds: ["liver"],
    pathologyLabel: "Budd-Chiari",
    pathophysiology: "Hepatic vein outflow obstruction → congestive hepatopathy.",
    presentation: ["Ascites, RUQ pain, hepatomegaly", "Hypercoagulable workup"],
    firstLineDrugIds: ["warfarin"],
    adjunctDrugIds: ["furosemide", "spironolactone"],
    treatmentGoals: ["Anticoagulation", "Revascularization / transplant if fulminant"],
    highYield: true,
  },
  {
    id: "insulinoma",
    name: "Insulinoma",
    structureIds: ["pancreas"],
    pathologyLabel: "Insulinoma",
    pathophysiology: "β-cell tumor secretes insulin → recurrent hypoglycemia.",
    presentation: ["Whipple triad: hypoglycemia symptoms, low glucose, relief with glucose"],
    firstLineDrugIds: ["octreotide"],
    adjunctDrugIds: ["glucagon"],
    diagnosticEndpoints: [{ label: "Fasting glucose", target: "<70 mg/dL with symptoms" }],
    treatmentGoals: ["Prevent hypoglycemia", "Surgical resection"],
    examPearl: "Octreotide suppresses insulin secretion pre-operatively.",
    highYield: true,
  },
  {
    id: "winged-scapula",
    name: "Winged scapula (long thoracic nerve injury)",
    structureIds: ["scapula"],
    pathologyLabel: "Winged scapula",
    pathophysiology: "Serratus anterior weakness → medial scapular prominence.",
    presentation: ["Scapular winging with wall push-up", "Often after axillary node dissection"],
    firstLineDrugIds: ["gabapentin", "ibuprofen"],
    treatmentGoals: ["Neuropathic pain control", "Physical therapy / nerve recovery"],
    highYield: false,
  },
  {
    id: "rotator-cuff-tear",
    name: "Rotator cuff tear",
    structureIds: ["scapula"],
    pathologyLabel: "Rotator cuff tear",
    pathophysiology: "Supraspinatus/infraspinatus tendon tear → painful arc, weakness.",
    presentation: ["Night pain, painful abduction arc", "↓ Supraspinatus strength"],
    firstLineDrugIds: ["ibuprofen", "naproxen"],
    adjunctDrugIds: ["acetaminophen"],
    treatmentGoals: ["NSAIDs + PT", "Surgical repair if full-thickness in active patient"],
    highYield: false,
  },
  {
    id: "skull-fracture",
    name: "Skull fracture",
    structureIds: ["skull"],
    pathologyLabel: "Skull fracture",
    pathophysiology: "Calvarial fracture — base fractures risk CSF leak and neurovascular injury.",
    presentation: ["Trauma, scalp hematoma", "Battle sign / raccoon eyes if base fracture"],
    firstLineDrugIds: ["acetaminophen", "morphine"],
    treatmentGoals: ["Neuro monitoring", "Treat intracranial complications"],
    highYield: true,
  },
  {
    id: "transverse-myelitis",
    name: "Transverse myelitis",
    structureIds: ["spinal-cord"],
    pathologyLabel: "Transverse myelitis",
    pathophysiology: "Inflammatory spinal cord lesion → bilateral motor/sensory/autonomic deficit.",
    presentation: ["Acute weakness, sensory level, bladder dysfunction"],
    firstLineDrugIds: ["methylprednisolone"],
    adjunctDrugIds: ["dexamethasone"],
    treatmentGoals: ["High-dose steroids", "Rule out compressive etiology"],
    highYield: true,
  },
  {
    id: "hypersplenism",
    name: "Hypersplenism",
    structureIds: ["spleen"],
    pathologyLabel: "Hypersplenism",
    pathophysiology: "Splenic sequestration → cytopenias (anemia, thrombocytopenia, leukopenia).",
    presentation: ["Fatigue, bleeding, infections", "Splenomegaly"],
    firstLineDrugIds: ["folic-acid"],
    adjunctDrugIds: ["prednisone"],
    treatmentGoals: ["Treat underlying cause", "Splenectomy if severe cytopenias"],
    highYield: true,
  },
  {
    id: "splenic-infarct",
    name: "Splenic infarction",
    structureIds: ["spleen"],
    pathologyLabel: "Splenic infarct",
    pathophysiology: "Splenic artery occlusion → wedge-shaped infarct, LUQ pain.",
    presentation: ["LUQ pain, fever", "Often in atrial fibrillation or hypercoagulable states"],
    firstLineDrugIds: ["apixaban"],
    adjunctDrugIds: ["warfarin"],
    treatmentGoals: ["Anticoagulation if embolic", "Analgesia"],
    highYield: true,
  },
  {
    id: "sternal-io-access",
    name: "Intraosseous access (sternal)",
    structureIds: ["sternum"],
    pathologyLabel: "Sternal IO access",
    pathophysiology: "Emergency vascular access via sternal marrow when peripheral/central access fails.",
    presentation: ["Cardiac arrest or shock", "Failed IV access"],
    firstLineDrugIds: ["lidocaine"],
    adjunctDrugIds: ["ketamine"],
    treatmentGoals: ["Rapid access for resuscitation drugs", "Transition to definitive access"],
    examPearl: "IO delivers same resuscitation meds as IV — flush well after each dose.",
    highYield: true,
  },
  {
    id: "pyloric-stenosis",
    name: "Pyloric stenosis",
    structureIds: ["stomach"],
    pathologyLabel: "Pyloric stenosis",
    pathophysiology: "Hypertrophied pylorus in infant → gastric outlet obstruction.",
    presentation: ["Projectile nonbilious vomiting", "Hypochloremic metabolic alkalosis"],
    firstLineDrugIds: ["ondansetron"],
    adjunctDrugIds: ["metoclopramide"],
    treatmentGoals: ["Correct dehydration/electrolytes", "Pyloromyotomy"],
    examPearl: "Olive-shaped mass + peristaltic waves — surgical cure.",
    highYield: true,
  },
  {
    id: "shin-splints",
    name: "Medial tibial stress syndrome",
    structureIds: ["tibia"],
    pathologyLabel: "Shin splints",
    pathophysiology: "Repetitive periosteal stress at tibia → exercise-related leg pain.",
    presentation: ["Anterior leg pain with activity", "Improves with rest"],
    firstLineDrugIds: ["ibuprofen", "naproxen"],
    adjunctDrugIds: ["acetaminophen"],
    treatmentGoals: ["Activity modification", "Gradual return to training"],
    highYield: false,
  },
  {
    id: "tracheomalacia",
    name: "Tracheomalacia",
    structureIds: ["trachea"],
    pathologyLabel: "Tracheomalacia",
    pathophysiology: "Tracheal cartilage weakness → dynamic airway collapse on expiration.",
    presentation: ["Barking cough, stridor with exertion", "Worse supine"],
    firstLineDrugIds: ["albuterol"],
    adjunctDrugIds: ["dexamethasone"],
    treatmentGoals: ["Airway support", "Surgical stenting if severe"],
    highYield: true,
  },
  {
    id: "spinal-stenosis",
    name: "Lumbar spinal stenosis",
    structureIds: ["vertebral-column"],
    pathologyLabel: "Spinal stenosis",
    pathophysiology: "Canal narrowing → neurogenic claudication (leg pain with walking, relieved by flexion).",
    presentation: ["Leg pain with ambulation", "Shopping-cart sign"],
    firstLineDrugIds: ["gabapentin", "pregabalin"],
    adjunctDrugIds: ["ibuprofen"],
    treatmentGoals: ["Neuropathic pain control", "Decompression if progressive deficit"],
    highYield: true,
  },
  {
    id: "compression-fracture",
    name: "Vertebral compression fracture",
    structureIds: ["vertebral-column"],
    pathologyLabel: "Compression fracture",
    pathophysiology: "Vertebral body collapse — osteoporosis or trauma.",
    presentation: ["Acute back pain after minor trauma", "Height loss in elderly"],
    firstLineDrugIds: ["acetaminophen", "morphine"],
    adjunctDrugIds: ["alendronate"],
    treatmentGoals: ["Analgesia", "Treat osteoporosis", "Kyphoplasty if indicated"],
    highYield: true,
  },
  {
    id: "celiac-disease",
    name: "Celiac disease",
    structureIds: ["small-intestine"],
    pathologyLabel: "Celiac disease",
    pathophysiology: "Gluten-triggered autoimmune enteropathy → malabsorption.",
    presentation: ["Diarrhea, bloating, weight loss", "Iron deficiency, dermatitis herpetiformis"],
    firstLineDrugIds: ["folic-acid"],
    adjunctDrugIds: ["prednisone"],
    diagnosticEndpoints: [{ label: "TTG IgA", target: "Positive with compatible biopsy" }],
    treatmentGoals: ["Strict gluten-free diet", "Replace deficiencies"],
    examPearl: "Lifelong gluten avoidance — steroids only for refractory celiac.",
    highYield: true,
  },
  {
    id: "compartment-syndrome",
    name: "Compartment syndrome",
    structureIds: ["tibia"],
    pathologyLabel: "Compartment syndrome",
    pathophysiology: "↑ fascial compartment pressure → ischemia of muscles/nerves.",
    presentation: ["Pain out of proportion, pain with passive stretch", "6 Ps late findings"],
    firstLineDrugIds: ["morphine"],
    adjunctDrugIds: ["ketamine"],
    treatmentGoals: ["Emergent fasciotomy", "Analgesia does not replace surgery"],
    examPearl: "Clinical diagnosis — do not delay surgery for compartment pressures if classic.",
    highYield: true,
  },
  {
    id: "mainstem-intubation",
    name: "Mainstem bronchus intubation",
    structureIds: ["trachea", "lungs"],
    pathologyLabel: "Mainstem intubation",
    pathophysiology: "ETT advanced into right mainstem → left lung collapse, hypoxemia.",
    presentation: ["Sudden desaturation after intubation", "Unilateral breath sounds"],
    firstLineDrugIds: ["albuterol"],
    adjunctDrugIds: ["furosemide"],
    treatmentGoals: ["Reposition ETT", "Confirm with bilateral breath sounds + CXR"],
    examPearl: "Right mainstem is default malposition — withdraw tube 2–3 cm.",
    highYield: true,
  },
  {
    id: "bladder-cancer",
    name: "Bladder cancer",
    structureIds: ["bladder"],
    pathologyLabel: "Bladder cancer",
    pathophysiology: "Urothelial malignancy → painless hematuria most common presentation.",
    presentation: ["Painless gross hematuria", "Smoking is major risk factor"],
    firstLineDrugIds: ["mitomycin"],
    adjunctDrugIds: ["cisplatin"],
    treatmentGoals: ["Staging with cystoscopy", "Intravesical or systemic therapy by stage"],
    highYield: true,
  },
  {
    id: "prostate-cancer",
    name: "Prostate cancer",
    structureIds: ["prostate"],
    pathologyLabel: "Prostate cancer",
    pathophysiology: "Adenocarcinoma of prostate → local invasion and metastasis to bone.",
    presentation: ["↑ PSA, abnormal DRE", "Bone pain if metastatic"],
    firstLineDrugIds: ["enzalutamide"],
    adjunctDrugIds: ["leuprolide"],
    treatmentGoals: ["Risk stratification", "Androgen deprivation ± novel agents"],
    highYield: true,
  },
  {
    id: "pancreatic-cancer",
    name: "Pancreatic adenocarcinoma",
    structureIds: ["pancreas"],
    pathologyLabel: "Pancreatic cancer",
    pathophysiology: "Pancreatic ductal adenocarcinoma → obstructive jaundice, weight loss, thrombosis.",
    presentation: ["Painless jaundice, weight loss", "Trousseau migratory thrombophlebitis"],
    firstLineDrugIds: ["gemcitabine"],
    adjunctDrugIds: ["fluorouracil"],
    treatmentGoals: ["Resectability assessment", "Palliative chemo if advanced"],
    highYield: true,
  },
  {
    id: "colorectal-cancer",
    name: "Colorectal cancer",
    structureIds: ["colon"],
    pathologyLabel: "Colorectal cancer",
    pathophysiology: "Adenomatous polyp progression → local invasion and metastasis.",
    presentation: ["Hematochezia, anemia, change in stool caliber", "Right vs left colon presentations differ"],
    firstLineDrugIds: ["fluorouracil"],
    adjunctDrugIds: ["cisplatin"],
    treatmentGoals: ["Surgical resection", "Adjuvant chemotherapy by stage"],
    highYield: true,
  },
  {
    id: "gastric-cancer",
    name: "Gastric cancer",
    structureIds: ["stomach"],
    pathologyLabel: "Gastric cancer",
    pathophysiology: "Gastric adenocarcinoma — H. pylori and dietary risk factors.",
    presentation: ["Early satiety, weight loss", "Virchow node if advanced"],
    firstLineDrugIds: ["trastuzumab"],
    adjunctDrugIds: ["fluorouracil"],
    treatmentGoals: ["HER2 testing", "Surgery + perioperative chemo"],
    highYield: true,
  },
  {
    id: "pkd",
    name: "Polycystic kidney disease",
    structureIds: ["kidneys"],
    pathologyLabel: "Polycystic kidney disease",
    pathophysiology: "Inherited cystic kidney disease → HTN, progressive CKD, berry aneurysms.",
    presentation: ["HTN, flank fullness, hematuria", "Family history"],
    firstLineDrugIds: ["lisinopril"],
    adjunctDrugIds: ["amlodipine"],
    treatmentGoals: ["BP control", "Monitor for aneurysm and CKD progression"],
    highYield: true,
  },
  {
    id: "cavernous-sinus-thrombosis",
    name: "Cavernous sinus thrombosis",
    structureIds: ["skull", "brain"],
    pathologyLabel: "Cavernous sinus thrombosis",
    pathophysiology: "Septic or aseptic thrombosis of cavernous sinus → cranial neuropathies.",
    presentation: ["Headache, fever, proptosis", "CN III/IV/VI palsies"],
    firstLineDrugIds: ["vancomycin"],
    adjunctDrugIds: ["cefuroxime", "moxifloxacin"],
    treatmentGoals: ["Broad antibiotics + anticoagulation debate", "Drain source infection"],
    examPearl: "Often spreads from sphenoid/ethmoid sinusitis — ophthalmoplegia + chemosis.",
    highYield: true,
  },
  {
    id: "cardiac-contusion",
    name: "Cardiac contusion",
    structureIds: ["sternum", "heart"],
    pathologyLabel: "Cardiac contusion",
    pathophysiology: "Blunt chest trauma → myocardial injury, arrhythmia risk.",
    presentation: ["Chest wall pain after trauma", "ECG changes, troponin elevation"],
    firstLineDrugIds: ["metoprolol"],
    adjunctDrugIds: ["aspirin"],
    treatmentGoals: ["Telemetry monitoring", "Treat arrhythmias"],
    highYield: true,
  },
  {
    id: "axillary-nerve-injury",
    name: "Axillary nerve injury",
    structureIds: ["humerus", "scapula"],
    pathologyLabel: "Axillary nerve injury",
    pathophysiology: "Axillary nerve damage (surgical neck fracture, anterior dislocation) → deltoid weakness.",
    presentation: ["Deltoid weakness, lateral shoulder numbness"],
    firstLineDrugIds: ["gabapentin", "pregabalin"],
    adjunctDrugIds: ["baclofen"],
    treatmentGoals: ["Neuropathic pain control", "Shoulder immobilization + PT"],
    highYield: false,
  },
  {
    id: "brachial-plexus-injury",
    name: "Brachial plexus injury",
    structureIds: ["clavicle"],
    pathologyLabel: "Brachial plexus injury",
    pathophysiology: "Traction/avulsion of brachial plexus → arm weakness/sensory loss.",
    presentation: ["Weakness after trauma or delivery", "Erb-Duchenne vs Klumpke patterns"],
    firstLineDrugIds: ["gabapentin", "pregabalin"],
    adjunctDrugIds: ["baclofen"],
    treatmentGoals: ["Pain control", "Neurosurgical evaluation if avulsion"],
    highYield: true,
  },
];
