/** Search terms for semi-auto pathology ↔ drug indication matching. */
export const PATHOLOGY_SEARCH_TERMS: Record<string, string[]> = {
  stemi: ["stemi", "myocardial infarction", "mi", "acs", "acute coronary"],
  "heart failure": ["heart failure", "hfref", "hfpef", "chf", "cardiac failure"],
  endocarditis: ["endocarditis", "infective endocarditis"],
  "pericardial tamponade": ["tamponade", "pericardial"],
  "aortic dissection": ["aortic dissection", "dissection"],
  coarctation: ["coarctation"],
  "aortic aneurysm": ["aneurysm", "aaa"],
  "carotid stenosis": ["carotid stenosis", "carotid disease"],
  stroke: ["stroke", "cva", "ischemic stroke", "tia"],
  pneumonia: ["pneumonia", "cap", "community-acquired pneumonia"],
  pe: ["pulmonary embolism", "pe", "venous thromboembolism", "vte"],
  copd: ["copd", "chronic obstructive", "emphysema", "chronic bronchitis"],
  pneumothorax: ["pneumothorax"],
  asthma: ["asthma", "bronchospasm"],
  cirrhosis: ["cirrhosis", "portal hypertension", "hepatic encephalopathy"],
  hepatitis: ["hepatitis", "hbv", "hcv"],
  cholecystitis: ["cholecystitis", "gallstone", "biliary"],
  cholelithiasis: ["cholelithiasis", "gallstone"],
  pancreatitis: ["pancreatitis"],
  "peptic ulcer": ["peptic ulcer", "pud", "ulcer disease"],
  gerd: ["gerd", "gastroesophageal reflux", "reflux"],
  appendicitis: ["appendicitis"],
  aki: ["acute kidney injury", "aki", "renal failure"],
  uti: ["uti", "urinary tract infection", "cystitis", "pyelonephritis"],
  bph: ["bph", "benign prostatic hyperplasia", "prostatic hyperplasia"],
  "prostate cancer": ["prostate cancer"],
  hypothyroidism: ["hypothyroidism", "hypothyroid", "hashimoto"],
  "hashimoto thyroiditis": ["hashimoto", "hypothyroidism"],
  "graves disease": ["graves", "hyperthyroidism", "thyrotoxicosis"],
  "thyroid cancer": ["thyroid cancer", "thyroid suppression"],
  diabetes: ["diabetes", "type 2 diabetes", "type 1 diabetes", "dm"],
  hypertension: ["hypertension", "high blood pressure"],
  hyperlipidemia: ["hyperlipidemia", "dyslipidemia", "ascvd", "hypercholesterolemia"],
  meningitis: ["meningitis"],
  "addison disease": ["addison", "adrenal insufficiency"],
  "cushing syndrome": ["cushing", "hypercortisolism"],
  fracture: ["fracture", "bone fracture"],
  "disc herniation": ["disc herniation", "radiculopathy", "sciatica"],
  diverticulitis: ["diverticulitis", "diverticular"],
  "crohn disease": ["crohn", "ibd", "inflammatory bowel"],
  "ulcerative colitis": ["ulcerative colitis", "uc", "ibd"],
  "celiac disease": ["celiac", "gluten"],
  "gastric ulcer": ["gastric ulcer", "peptic ulcer", "h pylori"],
  gastritis: ["gastritis", "h pylori"],
  "esophageal varices": ["esophageal varices", "variceal bleed", "portal hypertension"],
  "barrett esophagus": ["barrett", "gerd", "dysplasia"],
  "achalasia": ["achalasia", "esophageal motility"],
  "hiatal hernia": ["hiatal hernia", "gerd"],
  "intestinal obstruction": ["bowel obstruction", "ileus", "obstruction"],
  "mesenteric ischemia": ["mesenteric ischemia", "acute abdomen"],
  "splenic rupture": ["splenic rupture", "splenomegaly trauma"],
  "splenic sequestration": ["splenic sequestration", "sickle cell"],
  "renal cell carcinoma": ["renal cell carcinoma", "kidney cancer"],
  "nephrotic syndrome": ["nephrotic syndrome", "proteinuria"],
  "nephritic syndrome": ["nephritic syndrome", "glomerulonephritis"],
  "polycystic kidney disease": ["polycystic kidney", "pkd"],
  "renal artery stenosis": ["renal artery stenosis", "renovascular"],
  "bladder cancer": ["bladder cancer", "hematuria"],
  "neurogenic bladder": ["neurogenic bladder", "urinary retention"],
  "stress incontinence": ["stress incontinence", "urinary incontinence"],
  "testicular torsion": ["testicular torsion"],
  "ovarian cyst": ["ovarian cyst"],
  "ectopic pregnancy": ["ectopic pregnancy"],
  "spinal cord injury": ["spinal cord injury", "sci", "paraplegia"],
  "multiple sclerosis": ["multiple sclerosis", "ms", "demyelination"],
  "guillain-barre": ["guillain-barre", "gbs", "ascending paralysis"],
  "myasthenia gravis": ["myasthenia gravis", "mg"],
  "parkinson disease": ["parkinson", "parkinsonism"],
  "alzheimer disease": ["alzheimer", "dementia"],
  "epilepsy": ["epilepsy", "seizure"],
  "subarachnoid hemorrhage": ["subarachnoid hemorrhage", "sah", "aneurysm rupture"],
  "subdural hematoma": ["subdural hematoma", "sdh"],
  "brain tumor": ["brain tumor", "glioma", "meningioma"],
  "tracheal stenosis": ["tracheal stenosis", "airway obstruction"],
  "laryngeal cancer": ["laryngeal cancer", "hoarseness"],
  "pleural effusion": ["pleural effusion", "empyema"],
  "lung cancer": ["lung cancer", "nsclc", "sclc"],
  "pulmonary hypertension": ["pulmonary hypertension", "pah"],
  "aortic stenosis": ["aortic stenosis", "valvular"],
  "mitral regurgitation": ["mitral regurgitation", "mr"],
  "atrial fibrillation": ["atrial fibrillation", "afib", "af"],
  "ventricular tachycardia": ["ventricular tachycardia", "vtach", "arrhythmia"],
  "cardiomyopathy": ["cardiomyopathy", "dilated cardiomyopathy"],
  "myocarditis": ["myocarditis"],
  "pericarditis": ["pericarditis"],
  "pheochromocytoma": ["pheochromocytoma", "catecholamine"],
  "hyperaldosteronism": ["hyperaldosteronism", "conn syndrome"],
  "osteoporosis": ["osteoporosis", "bone density"],
  "osteoarthritis": ["osteoarthritis", "degenerative joint"],
  "rheumatoid arthritis": ["rheumatoid arthritis", "ra"],
  "gout": ["gout", "hyperuricemia"],
  "septic arthritis": ["septic arthritis", "joint infection"],
  "rotator cuff tear": ["rotator cuff", "shoulder pain"],
  "tendonitis": ["tendonitis", "tendinopathy"],
  "compartment syndrome": ["compartment syndrome"],
  "deep vein thrombosis": ["deep vein thrombosis", "dvt"],
  "cellulitis": ["cellulitis", "skin infection"],
  "osteomyelitis": ["osteomyelitis", "bone infection"],
};

export function slugifyPathology(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function searchTermsForPathology(pathology: string): string[] {
  const key = pathology.toLowerCase();
  const mapped = PATHOLOGY_SEARCH_TERMS[key];
  if (mapped) return mapped;
  return [key, ...pathology.toLowerCase().split(/\s+/).filter((t) => t.length > 3)];
}
