import type { ExamReference } from "@/lib/exam-prep/types";
import type { DrugEntry } from "@/lib/drugs300/types";

export type ClinicalEndpoint = {
  label: string;
  target?: string;
  frequency?: string;
};

/** Evidence provenance for disease → drug threads shown in Anatomy Explorer. */
export type AnatomyEvidenceLevel =
  | "guideline"
  | "labeling"
  | "board-standard"
  | "auto-matched";

/** Disease state anchored to anatomy structures with therapies and measurable endpoints. */
export type AnatomyDiseaseLink = {
  id: string;
  name: string;
  structureIds: string[];
  /** Optional match to structure.pathologies display strings */
  pathologyLabel?: string;
  pathophysiology: string;
  presentation: string[];
  /** Top 500 drug catalog ids — first-line therapies */
  firstLineDrugIds: string[];
  adjunctDrugIds?: string[];
  counselingPearl?: string;
  /** Labs, vitals, imaging targets for boards */
  diagnosticEndpoints?: ClinicalEndpoint[];
  monitoringEndpoints?: ClinicalEndpoint[];
  treatmentGoals?: string[];
  examPearl?: string;
  highYield: boolean;
  /** True when generated by indication matcher (lighter review) */
  generated?: boolean;
  /** Society / FDA authorities backing the thread */
  guidelines?: ExamReference[];
  evidenceLevel?: AnatomyEvidenceLevel;
  /** ISO date when a clinician/author last verified the therapy list */
  verifiedAt?: string;
};

export type ResolvedAnatomyDiseaseLink = AnatomyDiseaseLink & {
  firstLineDrugs: DrugEntry[];
  adjunctDrugs: DrugEntry[];
};

export type DrugClinicalContext = {
  drugId: string;
  diseases: ResolvedAnatomyDiseaseLink[];
  structureIds: string[];
  structureNames: string[];
};
