import type { ExamReference } from "@/lib/exam-prep/types";
import type { DrugEntry } from "@/lib/drugs300/types";

export type ClinicalEndpoint = {
  label: string;
  target?: string;
  frequency?: string;
};

/** Evidence provenance for disease → drug threads shown in Anatomy Explorer. */
export type AnatomyEvidenceLevel =
  | "guideline"
  | "labeling"
  | "board-standard"
  | "auto-matched";

/** Disease-specific reason a Top 500 drug is used, with optional MOA override. */
export type AnatomyDrugRationale = {
  /** Why this drug is chosen for this disease (not generic class copy). */
  whyUsed: string;
  /** Short MOA when disease context differs from the shared drug overlay. */
  briefMoa?: string;
};

/** Disease state anchored to anatomy structures with therapies and measurable endpoints. */
export type AnatomyDiseaseLink = {
  id: string;
  name: string;
  structureIds: string[];
  /** Optional match to structure.pathologies display strings */
  pathologyLabel?: string;
  pathophysiology: string;
  presentation: string[];
  /** How you make the diagnosis — keys + confirmatory finding (one line). */
  bestDiagnosis?: string;
  /** Why this treatment strategy for this disease. */
  treatmentRationale?: string;
  /** Per Top 500 drugId: why used here + optional brief MOA. */
  drugRationales?: Record<string, AnatomyDrugRationale>;
  /** Top 500 drug catalog ids — first-line therapies */
  firstLineDrugIds: string[];
  adjunctDrugIds?: string[];
  counselingPearl?: string;
  /** Labs, vitals, imaging targets for boards */
  diagnosticEndpoints?: ClinicalEndpoint[];
  monitoringEndpoints?: ClinicalEndpoint[];
  treatmentGoals?: string[];
  examPearl?: string;
  highYield: boolean;
  /** True when generated by indication matcher (lighter review) */
  generated?: boolean;
  /** Society / FDA authorities backing the thread */
  guidelines?: ExamReference[];
  evidenceLevel?: AnatomyEvidenceLevel;
  /** ISO date when a clinician/author last verified the therapy list */
  verifiedAt?: string;
};

export type ResolvedAnatomyDiseaseLink = AnatomyDiseaseLink & {
  firstLineDrugs: DrugEntry[];
  adjunctDrugs: DrugEntry[];
};

export type DrugClinicalContext = {
  drugId: string;
  diseases: ResolvedAnatomyDiseaseLink[];
  structureIds: string[];
  structureNames: string[];
};
