import type { SubjectArea } from "../types";

export const MEDICINE_SUBJECTS: SubjectArea[] = [
{
      id: "anatomy",
      label: "Anatomy",
      contentArea: "Gross anatomy & embryology",
      textbookRefs: "OpenStax Anatomy & Physiology, LibreTexts Anatomy",
      examHints: "structures, relations, innervation, histology, regional anatomy",
      keywords: ["anatomy", "tissue", "nerve", "artery", "muscle", "organ", "embryology"],
      focusPlaceholder: "e.g. Upper limb, cranial nerves",
    },
    {
      id: "physiology",
      label: "Physiology",
      contentArea: "Physiology",
      textbookRefs: "OpenStax A&P, Guyton-style OER physiology",
      examHints: "cardiovascular, renal, respiratory, endocrine, neurophysiology, homeostasis",
      keywords: ["physiology", "cardiac", "renal", "respiratory", "hormone", "membrane"],
      focusPlaceholder: "e.g. Cardiac cycle, acid-base",
    },
    {
      id: "pathology",
      label: "Pathology",
      contentArea: "Pathology",
      textbookRefs: "LibreTexts Pathology, OpenStax",
      examHints: "inflammation, neoplasia, hemodynamics, tissue injury, disease mechanisms",
      keywords: ["pathology", "neoplasia", "inflammation", "necrosis", "infarct"],
      focusPlaceholder: "e.g. Neoplasia, hemodynamic disorders",
    },
    {
      id: "pharmacology",
      label: "Pharmacology",
      contentArea: "Pharmacology",
      textbookRefs: "OpenStax Pharmacology, NIH DailyMed references",
      examHints: "MOA, adverse effects, interactions, contraindications, autonomic drugs",
      keywords: ["pharmacology", "drug", "receptor", "agonist", "antagonist", "toxicity"],
      focusPlaceholder: "e.g. Antihypertensives, antibiotics",
    },
    {
      id: "biochemistry",
      label: "Biochemistry",
      contentArea: "Biochemistry & nutrition",
      textbookRefs: "LibreTexts Medical Biochemistry",
      examHints: "metabolic pathways, enzymes, genetics, nutrition, inborn errors",
      keywords: ["biochemistry", "glycolysis", "urea", "amino acid", "enzyme", "GSD"],
      focusPlaceholder: "e.g. Glycolysis, lipid metabolism",
    },
    {
      id: "microbiology",
      label: "Microbiology & Immunology",
      contentArea: "Microbiology / immunology",
      textbookRefs: "OpenStax Microbiology, LibreTexts Immunology",
      examHints: "bacteria, viruses, fungi, parasites, hypersensitivity, vaccines",
      keywords: ["microbiology", "bacteria", "virus", "immune", "gram", "antibody"],
      focusPlaceholder: "e.g. Gram-positive cocci, HIV",
    },
    {
      id: "cardiology",
      label: "Cardiology",
      contentArea: "Cardiovascular system",
      textbookRefs: "OpenStax, ACC/AHA guideline summaries (OER texts)",
      examHints: "ECG, heart failure, ACS, arrhythmias, valvular disease, hypertension",
      keywords: ["cardiology", "ECG", "MI", "heart failure", "arrhythmia", "murmur"],
      focusPlaceholder: "e.g. Acute coronary syndrome",
    },
    {
      id: "pulmonology",
      label: "Pulmonology",
      contentArea: "Respiratory system",
      textbookRefs: "OpenStax A&P, pulmonary OER modules",
      examHints: "asthma, COPD, pneumonia, V/Q mismatch, PFTs, ABG interpretation",
      keywords: ["pulmonary", "asthma", "COPD", "pneumonia", "ABG", "ventilation"],
      focusPlaceholder: "e.g. COPD exacerbation",
    },
    {
      id: "nephrology",
      label: "Nephrology",
      contentArea: "Renal / urinary",
      textbookRefs: "OpenStax renal physiology chapters",
      examHints: "AKI, CKD, electrolytes, acid-base, glomerular disease, diuretics",
      keywords: ["renal", "kidney", "AKI", "CKD", "electrolyte", "glomerular"],
      focusPlaceholder: "e.g. Metabolic acidosis",
    },
    {
      id: "neurology",
      label: "Neurology",
      contentArea: "Nervous system & special senses",
      textbookRefs: "OpenStax, neuroanatomy OER",
      examHints: "stroke, seizures, headache, neuropathy, localization, CSF",
      keywords: ["neurology", "stroke", "seizure", "cranial nerve", "MS", "meningitis"],
      focusPlaceholder: "e.g. Ischemic stroke",
    },
    {
      id: "internal-medicine",
      label: "Internal Medicine",
      contentArea: "Multisystem / internal medicine",
      textbookRefs: "OpenStax, CDC guidelines",
      examHints: "diabetes, thyroid, GI, hepatology, rheumatology, preventive care",
      keywords: ["internal medicine", "diabetes", "thyroid", "cirrhosis", "IBD"],
      focusPlaceholder: "e.g. Type 2 diabetes management",
    },
    {
      id: "pediatrics",
      label: "Pediatrics",
      contentArea: "Pediatrics",
      textbookRefs: "OpenStax, AAP open resources",
      examHints: "growth, vaccines, neonatal jaundice, congenital disease, child abuse screening",
      keywords: ["pediatrics", "neonatal", "vaccine", "child", "congenital"],
      focusPlaceholder: "e.g. Neonatal jaundice",
    },
    {
      id: "obgyn",
      label: "OB/GYN",
      contentArea: "Reproductive system",
      textbookRefs: "OpenStax, reproductive health OER",
      examHints: "pregnancy, labor, contraception, STIs, cervical cancer screening",
      keywords: ["obstetrics", "gynecology", "pregnancy", "labor", "preeclampsia"],
      focusPlaceholder: "e.g. Preeclampsia",
    },
    {
      id: "psychiatry",
      label: "Psychiatry",
      contentArea: "Behavioral health",
      textbookRefs: "OpenStax Psychology, psychiatry OER",
      examHints: "mood disorders, psychosis, substance use, psychotropics, suicide risk",
      keywords: ["psychiatry", "depression", "schizophrenia", "bipolar", "SSRI"],
      focusPlaceholder: "e.g. Major depressive disorder",
    },
    {
      id: "emergency-medicine",
      label: "Emergency Medicine",
      contentArea: "Acute care",
      textbookRefs: "ATLS principles (OER summaries), toxicology references",
      examHints: "trauma ABCDE, shock, toxicology, ACLS, anaphylaxis",
      keywords: ["emergency", "trauma", "shock", "toxicology", "ACLS", "anaphylaxis"],
      focusPlaceholder: "e.g. Anaphylaxis management",
    },
];
