import type { SubjectArea } from "../types";

export const DENTISTRY_SUBJECTS: SubjectArea[] = [
  {
    id: "oral-pathology",
    label: "Oral Pathology",
    contentArea: "Oral pathology & medicine",
    textbookRefs: "Oral Pathology OER, ADA references",
    examHints: "lesions, neoplasia, infections, systemic oral manifestations",
    keywords: ["oral pathology", "lesion", "biopsy", "dysplasia", "carcinoma"],
    focusPlaceholder: "e.g. White lesions, odontogenic tumors",
    difficultyLevel: 3,
  },
  {
    id: "dental-anatomy",
    label: "Dental Anatomy",
    contentArea: "Head & neck anatomy",
    textbookRefs: "Dental anatomy atlases, OpenStax A&P",
    examHints: "tooth morphology, occlusion, TMJ, innervation, vasculature",
    keywords: ["dental anatomy", "tooth", "occlusion", "TMJ", "pulp"],
    focusPlaceholder: "e.g. Permanent dentition, nerve blocks",
    difficultyLevel: 2,
  },
  {
    id: "treatment-planning",
    label: "Treatment Planning",
    contentArea: "Comprehensive care planning",
    textbookRefs: "Clinical dentistry texts",
    examHints: "diagnosis, sequencing, risk assessment, prosthodontic planning",
    keywords: ["treatment plan", "diagnosis", "prognosis", "sequence"],
    focusPlaceholder: "e.g. Full-mouth rehabilitation",
    difficultyLevel: 4,
  },
  {
    id: "dental-pharmacology",
    label: "Dental Pharmacology",
    contentArea: "Pharmacology in dentistry",
    textbookRefs: "Dental pharmacology, FDA labels",
    examHints: "analgesics, antibiotics, local anesthetics, sedation, interactions",
    keywords: ["dental pharmacology", "lidocaine", "antibiotic", "analgesic"],
    focusPlaceholder: "e.g. Local anesthetics, antibiotic prophylaxis",
    difficultyLevel: 3,
  },
  {
    id: "radiology",
    label: "Dental Radiology",
    contentArea: "Imaging & radiation safety",
    textbookRefs: "Oral radiology references",
    examHints: "bitewing, periapical, CBCT interpretation, radiation safety",
    keywords: ["radiograph", "CBCT", "radiolucency", "radiopacity"],
    focusPlaceholder: "e.g. Caries detection, pathology on imaging",
    difficultyLevel: 3,
  },
  {
    id: "restorative-dentistry",
    label: "Restorative Dentistry",
    contentArea: "Operative & restorative",
    textbookRefs: "Operative dentistry OER",
    examHints: "caries management, materials, bonding, amalgam/composite, isolation",
    keywords: ["restorative", "composite", "caries", "cavity preparation"],
    focusPlaceholder: "e.g. Class II composites, material selection",
    difficultyLevel: 3,
  },
  {
    id: "periodontics",
    label: "Periodontics",
    contentArea: "Periodontal disease",
    textbookRefs: "Periodontology references",
    examHints: "gingivitis, periodontitis, classification, therapy, maintenance",
    keywords: ["periodontal", "pocket", "attachment loss", "scaling"],
    focusPlaceholder: "e.g. Stage III periodontitis",
    difficultyLevel: 3,
  },
  {
    id: "endodontics",
    label: "Endodontics",
    contentArea: "Pulp & periapical disease",
    textbookRefs: "Endodontics texts",
    examHints: "diagnosis, instrumentation, obturation, retreatment, pain",
    keywords: ["endodontic", "root canal", "pulpitis", "apical"],
    focusPlaceholder: "e.g. Irreversible pulpitis",
    difficultyLevel: 4,
  },
];
