import type { SubjectArea } from "../types";

export const BIOLOGY_SUBJECTS: SubjectArea[] = [
  {
    id: "genetics",
    label: "Genetics",
    contentArea: "Molecular & Mendelian genetics",
    textbookRefs: "OpenStax Biology, LibreTexts Genetics",
    examHints: "inheritance, pedigrees, molecular genetics, gene expression",
    keywords: ["genetics", "allele", "pedigree", "transcription", "mutation"],
    focusPlaceholder: "e.g. Autosomal recessive, CRISPR basics",
    difficultyLevel: 3,
  },
  {
    id: "physiology",
    label: "Physiology",
    contentArea: "Organ systems physiology",
    textbookRefs: "OpenStax A&P",
    examHints: "homeostasis, organ function, integration, feedback loops",
    keywords: ["physiology", "homeostasis", "organ", "hormone"],
    focusPlaceholder: "e.g. Cardiovascular physiology",
    difficultyLevel: 3,
  },
  {
    id: "molecular-biology",
    label: "Molecular Biology",
    contentArea: "Cell & molecular biology",
    textbookRefs: "LibreTexts Molecular Biology",
    examHints: "DNA replication, transcription, translation, enzymes, signaling",
    keywords: ["molecular", "DNA", "RNA", "protein", "enzyme"],
    focusPlaceholder: "e.g. Central dogma, PCR",
    difficultyLevel: 4,
  },
  {
    id: "cell-biology",
    label: "Cell Biology",
    contentArea: "Cell structure & function",
    textbookRefs: "OpenStax Biology",
    examHints: "organelles, membrane transport, cell cycle, apoptosis",
    keywords: ["cell", "mitochondria", "membrane", "mitosis"],
    focusPlaceholder: "e.g. Cell cycle regulation",
    difficultyLevel: 2,
  },
  {
    id: "ecology",
    label: "Ecology",
    contentArea: "Ecology & evolution",
    textbookRefs: "OpenStax Biology",
    examHints: "populations, communities, ecosystems, evolution, biodiversity",
    keywords: ["ecology", "ecosystem", "evolution", "natural selection"],
    focusPlaceholder: "e.g. Population dynamics",
    difficultyLevel: 2,
  },
];
