/**
 * NCLEX full-exam item quality assessment — wraps board QA gates.
 *
 * Classic vignette/MCQ generation still uses the best-tier bar.
 * Authentic NGN formats (bowtie, matrix, case, SATA, ordered, highlight) use a
 * serve/exam-fill bar — best_gate + MCQ distractor JSON wipe those formats.
 */
import type { BankItem } from "@/lib/question-bank";
import {
  assessNclexItemQuality,
  hasNclexDistractorRationales,
  isNclexExamFillQuality,
} from "../nclex-quality-gate";
import { auditNclexBankItem, nclexHasServeBlockIssues } from "../nclex-bank-audit";
import { nclexNgnCorrectAnswerValid } from "../nclex-ngn-audit";
import { repairGeneratedNclexNgnItem } from "../repair-generated-nclex-ngn";
import { assessNclexCuratedSeedItem } from "../nclex-curated-seeds-quality";
import { nclexBankItemIsBestReady } from "../nclex-serve-gate";
import type { EnrichedBankItem } from "../seed-helpers";

function hasStructuredDistractorBlock(item: BankItem): boolean {
  return hasNclexDistractorRationales(item);
}

/** Item types generated by NGN gap-fill — must not require classic MCQ distractor blocks. */
export const NCLEX_NGN_GENERATION_TYPES = new Set([
  "select_all",
  "sata",
  "ngn_bowtie",
  "bow_tie",
  "ngn_matrix",
  "matrix",
  "ordered_response",
  "ngn_highlight",
  "highlight",
  "case_study",
  "unfolding_case",
]);

export function isNclexNgnGenerationType(itemType?: string | null): boolean {
  return NCLEX_NGN_GENERATION_TYPES.has((itemType ?? "").trim());
}

export type NclexFullExamQcReport = {
  ok: boolean;
  tier: "best" | "serve" | "acceptable" | "reject";
  score: number;
  issues: string[];
};

/** Soft serve bar for authentic NGN generation / ingest (mirrors qa-gate-nclex-ngn-serve). */
export function assessNclexNgnGenerationItem(
  item: BankItem,
  index: number
): NclexFullExamQcReport {
  // Re-apply payload repair in case upstream normalize stripped structured fields.
  item = repairGeneratedNclexNgnItem(item);
  const issues: string[] = [];
  const verdict = assessNclexItemQuality(item, { source: "ai-curated" });

  if (verdict.tier === "reject") {
    issues.push(...verdict.issues);
  }
  if (nclexHasServeBlockIssues(item)) {
    issues.push("serve_block");
  }

  const hardAudit = auditNclexBankItem(item).issues.filter((i) => i.severity === "error");
  for (const issue of hardAudit) {
    if (!issues.includes(issue.code)) issues.push(issue.code);
  }

  const explanation = item.explanation?.trim() ?? "";
  if (explanation.length < 72) issues.push("explanation_too_short");

  const vignette = item.vignette?.trim() ?? "";
  if (vignette.length < 30) issues.push("missing_vignette");

  if (!item.correctAnswer?.trim()) issues.push("missing_answer");
  if ((item.options?.length ?? 0) < 2) issues.push("missing_options");

  const enriched = item as EnrichedBankItem;
  for (const si of assessNclexCuratedSeedItem(enriched, index)) {
    // Soft craft nits should not wipe format-authentic NGN during gap fill.
    if (
      si.code === "missing_distractor_rationales" ||
      si.code === "explanation_too_short" ||
      si.code === "weak_distractor_rationales" ||
      si.code === "stem_lead_in"
    ) {
      continue;
    }
    if (!issues.includes(si.code)) issues.push(si.code);
  }

  // After payload repair, structured NGN answers are valid even when MCQ
  // correct_not_in_options still flags composite strings.
  let uniqueIssues = [...new Set(issues)];
  if (nclexNgnCorrectAnswerValid(item)) {
    uniqueIssues = uniqueIssues.filter(
      (code) => code !== "ngn_answer_invalid" && code !== "correct_not_in_options"
    );
  }

  const fillOk = isNclexExamFillQuality(item, { source: "ai-curated" });
  const softOk =
    uniqueIssues.length === 0 &&
    explanation.length >= 80 &&
    vignette.length >= 40 &&
    Boolean(item.correctAnswer?.trim()) &&
    (item.options?.length ?? 0) >= 2;
  const ok = uniqueIssues.length === 0 && (fillOk || softOk);

  return {
    ok,
    tier: ok ? "serve" : verdict.tier === "reject" ? "reject" : "acceptable",
    score: verdict.score,
    issues: uniqueIssues,
  };
}

export function assessNclexFullExamItem(
  item: BankItem,
  index: number
): NclexFullExamQcReport {
  if (
    isNclexNgnGenerationType(item.itemType) ||
    Boolean(
      item.ngnPayload &&
        typeof item.ngnPayload === "object" &&
        ("caseGroupId" in item.ngnPayload || "kind" in item.ngnPayload)
    )
  ) {
    return assessNclexNgnGenerationItem(item, index);
  }

  const issues: string[] = [];

  const verdict = assessNclexItemQuality(item, { source: "ai-curated" });
  if (verdict.tier === "reject") {
    issues.push(...verdict.issues);
  }

  if (!nclexBankItemIsBestReady(item)) {
    issues.push("best_gate_fail");
  }

  const explanation = item.explanation?.trim() ?? "";
  if (explanation.length < 120) issues.push("explanation_too_short");
  if (!/Why other options are incorrect/i.test(explanation) && !hasStructuredDistractorBlock(item)) {
    issues.push("missing_distractor_rationales");
  }

  const vignette = item.vignette?.trim() ?? "";
  if (vignette.length < 40) issues.push("missing_vignette");

  const enriched = item as EnrichedBankItem;
  const seedIssues = assessNclexCuratedSeedItem(enriched, index);
  for (const si of seedIssues) {
    if (!issues.includes(si.code)) issues.push(si.code);
  }

  const uniqueIssues = [...new Set(issues)];
  const bestOk = nclexBankItemIsBestReady(item);
  const ok = uniqueIssues.length === 0 && bestOk;

  return {
    ok,
    tier: ok ? (verdict.tier === "best" ? "best" : "serve") : verdict.tier,
    score: verdict.score,
    issues: uniqueIssues,
  };
}

export function nclexFullExamItemPasses(item: BankItem, index: number): boolean {
  return assessNclexFullExamItem(item, index).ok;
}
