import type { SubjectArea } from "../types";

export const CHEMISTRY_SUBJECTS: SubjectArea[] = [
  {
    id: "organic-chemistry",
    label: "Organic Chemistry",
    contentArea: "Organic mechanisms & synthesis",
    textbookRefs: "LibreTexts Organic Chemistry",
    examHints: "mechanisms, stereochemistry, functional groups, synthesis",
    keywords: ["organic", "mechanism", "stereochemistry", "SN1", "carbonyl"],
    focusPlaceholder: "e.g. Substitution reactions",
    difficultyLevel: 4,
  },
  {
    id: "biochemistry",
    label: "Biochemistry",
    contentArea: "Biochemical pathways",
    textbookRefs: "LibreTexts Biochemistry",
    examHints: "metabolism, enzymes, amino acids, lipids, regulation",
    keywords: ["biochemistry", "glycolysis", "enzyme", "amino acid"],
    focusPlaceholder: "e.g. Enzyme kinetics",
    difficultyLevel: 4,
  },
  {
    id: "general-chemistry",
    label: "General Chemistry",
    contentArea: "General chemistry",
    textbookRefs: "OpenStax Chemistry",
    examHints: "stoichiometry, thermochemistry, equilibrium, acids/bases, electrochemistry",
    keywords: ["stoichiometry", "equilibrium", "acid", "molarity"],
    focusPlaceholder: "e.g. Acid-base equilibria",
    difficultyLevel: 2,
  },
  {
    id: "physical-chemistry",
    label: "Physical Chemistry",
    contentArea: "Physical chemistry",
    textbookRefs: "LibreTexts Physical Chemistry",
    examHints: "thermodynamics, kinetics, quantum basics, spectroscopy",
    keywords: ["thermodynamics", "kinetics", "enthalpy", "entropy"],
    focusPlaceholder: "e.g. Reaction kinetics",
    difficultyLevel: 5,
  },
  {
    id: "analytical-chemistry",
    label: "Analytical Chemistry",
    contentArea: "Analytical methods",
    textbookRefs: "LibreTexts Analytical Chemistry",
    examHints: "titrations, chromatography, spectroscopy, error analysis",
    keywords: ["titration", "chromatography", "spectroscopy", "analytical"],
    focusPlaceholder: "e.g. Titration curves",
    difficultyLevel: 3,
  },
];
