import type { SubjectArea } from "../types";

export const PHARMACY_SUBJECTS: SubjectArea[] = [
{
      id: "pharmacokinetics",
      label: "Pharmacokinetics & Pharmacodynamics",
      contentArea: "NAPLEX — Foundational sciences",
      textbookRefs: "LibreTexts Pharmacology, NAPLEX competency statements",
      examHints: "ADME, half-life, bioavailability, first-pass, protein binding, receptors",
      keywords: ["pharmacokinetics", "ADME", "half-life", "bioavailability", "clearance"],
      focusPlaceholder: "e.g. Half-life and dosing intervals",
    },
    {
      id: "pharmacology",
      label: "General Pharmacology",
      contentArea: "NAPLEX — Drug mechanisms",
      textbookRefs: "OpenStax Pharmacology",
      examHints: "MOA, drug classes, receptor subtypes, adverse effects, interactions",
      keywords: ["pharmacology", "MOA", "receptor", "agonist", "antagonist"],
      focusPlaceholder: "e.g. Beta-adrenergic blockers",
    },
    {
      id: "pharmaceutics",
      label: "Pharmaceutics",
      contentArea: "NAPLEX — Dosage forms",
      textbookRefs: "LibreTexts Pharmaceutics",
      examHints: "tablets, capsules, suspensions, transdermal, stability, excipients",
      keywords: ["pharmaceutics", "dosage form", "tablet", "bioavailability", "excipient"],
      focusPlaceholder: "e.g. Extended-release formulations",
    },
    {
      id: "compounding-calculations",
      label: "Pharmacy Calculations",
      contentArea: "NAPLEX — Calculations",
      textbookRefs: "NAPLEX calculation competencies, alligation/alligation alternate",
      examHints: "dosing, concentrations, IV flow, isotonicity, pediatric weight-based dosing",
      keywords: ["calculation", "dose", "concentration", "alligation", "IV", "mg/kg"],
      focusPlaceholder: "e.g. IV infusion rate",
    },
    {
      id: "cardiovascular-rx",
      label: "Cardiovascular Pharmacotherapy",
      contentArea: "NAPLEX — Cardiovascular",
      textbookRefs: "OpenStax, ACC guideline summaries",
      examHints: "antihypertensives, heart failure, anticoagulants, statins, ACS therapy",
      keywords: ["cardiovascular", "hypertension", "statin", "warfarin", "ACE inhibitor"],
      focusPlaceholder: "e.g. Heart failure GDMT",
    },
    {
      id: "infectious-disease-rx",
      label: "Infectious Disease Therapy",
      contentArea: "NAPLEX — Anti-infectives",
      textbookRefs: "Sanford Guide open summaries, CDC antibiotic guidance",
      examHints: "antibiotic spectra, resistance, prophylaxis, HIV ART, vaccines",
      keywords: ["antibiotic", "antimicrobial", "resistance", "MRSA", "HIV"],
      focusPlaceholder: "e.g. Community-acquired pneumonia",
    },
    {
      id: "endocrine-rx",
      label: "Endocrine Pharmacotherapy",
      contentArea: "NAPLEX — Endocrine",
      textbookRefs: "OpenStax diabetes chapters, ADA open summaries",
      examHints: "insulin, oral hypoglycemics, thyroid, corticosteroids, osteoporosis",
      keywords: ["diabetes", "insulin", "metformin", "thyroid", "corticosteroid"],
      focusPlaceholder: "e.g. Insulin types",
    },
    {
      id: "cns-rx",
      label: "CNS & Psychiatric Medications",
      contentArea: "NAPLEX — CNS",
      textbookRefs: "OpenStax psychopharmacology modules",
      examHints: "antidepressants, antipsychotics, antiepileptics, opioids, benzodiazepines",
      keywords: ["CNS", "SSRI", "antipsychotic", "seizure", "opioid", "benzodiazepine"],
      focusPlaceholder: "e.g. SSRI selection",
    },
    {
      id: "oncology-rx",
      label: "Oncology Pharmacotherapy",
      contentArea: "NAPLEX — Oncology",
      textbookRefs: "NCI open references, chemotherapy basics OER",
      examHints: "chemotherapy classes, emesis prophylaxis, neutropenia, supportive care",
      keywords: ["oncology", "chemotherapy", "neutropenia", "antiemetic", "cancer"],
      focusPlaceholder: "e.g. Chemotherapy-induced nausea",
    },
    {
      id: "otc-self-care",
      label: "OTC & Self-Care",
      contentArea: "NAPLEX — Nonprescription",
      textbookRefs: "OTC labeling standards, FDA open resources",
      examHints: "analgesics, cough/cold, allergies, GI OTC, pregnancy/lactation counseling",
      keywords: ["OTC", "self-care", "acetaminophen", "ibuprofen", "antihistamine"],
      focusPlaceholder: "e.g. Cold symptom management",
    },
    {
      id: "patient-counseling",
      label: "Patient Counseling",
      contentArea: "NAPLEX — Communication",
      textbookRefs: "ASHP counseling guidelines (open summaries)",
      examHints: "medication adherence, literacy, REMS, inhaler technique, monitoring",
      keywords: ["counseling", "adherence", "patient", "education", "monitoring"],
      focusPlaceholder: "e.g. Inhaler technique teaching",
    },
    {
      id: "pharmacy-law",
      label: "Pharmacy Law & Ethics",
      contentArea: "NAPLEX — Professional practice",
      textbookRefs: "State practice act summaries, DEA scheduling basics",
      examHints: "controlled substances, dispensing, confidentiality, errors, MTM",
      keywords: ["law", "ethics", "controlled substance", "DEA", "dispensing", "HIPAA"],
      focusPlaceholder: "e.g. Controlled substance schedules",
    },
];
