import type { ReadinessPageData } from "@/lib/learning/readiness-check/service";

export const READINESS_PREVIEW_BOARD: ReadinessPageData = {
  examSlug: "nclex",
  fieldId: "nursing",
  length: 24,
  hasStudyAccess: true,
  mode: "result",
  examDate: "2026-09-20",
  outcome: null,
  resume: null,
  result: {
    checkId: "preview",
    overallLevel: "getting_close",
    overallLabel: "Getting close",
    summaryLine: "Getting close. A place to practice next: Pharmacological Therapies and Safety & Infection Control.",
    completedAt: "2026-09-20T12:00:00.000Z",
    kind: "retake",
    retakeDue: true,
    daysUntilSuggest: 0,
  },
  examName: "NCLEX",
  todayHref: "/question-bank?field=nursing&mode=bank&style=today&count=20",
  areas: [
    { areaId: "management-of-care", label: "Management of Care", answered: 3, correct: 3, level: "on_track", labelText: "On track", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=management-of-care&count=15" },
    { areaId: "safety-infection", label: "Safety & Infection Control", answered: 3, correct: 1, level: "not_yet", labelText: "Not yet", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=safety-infection&count=15" },
    { areaId: "health-promotion", label: "Health Promotion", answered: 3, correct: 2, level: "getting_close", labelText: "Getting close", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=health-promotion&count=15" },
    { areaId: "psychosocial", label: "Psychosocial Integrity", answered: 3, correct: 3, level: "on_track", labelText: "On track", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=psychosocial&count=15" },
    { areaId: "basic-care", label: "Basic Care & Comfort", answered: 3, correct: 3, level: "on_track", labelText: "On track", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=basic-care&count=15" },
    { areaId: "pharmacology", label: "Pharmacological Therapies", answered: 3, correct: 1, level: "not_yet", labelText: "Not yet", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=pharmacology&count=15" },
    { areaId: "risk-reduction", label: "Reduction of Risk Potential", answered: 3, correct: 3, level: "on_track", labelText: "On track", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=risk-reduction&count=15" },
    { areaId: "physiological-adaptation", label: "Physiological Adaptation", answered: 1, correct: 1, level: "insufficient", thinBank: true, labelText: "Not enough clean questions in this area yet", practiceHref: "/question-bank?field=nursing&mode=bank&blueprintArea=physiological-adaptation&count=15" },
  ],
  progress: [
    { areaId: "management-of-care", label: "Management of Care", baseline: "getting_close", latest: "on_track", movement: "up", detail: "Was Getting close · Now On track" },
    { areaId: "safety-infection", label: "Safety & Infection Control", baseline: "not_yet", latest: "not_yet", movement: "same", detail: "Still Not yet" },
    { areaId: "health-promotion", label: "Health Promotion", baseline: "not_yet", latest: "getting_close", movement: "up", detail: "Was Not yet · Now Getting close" },
    { areaId: "psychosocial", label: "Psychosocial Integrity", baseline: "on_track", latest: "on_track", movement: "same", detail: "Still On track" },
    { areaId: "basic-care", label: "Basic Care & Comfort", baseline: "insufficient", latest: "on_track", movement: "new", detail: "Now On track" },
    { areaId: "pharmacology", label: "Pharmacological Therapies", baseline: "not_yet", latest: "not_yet", movement: "same", detail: "Still Not yet" },
    { areaId: "risk-reduction", label: "Reduction of Risk Potential", baseline: "getting_close", latest: "on_track", movement: "up", detail: "Was Getting close · Now On track" },
    { areaId: "physiological-adaptation", label: "Physiological Adaptation", baseline: "insufficient", latest: "insufficient", movement: "same", detail: "Not enough data yet" },
  ],
  focus: [],
  history: [
    {
      id: "latest",
      kind: "retake",
      isBaseline: false,
      completedAt: "2026-09-20T12:00:00.000Z",
      overallLabel: "Getting close",
      summaryLine: "Getting close. A place to practice next: Pharmacological Therapies and Safety & Infection Control.",
      correctCount: 17,
      answeredCount: 22,
    },
    {
      id: "base",
      kind: "baseline",
      isBaseline: true,
      completedAt: "2026-09-02T12:00:00.000Z",
      overallLabel: "Not yet",
      summaryLine: "Not yet. A place to practice next: Pharmacological Therapies and Safety & Infection Control.",
      correctCount: 10,
      answeredCount: 24,
    },
  ],
  baselineSummary: "Not yet. A place to practice next: Pharmacological Therapies and Safety & Infection Control.",
  baselineCompletedAt: "2026-09-02T12:00:00.000Z",
  showRestart: false,
};

