import { buildUsmleReviewModule } from "./usmle-module-builder";

export const PHARMACEUTICAL_ADS_ABSTRACTS_STEP3_MODULE = buildUsmleReviewModule({
  why: [
    "Pharmaceutical advertisements and medical abstracts are a distinct Step 3 item type — roughly 10–15% of the exam. These items test whether you can critically appraise industry claims, identify study design limitations, and distinguish statistical from clinical significance.",
    "The classic traps: relative risk reduction without absolute event rates, surrogate endpoints presented as patient outcomes, post-hoc subgroup analyses, and wide confidence intervals crossing the null hypothesis.",
  ],
  concepts: [
    "Drug ad appraisal: study type, population, primary endpoint, absolute vs relative benefit, NNT, conflicts of interest",
    "Relative risk reduction without ARR exaggerates small benefits — always calculate NNT = 1/ARR",
    "Surrogate endpoints (LDL lowering, tumor response) may not translate to hard outcomes (MI, mortality)",
    "Primary vs secondary endpoints — secondary findings are hypothesis-generating, not confirmatory",
    "Abstract structure: population, intervention, comparator, outcomes, follow-up, dropout, ITT vs per-protocol",
    "Intention-to-treat analysis preserves randomization benefits — per-protocol can inflate efficacy",
    "Confidence interval excluding null (1.0 for RR/OR) = statistically significant; wide CI = imprecise estimate",
    "p-value measures probability of data if null true — NOT probability treatment works or effect size",
    "Non-inferiority trials require pre-specified margin — active control must be known effective",
    "Case-control measures OR; cohort measures RR; cross-sectional cannot establish temporality",
    "Lead-time bias: screening detects disease earlier without improving survival time from biologic onset",
    "Length bias: screening preferentially detects slow-growing disease with better prognosis",
    "Meta-analysis: assess heterogeneity (I²), funnel plot for publication bias, quality of included trials",
    "Post-marketing surveillance detects rare ADRs not seen in trials — black box warnings override marketing",
    "Number needed to harm (NNH) = 1/ARI — balance against NNT for net clinical benefit",
  ],
  clinical: [
    "Ad claims 50% RRR for stroke prevention; event rate 2% → 1% (ARR 1%, NNT 100) — small absolute benefit; shared decision-making",
    "Trial primary endpoint LDL reduction 30 mg/dL but no MI/mortality data — surrogate only; cannot assume hard outcome benefit",
    "Abstract: RR 0.85 for mortality, CI 0.65–1.12 — not statistically significant despite point estimate favoring drug",
    "Industry-sponsored RCT with high dropout in treatment arm analyzed per-protocol — biased toward efficacy; ITT preferred",
    "Screening trial shows improved 5-year survival for cancer — lead-time bias possible; look for mortality reduction",
    "Meta-analysis I² = 75% — substantial heterogeneity; pooling may be inappropriate; examine subgroups and study quality",
    "Non-inferiority trial of new anticoagulant vs warfarin with margin not pre-specified — invalid design conclusion",
    "Post-hoc subgroup 'benefit in women over 65' — hypothesis-generating only; not basis for labeling claim",
    "Drug ad fine print: NNH 50 for serious bleeding vs NNT 100 for stroke prevention — net benefit depends on patient values",
    "Case-control study of drug and cancer reports OR 2.5 — cannot calculate incidence; confounding by indication possible",
  ],
  tables: [
    {
      caption: "Appraising a drug advertisement",
      headers: ["Question", "What to look for", "Red flag"],
      rows: [
        ["Study design?", "RCT preferred", "Observational only"],
        ["Primary endpoint?", "Hard clinical outcome", "Surrogate only (LDL, A1c)"],
        ["Absolute benefit?", "Event rates in both arms", "RRR alone without ARR/NNT"],
        ["Population?", "Matches your patient?", "Exclusion of elderly, CKD, comorbidities"],
        ["Funding?", "Disclose conflicts", "Industry-only sponsorship undisclosed"],
        ["Safety?", "NNH for serious harms", "Minimized adverse events"],
      ],
    },
    {
      caption: "Statistical vs clinical significance",
      headers: ["Finding", "Statistical", "Clinical", "Conclusion"],
      rows: [
        ["RR 0.90, p=0.04, ARR 0.5%", "Significant", "NNT 200 — small", "May not be worth cost/harm"],
        ["RR 0.70, CI 0.45–1.08", "Not significant", "Large point estimate", "Underpowered; inconclusive"],
        ["LDL ↓40 mg/dL", "Significant", "Surrogate", "Need hard outcome trial"],
        ["NNH 20, NNT 100", "—", "Harm > benefit?", "Individualize decision"],
      ],
    },
    {
      caption: "Study design and appropriate measures",
      headers: ["Design", "Measure", "Can establish causation?", "Common bias"],
      rows: [
        ["RCT", "RR, ARR, NNT", "Yes (gold standard)", "Attrition, unblinding"],
        ["Prospective cohort", "RR, incidence", "Strong", "Confounding"],
        ["Case-control", "OR", "Moderate", "Recall, selection"],
        ["Cross-sectional", "Prevalence", "No (temporality)", "Survival, selection"],
        ["Meta-analysis", "Pooled RR/OR", "Depends on inputs", "Heterogeneity, publication bias"],
      ],
    },
    {
      caption: "Screening trial biases",
      headers: ["Bias", "Mechanism", "Effect on apparent benefit"],
      rows: [
        ["Lead-time", "Earlier diagnosis, same death date", "Inflates survival from diagnosis"],
        ["Length", "Detects indolent disease preferentially", "Overestimates screening benefit"],
        ["Selection", "Volunteers healthier", "Overestimates benefit in real population"],
      ],
    },
  ],
  visual: [
    "Drug ad deconstruction: headline RRR → find absolute rates → calculate NNT → assess harms (NNH)",
    "Forest plot reading: point estimate, CI crossing 1.0, heterogeneity I²",
    "Surrogate vs hard endpoint chain: LDL → plaque → MI → death (need trials at each link)",
    "ITT vs per-protocol: all randomized patients analyzed in assigned groups regardless of adherence",
    "Funnel plot asymmetry suggests publication bias in meta-analyses",
  ],
  misconceptions: [
    "Accepting surrogate endpoint improvement as patient outcome without hard endpoint data",
    "Ignoring confidence interval because p <0.05 — CI can still cross null",
    "Treating post-hoc subgroups as confirmatory findings — hypothesis-generating only",
    "Using OR as RR when outcome is common — OR exaggerates association vs RR",
    "Assuming screening survival benefit equals mortality benefit — lead-time and length bias",
  ],
  pearls: [
    "Always convert RRR to ARR and NNT before recommending a drug from an ad",
    "CI crossing 1.0 for RR/OR = not statistically significant — regardless of p-value nuances",
    "Primary endpoint wins; secondary endpoints are exploratory unless multiplicity adjusted",
    "Non-inferiority margin must be pre-specified — otherwise trial cannot claim non-inferiority",
    "Black box warnings and post-marketing data override marketing language",
  ],
  summary: [
    "Drug ads: find absolute event rates, calculate NNT, assess NNH and conflicts of interest",
    "Surrogate endpoints ≠ patient outcomes unless trial powered for hard endpoints",
    "ITT preferred; post-hoc subgroups hypothesis-generating only",
    "CI excluding null = significant; wide CI = imprecise — more informative than p alone",
    "Screening biases: lead-time, length, selection — look for mortality reduction not just survival",
  ],
});
