import { buildUsmleReviewModule } from "./usmle-module-builder";

export const PHYSIOLOGY_SYSTEMS_STEP1_MODULE = buildUsmleReviewModule({
  why: [
    "Integrated physiology is the bridge between basic science and clinical vignettes on Step 1. Boards test whether you can predict what happens to cardiac output, renal clearance, acid-base status, and oxygen delivery when a single variable changes — not whether you memorized isolated formulas.",
    "High-yield physiology clusters around pressure-volume loops, nephron segment function, V/Q mismatch, acid-base compensation, and autonomic reflexes. These frameworks explain murmur maneuvers, diuretic sites, shunt physiology, and why a patient with metabolic alkalosis paradoxically acidifies urine.",
  ],
  concepts: [
    "Frank-Starling: increased preload → increased stroke volume up to a limit; afterload reduction improves SV in failing heart",
    "PV loop shifts: ↑contractility = left/up; ↑afterload = right/up; ↑preload = rightward end-diastolic volume",
    "Murmur maneuvers: HOCM louder with ↓preload (Valsalva, standing); MVP later with ↑preload (squatting); AS quieter with handgrip",
    "RAAS activation in hypovolemia: renin → Ang I → ACE → Ang II (vasoconstrict + aldosterone) + ADH",
    "Nephron segments: PCT (65% Na reabsorption), thick ascending limb (loop diuretic), DCT (thiazide), collecting duct (K+-sparing)",
    "FeNa <1% prerenal AKI vs >2% intrinsic (ATN); BUN:Cr >20:1 supports prerenal",
    "V/Q mismatch: apex high V/Q (dead space), base low V/Q; shunt hypoxemia does not fully correct with 100% O₂",
    "Hypoxemia mechanisms: low FiO₂, hypoventilation, diffusion limitation, V/Q mismatch, shunt",
    "Henderson-Hasselbalch; respiratory vs metabolic; anion gap = Na − (Cl + HCO₃); MUDPILES for gap acidosis",
    "RTA types: I distal (cannot acidify urine, pH >5.5), II proximal (HCO₃ wasting), IV hyperkalemic (aldosterone deficiency)",
    "O₂-Hb dissociation curve: right shift (↓ affinity) with ↑CO₂, ↑H⁺, ↑2,3-BPG, ↑temperature",
    "Starling forces: filtration = Kf[(Pc − Pi) − (πc − πi)]; edema from ↑Pc, ↓πc, lymphatic obstruction, or ↑Kf",
  ],
  clinical: [
    "Young athlete with syncope and harsh systolic murmur louder with Valsalva — HOCM physiology (dynamic LVOT obstruction with ↓preload)",
    "CHF patient on loop diuretic develops muscle cramps and flattened T waves — hypokalemia from thick ascending limb blockade; check Mg²⁺",
    "COPD exacerbation with pH 7.28, PaCO₂ 65 — acute on chronic respiratory acidosis; next step is NIV before intubation if protecting airway",
    "DKA patient with K⁺ 5.8 — total body K⁺ depleted despite serum level; replete K⁺ before insulin when K⁺ <3.3",
    "Volume-depleted patient with metabolic alkalosis and acidic urine — paradoxical aciduria ( kidneys retain H⁺ while excreting NaHCO₃)",
    "Pneumonia with hypoxemia unresponsive to high-flow O₂ — intrapulmonary shunt physiology; consider ARDS and PEEP",
    "Patient with RTA type I and nephrolithiasis — cannot acidify urine (pH >5.5), hypokalemia, hypercalciuria",
    "Elderly on thiazide with confusion and muscle weakness — hyponatremia from SIADH-like effect plus volume contraction",
    "Metabolic acidosis with anion gap 22 and osmolar gap 25 — toxic alcohol ingestion until proven otherwise",
    "Pregnant patient with respiratory alkalosis — normal compensated chronic respiratory alkalosis (progesterone stimulates central chemoreceptors)",
  ],
  tables: [
    {
      caption: "Acid-base patterns and compensation",
      headers: ["Primary disorder", "pH", "PCO₂", "HCO₃", "Compensation rule"],
      rows: [
        ["Metabolic acidosis", "↓", "↓ (respiratory)", "↓", "Winter's: PCO₂ ≈ 1.5×HCO₃ + 8 (±2)"],
        ["Metabolic alkalosis", "↑", "↑ (respiratory)", "↑", "PCO₂ ↑ ~0.7 mmHg per 1 mEq/L HCO₃"],
        ["Respiratory acidosis", "↓", "↑", "↑ (renal)", "Acute: HCO₃ ↑ 1 mEq/L per 10 mmHg PCO₂"],
        ["Respiratory alkalosis", "↑", "↓", "↓ (renal)", "Chronic: HCO₃ ↓ 2–5 mEq/L per 10 mmHg PCO₂"],
      ],
    },
    {
      caption: "Diuretic site and electrolyte effects",
      headers: ["Diuretic", "Site", "Key electrolyte effect"],
      rows: [
        ["Acetazolamide", "PCT", "HCO₃ wasting → metabolic acidosis"],
        ["Furosemide", "Thick ascending limb", "Na, K, Cl, Mg loss → hypokalemia"],
        ["HCTZ", "DCT", "Na loss; less K than loop; hyperuricemia, hypercalcemia"],
        ["Spironolactone", "Collecting duct", "K retention; hyperkalemia risk with ACEi/ARB"],
      ],
    },
    {
      caption: "Murmur maneuvers — board favorites",
      headers: ["Maneuver", "Effect on preload/afterload", "Classic murmur change"],
      rows: [
        ["Valsalva / standing", "↓ preload", "HOCM louder; most others softer"],
        ["Squatting / leg raise", "↑ preload", "HOCM softer; MVP later"],
        ["Handgrip", "↑ afterload", "AS softer; MR louder"],
        ["Amyl nitrite", "↓ afterload", "AS softer; HOCM louder"],
      ],
    },
  ],
  visual: [
    "PV loop quadrants: visualize contractility vs afterload vs preload as orthogonal shifts",
    "Nephron map: color-code diuretic sites from glomerulus to collecting duct",
    "V/Q scatter plot: apex = dead space, base = shunt, middle = matched ventilation-perfusion",
    "Acid-base decision tree: check pH → primary disorder → calculate expected compensation → anion gap",
    "O₂-Hb curve: left shift (fetal Hb, CO poisoning) vs right shift (exercise, acidosis, altitude)",
  ],
  misconceptions: [
    "Assuming SpO₂ excludes significant hypoventilation — pulse ox can appear normal until severe hypercapnia",
    "Treating all metabolic alkalosis with saline — chloride-responsive (vomiting, diuretics) vs resistant (hyperaldosteronism)",
    "Forgetting shunt physiology does not fully correct with supplemental O₂ — unlike V/Q mismatch",
    "Using FeNa alone without clinical context — diuretics and CKD alter interpretation",
    "Confusing RTA type II (proximal HCO₃ wasting) with type I (distal acidification failure)",
  ],
  pearls: [
    "Standing makes HOCM murmur louder — opposite of most murmurs; board loves this pairing",
    "Loop diuretic after thiazide can 'break' refractory edema — sequential nephron blockade",
    "Metabolic alkalosis + hypertension in young patient → think hyperaldosteronism or Liddle syndrome",
    "High-altitude hypoxemia is V/Q mismatch + low PiO₂, not diffusion defect in healthy lungs",
    "Paradoxical aciduria in volume-depleted alkalosis is a classic Step 1 trap answer",
  ],
  summary: [
    "Master PV loops, murmur maneuvers, and Frank-Starling for cardiovascular physiology",
    "Know nephron segments, diuretic sites, FeNa, and acid-base compensation rules",
    "V/Q mismatch vs shunt explains hypoxemia response to supplemental O₂",
    "Anion gap + osmolar gap framework for metabolic acidosis differentials",
    "RTA types, paradoxical aciduria, and electrolyte effects of RAAS blockade",
  ],
});

export const BIOCHEMISTRY_METABOLISM_STEP1_MODULE = buildUsmleReviewModule({
  why: [
    "Biochemistry on Step 1 links enzyme defects to substrate accumulation, clinical phenotype, and treatment. Boards reward pathway logic — glycolysis vs gluconeogenesis irreversible steps, urea cycle defects, lysosomal storage diseases, and vitamin cofactor dependencies.",
    "Metabolic vignettes often present a neonate or child with vomiting after feeds, hypoglycemia, acidosis, or neurologic decline. The correct answer is usually the enzyme defect that explains ALL findings, not the most dramatic lab in isolation.",
  ],
  concepts: [
    "Glycolysis irreversible steps: hexokinase/glucokinase, PFK-1, pyruvate kinase — bypassed in gluconeogenesis by pyruvate carboxylase, PEPCK, fructose-1,6-bisphosphatase, G6Pase",
    "Insulin favors anabolic pathways; glucagon/cortisol/epinephrine favor catabolism and gluconeogenesis",
    "Urea cycle defects → hyperammonemia WITHOUT acidosis; OTC deficiency → orotic aciduria (carbamoyl phosphate spills into pyrimidine synthesis)",
    "MSUD: branched-chain ketoacid dehydrogenase deficiency — maple syrup urine, neurologic decline; restrict leucine/isoleucine/valine",
    "GSD I (von Gierke): glucose-6-phosphatase — severe fasting hypoglycemia, lactic acidosis, hepatomegaly",
    "GSD II (Pompe): lysosomal α-1,4-glucosidase — cardiomegaly, hypotonia; treat with enzyme replacement",
    "GSD V (McArdle): muscle glycogen phosphorylase — exercise intolerance, myoglobinuria, second-wind phenomenon",
    "Fatty acid oxidation defects: hypoketotic hypoglycemia with fasting stress — cannot generate ketones",
    "Lysosomal storage: Hurler (α-L-iduronidase), Hunter (iduronate sulfatase, no corneal clouding), Tay-Sachs (hexosaminidase A)",
    "HMG-CoA reductase is statin target; FH from LDL receptor mutation — tendon xanthomas, premature CAD",
    "Vitamin cofactors: B1/TPP (PDH, α-KGDH, transketolase), B2/FAD, B3/NAD, B6/PLP, folate/B12 (methionine synthase)",
    "DNA repair defects: xeroderma pigmentosum (nucleotide excision), HNPCC/Lynch (mismatch repair), ataxia-telangiectasia",
  ],
  clinical: [
    "Neonate with vomiting after milk feeds, reducing substances in urine, E. coli sepsis — classic galactosemia (galactose-1-phosphate uridyltransferase)",
    "Infant with lethargy, hyperammonemia, no acidosis, elevated orotic acid — OTC deficiency (X-linked)",
    "Child with intellectual disability, musty odor, fair skin, seizures — PKU (phenylalanine hydroxylase); restrict phenylalanine",
    "Marathon runner with cramping, dark urine, no second wind — McArdle disease (GSD V)",
    "Infant with hepatomegaly, fasting hypoglycemia, lactic acidosis — von Gierke (GSD I); avoid fructose/galactose",
    "Malnourished alcoholic given glucose before thiamine — Wernicke encephalopathy (ophthalmoplegia, ataxia, confusion)",
    "Macrocytic anemia with neurologic symptoms and ↑methylmalonic acid — B12 deficiency, not folate alone",
    "Child with coarse facies, corneal clouding, developmental delay — Hurler syndrome (MPS I)",
    "Teen with fasting hypoglycemia, low ketones, dicarboxylic aciduria — MCAD or other FA oxidation defect",
    "Patient on statin with muscle pain and elevated CK — check for gemfibrozil interaction (CYP/glucuronidation)",
  ],
  tables: [
    {
      caption: "High-yield inborn errors of metabolism",
      headers: ["Disease", "Enzyme defect", "Key findings", "Treatment"],
      rows: [
        ["PKU", "Phenylalanine hydroxylase", "Musty odor, fair skin, seizures", "Low phenylalanine diet"],
        ["Galactosemia", "Galactose-1-P uridyltransferase", "Jaundice, cataracts, E. coli sepsis", "Galactose-free diet"],
        ["MSUD", "Branched-chain α-ketoacid DH", "Maple syrup urine, neuro decline", "Restrict BCAA"],
        ["OTC deficiency", "Ornithine transcarbamylase", "Hyperammonemia, orotic aciduria", "Low protein, arginine, nitrogen scavengers"],
        ["Classic homocystinuria", "Cystathionine β-synthase", "Marfanoid, lens dislocation down/out, thrombosis", "B6, folate, B12, restrict methionine"],
      ],
    },
    {
      caption: "Glycogen storage diseases",
      headers: ["Type", "Name", "Enzyme", "Key feature"],
      rows: [
        ["I", "von Gierke", "Glucose-6-phosphatase", "Severe fasting hypoglycemia, lactic acidosis"],
        ["II", "Pompe", "Lysosomal α-1,4-glucosidase", "Cardiomegaly, hypotonia"],
        ["III", "Cori", "Debranching enzyme", "Milder hypoglycemia, hepatomegaly"],
        ["V", "McArdle", "Muscle glycogen phosphorylase", "Exercise intolerance, myoglobinuria"],
      ],
    },
    {
      caption: "Vitamin deficiency syndromes",
      headers: ["Vitamin", "Active form", "Classic deficiency"],
      rows: [
        ["B1 (thiamine)", "TPP", "Wernicke-Korsakoff, beriberi"],
        ["B3 (niacin)", "NAD/NADP", "Pellagra (3 Ds: dermatitis, diarrhea, dementia)"],
        ["B6 (pyridoxine)", "PLP", "Sideroblastic anemia, neuropathy with INH"],
        ["B12", "Methylcobalamin", "Macrocytic anemia + neuro + ↑MMA"],
        ["C", "Ascorbic acid", "Scurvy (bleeding gums, poor wound healing)"],
        ["D", "1,25-(OH)₂D", "Rickets/osteomalacia"],
      ],
    },
  ],
  visual: [
    "Glycolysis/gluconeogenesis mirror: highlight 4 irreversible steps and their bypass enzymes",
    "Urea cycle with OTC spillover to orotic acid synthesis pathway",
    "Lysosomal storage disease ladder: substrate → enzyme → clinical phenotype",
    "Fed vs fasted state: insulin vs glucagon effects on glycogen, lipolysis, ketogenesis",
    "B12 vs folate: methylmalonic acid elevation distinguishes B12 deficiency",
  ],
  misconceptions: [
    "Confusing ketosis (diabetes, starvation) with hypoketotic hypoglycemia (FA oxidation defects)",
    "Giving glucose before thiamine in malnourished patients — precipitates Wernicke",
    "Missing B12 vs folate: only B12 causes neurologic symptoms and methylmalonic acid elevation",
    "Assuming all hyperammonemia has metabolic acidosis — urea cycle defects do not",
    "Treating Hunter like Hurler — Hunter lacks corneal clouding (X-linked vs autosomal recessive)",
  ],
  pearls: [
    "Give thiamine BEFORE glucose in malnourished or alcoholic patients — board classic",
    "Infant vomiting after milk + reducing substances = galactosemia until proven otherwise",
    "MSUD: maple syrup odor in diaper — restrict leucine, isoleucine, valine",
    "OTC deficiency: hyperammonemia + orotic aciduria WITHOUT acidosis — only urea cycle defect with orotic aciduria",
    "McArdle: second-wind phenomenon and exercise-induced myoglobinuria",
  ],
  summary: [
    "Link enzyme defect → substrate buildup → clinical phenotype for IEM vignettes",
    "Know glycolysis/gluconeogenesis irreversible steps and fasting vs fed regulation",
    "Urea cycle defects: hyperammonemia, OTC → orotic aciduria, no acidosis",
    "GSD types I, II, V and lysosomal storage disease distinguishing features",
    "Vitamin cofactors and B12 vs folate differentiation (MMA, neurologic symptoms)",
  ],
});

export const MICROBIOLOGY_IMMUNOLOGY_STEP1_MODULE = buildUsmleReviewModule({
  why: [
    "Microbiology and immunology on Step 1 test pattern recognition plus mechanism — Gram stain algorithm, viral serology matrices, hypersensitivity types, and primary immunodeficiency patterns. Clinical vignettes pair a patient population with an organism or immune defect.",
    "High-yield clusters include encapsulated organisms in asplenia, Neisseria in complement deficiency, HBV serology interpretation, exotoxin vs endotoxin mechanisms, and live vs killed vaccine contraindications.",
  ],
  concepts: [
    "Gram algorithm: cocci in clusters (Staph) vs chains (Strep); bacilli (Bacillus, Clostridium, Listeria); Gram-negative diplococci (Neisseria); rods (Enterobacteriaceae, Pseudomonas)",
    "Staph aureus: catalase+, coagulase+; MRSA = mecA; Strep: catalase−, bacitracin/ optochin for pneumo vs viridans",
    "Atypical bacteria lack classic cell wall (Mycoplasma) — treat with macrolide/tetracycline, NOT beta-lactam",
    "Exotoxin (secreted protein, specific MOA, toxoid vaccines) vs endotoxin (LPS, Gram-negative, TNF/IL-1 release)",
    "HBV serology: HBsAg+ = active infection; anti-HBs+ = immunity; anti-HBc IgM = acute; anti-HBc IgG = past/chronic",
    "HIV lifecycle targets: entry (maraviroc), RT (NRTI/NNRTI), integrase, protease inhibitors",
    "Hypersensitivity I–IV: anaphylaxis (IgE), cytotoxic (AIHA), immune complex (SLE), delayed (TB PPD, contact dermatitis)",
    "Primary immunodeficiencies: B cell (XLA, CVID) → encapsulated bacteria; T cell (DiGeorge) → viral/fungal/opportunistic",
    "Phagocyte defects: CGD (NADPH oxidase, catalase+ organisms), Chediak-Higashi (microtubule dysfunction)",
    "Complement C5–C9 deficiency → recurrent Neisseria meningitidis/gonorrhoeae",
    "Autoantibodies: ANA (SLE), anti-dsDNA (SLE nephritis), RF/anti-CCP (RA), c-ANCA/PR3 (GPA), p-ANCA (MPA)",
    "Live vaccines contraindicated in pregnancy and severe immunocompromise; killed/subunit vaccines generally safe",
  ],
  clinical: [
    "Postsplenectomy patient with fever and encapsulated organism bacteremia — Streptococcus pneumoniae; vaccinate pre-op when possible",
    "Teen with petechial rash and meningismus after college party — N. meningitidis; complement deficiency increases risk",
    "Patient with recurrent gonococcal and meningococcal infections — terminal complement (C5–C9) deficiency",
    "Young adult with 'walking pneumonia,' cold agglutinins — Mycoplasma pneumoniae; treat with azithromycin, not amoxicillin",
    "Neonate with conjunctivitis and pneumonia — Chlamydia trachomatis (D–K); treat mother and infant",
    "Farmer with pulmonary infiltrates after moldy hay — hypersensitivity pneumonitis (thermophilic actinomycetes)",
    "Patient with SLE flare: malar rash, joint pain, anti-dsDNA+, low C3/C4 — type III hypersensitivity immune complex disease",
    "Child with eczema, recurrent staph abscesses, elevated IgE — STAT3 hyper-IgE (Job) syndrome",
    "DiGeorge syndrome: cardiac outflow defects, hypocalcemia, absent thymic shadow — T cell deficiency, live vaccines contraindicated",
    "HBV panel: HBsAg−, anti-HBs+, anti-HBc− — vaccinated (immunity from vaccine, no prior infection)",
  ],
  tables: [
    {
      caption: "HBV serology interpretation",
      headers: ["Pattern", "HBsAg", "Anti-HBs", "Anti-HBc IgM", "Anti-HBc IgG", "Interpretation"],
      rows: [
        ["Acute infection", "+", "−", "+", "−/+", "Acute or early"],
        ["Chronic infection", "+", "−", "−", "+", "Chronic carrier"],
        ["Immunity (natural)", "−", "+", "−", "+", "Resolved infection"],
        ["Immunity (vaccine)", "−", "+", "−", "−", "Vaccinated"],
        ["Window period", "−", "−", "+", "−", "Acute, HBsAg cleared"],
      ],
    },
    {
      caption: "Hypersensitivity types",
      headers: ["Type", "Mechanism", "Examples", "Timing"],
      rows: [
        ["I", "IgE, mast cell degranulation", "Anaphylaxis, allergic rhinitis", "Minutes"],
        ["II", "IgG/IgM vs cell surface", "AIHA, Goodpasture, ABO transfusion", "Hours"],
        ["III", "Immune complex deposition", "SLE, PSGN, serum sickness", "Hours–days"],
        ["IV", "T cell mediated", "TB PPD, contact dermatitis, graft rejection", "Days"],
      ],
    },
    {
      caption: "Primary immunodeficiency patterns",
      headers: ["Defect", "Syndrome", "Recurrent infections"],
      rows: [
        ["B cell", "XLA, CVID", "Encapsulated bacteria (Strep pneumo, H flu)"],
        ["T cell", "DiGeorge, SCID", "Viral, fungal, PCP, CMV"],
        ["Phagocyte", "CGD", "Catalase+ organisms (S aureus, Aspergillus, Nocardia)"],
        ["Complement", "C5–C9 deficiency", "Neisseria species"],
      ],
    },
  ],
  visual: [
    "Gram stain decision tree: shape → Gram result → catalase/coagulase → final organism",
    "HBV serology matrix: 5 patterns cover 95% of board questions",
    "Hypersensitivity timeline: minutes (I) → hours (II/III) → days (IV)",
    "Immunodeficiency ladder: which arm of immunity failed → which pathogens recur",
    "Exotoxin vs endotoxin: secreted protein with target vs LPS in outer membrane",
  ],
  misconceptions: [
    "Treating Mycoplasma with beta-lactam — lacks peptidoglycan cell wall",
    "Confusing anti-HBs (immunity) with HBsAg (active infection)",
    "Calling all granulomas TB — sarcoid, foreign body, fungal also granulomatous",
    "Live vaccines in pregnancy or severe immunocompromise — contraindicated",
    "Assuming PPD tests humoral immunity — it tests cell-mediated (type IV) response",
  ],
  pearls: [
    "Terminal complement deficiency → recurrent Neisseria — high-yield association",
    "Group B Strep prophylaxis in labor if colonized — prevents neonatal sepsis/meningitis",
    "Asplenic patients need pneumococcal, meningococcal, H flu vaccines — encapsulated organisms",
    "Anti-dsDNA correlates with SLE nephritis activity — not just ANA positivity",
    "CGD: nitroblue tetrazolium test fails to turn formazan blue — NADPH oxidase defect",
  ],
  summary: [
    "Gram algorithm + atypical bacteria (no cell wall) → correct antibiotic class",
    "HBV serology 5-pattern matrix for acute, chronic, and immune status",
    "Hypersensitivity I–IV with classic examples and timing",
    "Primary immunodeficiency → pathogen pattern (encapsulated, Neisseria, catalase+)",
    "Autoantibody associations: ANA/dsDNA (SLE), RF/CCP (RA), ANCA (vasculitis)",
  ],
});

export const ANATOMY_EMBRYOLOGY_STEP1_MODULE = buildUsmleReviewModule({
  why: [
    "Anatomy and embryology on Step 1 test spatial relationships linked to clinical consequences — cranial nerve deficits, hernia types, pharyngeal arch derivatives, and congenital malformations from failed embryologic events. A single anatomic fact predicts the lesion location and associated defects.",
    "Embryology vignettes connect pouch/arch failures to syndromes: DiGeorge (3rd/4th pouch), Meckel diverticulum (vitelline duct), neural tube defects (folate), and TGA/TOF (septation errors). Anatomy items often present trauma or surgical complications.",
  ],
  concepts: [
    "Cranial nerves: CN III (down-and-out, ptosis, pupil often involved), CN VI (lateral rectus, horizontal diplopia worse at distance), CN VII (facial weakness — UMN spares forehead)",
    "Carotid sheath: common carotid, IJV, vagus nerve — runs from skull base to thoracic inlet",
    "Inguinal hernia: indirect through internal ring (lateral to inferior epigastrics, congenital patent processus); direct through Hesselbach triangle (acquired)",
    "Pharyngeal arches: 1st Meckel → mandible, malleus, MCN V3; 2nd Reichert → stapes, CN VII; 3rd → stylopharyngeus, CN IX; 4th–6th → laryngeal cartilages, CN X",
    "Pharyngeal pouches: 1st → middle ear/cleft; 2nd → palatine tonsil; 3rd → inferior parathyroids, thymus; 4th → superior parathyroids",
    "Neural tube defects: folate prevention; open NTD → elevated AFP; anencephaly, spina bifida",
    "DiGeorge 22q11: 3rd/4th pouch failure → absent thymus/parathyroids, cardiac outflow defects, hypocalcemia",
    "Portal triad: hepatic artery, portal vein, bile duct — Cantlie line separates liver segments for resection",
    "Ectopic pregnancy most often ampulla of fallopian tube — rupture causes hemoperitoneum",
    "Meckel rule of 2s: 2% population, 2 feet from ileocecal valve, 2 types ectopic tissue, presents by age 2",
    "SVC syndrome: face/arm swelling, distended chest wall veins — lung cancer or mediastinal mass",
    "Femoral triangle: NAVEL — nerve, artery, vein, empty space, lymphatics (lateral to medial)",
  ],
  clinical: [
    "Child with chin laceration and lower lip numbness — mental nerve (V3) injury from anterior mandible fracture",
    "Neonate with single umbilical artery — associated with renal and cardiac anomalies; evaluate further",
    "DiGeorge infant: tet spells, hypocalcemic seizures, absent thymic shadow — 22q11 deletion, cardiac outflow defect",
    "Young man with right-sided scrotal swelling that increases with cough — indirect inguinal hernia through internal ring",
    "Elderly man with bulge in Hesselbach triangle — direct inguinal hernia through transversalis fascia weakness",
    "Pregnant patient with missed period, adnexal mass, empty uterus on ultrasound — ectopic pregnancy in ampulla",
    "Child with painless rectal bleeding, technetium-99m scan positive — Meckel diverticulum with ectopic gastric mucosa",
    "Patient with CN III palsy (down-and-out eye, ptosis, dilated pupil) — posterior communicating artery aneurysm until proven otherwise",
    "Facial weakness sparing forehead after stroke — UMN lesion (contralateral cortex); forehead spared because bilateral innervation",
    "Lateral rectus palsy (CN VI) with papilledema — false localizing sign of raised ICP; still evaluate all CN",
  ],
  tables: [
    {
      caption: "Pharyngeal arch derivatives",
      headers: ["Arch", "Skeleton/cartilage", "Nerve", "Muscle"],
      rows: [
        ["1st (Meckel)", "Malleus, incus, mandible", "CN V3 (trigeminal)", "Muscles of mastication"],
        ["2nd (Reichert)", "Stapes, styloid, lesser horn hyoid", "CN VII (facial)", "Facial expression muscles"],
        ["3rd", "Greater horn hyoid", "CN IX (glossopharyngeal)", "Stylopharyngeus"],
        ["4th–6th", "Laryngeal cartilages", "CN X (vagus)", "Pharyngeal/laryngeal muscles"],
      ],
    },
    {
      caption: "Indirect vs direct inguinal hernia",
      headers: ["Feature", "Indirect", "Direct"],
      rows: [
        ["Anatomic site", "Through internal inguinal ring", "Hesselbach triangle"],
        ["Etiology", "Patent processus vaginalis", "Acquired floor weakness"],
        ["Age", "Any age, common in infants", "Older adults"],
        ["Relation to epigastrics", "Lateral", "Medial"],
        ["Into scrotum", "Often", "Rarely"],
      ],
    },
    {
      caption: "Cranial nerve localizing findings",
      headers: ["CN", "Deficit", "Classic cause"],
      rows: [
        ["III", "Down-and-out eye, ptosis, dilated pupil", "PCom aneurysm, uncal herniation"],
        ["IV", "Vertical diplopia, head tilt", "Midbrain, trauma"],
        ["VI", "Horizontal diplopia, esotropia", "Raised ICP, cavernous sinus"],
        ["VII", "Facial weakness", "Bell palsy (LMN), stroke (UMN spares forehead)"],
      ],
    },
  ],
  visual: [
    "Pharyngeal arch map: arch number → nerve → derivative structures",
    "Inguinal canal cross-section: internal ring (lateral) vs Hesselbach triangle (medial)",
    "DiGeorge pathway: 3rd/4th pouch failure → thymus + parathyroid + cardiac outflow defects",
    "Cranial nerve orbit diagram: III, IV, VI paths and expected eye positions",
    "Neural tube closure timeline: folate critical at weeks 3–4; AFP elevation in open defects",
  ],
  misconceptions: [
    "Confusing indirect (congenital, lateral) with direct (acquired, medial) inguinal hernia",
    "Missing CN VI as false localizing sign in raised ICP — still test all cranial nerves",
    "Assuming all facial weakness is Bell palsy — UMN stroke spares forehead",
    "Forgetting Meckel can cause painless GI bleeding from ectopic gastric mucosa, not just obstruction",
    "Equating single umbilical artery as always benign — warrants renal/cardiac evaluation",
  ],
  pearls: [
    "CN III palsy with pupil involvement → compressive lesion (aneurysm) until proven otherwise",
    "Indirect hernia lateral to inferior epigastric vessels; direct hernia medial — board favorite",
    "DiGeorge = CATCH-22: Cardiac, Abnormal facies, Thymic hypoplasia, Cleft palate, Hypocalcemia",
    "Meckel rule of 2s — painless lower GI bleeding in child, check technetium scan",
    "UMN facial palsy spares forehead; LMN (Bell palsy) involves entire half of face",
  ],
  summary: [
    "Cranial nerve deficits localize lesions — III (PCom aneurysm), VI (false localizing), VII (UMN vs LMN)",
    "Indirect vs direct inguinal hernia: lateral vs medial to epigastrics, congenital vs acquired",
    "Pharyngeal arch/pouch derivatives → DiGeorge, branchial cysts, parathyroid embryology",
    "Neural tube defects: folate prevention, AFP elevation, open vs closed",
    "Meckel diverticulum, ectopic pregnancy ampulla, portal triad anatomic relations",
  ],
});
