import { buildUsmleReviewModule } from "./usmle-module-builder";

export const CARDIOVASCULAR_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Cardiovascular medicine dominates Step 2 CK — ACS pathways, heart failure GDMT, valvular disease timing, arrhythmias, and pericardial syndromes appear in nearly every practice exam. Boards test the next best step under time pressure, not exhaustive cardiology knowledge.",
    "The highest-yield traps: withholding beta-blockers in stable HFrEF, misreading aVR ST elevation as benign, delaying cath lab activation for obvious STEMI, and missing papillary muscle rupture post-MI.",
  ],
  concepts: [
    "STEMI: ST elevation ≥2 contiguous leads or new LBBB → emergent PCI (door-to-balloon ≤90 min); fibrinolytics if PCI unavailable within 120 min",
    "NSTEMI/UA: anticoagulate + DAPT; early invasive strategy if high TIMI/GRACE score",
    "HFrEF four pillars: ACEi/ARB or ARNI + beta-blocker + MRA + SGLT2i — all reduce mortality",
    "Acute decompensated HF: IV loop diuretic first; BiPAP for hypoxia/hypercapnia; avoid routine inotropes",
    "Aortic stenosis triad: angina, syncope, HF — symptom onset = urgent AVR/TAVR indication",
    "Mitral regurgitation post-inferior MI: papillary muscle rupture — holosystolic murmur, flash pulmonary edema, shock",
    "Cardiac tamponade: Beck triad + pulsus paradoxus >10 mmHg — echo then pericardiocentesis",
    "Atrial fibrillation rate vs rhythm control; anticoagulate by CHA₂DS₂-VASc; HAS-BLED for bleeding risk",
    "Long QT culprits: fluoroquinolones, macrolides, antipsychotics, antifungals — check baseline QTc",
    "Pericarditis: pleuritic pain worse supine, friction rub — NSAIDs + colchicine; avoid anticoagulation if effusion",
    "aVR ST elevation + diffuse ST depression → left main or proximal LAD occlusion — emergent cath",
  ],
  clinical: [
    "55-year-old with crushing chest pain 2 hours, ST elevation V1–V4 — activate cath lab; do not wait for troponin",
    "Known HFrEF with 10 lb weight gain, orthopnea — IV furosemide is next step, not echo first",
    "Elderly woman with systolic murmur radiating to carotids, exertional syncope, gradient 55 mmHg — severe AS, refer AVR even if 'minimal symptoms'",
    "Post-inferior MI, new holosystolic murmur, pulmonary edema, shock — papillary muscle rupture, surgical emergency",
    "Hypotensive, JVD, muffled heart sounds after chest trauma — tamponade; echo then pericardiocentesis",
    "Stable HFrEF, EF 30% — start/continue beta-blocker (carvedilol, metoprolol succinate, bisoprolol); do not withhold for 'heart failure'",
    "ECG: ST elevation aVR with diffuse ST depression — left main disease; emergent angiography",
    "New AF with RVR and hypotension — synchronized cardioversion; rate control with diltiazem if stable",
    "Digoxin toxicity: nausea, yellow vision, bidirectional VT — hold digoxin, check level; hypokalemia worsens toxicity",
    "Pericarditis post-MI (Dressler) vs early post-MI pericarditis — both NSAIDs; avoid anticoagulation if large effusion",
  ],
  tables: [
    {
      caption: "ACS management pathway",
      headers: ["Type", "ECG", "Next step", "Trap"],
      rows: [
        ["STEMI", "ST elevation ≥2 leads", "Cath lab activation + DAPT", "Waiting for troponin"],
        ["NSTEMI high risk", "ST depression/T inversion", "Early invasive + anticoagulation", "Conservative strategy in high TIMI"],
        ["UA low risk", "Normal/nonspecific", "Medical therapy, stress test", "Immediate cath without risk stratification"],
      ],
    },
    {
      caption: "HFrEF guideline-directed therapy",
      headers: ["Agent class", "Examples", "Mortality benefit"],
      rows: [
        ["ACEi/ARB/ARNI", "Sacubitril-valsartan", "Yes — foundational"],
        ["Beta-blocker", "Carvedilol, metoprolol succinate", "Yes — start when euvolemic"],
        ["MRA", "Spironolactone, eplerenone", "Yes — monitor K⁺/Cr"],
        ["SGLT2i", "Dapagliflozin, empagliflozin", "Yes — even without diabetes"],
      ],
    },
    {
      caption: "Valvular disease urgency",
      headers: ["Lesion", "Symptom trigger", "Action"],
      rows: [
        ["Severe AS", "Angina, syncope, HF", "Urgent AVR/TAVR"],
        ["Acute MR (papillary rupture)", "Flash pulmonary edema post-MI", "Emergent surgery"],
        ["Severe MR chronic", "Symptoms or EF decline", "Mitral repair/replacement"],
        ["Symptomatic severe MS", "Dyspnea, AF", "Mitral valvuloplasty/surgery"],
      ],
    },
  ],
  visual: [
    "ACS timeline: symptom onset → ECG → cath lab activation → door-to-balloon clock",
    "HFrEF four pillars stacked — all required for mortality benefit",
    "PV loop in AS: high afterload, reduced stroke volume, hypertrophied ventricle",
    "Tamponade pressure-volume relationship: ventricular filling limited by pericardial constraint",
    "aVR pattern: 'smile' ST elevation with diffuse ST depression = left main",
  ],
  misconceptions: [
    "Withholding beta-blockers in stable HFrEF — they reduce mortality; only hold in acute decompensation",
    "Treating aVR ST elevation + diffuse depression as benign — left main equivalent",
    "Routine intubation before BiPAP in ADHF with respiratory distress — try NIV first",
    "Beta-blocker monotherapy in cocaine chest pain — unopposed alpha vasoconstriction; benzodiazepines first",
    "Assuming all systolic murmurs need immediate surgery — timing depends on symptoms and severity",
  ],
  pearls: [
    "STEMI: clinical + ECG sufficient for cath lab — troponin confirms but does not gate treatment",
    "Syncope in severe AS = indication for valve replacement even without other symptoms",
    "Papillary muscle rupture post-inferior MI — inferior territory, new MR murmur, hemodynamic collapse",
    "Cardiogenic shock post-MI: early PCI is mortality-reducing; vasopressors as bridge only",
    "Pericarditis pain improves leaning forward — pleuritic, friction rub, diffuse ST elevation",
  ],
  summary: [
    "STEMI → cath lab; NSTEMI → risk stratify for early invasive strategy",
    "HFrEF four pillars all reduce mortality — never withhold stable beta-blocker",
    "AS symptom triad = urgent valve replacement; papillary rupture = surgical emergency",
    "Tamponade: Beck triad + pulsus paradoxus; aVR pattern = left main occlusion",
    "AF anticoagulation by CHA₂DS₂-VASc; rate control vs cardioversion based on stability",
  ],
});

export const PULMONARY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Pulmonary items on Step 2 CK cluster around COPD/asthma exacerbations, PE workup, pneumonia management, pleural disease, and mechanical ventilation basics. The board tests whether you choose BiPAP before intubation, CT-PA when Wells is intermediate-high, and Light criteria before draining effusions.",
  ],
  concepts: [
    "COPD exacerbation: SABA/SAMA bronchodilators + systemic steroids (5 days) + antibiotics if purulent sputum",
    "BiPAP indication: pH 7.25–7.35 with hypercapnia; reduces intubation and mortality in COPD exacerbation",
    "COPD step-up: LAMA → LAMA+LABA → add ICS if eosinophils ≥300 or frequent exacerbations",
    "Target SpO₂ 88–92% in COPD — avoid hyperoxia suppressing hypoxic drive",
    "Wells PE score ≥2 → imaging; low probability + negative D-dimer rules out PE",
    "Massive PE: hemodynamic compromise → thrombolytics if no contraindication; else embolectomy",
    "Asthma step-up: PRN SABA → low-dose ICS → ICS+LABA → add LAMA/biologic for severe persistent",
    "Status asthmaticus: continuous nebs, systemic steroids, magnesium; intubate if fatigue/imminent arrest",
    "Light criteria exudate: protein ratio >0.5 OR LDH ratio >0.6 OR LDH >2/3 ULN",
    "Parapneumonic effusion pH <7.2 → chest tube drainage required",
    "Tension pneumothorax: clinical diagnosis — needle decompress 2nd ICS MCL without waiting for CXR",
    "UIP pattern honeycombing + basal fibrosis = IPF; nintedanib/pirfenidone slow progression; avoid steroids as primary",
  ],
  clinical: [
    "68-year-old COPD, obtunded, RR 28, pH 7.28, PaCO₂ 72 — BiPAP next step, not intubation if airway protected",
    "35-year-old on OCPs, pleuritic chest pain, tachycardia, Wells ≥2 — CT-PA; do not rely on D-dimer alone",
    "Massive PE with hypotension and RV strain — thrombolytics unless active bleeding contraindication",
    "Asthma exacerbation, PEF 40% predicted after initial nebs — add systemic steroids, admit, continue bronchodilators",
    "Pleural effusion after pneumonia, pH 7.15, glucose 40 — complicated parapneumonic; chest tube drainage",
    "Young tall smoker with sudden dyspnea, unilateral absent breath sounds — primary spontaneous pneumothorax; chest tube if large/symptomatic",
    "Trauma patient with tracheal deviation, hypotension, absent breath sounds — tension PTX; needle then chest tube",
    "COPD on 6 L O₂, SpO₂ 100%, worsening somnolence — reduce O₂ to target 88–92%",
    "Transudative effusion in CHF — treat HF, do not drain without indication; recurrence if underlying not treated",
    "Interstitial lung disease, UIP pattern, FVC declining — nintedanib or pirfenidone; refer transplant evaluation",
  ],
  tables: [
    {
      caption: "COPD pharmacotherapy escalation (GOLD)",
      headers: ["Group", "Symptoms/exacerbations", "Therapy"],
      rows: [
        ["A", "Low symptoms, low exacerbations", "PRN SABA or SAMA"],
        ["B", "High symptoms, low exacerbations", "LAMA or LABA"],
        ["E", "Frequent exacerbations", "LAMA+LABA ± ICS if eos ≥300"],
      ],
    },
    {
      caption: "PE management by severity",
      headers: ["Category", "Features", "Treatment"],
      rows: [
        ["Low risk", "Normal BP, no RV strain", "Anticoagulation (DOAC or LMWH→warfarin)"],
        ["Submassive", "RV strain, stable BP", "Anticoagulation; consider catheter-directed if bleeding risk"],
        ["Massive", "Hypotension/shock", "Thrombolytics or embolectomy + anticoagulation"],
      ],
    },
    {
      caption: "Light criteria for exudate (any ONE positive)",
      headers: ["Criterion", "Threshold"],
      rows: [
        ["Pleural protein / serum protein", "> 0.5"],
        ["Pleural LDH / serum LDH", "> 0.6"],
        ["Pleural LDH", "> 2/3 upper limit of normal"],
      ],
    },
  ],
  visual: [
    "COPD exacerbation algorithm: bronchodilator → steroid → antibiotics → BiPAP if pH 7.25–35",
    "Wells score → D-dimer (low prob) vs CT-PA (intermediate-high) decision tree",
    "Asthma stepwise ladder: SABA → ICS → ICS/LABA → biologics",
    "Pleural effusion: transudate (treat cause) vs exudate (diagnose: pH, cytology, culture)",
    "Tension PTX: tracheal deviation away from affected side, JVD, hypotension — decompress immediately",
  ],
  misconceptions: [
    "High-flow O₂ to 100% SpO₂ in COPD — causes CO₂ retention and worsening hypercapnia",
    "Waiting for CXR in clinically obvious tension pneumothorax — decompress first",
    "Draining transudative effusion without treating CHF/cirrhosis — recurrence guaranteed",
    "Steroids as primary therapy for IPF/UIP — no benefit; antifibrotics preferred",
    "D-dimer when Wells is intermediate-high — low sensitivity in high pretest probability",
  ],
  pearls: [
    "BiPAP in COPD with pH 7.25–7.35 reduces intubation and mortality — board favorite",
    "Wells ≥2 → go straight to CT-PA; do not wait on D-dimer",
    "Parapneumonic pH <7.2 mandates drainage — not optional",
    "Tension PTX is clinical diagnosis — needle 2nd ICS midclavicular line",
    "OCP + pleuritic chest pain + tachycardia = PE until proven otherwise",
  ],
  summary: [
    "COPD exacerbation: bronchodilators + steroids ± antibiotics; BiPAP if pH 7.25–7.35",
    "PE: Wells + D-dimer (low risk) or CT-PA; massive PE → thrombolytics",
    "Asthma step-up therapy; status asthmaticus → continuous nebs + steroids + magnesium",
    "Light criteria distinguish exudate vs transudate; pH <7.2 parapneumonic needs tube",
    "Target SpO₂ 88–92% in COPD; tension PTX → immediate decompression",
  ],
});

export const GASTROENTEROLOGY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "GI and hepatology vignettes test acute bleeding algorithms, cirrhosis complications, pancreatitis severity, IBD differentiation, and hepatitis serology. Step 2 CK rewards knowing when to scope emergently, when to give octreotide and antibiotics in variceal bleed, and when MRCP is the next step over CT.",
  ],
  concepts: [
    "Upper GI bleed: resuscitate → PPI → scope within 24 h (12 h if unstable); variceal bleed adds octreotide + ceftriaxone + band ligation",
    "Lower GI bleed: colonoscopy after prep; angiography if brisk ongoing bleed",
    "Cirrhosis complications: ascites (SAAG ≥1.1 = portal HTN), SBP (PMN >250, treat before culture returns), hepatic encephalopathy (lactulose + rifaximin)",
    "HRS: albumin + midodrine/octreotide ± terlipressin; avoid nephrotoxic drugs",
    "Acute pancreatitis: aggressive IV fluids, pain control; ERCP if cholangitis or obstructing stone with rising bilirubin",
    "Ranson criteria and BISAP for pancreatitis severity; necrotizing pancreatitis — avoid early antibiotics unless infected",
    "IBD: Crohn (skip lesions, transmural, fistulae) vs UC (continuous, mucosal, bloody diarrhea)",
    "C diff: oral vancomycin or fidaxomicin; stop inciting antibiotic; do NOT use IV metronidazole or loperamide",
    "Hepatitis serology: HAV IgM (acute), HBsAg (active HBV), anti-HCV + HCV RNA (active HCV)",
    "NAFLD/NASH: weight loss first-line; avoid unnecessary liver biopsy if imaging diagnostic",
    "Acute cholecystitis: Murphy sign, US findings — cholecystectomy (early vs delayed based on severity)",
    "Appendicitis: clinical + CT/US; appendectomy; antibiotics if perforated",
  ],
  clinical: [
    "Cirrhosis with hematemesis, hypotension — resuscitate, octreotide, ceftriaxone, emergent EGD for band ligation",
    "Ascites tap shows PMN 400 — SBP; start ceftriaxone immediately, add albumin if Cr elevated",
    "Confused cirrhotic with asterixis — hepatic encephalopathy; lactulose to 2–3 soft stools/day, treat precipitant (GI bleed, infection, constipation)",
    "Acute pancreatitis, RUQ pain, lipase 1200 — IV fluids, pain control; MRCP/ERCP if cholangitis suspected",
    "Bloody diarrhea with continuous colon involvement on scope — UC; start mesalamine ± steroids",
    "Young patient with RLQ pain, fever, McBurney point tenderness — appendectomy; CT if atypical",
    "RUQ pain after fatty meal, positive Murphy sign, gallstones on US — acute cholecystitis; cholecystectomy",
    "Diarrhea on clindamycin, WBC 18K, C diff toxin+ — oral vancomycin; stop clindamycin",
    "Chronic HBV with HBsAg+, HBeAg+, high HBV DNA — antiviral therapy (tenofovir/entecavir)",
    "Iron deficiency anemia in 60-year-old man — upper and lower GI scope to exclude malignancy",
  ],
  tables: [
    {
      caption: "Crohn disease vs ulcerative colitis",
      headers: ["Feature", "Crohn", "Ulcerative colitis"],
      rows: [
        ["Distribution", "Skip lesions, any GI tract", "Continuous from rectum"],
        ["Depth", "Transmural", "Mucosal/submucosal"],
        ["Complications", "Fistulae, abscess, strictures", "Toxic megacolon, cancer risk"],
        ["Smoking", "Worsens disease", "Paradoxically protective"],
        ["Surgery", "Not curative", "Curative (colectomy)"],
      ],
    },
    {
      caption: "Variceal vs non-variceal upper GI bleed",
      headers: ["Step", "Variceal", "Non-variceal (PUD)"],
      rows: [
        ["Resuscitation", "PRBCs, access, type/cross", "Same"],
        ["Medical", "Octreotide + ceftriaxone + PPI", "PPI (high-dose IV)"],
        ["Endoscopy", "Band ligation emergently", "Hemostasis within 24 h"],
        ["Refractory", "TIPS", "Repeat endoscopy or surgery"],
      ],
    },
    {
      caption: "Ascites SAAG interpretation",
      headers: ["SAAG", "Cause", "Examples"],
      rows: [
        ["≥ 1.1", "Portal hypertension", "Cirrhosis, cardiac ascites, Budd-Chiari"],
        ["< 1.1", "Non-portal", "SBP, malignancy, TB, nephrotic"],
      ],
    },
  ],
  visual: [
    "Upper GI bleed pathway: ABC → PPI → scope timing → variceal vs ulcer management branch",
    "Cirrhosis complication pentagon: ascites, varices, SBP, HRS, encephalopathy",
    "Pancreatitis severity: Ranson/BISAP → ICU vs ward → ERCP indication tree",
    "IBD anatomic diagram: continuous UC from rectum vs skip Crohn lesions",
    "Hepatitis serology flowchart for HBV acute, chronic, and immune states",
  ],
  misconceptions: [
    "IV metronidazole for C diff — must use oral vancomycin or fidaxomicin for colonic delivery",
    "Loperamide in bloody infectious diarrhea — increases toxic megacolon risk in IBD",
    "Early prophylactic antibiotics in sterile necrotizing pancreatitis — only if infected necrosis suspected",
    "TIPS before band ligation as first-line for variceal bleed — endoscopy first when feasible",
    "Skipping colonoscopy in iron deficiency anemia in men and postmenopausal women — cancer until excluded",
  ],
  pearls: [
    "Variceal bleed triad: octreotide + ceftriaxone + band ligation — all three on board",
    "SBP: PMN >250 in ascites → treat empirically before culture returns",
    "Lactulose goal: 2–3 soft stools/day — not diarrhea to dehydration",
    "C diff first episode: oral vancomycin beats metronidazole in guidelines",
    "Iron deficiency in adult man = GI malignancy workup until proven otherwise",
  ],
  summary: [
    "Upper GI bleed: resuscitate, PPI, scope; varices add octreotide + ceftriaxone + banding",
    "Cirrhosis: SAAG, SBP treatment, encephalopathy with lactulose + treat precipitant",
    "Pancreatitis: fluids first; ERCP if cholangitis; avoid routine antibiotics in sterile necrosis",
    "Crohn vs UC: skip/transmural vs continuous/mucosal",
    "C diff: oral vancomycin; never IV metronidazole or loperamide",
  ],
});

export const HEMATOLOGY_ONCOLOGY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Hematology-oncology Step 2 CK items test anemia workup algorithms, coagulopathy patterns, leukemia/lymphoma presenting features, oncologic emergencies (TLS, spinal cord compression, hypercalcemia), and transfusion principles. Boards love the next lab to order, not exotic staging.",
  ],
  concepts: [
    "Microcytic anemia: iron studies (↓Fe, ↑TIBC, ↓ferritin) → GI blood loss workup in adults",
    "Macrocytic: B12/folate (B12 adds neuro + ↑MMA); reticulocyte index for hemolysis/blood loss",
    "Hemolytic anemia: ↑LDH, ↑indirect bili, ↑reticulocytes, ↓haptoglobin; schistocytes suggest MAHA/TTP",
    "TTP pentad: fever, thrombocytopenia, MAHA, neuro, renal — ADAMTS13 deficiency; plasmapheresis emergently",
    "ITP: isolated thrombocytopenia, no schistocytes; treat if plt <30K or bleeding — steroids, IVIG",
    "DIC: widespread microthrombi + consumptive coagulopathy — treat underlying cause; blood products for bleeding",
    "VTE prophylaxis and treatment: LMWH/DOAC; cancer-associated thrombosis often extended anticoagulation",
    "AML: Auer rods, myeloperoxidase+; ATRA for APL (t(15;17)) before chemotherapy — prevents DIC death",
    "CLL: smudge cells, older adult, lymphocytosis; watch and wait if early",
    "Hodgkin: Reed-Sternberg cells, bimodal age, curable; ABVD regimen",
    "Tumor lysis syndrome: hydrate, allopurinol/rasburicase, monitor K/Ca/phos — before chemo in bulky disease",
    "Hypercalcemia of malignancy: IV fluids, bisphosphonate, calcitonin if severe",
  ],
  clinical: [
    "Fatigued 65-year-old man, Hgb 9, MCV 72, ferritin 8 — iron deficiency; scope upper and lower GI",
    "Anemia + neurologic symptoms + ↑MMA — B12 deficiency; check intrinsic factor antibodies",
    "Thrombocytopenia, schistocytes, fever, confusion — TTP; start plasmapheresis before ADAMTS13 returns",
    "Isolated plt 15K, no schistocytes, otherwise well — ITP; steroids if symptomatic or plt <30K",
    "Sepsis with bleeding, prolonged PT/PTT, low fibrinogen, ↑D-dimer — DIC; treat sepsis, products as needed",
    "New AML with t(15;17), DIC labs — ATRA immediately before standard chemo",
    "Young man with mediastinal mass, cough supine, SVC syndrome — lymphoma; biopsy before steroids if possible",
    "Cancer patient starting chemo, bulky disease, high uric acid — rasburicase or allopurinol + aggressive hydration",
    "Back pain, leg weakness, bladder dysfunction in cancer patient — spinal cord compression; dexamethasone + MRI + radiation",
    "Ca 14, confused, dehydrated cancer patient — IV NS + zoledronic acid",
  ],
  tables: [
    {
      caption: "Anemia workup framework",
      headers: ["MCV", "First labs", "Common causes"],
      rows: [
        ["Microcytic", "Iron studies, retic count", "Iron deficiency, thalassemia, ACD"],
        ["Normocytic", "Reticulocyte index, renal/hepatic", "Blood loss, hemolysis, CKD, mixed"],
        ["Macrocytic", "B12, folate, MMA, retic count", "B12/folate deficiency, MDS, drugs"],
      ],
    },
    {
      caption: "TTP vs ITP vs DIC",
      headers: ["Feature", "TTP", "ITP", "DIC"],
      rows: [
        ["Schistocytes", "Yes (MAHA)", "No", "Often yes"],
        ["Coagulopathy", "Normal PT/PTT", "Normal", "Prolonged PT/PTT, low fibrinogen"],
        ["Treatment", "Plasmapheresis", "Steroids/IVIG", "Treat cause + products"],
        ["Urgency", "Emergent", "If bleeding/severe plt drop", "Emergent if bleeding"],
      ],
    },
    {
      caption: "Oncologic emergencies",
      headers: ["Emergency", "Presentation", "First step"],
      rows: [
        ["TLS", "↑K, ↑uric acid, ↓Ca pre/post chemo", "Hydration + rasburicase/allopurinol"],
        ["Spinal cord compression", "Back pain, weakness, bladder", "Dexamethasone + MRI + RT"],
        ["Hypercalcemia", "Confusion, polyuria, constipation", "IV fluids + bisphosphonate"],
        ["SVC syndrome", "Face/arm swelling, dyspnea", "Treat malignancy; stent if severe"],
      ],
    },
  ],
  visual: [
    "Anemia algorithm: MCV → iron studies vs B12/folate vs reticulocyte index",
    "Schistocyte on smear → MAHA branch: TTP vs DIC vs HUS",
    "APL pathway: t(15;17) → ATRA before chemo prevents DIC catastrophe",
    "TLS prevention: bulky/high-turnover tumors → hydrate + uric acid lowering before chemo",
    "Spinal cord compression: back pain red flags in cancer → MRI spine emergently",
  ],
  misconceptions: [
    "Platelet transfusion in TTP — contraindicated unless life-threatening bleed; worsens thrombosis",
    "Starting chemotherapy in APL without ATRA — DIC mortality is preventable",
    "Steroids before biopsy in suspected lymphoma — can obscure diagnosis; biopsy first when feasible",
    "Oral iron with active GI bleed without source control — replete but still scope",
    "Assuming all thrombocytopenia is ITP — always check smear for schistocytes",
  ],
  pearls: [
    "TTP: plasmapheresis is emergent — do not wait for ADAMTS13 result",
    "APL (t(15;17)): ATRA before chemo — board classic",
    "Iron deficiency in adult man = GI cancer workup until excluded",
    "B12 deficiency: neurologic symptoms + ↑MMA distinguish from folate",
    "ITP: isolated thrombocytopenia, normal smear otherwise, no schistocytes",
  ],
  summary: [
    "Anemia: MCV-driven workup — iron studies, B12/MMA, reticulocyte index",
    "TTP = pentad + plasmapheresis emergently; ITP = isolated plt drop, steroids/IVIG",
    "APL needs ATRA before chemo; DIC treat underlying cause",
    "Oncologic emergencies: TLS (hydrate + rasburicase), cord compression (steroids + MRI + RT)",
    "Iron deficiency in adults warrants GI malignancy evaluation",
  ],
});

export const RHEUMATOLOGY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Rheumatology vignettes test autoimmune pattern recognition — joint distribution, autoantibodies, systemic features, and first-line management. Step 2 CK focuses on RA vs OA, SLE flares, gout vs pseudogout crystals, vasculitis syndromes, and when to start DMARDs vs steroids.",
  ],
  concepts: [
    "RA: symmetric polyarthritis, morning stiffness >1 h, RF and anti-CCP+; start methotrexate early ± short steroid bridge",
    "OA: asymmetric, worse with use, bony enlargement, no systemic features; acetaminophen/NSAIDs, weight loss",
    "SLE: malar rash, arthritis, serositis, anti-dsDNA+, low C3/C4; hydroxychloroquine for all; steroids for flares",
    "Lupus nephritis: proteinuria, active sediment, anti-dsDNA+ — biopsy for class; mycophenolate or cyclophosphamide",
    "Gout: monosodium urate needles negatively birefringent; acute = NSAIDs/colchicine/steroids; urate-lowering after acute resolved",
    "Pseudogout: CPPD rhomboid positively birefringent; associated with hyperparathyroidism, hemochromatosis",
    "Giant cell arteritis: headache, jaw claudication, elevated ESR in elderly — start high-dose prednisone BEFORE biopsy",
    "Polymyalgia rheumatica: bilateral shoulder/hip girdle pain, elevated ESR — low-dose prednisone; screen for GCA",
    "ANCA vasculitis: c-ANCA/PR3 (GPA), p-ANCA/MPO (MPA); RPGN with hematuria — cyclophosphamide + steroids",
    "Reactive arthritis: can't see, can't pee, can't climb a tree — post-infectious triad",
    "Polymyositis vs dermatomyositis: proximal weakness; dermatomyositis adds heliotrope rash, shawl sign — cancer screen",
    "Fibromyalgia: widespread pain, normal exam/labs, no joint damage — exercise, SNRIs, avoid chronic opioids",
  ],
  clinical: [
    "28-year-old woman, symmetric hand/wrist swelling, morning stiffness 2 hours, anti-CCP+ — RA; start methotrexate",
    "Elderly with unilateral knee pain worse with walking, crepitus, no morning stiffness — OA; weight loss + NSAIDs",
    "Young woman with malar rash, oral ulcers, arthritis, anti-dsDNA+, low C3 — SLE flare; hydroxychloroquine + steroid",
    "SLE with nephrotic-range proteinuria, active urine sediment — lupus nephritis; renal biopsy guides therapy",
    "First MTP hot swollen joint, urate crystals negative birefringent — acute gout; NSAIDs/colchicine; defer allopurinol start",
    "Knee effusion in elderly, rhomboid CPPD crystals positive birefringent — pseudogout",
    "72-year-old new headache, jaw claudication, ESR 90 — GCA; prednisone 60 mg NOW, schedule temporal artery biopsy within days",
    "Bilateral shoulder/hip girdle stiffness, ESR 80, age 70 — PMR; prednisone 15–20 mg; ask about visual symptoms (GCA)",
    "Hemoptysis, hematuria, c-ANCA+ — GPA; cyclophosphamide + prednisone",
    "Proximal weakness, heliotrope rash, Gottron papules — dermatomyositis; cancer screening + immunosuppression",
  ],
  tables: [
    {
      caption: "RA vs OA",
      headers: ["Feature", "RA", "OA"],
      rows: [
        ["Distribution", "Symmetric small joints", "Weight-bearing, asymmetric"],
        ["Stiffness", ">1 hour morning", "Brief, worse with use"],
        ["Systemic", "Fatigue, fevers possible", "None"],
        ["Labs", "RF, anti-CCP, ESR/CRP", "Normal or mild ESR"],
        ["X-ray", "Erosions, juxta-articular osteopenia", "Osteophytes, joint space loss"],
      ],
    },
    {
      caption: "Crystal arthropathies",
      headers: ["Crystal", "Shape", "Birefringence", "Classic joint"],
      rows: [
        ["Monosodium urate (gout)", "Needles", "Negative", "1st MTP (podagra)"],
        ["CPPD (pseudogout)", "Rhomboid", "Positive", "Knee, wrist"],
      ],
    },
    {
      caption: "ANCA-associated vasculitis",
      headers: ["Syndrome", "ANCA", "Target antigen", "Key features"],
      rows: [
        ["GPA (Wegener)", "c-ANCA", "PR3", "Upper/lower respiratory + kidney"],
        ["MPA", "p-ANCA", "MPO", "RPGN, pulmonary hemorrhage"],
        ["EGPA", "p-ANCA (40%)", "MPO", "Asthma, eosinophilia, neuropathy"],
      ],
    },
  ],
  visual: [
    "Joint distribution maps: RA symmetric hands/wrists vs OA knees/hips/DIPs (Heberden)",
    "Crystal birefringence under polarized light: gout negative vs pseudogout positive",
    "GCA timeline: treat with steroids FIRST → biopsy within 1–2 weeks still valid",
    "SLE organ involvement web: skin, joints, kidneys, CNS, hematologic",
    "ANCA vasculitis: upper airway + lung + kidney trifecta for GPA",
  ],
  misconceptions: [
    "Starting allopurinol during acute gout flare — wait until attack resolves",
    "Delaying steroids in suspected GCA to get biopsy first — risk irreversible blindness",
    "NSAIDs alone for RA without DMARD — methotrexate prevents joint destruction",
    "Assuming negative RF excludes RA — anti-CCP more specific; seronegative RA exists",
    "Fibromyalgia inflammatory markers elevated — diagnosis of exclusion with normal labs",
  ],
  pearls: [
    "GCA: treat with high-dose prednisone BEFORE biopsy — vision saves",
    "Anti-CCP more specific for RA than RF — both can guide early methotrexate",
    "Gout crystals: negatively birefringent needles; pseudogout positively birefringent rhomboids",
    "Hydroxychloroquine for all SLE patients — reduces flares and mortality",
    "PMR and GCA overlap — any visual symptoms in PMR patient = treat as GCA",
  ],
  summary: [
    "RA: symmetric polyarthritis, anti-CCP, early methotrexate; OA: use-related, no systemic features",
    "SLE: anti-dsDNA, low complement, hydroxychloroquine; nephritis needs biopsy",
    "Gout vs pseudogout: crystal birefringence; defer urate-lowering in acute gout",
    "GCA: prednisone before biopsy; PMR responds to low-dose prednisone",
    "ANCA vasculitis: GPA (c-ANCA/PR3), MPA (p-ANCA/MPO) + cyclophosphamide/steroids",
  ],
});

export const OBSTETRICS_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "OB/GYN on Step 2 CK tests prenatal screening, hypertensive disorders of pregnancy, labor complications, postpartum emergencies, and gynecologic oncology red flags. Boards emphasize timing — when to deliver, when to give magnesium for neuroprotection, and when stat cesarean is required.",
  ],
  concepts: [
    "Prenatal labs: blood type/Rh, antibody screen, rubella immunity, HIV/HBV/HCV, GBS culture 36–37 weeks",
    "Rh negative: RhoGAM at 28 weeks and within 72 h of delivery if Rh+ infant; also after bleeding/trauma",
    "Preeclampsia: BP ≥140/90 after 20 weeks + proteinuria or end-organ dysfunction; severe features → deliver",
    "Eclampsia: magnesium sulfate for seizure prophylaxis/treatment (4–6 g load, 2 g/h maintenance)",
    "HELLP: hemolysis, elevated LFTs, low platelets — deliver regardless of gestational age if unstable",
    "Placenta previa: painless bleeding; no digital exam; cesarean delivery",
    "Abruptio placentae: painful bleeding, tender uterus, fetal distress — emergent delivery",
    "Shoulder dystocia: McRoberts, suprapubic pressure, episiotomy; avoid excessive traction",
    "Postpartum hemorrhage: uterine massage, oxytocin, methylergonovine, carboprost; consider Bakri balloon",
    "Ectopic pregnancy: methotrexate if stable, unruptured, low hCG; surgery if unstable",
    "Gestational diabetes: 24–28 week glucose screen; insulin if diet fails",
    "Cervical cancer screening: Pap 21–29 q3y; 30–65 HPV co-testing q5y or Pap q3y",
  ],
  clinical: [
    "32 weeks, BP 165/105, proteinuria 2+, headache — severe preeclampsia; magnesium + betamethasone + deliver if unstable",
    "Seizing pregnant patient at term — eclampsia; magnesium sulfate, stabilize, deliver",
    "Third trimester painless bright red bleeding, placenta over os on US — previa; cesarean, no digital exam",
    "Third trimester painful bleeding, rigid uterus, fetal bradycardia — abruptio; emergent cesarean",
    "Positive pregnancy test, adnexal mass, empty uterus — ectopic; methotrexate if stable criteria met",
    "Rh-negative mother delivers Rh-positive infant — RhoGAM within 72 hours",
    "Postpartum heavy bleeding, boggy uterus — uterine atony; massage + oxytocin + methylergonovine",
    "28 weeks, 1-hour glucose 165 — failed screen; proceed to 3-hour GTT for GDM diagnosis",
    "Fever, uterine tenderness, foul lochia postpartum — endometritis; clindamycin + gentamicin",
    "Postmenopausal bleeding — endometrial biopsy to exclude endometrial cancer",
  ],
  tables: [
    {
      caption: "Hypertensive disorders of pregnancy",
      headers: ["Condition", "Timing", "Key features", "Management"],
      rows: [
        ["Gestational HTN", "≥20 weeks", "BP ↑, no proteinuria", "Monitor, deliver 37–38 weeks"],
        ["Preeclampsia", "≥20 weeks", "BP + proteinuria/end-organ", "Deliver if term or severe features"],
        ["Severe preeclampsia", "Any", "BP ≥160/110, symptoms, labs", "Magnesium + deliver"],
        ["Eclampsia", "Any", "Seizures", "Magnesium + deliver"],
        ["HELLP", "Often ≥27 weeks", "Hemolysis, ↑LFT, ↓plt", "Deliver"],
      ],
    },
    {
      caption: "Third-trimester bleeding",
      headers: ["Cause", "Pain", "Exam", "Management"],
      rows: [
        ["Placenta previa", "Painless", "No digital exam", "Cesarean"],
        ["Abruptio", "Painful", "Rigid, tender uterus", "Emergent delivery"],
        ["Uterine rupture", "Severe pain", "Loss of fetal station", "Emergent laparotomy"],
      ],
    },
    {
      caption: "Magnesium sulfate indications",
      headers: ["Indication", "Loading", "Maintenance", "Toxicity antidote"],
      rows: [
        ["Eclampsia/severe preeclampsia", "4–6 g IV", "2 g/h", "Calcium gluconate"],
        ["Neuroprotection <32 weeks", "4–6 g IV", "2 g/h", "Monitor reflexes/RR"],
      ],
    },
  ],
  visual: [
    "Preeclampsia severity ladder: mild → severe features → eclampsia → HELLP → delivery",
    "Third-trimester bleeding algorithm: painless (previa) vs painful (abruptio)",
    "Ectopic pregnancy decision: stable + criteria → methotrexate vs unstable → surgery",
    "PPH four T's: tone, trauma, tissue, thrombin — uterine atony most common",
    "Prenatal visit timeline: dating US, anatomy scan, GBS, glucose screen",
  ],
  misconceptions: [
    "Digital exam with suspected previa — can provoke hemorrhage; ultrasound first",
    "Delaying delivery in HELLP for steroid maturity — maternal risk dominates",
    "Phenytin for eclampsia — magnesium is first-line",
    "Assuming all postpartum bleeding is atony — retain products and lacerations also common",
    "Skipping endometrial biopsy in postmenopausal bleeding — cancer until excluded",
  ],
  pearls: [
    "Magnesium for eclampsia AND neuroprotection <32 weeks — know loading dose",
    "Previa = painless; abruptio = painful — board dichotomy",
    "RhoGAM at 28 weeks AND postpartum if baby Rh+ — both required",
    "Severe preeclampsia: BP ≥160/110 OR symptoms OR labs — any one qualifies",
    "Postpartum endometritis: clindamycin + gentamicin — covers polymicrobial flora",
  ],
  summary: [
    "Preeclampsia/eclampsia: magnesium + deliver; HELLP = deliver regardless of GA if unstable",
    "Previa painless, abruptio painful — no digital exam in previa",
    "Ectopic: methotrexate if stable criteria; surgery if ruptured/unstable",
    "PPH: uterine atony first — massage + oxytocin + ergot alkaloids",
    "Rh-negative: RhoGAM prophylaxis; postmenopausal bleeding needs endometrial sampling",
  ],
});

export const PEDIATRICS_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Pediatrics on Step 2 CK tests developmental milestones, common childhood infections, congenital heart disease, vaccination schedules, and child abuse red flags. Vignettes often hinge on age-specific normal variants vs pathology and when the febrile infant requires full sepsis workup.",
  ],
  concepts: [
    "Developmental milestones: 2 mo social smile, 4 mo rolls, 6 mo sits, 9 mo crawls, 12 mo walks, 15 mo words, 18 mo runs, 2 yr 2-word phrases",
    "Febrile infant <28 days: full sepsis workup (blood, urine, CSF) + empiric ampicillin + ceftriaxone/cefotaxime + admission",
    "Febrile infant 29–60 days: risk stratify ( Rochester/Philadelphia); low risk may outpatient; high risk admit + treat",
    "Kawasaki: fever ≥5 days + conjunctivitis, strawberry tongue, lymphadenopathy, rash, extremity changes — IVIG + aspirin; echo",
    "Croup: barky cough, stridor, stepladder sign — dexamethasone; racemic epinephrine if moderate-severe",
    "Bronchiolitis: RSV, wheezing infant — supportive care; no bronchodilators/steroids routinely",
    "Acute otitis media: amoxicillin first-line; high-dose if recent abx or severe",
    "Vaccine schedule highlights: HepB birth, DTaP/IPV/Hib/pneumococcal series, MMR/Varicella 12–15 mo, HPV 11–12",
    "Congenital heart disease: VSD most common; cyanotic — TOF, TGA, truncus; ductal-dependent lesions need PGE1",
    "Child abuse red flags: inconsistent history, delayed presentation, patterned bruises, posterior rib fractures, retinal hemorrhages",
    "Failure to thrive: caloric intake vs malabsorption vs nonorganic — detailed feeding history",
    "Lead poisoning: pica, developmental delay, basophilic stippling — chelation if level very high",
  ],
  clinical: [
    "14-day-old fever 38.5°C — full sepsis workup, admit, ampicillin + ceftriaxone regardless of appearance",
    "3-year-old barky cough, stridor at rest, hypoxia — croup; dexamethasone + racemic epinephrine + observe",
    "6-month-old wheezing, RSV+, mild distress — bronchiolitis; supportive care, no routine albuterol",
    "Fever 6 days, conjunctival injection, cracked lips, cervical LAD — Kawasaki; IVIG + high-dose aspirin + echo",
    "Cyanotic newborn, single loud S2, egg-on-string heart — TGA; PGE1 to keep ductus open before surgery",
    "Toddler not walking at 18 months — developmental delay workup; check hip exam, neuromuscular",
    "Retinal hemorrhages, subdural hematomas, inconsistent burn story — nonaccidental trauma; report + skeletal survey",
    "Otitis media in 2-year-old with fever — high-dose amoxicillin 90 mg/kg/day",
    "Unimmunized child with parotid swelling — mumps; supportive; report to public health",
    "Pale toddler, microcytic anemia, pica — iron deficiency; oral iron + dietary counseling",
  ],
  tables: [
    {
      caption: "Key developmental milestones",
      headers: ["Age", "Gross motor", "Fine/social/language"],
      rows: [
        ["2 months", "Lifts head prone", "Social smile"],
        ["6 months", "Sits unsupported", "Babbles, reaches"],
        ["12 months", "Walks", "1–2 words, pincer grasp"],
        ["18 months", "Runs", "10–25 words, spoon use"],
        ["2 years", "Up/down stairs", "2-word phrases, follows 2-step commands"],
        ["3 years", "Tricycle", "3-word sentences, toilet trained"],
      ],
    },
    {
      caption: "Febrile infant management by age",
      headers: ["Age", "Approach"],
      rows: [
        ["0–28 days", "Full sepsis workup + admit + empiric abx always"],
        ["29–60 days", "Risk stratify; admit if ill-appearing or high risk"],
        ["61–90 days", "Selective workup based on appearance and fever height"],
        [">3 months", "Source-based evaluation; UTI common in girls"],
      ],
    },
    {
      caption: "Cyanotic vs acyanotic CHD",
      headers: ["Type", "Examples", "Urgency"],
      rows: [
        ["Cyanotic", "TOF, TGA, truncus", "PGE1 if ductal-dependent"],
        ["Acyanotic", "VSD, ASD, PDA", "Monitor; CHF if large shunt"],
        ["Critical", "Coarctation, HLHS, critical AS", "PGE1 + prostaglandin-dependent lesion"],
      ],
    },
  ],
  visual: [
    "Developmental milestone timeline: 2-4-6-9-12-15-18-24 months",
    "Febrile infant algorithm by age: 0-28d always admit vs 29-60d risk stratify",
    "Kawasaki criteria pentad + fever ≥5 days → IVIG pathway",
    "Croup severity: barky cough → stridor at rest → hypoxia → racemic epinephrine",
    "Child abuse injury patterns: posterior ribs, retinal hemorrhages, patterned bruises",
  ],
  misconceptions: [
    "Routine bronchodilators in bronchiolitis — no mortality benefit; supportive care",
    "Outpatient management of febrile neonate <28 days — always admit and treat",
    "Low-dose amoxicillin for AOM — use 90 mg/kg/day high-dose standard",
    "Missing Kawasaki if not all criteria day 5 — incomplete Kawasaki exists; echo helps",
    "Attributing patterned bruises to 'easy bruising' — abuse until proven otherwise",
  ],
  pearls: [
    "Neonate with fever = full sepsis workup + admit — no exceptions on boards",
    "Kawasaki: IVIG within 10 days of fever reduces coronary aneurysm risk",
    "Croup: single dose dexamethasone; racemic epi if stridor at rest",
    "TGA: parallel circulations — PGE1 keeps ductus open until septostomy/surgery",
    "Posterior rib fractures in infant = nonaccidental trauma until proven otherwise",
  ],
  summary: [
    "Know milestone timeline: 6 mo sit, 12 mo walk, 18 mo run, 2 yr 2-word phrases",
    "Febrile infant <28 days: full workup + admit + empiric antibiotics",
    "Kawasaki: IVIG + aspirin + echo; croup: dexamethasone ± racemic epinephrine",
    "Bronchiolitis supportive only; AOM high-dose amoxicillin",
    "Child abuse red flags: inconsistent history, posterior rib fractures, retinal hemorrhages",
  ],
});

export const PSYCHIATRY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Psychiatry on Step 2 CK tests diagnosis criteria, first-line pharmacotherapy, dangerous medication interactions, substance withdrawal timelines, and suicide risk assessment. Boards emphasize medical clearance before psychiatric admission and when to hospitalize involuntarily.",
  ],
  concepts: [
    "Major depression: ≥5 symptoms × 2 weeks including depressed mood or anhedonia; SSRI first-line (sertraline, escitalopram)",
    "Bipolar I: mania ≥1 week; mood stabilizer (lithium, valproate) ± atypical antipsychotic; avoid antidepressant monotherapy",
    "Schizophrenia: ≥2 symptoms × 1 month (delusions, hallucinations, disorganized speech/behavior, negative symptoms)",
    "First-episode psychosis: rule out substance/medical (TSH, B12, UA, tox screen, CT if focal)",
    "Generalized anxiety: SSRI/SNRI first-line; buspirone; benzodiazepines short-term only",
    "Panic disorder: SSRI + CBT; avoid benzo monotherapy long-term",
    "PTSD: trauma-focused CBT + SSRI/SNRI (sertraline, paroxetine, venlafaxine)",
    "Alcohol withdrawal: CIWA protocol; benzodiazepines; thiamine before glucose; Wernicke prevention",
    "DTs: hallucinations, autonomic instability 48–96 h post last drink — ICU, high-dose benzos",
    "Opioid withdrawal: supportive; buprenorphine/methadone for OUD; naloxone for overdose",
    "Serotonin syndrome: agitation, hyperreflexia, clonus, hyperthermia — stop serotonergic agents, cyproheptadine",
    "Neuroleptic malignant syndrome: rigidity, fever, ↑CK after antipsychotic — stop drug, dantrolene/bromocriptine, ICU",
    "Suicide risk: plan, means, intent, prior attempts — hospitalize if high risk; safety plan if low-moderate with support",
    "Involuntary hold: danger to self, danger to others, grave disability — varies by state statute in vignette",
  ],
  clinical: [
    "Depressed patient with insomnia, guilt, passive SI without plan — SSRI + close follow-up; safety assessment documented",
    "Manic patient, decreased sleep, grandiosity, spending sprees — valproate or lithium + antipsychotic; do NOT start SSRI alone",
    "Auditory hallucinations commanding violence, disorganized thought — schizophrenia; start antipsychotic after medical workup",
    "Patient on fluoxetine + tramadol, agitated, clonus, hyperthermia — serotonin syndrome; stop agents, supportive + cyproheptadine",
    "Post-antipsychotic rigidity, fever 40°C, CK 8000 — NMS; stop antipsychotic, ICU, dantrolene",
    "Chronic alcoholic admitted, confused, ataxic — Wernicke; thiamine IV before glucose",
    "Alcohol withdrawal day 2, tremor, tachycardia, BP 180/100 — CIWA-driven benzodiazepines",
    "Found down, pinpoint pupils, respiratory depression — opioid overdose; naloxone",
    "Combat veteran, nightmares, hypervigilance, avoidance — PTSD; trauma-focused therapy + SSRI",
    "Patient with gun at home, specific suicide plan — involuntary hospitalization; remove means",
  ],
  tables: [
    {
      caption: "First-line psychopharmacotherapy",
      headers: ["Disorder", "First-line", "Avoid/trap"],
      rows: [
        ["Major depression", "SSRI (sertraline, escitalopram)", "Benzo monotherapy long-term"],
        ["Bipolar mania", "Lithium or valproate + antipsychotic", "Antidepressant monotherapy"],
        ["Schizophrenia", "Atypical antipsychotic (risperidone, olanzapine)", "Two antipsychotics without reason"],
        ["GAD", "SSRI/SNRI, buspirone", "Chronic benzodiazepines"],
        ["PTSD", "Trauma CBT + SSRI/SNRI", "Benzodiazepines (worse outcomes)"],
      ],
    },
    {
      caption: "Serotonin syndrome vs NMS",
      headers: ["Feature", "Serotonin syndrome", "NMS"],
      rows: [
        ["Trigger", "Serotonergic drugs", "Antipsychotics"],
        ["Reflexes", "Hyperreflexia, clonus", "Lead-pipe rigidity"],
        ["Onset", "Hours", "Days"],
        ["Treatment", "Stop agents, cyproheptadine", "Stop antipsychotic, dantrolene"],
      ],
    },
    {
      caption: "Substance withdrawal timeline",
      headers: ["Substance", "Peak", "Danger", "Treatment"],
      rows: [
        ["Alcohol", "24–72 h (DTs 48–96 h)", "Seizures, DTs", "Benzodiazepines, thiamine"],
        ["Benzodiazepines", "Days", "Seizures", "Long-acting benzo taper"],
        ["Opioids", "48–72 h", "Uncomfortable, not lethal", "Supportive, buprenorphine for OUD"],
      ],
    },
  ],
  visual: [
    "Depression diagnosis: ≥5 SIGECAPS × 2 weeks with mood or anhedonia required",
    "Bipolar treatment pyramid: mood stabilizer base, antipsychotic for mania, avoid solo antidepressant",
    "Suicide risk assessment: ideation → plan → means → intent → hospitalization decision",
    "Alcohol withdrawal timeline: tremor → seizures → DTs peak 48–96 h",
    "Serotonin syndrome vs NMS: clonus/hyperreflexia vs rigidity/bradykinesia",
  ],
  misconceptions: [
    "Antidepressant monotherapy in bipolar depression — triggers mania",
    "Benzodiazepines as PTSD first-line — worsen outcomes; SSRIs + trauma therapy preferred",
    "Glucose before thiamine in alcoholic — precipitates Wernicke",
    "Missing medical workup in first-episode psychosis — hyperthyroid, B12, substance-induced",
    "Discharging high-risk suicide with plan and means — hospitalize",
  ],
  pearls: [
    "Bipolar: mood stabilizer before antidepressant — always",
    "Serotonin syndrome: clonus and hyperreflexia distinguish from NMS rigidity",
    "Thiamine before glucose in alcoholics — Wernicke prevention",
    "Opioid overdose: naloxone; short half-life — observe for re-sedation",
    "Involuntary hold: danger to self, others, or grave disability",
  ],
  summary: [
    "Depression: SSRI first-line; assess suicide risk (plan, means, intent)",
    "Bipolar mania: mood stabilizer + antipsychotic; never antidepressant alone",
    "Schizophrenia: atypical antipsychotic after medical/substance ruled out",
    "Serotonin syndrome vs NMS: clonus vs rigidity; different triggers and treatment",
    "Alcohol withdrawal: benzos + thiamine; DTs at 48–96 h",
  ],
});

export const EMERGENCY_TOXICOLOGY_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Emergency medicine and toxicology items test ABC stabilization, toxidrome recognition, antidote pairing, and trauma priorities (ATLS). Step 2 CK loves acetaminophen nomogram, tricyclic sodium bicarbonate, beta-blocker/calcium channel blocker overdose, and carbon monoxide poisoning.",
  ],
  concepts: [
    "ATLS: Airway (c-spine if trauma) → Breathing → Circulation → Disability → Exposure",
    "Tension pneumothorax: decompress before CXR; massive hemothorax: chest tube + blood products",
    "Acetaminophen overdose: Rumack-Matthew nomogram; NAC within 8 h ideal; start NAC if level above line or unknown time with hepatic risk",
    "TCA overdose: QRS widening, anticholinergic signs — sodium bicarbonate for QRS >100 ms",
    "Opioid: miosis, respiratory depression — naloxone; re-dose for long-acting agents",
    "Benzodiazepine: flumazenil generally avoided (seizure risk in chronic use/polypharmacy)",
    "Salicylate: respiratory alkalosis + metabolic acidosis, tinnitus — alkalinize urine, hemodialysis if severe",
    "Ethylene glycol/methanol: osmolar gap, anion gap — fomepizole or ethanol + dialysis",
    "Carbon monoxide: cherry red skin (unreliable), carboxyhemoglobin — 100% O₂, hyperbaric if severe/neuro",
    "Organophosphate: DUMBBELSS cholinergic crisis — atropine + pralidoxime",
    "Beta-blocker overdose: glucagon first-line; high-dose insulin for calcium channel blocker",
    "Cyanide: smoke inhalation, sodium nitroprusside — hydroxocobalamin or nitrite/thiosulfate",
    "Heat stroke: core temp >40°C + CNS dysfunction — rapid cooling, ICU",
  ],
  clinical: [
    "Suicide attempt, empty Tylenol bottle, 4 hours ago — acetaminophen level + start NAC if above nomogram",
    "Overdose, wide QRS 120, dry skin, urinary retention — TCA; sodium bicarbonate bolus",
    "Found unresponsive, pinpoint pupils, RR 6 — naloxone; support ventilation",
    "Acidotic, tinnitus, mixed respiratory alkalosis/metabolic acidosis — salicylate toxicity; alkalinize, consider dialysis",
    "Drunk appearance, osmolar gap 30, calcium oxalate crystals — ethylene glycol; fomepizole + dialysis",
    "House fire, confusion, COHb 25% — 100% O₂; hyperbaric if pregnancy, neuro symptoms, or COHb >25%",
    "Farmer with SLUDGE symptoms, bradycardia — organophosphate; atropine until secretions dry + pralidoxime",
    "Propranolol overdose, HR 35, hypotension — glucagon; calcium if CCB co-ingestion",
    "Trauma, BP 80/50, distended neck veins, muffled heart sounds — tamponade; echo + pericardiocentesis",
    "Marathon runner collapse, temp 41°C, altered — heat stroke; ice water immersion",
  ],
  tables: [
    {
      caption: "High-yield antidotes",
      headers: ["Toxin", "Antidote", "Key clue"],
      rows: [
        ["Acetaminophen", "N-acetylcysteine", "Rumack nomogram, AST rise late"],
        ["TCA", "Sodium bicarbonate", "QRS >100 ms, anticholinergic"],
        ["Opioid", "Naloxone", "Miosis, respiratory depression"],
        ["Organophosphate", "Atropine + pralidoxime", "DUMBBELSS, bradycardia"],
        ["Beta-blocker", "Glucagon", "Bradycardia, hypoglycemia"],
        ["CCB", "High-dose insulin", "Refractory hypotension despite fluids"],
        ["Cyanide", "Hydroxocobalamin", "Smoke inhalation, acidosis"],
        ["Methanol/ethylene glycol", "Fomepizole", "Osmolar gap + anion gap"],
      ],
    },
    {
      caption: "Toxidrome patterns",
      headers: ["Toxidrome", "Vitals", "Pupils", "Skin", "Examples"],
      rows: [
        ["Cholinergic", "Bradycardia", "Miotic", "Diaphoretic", "Organophosphate, nerve agents"],
        ["Anticholinergic", "Tachycardia", "Mydriatic", "Dry, flushed", "TCA, antihistamines, atropine"],
        ["Sympathomimetic", "Tachycardia, HTN", "Mydriatic", "Diaphoretic", "Cocaine, amphetamines"],
        ["Opioid", "Bradypnea", "Miotic", "Normal", "Heroin, fentanyl"],
      ],
    },
    {
      caption: "ATLS primary survey",
      headers: ["Step", "Action", "Life threat"],
      rows: [
        ["A", "Airway + c-spine control", "Obstruction, facial trauma"],
        ["B", "Breathing + ventilation", "Tension PTX, flail chest"],
        ["C", "Circulation + hemorrhage control", "Hemorrhagic shock"],
        ["D", "Disability (GCS)", "TBI, spinal injury"],
        ["E", "Exposure + temperature", "Hypothermia, occult injury"],
      ],
    },
  ],
  visual: [
    "Acetaminophen Rumack-Matthew nomogram: treat if level above line at given hours",
    "TCA ECG: QRS widening → sodium bicarbonate until QRS narrows",
    "Toxidrome comparison grid: pupils + skin + vitals pattern recognition",
    "ATLS primary survey linear sequence — do not skip order",
    "Osmolar gap + anion gap Venn for toxic alcohols",
  ],
  misconceptions: [
    "Waiting for acetaminophen level at 4 h when taken at unknown time — start NAC if suspicion high",
    "Flumazenil routinely in benzo overdose — seizure risk with chronic use",
    "Normal gap-acidosis excludes toxic alcohol — calculate osmolar gap",
    "Cherry-red skin required for CO diagnosis — treat on exposure + symptoms",
    "Atropine alone in organophosphate without pralidoxime — nicotinic paralysis persists",
  ],
  pearls: [
    "TCA: bicarbonate for QRS >100 ms — most specific tox ECG finding",
    "Acetaminophen: NAC within 8 h prevents hepatotoxicity — do not wait for symptoms",
    "Glucagon for beta-blocker overdose; high-dose insulin for calcium channel blocker",
    "CO poisoning: pulse oximetry unreliable — check carboxyhemoglobin",
    "Organophosphate: atropine until drying + pralidoxime for nicotinic effects if early",
  ],
  summary: [
    "ATLS primary survey: airway → breathing → circulation → disability → exposure",
    "Acetaminophen nomogram + NAC; TCA → sodium bicarbonate for wide QRS",
    "Toxidromes: cholinergic (SLUDGE) vs anticholinergic (dry, mad as a hatter)",
    "Toxic alcohols: osmolar gap + anion gap → fomepizole + dialysis",
    "Beta-blocker → glucagon; CCB → high-dose insulin; CO → 100% O₂ ± hyperbaric",
  ],
});

export const DERMATOLOGY_ALLERGIC_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Dermatology and allergy items on Step 2 CK test morphology-based diagnosis, first-line topical vs systemic therapy, anaphylaxis management, and drug eruption patterns. Boards emphasize Stevens-Johnson/toxic epidermal necrolysis drug culprits and when to stop the offending agent immediately.",
  ],
  concepts: [
    "Anaphylaxis: IM epinephrine 0.3–0.5 mg (0.01 mg/kg children) in anterolateral thigh — first and repeat q5–15 min",
    "Anaphylaxis adjuncts: fluids, albuterol for bronchospasm, H1/H2 blockers, steroids (do NOT delay epinephrine)",
    "Urticaria acute: antihistamines; if angioedema/anaphylaxis features → epinephrine",
    "Atopic dermatitis: emollients + topical steroids; severe → tacrolimus, dupilumab",
    "Psoriasis: topical steroids/vitamin D; moderate-severe → methotrexate, biologics; strep triggers guttate",
    "Acne vulgaris: comedonal → retinoid; inflammatory → add benzoyl peroxide + topical abx; severe → isotretinoin",
    "Rosacea: metronidazole/ivermectin topically; avoid steroids ( worsen)",
    "Cellulitis: cephalexin or dicloxacillin for non-purulent; MRSA coverage if purulent/systemic risk",
    "Necrotizing fasciitis: pain out of proportion, bullae, crepitus — surgical debridement emergently + broad abx",
    "SJS/TEN: mucosal involvement, epidermal detachment — stop causative drug (sulfa, AEDs, allopurinol); burn unit",
    "DRESS: rash + eosinophilia + systemic (hepatitis) weeks after drug — stop drug, steroids",
    "Lyme: erythema migrans — doxycycline; disseminated/neuro → ceftriaxone",
    "Scabies: permethrin 5% cream; treat contacts; ivermectin if crusted",
  ],
  clinical: [
    "Peanut ingestion, wheeze, urticaria, hypotension — IM epinephrine immediately, then IV fluids, observe",
    "Widespread urticaria after antibiotic, stable — stop drug, H1 blocker; epinephrine if angioedema or BP drop",
    "Painful expanding leg erythema, fever — cellulitis; cephalexin if no MRSA risk factors",
    "Diabetic foot, purple bullae, crepitus, severe pain — necrotizing fasciitis; surgery + vanc + pip-tazo + clindamycin",
    "Days after starting phenytoin, fever, target lesions, oral mucosal sloughing — SJS; stop phenytoin, admit burn unit",
    "Bull's-eye rash after hiking — Lyme; doxycycline 14–21 days",
    "Intensely pruritic linear burrows in web spaces — scabies; permethrin + treat household",
    "Silvery plaques on elbows/knees, nail pitting — psoriasis; topical steroid + vitamin D analog",
    "Teen with inflammatory acne failing topicals — oral doxycycline ± BPO; isotretinoin if severe/scarring",
    "Weeks after allopurinol, rash, eosinophilia, hepatitis — DRESS; stop allopurinol, corticosteroids",
  ],
  tables: [
    {
      caption: "Anaphylaxis management",
      headers: ["Step", "Intervention", "Notes"],
      rows: [
        ["1", "IM epinephrine anterolateral thigh", "Repeat q5–15 min if needed"],
        ["2", "Supine, legs elevated", "Position if hypotensive"],
        ["3", "IV fluids", "Crystalloid bolus"],
        ["4", "Adjuncts: albuterol, H1/H2, steroids", "Never substitute for epinephrine"],
        ["5", "Observe 4–8+ hours", "Biphasic reaction risk"],
      ],
    },
    {
      caption: "Drug eruptions severity spectrum",
      headers: ["Syndrome", "Timing", "Features", "Action"],
      rows: [
        ["Morbilliform", "Days", "Maculopapular, no mucosa", "Stop drug, antihistamines"],
        ["DRESS", "2–8 weeks", "Rash + eosinophilia + organ", "Stop drug, steroids"],
        ["SJS", "<10% BSA detachment", "Mucosal involvement", "Stop drug, burn unit"],
        ["TEN", ">30% BSA detachment", "Extensive sloughing", "Stop drug, ICU/burn unit"],
      ],
    },
    {
      caption: "Common dermatology first-line therapy",
      headers: ["Condition", "First-line", "Avoid"],
      rows: [
        ["Atopic dermatitis", "Emollients + low-potency topical steroid", "Oral steroids chronic use"],
        ["Psoriasis mild", "Topical steroid + vitamin D", "Systemic steroids (rebound)"],
        ["Acne moderate", "BPO + topical retinoid ± topical abx", "Monotherapy topical abx"],
        ["Cellulitis non-purulent", "Cephalexin/dicloxacillin", "Routine MRSA coverage"],
        ["Rosacea", "Topical metronidazole/ivermectin", "Topical steroids"],
      ],
    },
  ],
  visual: [
    "Anaphylaxis action plan: epinephrine first → position → fluids → adjuncts → observe",
    "SJS/TEN spectrum: mucosal involvement + % BSA detachment determines severity",
    "Lyme erythema migrans: expanding annular lesion with central clearing",
    "Scabies burrows: linear tracks in web spaces, worse at night",
    "Psoriasis morphology: silvery scale on erythematous plaque, extensor surfaces",
  ],
  misconceptions: [
    "Antihistamines or steroids before epinephrine in anaphylaxis — epinephrine is first",
    "Oral steroids for routine atopic dermatitis maintenance — emollients and topical steroids first",
    "Outpatient management of necrotizing fasciitis — surgical emergency",
    "Continuing causative drug in SJS while starting steroids — stop offender immediately",
    "Routine MRSA coverage for all cellulitis — narrow spectrum if non-purulent",
  ],
  pearls: [
    "Anaphylaxis: IM epinephrine in thigh — repeat without hesitation if not improving",
    "SJS/TEN culprits: sulfa drugs, antiepileptics, allopurinol — stop immediately",
    "Necrotizing fasciitis: pain out of proportion + surgical emergency",
    "Lyme with EM rash: treat without waiting for serology confirmation",
    "Isotretinoin requires iPLEDGE — teratogenic; two forms contraception",
  ],
  summary: [
    "Anaphylaxis: IM epinephrine first, repeat q5–15 min; observe for biphasic reaction",
    "SJS/TEN: stop causative drug, burn unit care; DRESS = rash + eosinophilia + organs",
    "Cellulitis narrow spectrum unless MRSA risk; nec fasc = surgery + broad abx",
    "Psoriasis, acne, atopic dermatitis stepwise topical → systemic therapy",
    "Lyme EM → doxycycline; scabies → permethrin + treat contacts",
  ],
});

export const ETHICS_BIOSTATS_USMLE_MODULE = buildUsmleReviewModule({
  why: [
    "Ethics and biostatistics appear on all USMLE steps but dominate Step 3. Items test capacity assessment, confidentiality exceptions, study design interpretation, and applying NNT/ARR to clinical decisions — not memorizing formulas in isolation.",
  ],
  concepts: [
    "Capacity is decision-specific: understand, appreciate, reason, communicate — competence is legal determination",
    "Informed consent: diagnosis, intervention, risks/benefits, alternatives (including none), questions answered",
    "Emergency/implied consent when life-threatening and patient cannot participate",
    "Surrogate hierarchy: advance directive → healthcare proxy → spouse → adult children → parents → siblings",
    "Confidentiality exceptions: Tarasoff (identifiable imminent harm), mandatory reporting (abuse, certain diseases), impaired colleague",
    "Sensitivity (SnNout): rules out when negative; specificity (SpPin): rules in when positive",
    "PPV/NPV depend on prevalence — screening in low prevalence → many false positives despite good test",
    "NNT = 1/ARR; NNH = 1/ARI — always interpret absolute vs relative risk",
    "Type I error (alpha): false positive; Type II (beta): false negative; power = 1 − beta",
    "RCT > cohort > case-control > cross-sectional for causation strength",
    "Intention-to-treat preserves randomization; per-protocol can bias results",
    "Lead-time and length bias inflate screening survival without true benefit",
    "CI excluding null (1.0 for RR/OR) = statistically significant at that level",
  ],
  clinical: [
    "Capacitated adult refuses life-saving transfusion — respect autonomy; document informed refusal",
    "Intoxicated trauma patient needs emergent surgery — implied consent; full discussion when stable",
    "Teen requests STI treatment — treat per mature minor statute in vignette without parental notification",
    "Patient threatens named coworker with imminent violence — Tarasoff duty to warn/protect",
    "Screening test 99% sensitive/specific, disease prevalence 0.1% — many false positives; counsel before screening",
    "Drug trial RRR 50% but event rate 2% → 1% (ARR 1%, NNT 100) — small absolute benefit",
    "Meta-analysis I² >50% — heterogeneity high; pooling may mislead",
    "Case-control study reports OR — cannot calculate incidence; recall bias possible",
    "p <0.05 but CI for RR crosses 1.0 — not statistically significant despite p-value (check CI always)",
    "Suspected child abuse with unsafe home — report to CPS; safety first",
  ],
  tables: [
    {
      caption: "Study design hierarchy",
      headers: ["Design", "Measures", "Bias risk", "Causation strength"],
      rows: [
        ["RCT", "RR, ARR, NNT", "Low (if well done)", "Strongest"],
        ["Cohort", "RR, incidence", "Confounding", "Strong"],
        ["Case-control", "OR", "Recall, selection", "Moderate"],
        ["Cross-sectional", "Prevalence", "Temporality unclear", "Weak for causation"],
      ],
    },
    {
      caption: "Ethics framework quick reference",
      headers: ["Scenario", "Principle", "Action"],
      rows: [
        ["Capacitated refusal", "Autonomy", "Respect refusal, document"],
        ["Incapacitated emergency", "Beneficence", "Treat in best interest/implied consent"],
        ["Minor emancipated/mature", "Autonomy (limited)", "Confidential care per statute"],
        ["Imminent harm to third party", "Duty to warn", "Tarasoff — warn/protect"],
        ["Colleague impairment", "Nonmaleficence", "Report to appropriate authority"],
      ],
    },
    {
      caption: "Biostatistics formulas",
      headers: ["Measure", "Formula", "Clinical use"],
      rows: [
        ["NNT", "1 / ARR", "Patients to treat for one benefit"],
        ["NNH", "1 / ARI", "Patients exposed for one harm"],
        ["Sensitivity", "TP / (TP + FN)", "Rules out when negative"],
        ["Specificity", "TN / (TN + FP)", "Rules in when positive"],
        ["PPV", "TP / (TP + FP)", "Depends on prevalence"],
      ],
    },
  ],
  visual: [
    "Capacity assessment four elements: understand → appreciate → reason → communicate",
    "Surrogate decision tree: advance directive → proxy → family hierarchy",
    "RRR vs ARR: always convert relative to absolute before clinical decisions",
    "Screening test outcomes: prevalence effect on PPV/NPV",
    "Study design ladder: RCT at top, cross-sectional at bottom for causation",
  ],
  misconceptions: [
    "Equating disagreement with lack of capacity — need formal four-element assessment",
    "Breaking confidentiality for vague threats without identifiable victim/imminence",
    "Using RR alone without ARR — exaggerates small absolute benefits",
    "Assuming p <0.05 means clinically important — check effect size and CI",
    "Post-hoc subgroup analyses as confirmatory — hypothesis-generating only",
  ],
  pearls: [
    "Never treat non-emergent capacitated adult against wishes — even if family disagrees",
    "Drug ad '50% reduction' — find absolute rates in fine print (NNT often 100+)",
    "Screening test with great sens/spec still has low PPV in low prevalence populations",
    "ITT analysis preserves benefits of randomization — preferred for efficacy reporting",
    "Impaired colleague: report through proper channels — not gossip",
  ],
  summary: [
    "Capacity: decision-specific four elements; respect informed refusal in capacitated adults",
    "Confidentiality exceptions: Tarasoff, mandatory reporting, colleague impairment",
    "NNT = 1/ARR; interpret absolute not relative effects",
    "Study design hierarchy: RCT > cohort > case-control; ITT preferred",
    "PPV/NPV prevalence-dependent; CI more informative than p-value alone",
  ],
});
