import type { TopicModuleDefinition } from "./topic-module-template";

export type UsmleLearningStage = {
  id: "foundations" | "clerkship" | "board-crunch";
  label: string;
  description: string;
  fieldId: "usmle-step-1" | "usmle-step-2" | "usmle-step-3";
  audience: string;
};

export const USMLE_LEARNING_STAGES: UsmleLearningStage[] = [
  {
    id: "foundations",
    label: "Foundations",
    description: "Mechanisms, pathophysiology, and basic science vignettes (pre-clinical / Step 1).",
    fieldId: "usmle-step-1",
    audience: "M1–M2",
  },
  {
    id: "clerkship",
    label: "Clinical clerkships",
    description: "Diagnosis, initial workup, and next-best-step management (Step 2 CK).",
    fieldId: "usmle-step-2",
    audience: "M3",
  },
  {
    id: "board-crunch",
    label: "Board crunch",
    description: "Timed blocks, weak-area drills, and high-yield systems review (M4 / dedicated).",
    fieldId: "usmle-step-2",
    audience: "M3–M4",
  },
];

/** Flagship USMLE topic modules — expand over time; each maps to review + Q-bank practice. */
export const USMLE_TOPIC_MODULES: TopicModuleDefinition[] = [
  {
    id: "usmle-cardio-acs",
    examSlug: "usmle",
    slug: "acute-coronary-syndrome",
    stage: "clerkship",
    system: "Cardiovascular",
    title: "Acute Coronary Syndrome",
    overview: "ECG patterns, troponin kinetics, antithrombotics, and reperfusion decisions.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 35,
    reviewTopicSlug: "acute-coronary-syndrome",
    questions: { practiceTopicSlug: "cardiology", reviewCount: 15, challengeCount: 5, curatedOnly: true },
    tags: ["cardiology", "acs", "high-yield"],
    sortOrder: 0,
  },
  {
    id: "usmle-renal-aki",
    examSlug: "usmle",
    slug: "acute-kidney-injury",
    stage: "clerkship",
    system: "Renal",
    title: "Acute Kidney Injury",
    overview: "Prerenal vs intrinsic vs postrenal; FENa, casts, and initial management.",
    skills: ["diagnosis", "interpretation", "next_step"],
    estimatedMinutes: 30,
    questions: { practiceTopicSlug: "nephrology", reviewCount: 12, challengeCount: 5, curatedOnly: true },
    tags: ["nephrology", "renal", "high-yield"],
    sortOrder: 1,
  },
  {
    id: "usmle-neuro-stroke",
    examSlug: "usmle",
    slug: "acute-ischemic-stroke",
    stage: "clerkship",
    system: "Neurology",
    title: "Acute Ischemic Stroke",
    overview: "NIHSS, CT exclusion of hemorrhage, tPA/thrombectomy windows, and AF embolism.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 30,
    questions: { practiceTopicSlug: "neurology", reviewCount: 12, challengeCount: 5, curatedOnly: true },
    tags: ["neurology", "stroke", "high-yield"],
    sortOrder: 2,
  },
  {
    id: "usmle-id-meningitis",
    examSlug: "usmle",
    slug: "bacterial-meningitis",
    stage: "clerkship",
    system: "Infectious Disease",
    title: "Bacterial Meningitis",
    overview: "CSF interpretation, empiric antibiotics, dexamethasone timing, and sick contacts.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 25,
    questions: { practiceTopicSlug: "microbiology", reviewCount: 10, challengeCount: 5, curatedOnly: true },
    tags: ["infectious-disease", "meningitis"],
    sortOrder: 3,
  },
  {
    id: "usmle-pulm-chf",
    examSlug: "usmle",
    slug: "acute-decompensated-hf",
    stage: "clerkship",
    system: "Pulmonary / Cardiovascular",
    title: "Acute Decompensated Heart Failure",
    overview: "Volume status, BNP, diuresis, afterload reduction, and when to escalate care.",
    skills: ["diagnosis", "next_step", "complication"],
    estimatedMinutes: 30,
    questions: { practiceTopicSlug: "cardiology", reviewCount: 12, curatedOnly: true },
    tags: ["cardiology", "heart-failure"],
    sortOrder: 4,
  },
  {
    id: "usmle-path-mechanism",
    examSlug: "usmle",
    slug: "pathophysiology-mechanisms",
    stage: "foundations",
    system: "Pathophysiology",
    title: "Mechanism & Pathophysiology",
    overview: "Link presentation to underlying mechanism — core Step 1 reasoning pattern.",
    skills: ["mechanism"],
    estimatedMinutes: 25,
    reviewTopicSlug: "pathology-neoplasia",
    questions: { practiceTopicSlug: "pathology", reviewCount: 15, curatedOnly: true },
    tags: ["pathology", "mechanism", "step1"],
    sortOrder: 10,
  },
  {
    id: "usmle-pharm-moa",
    examSlug: "usmle",
    slug: "pharmacology-moa",
    stage: "foundations",
    system: "Pharmacology",
    title: "Pharmacology MOA",
    overview: "Drug class mechanisms, adverse effects, and clinical selection anchors.",
    skills: ["pharm_moa"],
    estimatedMinutes: 25,
    reviewTopicSlug: "pharmacology-moa",
    questions: { practiceTopicSlug: "pharmacology", reviewCount: 15, curatedOnly: true },
    tags: ["pharmacology", "moa", "step1"],
    sortOrder: 11,
  },
  {
    id: "usmle-micro-immuno",
    examSlug: "usmle",
    slug: "microbiology-immunology",
    stage: "foundations",
    system: "Microbiology / Immunology",
    title: "Microbiology & Immunology",
    overview: "Hypersensitivity, host defense, and classic bug-disease associations for Step 1.",
    skills: ["mechanism", "diagnosis"],
    estimatedMinutes: 30,
    reviewTopicSlug: "microbiology-immunology",
    questions: { practiceTopicSlug: "microbiology", reviewCount: 15, curatedOnly: true },
    tags: ["microbiology", "immunology", "step1"],
    sortOrder: 12,
  },
  {
    id: "usmle-s3-biostats",
    examSlug: "usmle",
    slug: "biostatistics-epidemiology",
    stage: "board-crunch",
    system: "Biostatistics",
    title: "Biostatistics & Epidemiology",
    overview: "Sensitivity/specificity, NNT, study design, and abstract interpretation for Step 3.",
    skills: ["interpretation"],
    estimatedMinutes: 30,
    reviewTopicSlug: "biostatistics-epidemiology",
    questions: { practiceTopicSlug: "internal-medicine", reviewCount: 12, curatedOnly: true },
    tags: ["biostatistics", "step3", "high-yield"],
    sortOrder: 21,
  },
  {
    id: "usmle-s3-ethics",
    examSlug: "usmle",
    slug: "medical-ethics-legal",
    stage: "board-crunch",
    system: "Ethics / Legal",
    title: "Medical Ethics & Capacity",
    overview: "Capacity, consent, surrogate decision-making, and mandatory reporting for Step 3.",
    skills: ["next_step"],
    estimatedMinutes: 25,
    reviewTopicSlug: "medical-ethics-legal",
    questions: { practiceTopicSlug: "internal-medicine", reviewCount: 10, curatedOnly: true },
    tags: ["ethics", "step3"],
    sortOrder: 22,
  },
  {
    id: "usmle-s3-ccs",
    examSlug: "usmle",
    slug: "ccs-case-management",
    stage: "board-crunch",
    system: "CCS",
    title: "Computer-Based Case Simulations",
    overview: "Stabilize, monitor, and escalate — the CCS management loop for Step 3 Day 2.",
    skills: ["next_step", "complication"],
    estimatedMinutes: 35,
    reviewTopicSlug: "ccs-case-management",
    questions: { practiceTopicSlug: "internal-medicine", reviewCount: 10, curatedOnly: true },
    tags: ["ccs", "step3", "high-yield"],
    sortOrder: 23,
  },
  {
    id: "usmle-s2-peds-fever",
    examSlug: "usmle",
    slug: "pediatric-fever",
    stage: "clerkship",
    system: "Pediatrics",
    title: "Pediatric Fever Workup",
    overview: "Age-stratified fever evaluation from neonate to toddler.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 25,
    reviewTopicSlug: "pediatrics",
    questions: { practiceTopicSlug: "pediatrics", reviewCount: 12, curatedOnly: true },
    tags: ["pediatrics", "fever", "step2"],
    sortOrder: 5,
  },
  {
    id: "usmle-s2-ob-hypertension",
    examSlug: "usmle",
    slug: "ob-hypertensive-disorders",
    stage: "clerkship",
    system: "OB/GYN",
    title: "Hypertensive Disorders of Pregnancy",
    overview: "Preeclampsia, eclampsia, HELLP, and obstetric hemorrhage.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 30,
    reviewTopicSlug: "obstetrics",
    questions: { practiceTopicSlug: "obgyn", reviewCount: 12, curatedOnly: true },
    tags: ["obgyn", "preeclampsia", "step2"],
    sortOrder: 6,
  },
  {
    id: "usmle-s2-psych-emergency",
    examSlug: "usmle",
    slug: "psychiatric-emergencies",
    stage: "clerkship",
    system: "Psychiatry",
    title: "Psychiatric Emergencies",
    overview: "Suicide risk, serotonin syndrome, NMS, and acute psychosis management.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 25,
    reviewTopicSlug: "psychiatry",
    questions: { practiceTopicSlug: "psychiatry", reviewCount: 10, curatedOnly: true },
    tags: ["psychiatry", "step2"],
    sortOrder: 7,
  },
  {
    id: "usmle-s2-pulm-exac",
    examSlug: "usmle",
    slug: "pulmonary-exacerbations",
    stage: "clerkship",
    system: "Pulmonary",
    title: "COPD, Asthma & PE",
    overview: "Obstructive exacerbations and pulmonary embolism workup for Step 2 CK.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 30,
    reviewTopicSlug: "pulmonary",
    questions: { practiceTopicSlug: "pulmonology", reviewCount: 12, curatedOnly: true },
    tags: ["pulmonary", "step2", "high-yield"],
    sortOrder: 8,
  },
  {
    id: "usmle-s2-surgery-acute",
    examSlug: "usmle",
    slug: "surgery-acute-care",
    stage: "clerkship",
    system: "Surgery",
    title: "Acute Abdomen & Post-Op Complications",
    overview: "Surgical abdomen, post-op fever 5 W's, and anaphylaxis for Step 2 CK.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 25,
    reviewTopicSlug: "emergency-toxicology",
    questions: { practiceTopicSlug: "internal-medicine", reviewCount: 10, curatedOnly: true },
    tags: ["surgery", "step2"],
    sortOrder: 9,
  },
  {
    id: "usmle-board-mixed",
    examSlug: "usmle",
    slug: "board-crunch-mixed",
    stage: "board-crunch",
    system: "Mixed",
    title: "Mixed Timed Block",
    overview: "40-question exam-style block pulling weak systems and high-yield tags.",
    skills: ["diagnosis", "next_step"],
    estimatedMinutes: 60,
    questions: { practiceTopicSlug: "internal-medicine", reviewCount: 40, curatedOnly: true },
    tags: ["mixed", "timed"],
    sortOrder: 20,
  },
];

export function modulesForStage(stageId: UsmleLearningStage["id"]): TopicModuleDefinition[] {
  return USMLE_TOPIC_MODULES.filter((m) => m.stage === stageId).sort(
    (a, b) => a.sortOrder - b.sortOrder
  );
}

export function getUsmleModuleBySlug(slug: string): TopicModuleDefinition | undefined {
  return USMLE_TOPIC_MODULES.find((m) => m.slug === slug);
}
