import type { SubjectArea } from "../types";

/** NCCPA PANCE content categories (effective January 2025). */
export const PANCE_SUBJECTS: SubjectArea[] = [
  {
    id: "cardiovascular",
    label: "Cardiovascular System",
    contentArea: "Cardiovascular (11%)",
    textbookRefs: "OpenStax Anatomy & Physiology, ACC/AHA guidelines",
    examHints: "ACS, heart failure, arrhythmias, hypertension, valvular disease, shock",
    keywords: ["cardiology", "ECG", "chest pain", "heart failure", "arrhythmia"],
    focusPlaceholder: "e.g. ACS, heart failure, arrhythmias",
    difficultyLevel: 3,
  },
  {
    id: "pulmonary",
    label: "Pulmonary System",
    contentArea: "Pulmonary (9%)",
    textbookRefs: "OpenStax, GOLD COPD, asthma guidelines",
    examHints: "COPD, asthma, pneumonia, PE, pleural disease, oxygen therapy",
    keywords: ["pulmonary", "COPD", "asthma", "pneumonia", "PE", "dyspnea"],
    focusPlaceholder: "e.g. COPD, asthma, pneumonia",
    difficultyLevel: 3,
  },
  {
    id: "gastrointestinal",
    label: "Gastrointestinal / Nutrition",
    contentArea: "GI & Nutrition (8%)",
    textbookRefs: "OpenStax, ACG guidelines",
    examHints: "GERD, pancreatitis, hepatitis, IBD, GI bleeding, malnutrition",
    keywords: ["GI", "liver", "pancreas", "IBD", "bleeding", "nutrition"],
    focusPlaceholder: "e.g. GI bleed, liver disease",
    difficultyLevel: 3,
  },
  {
    id: "musculoskeletal",
    label: "Musculoskeletal System",
    contentArea: "Musculoskeletal (8%)",
    textbookRefs: "OpenStax, AAOS references",
    examHints: "fractures, arthritis, back pain, compartment syndrome, gout",
    keywords: ["MSK", "fracture", "arthritis", "back pain", "orthopedic"],
    focusPlaceholder: "e.g. Low back pain, septic arthritis",
    difficultyLevel: 3,
  },
  {
    id: "infectious-diseases",
    label: "Infectious Diseases",
    contentArea: "Infectious Diseases (7%)",
    textbookRefs: "IDSA guidelines, CDC",
    examHints: "sepsis, HIV, TB, meningitis, skin infections, antibiotic selection",
    keywords: ["infection", "sepsis", "antibiotic", "HIV", "meningitis"],
    focusPlaceholder: "e.g. Sepsis, CAP, HIV",
    difficultyLevel: 3,
  },
  {
    id: "neurologic",
    label: "Neurologic System",
    contentArea: "Neurologic (7%)",
    textbookRefs: "OpenStax, AAN guidelines",
    examHints: "stroke, seizure, headache, MS, peripheral neuropathy",
    keywords: ["neurology", "stroke", "seizure", "headache", "neuropathy"],
    focusPlaceholder: "e.g. Stroke, seizure, headache",
    difficultyLevel: 3,
  },
  {
    id: "psychiatry",
    label: "Psychiatry / Behavioral Science",
    contentArea: "Psychiatry & Behavioral (7%)",
    textbookRefs: "DSM-5-TR, APA guidelines",
    examHints: "depression, anxiety, psychosis, substance use, suicide risk",
    keywords: ["psychiatry", "depression", "anxiety", "bipolar", "substance"],
    focusPlaceholder: "e.g. Major depression, alcohol withdrawal",
    difficultyLevel: 3,
  },
  {
    id: "reproductive",
    label: "Reproductive System",
    contentArea: "Reproductive (7%)",
    textbookRefs: "ACOG guidelines",
    examHints: "pregnancy complications, STIs, contraception, gynecologic emergencies",
    keywords: ["OB", "GYN", "pregnancy", "STI", "contraception"],
    focusPlaceholder: "e.g. Preeclampsia, PID",
    difficultyLevel: 3,
  },
  {
    id: "endocrine",
    label: "Endocrine System",
    contentArea: "Endocrine (6%)",
    textbookRefs: "ADA, Endocrine Society guidelines",
    examHints: "diabetes, thyroid, adrenal, DKA, hypoglycemia",
    keywords: ["endocrine", "diabetes", "thyroid", "DKA", "insulin"],
    focusPlaceholder: "e.g. DKA, hypothyroidism",
    difficultyLevel: 3,
  },
  {
    id: "eent",
    label: "Eyes, Ears, Nose & Throat",
    contentArea: "EENT (6%)",
    textbookRefs: "OpenStax, AAFP references",
    examHints: "red eye, hearing loss, sinusitis, pharyngitis, vertigo",
    keywords: ["EENT", "eye", "ear", "sinus", "pharyngitis"],
    focusPlaceholder: "e.g. Acute otitis media, glaucoma",
    difficultyLevel: 2,
  },
  {
    id: "hematologic",
    label: "Hematologic System",
    contentArea: "Hematologic (5%)",
    textbookRefs: "ASH guidelines",
    examHints: "anemia, coagulopathy, thrombocytopenia, leukemia workup",
    keywords: ["hematology", "anemia", "coagulation", "bleeding"],
    focusPlaceholder: "e.g. Iron deficiency anemia, DIC",
    difficultyLevel: 3,
  },
  {
    id: "renal",
    label: "Renal System",
    contentArea: "Renal (5%)",
    textbookRefs: "KDIGO guidelines",
    examHints: "AKI, CKD, electrolytes, acid-base, dialysis indications",
    keywords: ["renal", "AKI", "CKD", "electrolyte", "dialysis"],
    focusPlaceholder: "e.g. AKI, hyperkalemia",
    difficultyLevel: 3,
  },
  {
    id: "dermatologic",
    label: "Dermatologic System",
    contentArea: "Dermatologic (4%)",
    textbookRefs: "AAD references",
    examHints: "rash patterns, cellulitis, melanoma screening, drug eruptions",
    keywords: ["dermatology", "rash", "cellulitis", "skin"],
    focusPlaceholder: "e.g. Cellulitis, psoriasis",
    difficultyLevel: 2,
  },
  {
    id: "genitourinary",
    label: "Genitourinary System",
    contentArea: "Genitourinary (4%)",
    textbookRefs: "AUA guidelines",
    examHints: "UTI, BPH, nephrolithiasis, urologic emergencies",
    keywords: ["GU", "UTI", "BPH", "kidney stone", "urology"],
    focusPlaceholder: "e.g. UTI, acute urinary retention",
    difficultyLevel: 3,
  },
  {
    id: "professional-practice",
    label: "Professional Practice",
    contentArea: "Professional Practice (6%)",
    textbookRefs: "NCCPA professional practice outline",
    examHints: "ethics, informed consent, scope of practice, patient safety, documentation",
    keywords: ["ethics", "consent", "scope", "safety", "documentation"],
    focusPlaceholder: "e.g. Informed consent, error disclosure",
    difficultyLevel: 2,
  },
];
