import type { SubjectArea } from "../types";

/** AANPCB FNP blueprint domains + high-yield clinical systems (2024+ test plan). */
export const AANP_FNP_SUBJECTS: SubjectArea[] = [
  {
    id: "assess",
    label: "Assess",
    contentArea: "AANP FNP — Domain I: Assess (32%)",
    textbookRefs: "Open RN Assessment, AANPCB FNP Content Outline",
    examHints:
      "history, ROS, physical exam, screening, diagnostic test selection, lifespan assessment",
    keywords: ["assessment", "history", "physical exam", "screening", "diagnostics"],
    focusPlaceholder: "e.g. Abdominal exam findings",
  },
  {
    id: "diagnose",
    label: "Diagnose",
    contentArea: "AANP FNP — Domain II: Diagnose (26.5%)",
    textbookRefs: "AANPCB FNP Content Outline, clinical reasoning",
    examHints: "differential diagnosis, primary diagnosis, data synthesis, red flags",
    keywords: ["diagnosis", "differential", "interpretation", "clinical reasoning"],
    focusPlaceholder: "e.g. Chest pain differential",
  },
  {
    id: "plan",
    label: "Plan",
    contentArea: "AANP FNP — Domain III: Plan (26.5%)",
    textbookRefs: "AANPCB FNP Content Outline, pharmacology, guidelines",
    examHints:
      "pharmacologic and non-pharmacologic therapy, referrals, patient education, preventive care",
    keywords: ["plan", "treatment", "prescribe", "counseling", "referral"],
    focusPlaceholder: "e.g. First-line HTN therapy",
  },
  {
    id: "evaluate",
    label: "Evaluate",
    contentArea: "AANP FNP — Domain IV: Evaluate (15%)",
    textbookRefs: "AANPCB FNP Content Outline, outcomes monitoring",
    examHints: "treatment response, adverse effects, care plan modification, follow-up",
    keywords: ["evaluate", "monitor", "follow-up", "outcomes", "adherence"],
    focusPlaceholder: "e.g. Monitoring on statin therapy",
  },
  {
    id: "cardiovascular",
    label: "Cardiovascular",
    contentArea: "FNP — Cardiovascular disorders across the lifespan",
    textbookRefs: "Open RN Cardiovascular, ACC/AHA guidelines",
    examHints: "HTN, heart failure, ACS, arrhythmia, lipid management",
    keywords: ["cardiology", "hypertension", "heart failure", "ECG", "chest pain"],
    focusPlaceholder: "e.g. Acute coronary syndrome",
  },
  {
    id: "pulmonary",
    label: "Pulmonary",
    contentArea: "FNP — Respiratory disorders",
    textbookRefs: "Open RN Respiratory, GOLD/NAEPP guidelines",
    examHints: "asthma, COPD, pneumonia, PE, oxygen therapy",
    keywords: ["pulmonary", "asthma", "COPD", "respiratory", "dyspnea"],
    focusPlaceholder: "e.g. COPD exacerbation",
  },
  {
    id: "endocrine",
    label: "Endocrine & Metabolic",
    contentArea: "FNP — Endocrine and metabolic disorders",
    textbookRefs: "ADA guidelines, thyroid disorders",
    examHints: "diabetes, thyroid, adrenal, electrolytes, obesity",
    keywords: ["diabetes", "thyroid", "endocrine", "metabolic", "insulin"],
    focusPlaceholder: "e.g. Type 2 diabetes management",
  },
  {
    id: "womens-health",
    label: "Women's Health",
    contentArea: "FNP — Women's health (integrated across adult lifespan)",
    textbookRefs: "ACOG guidelines, prenatal/postpartum care",
    examHints: "contraception, prenatal care, menopause, STI screening, breast health",
    keywords: ["OB", "GYN", "prenatal", "contraception", "menopause"],
    focusPlaceholder: "e.g. First prenatal visit",
  },
  {
    id: "pediatrics",
    label: "Pediatrics",
    contentArea: "FNP — Newborn through adolescent (22% of exam)",
    textbookRefs: "Bright Futures, AAP guidelines",
    examHints: "well-child, immunizations, developmental milestones, pediatric emergencies",
    keywords: ["pediatric", "child", "adolescent", "immunization", "development"],
    focusPlaceholder: "e.g. Febrile infant workup",
  },
  {
    id: "geriatrics",
    label: "Geriatrics",
    contentArea: "FNP — Older adult care (30% of exam)",
    textbookRefs: "AGS Beers Criteria, geriatric syndromes",
    examHints: "polypharmacy, falls, dementia, frailty, advance care planning",
    keywords: ["geriatric", "older adult", "polypharmacy", "falls", "dementia"],
    focusPlaceholder: "e.g. Delirium vs dementia",
  },
  {
    id: "psychiatry-behavioral",
    label: "Psychiatry & Behavioral Health",
    contentArea: "FNP — Mental health and behavioral conditions",
    textbookRefs: "DSM-5-TR criteria, APA guidelines",
    examHints: "depression, anxiety, substance use, suicide risk, psychotropic monitoring",
    keywords: ["psychiatry", "mental health", "depression", "anxiety", "substance use"],
    focusPlaceholder: "e.g. Major depressive disorder",
  },
  {
    id: "infectious-disease",
    label: "Infectious Disease",
    contentArea: "FNP — Infectious and immunologic disorders",
    textbookRefs: "IDSA guidelines, CDC immunization schedule",
    examHints: "UTI, STI, HIV, sepsis, antibiotic selection, infection prevention",
    keywords: ["infection", "antibiotic", "sepsis", "HIV", "immunization"],
    focusPlaceholder: "e.g. Community-acquired pneumonia",
  },
];
