import { LEGAL_DISCLAIMERS, LEGAL_ENTITY, LEGAL_LAST_UPDATED } from "@/lib/legal";

/** Bump when signup/consent attestation language changes — stored on each consent record. */
export const CONSENT_ATTESTATION_VERSION = "2026-07-05";

/**
 * Full attestation text presented at signup and archived on each consent record.
 * Keep in sync with LegalCheckbox and the public Disclaimers page.
 */
export function getSignupConsentAttestations(): string[] {
  const { productName, companyName } = LEGAL_ENTITY;

  return [
    `Content provider: Practice questions, mock exams, explanations, memory cards, and related study content in ${productName} are authored, curated, and/or generated by ${companyName} ("Company"), which operates ${productName}. The Company is solely responsible for this content.`,
    `No affiliation or endorsement: ${productName} is not affiliated with, authorized by, endorsed by, sponsored by, or approved by the NCSBN, NBME, NABP, NCCPA, FSBPT, AANP Certification Board, or any other licensing or certification body. Exam names are used for descriptive purposes only.`,
    `Not official examination material: Content is original study material for educational and self-assessment purposes. It is NOT actual NCLEX®, USMLE®, NAPLEX®, PANCE®, NPTE®, AANP FNP®, or other official board or licensing examination content; does not include real past or future exam items; and must not be treated as a substitute for official prep materials from examination authorities or accredited publishers.`,
    `Supplement other resources: I acknowledge that preparation for licensure or certification exams should include multiple sources (textbooks, accredited review courses, clinical training, and official prep resources as appropriate). I will use ${productName} as a supplement—not my sole resource—and will consult additional authoritative materials as needed to pass my examination.`,
    LEGAL_DISCLAIMERS.aiGenerated,
    LEGAL_DISCLAIMERS.noGuarantee,
    LEGAL_DISCLAIMERS.progressMetrics,
    LEGAL_DISCLAIMERS.notMedicalAdvice,
    LEGAL_DISCLAIMERS.educationalPurpose,
    LEGAL_DISCLAIMERS.userResponsibility,
    LEGAL_DISCLAIMERS.ageRequirement,
    `Legal documents: I have read and agree to the Terms of Service, Privacy Policy, and Educational Disclaimers (version ${LEGAL_LAST_UPDATED}).`,
    `Billing acknowledgement: I understand subscription, auto-renewal, and non-refundable payment terms described in the Terms of Service unless required otherwise by applicable law.`,
    `Dispute resolution & liability: I acknowledge the limitation of liability, indemnification, and binding individual arbitration provisions described in the Terms of Service and Disclaimers.`,
  ];
}

/** Short labels for signup UI — full text is stored on the consent record at registration. */
export function getSignupConsentSummaryLines(): string[] {
  const { productName, companyName } = LEGAL_ENTITY;
  return [
    `Study content is created by ${companyName} (${productName}) — an independent provider not affiliated with NCLEX®, USMLE®, NAPLEX®, PANCE®, or other licensing boards.`,
    "Questions and mock exams are original study material — not actual official board exam items.",
    "I will use additional textbooks, courses, and official prep resources as needed to prepare for my exam.",
    "AI-generated content may contain errors; I am responsible for verifying facts before relying on them.",
  ];
}
