import type { SubjectArea } from "../types";

export const MATH_SUBJECTS: SubjectArea[] = [
  {
    id: "algebra",
    label: "Algebra",
    contentArea: "Algebra & functions",
    textbookRefs: "OpenStax Algebra, LibreTexts",
    examHints: "equations, inequalities, functions, polynomials, exponents",
    keywords: ["algebra", "equation", "polynomial", "quadratic"],
    focusPlaceholder: "e.g. Quadratic equations",
    difficultyLevel: 2,
  },
  {
    id: "calculus",
    label: "Calculus",
    contentArea: "Differential & integral calculus",
    textbookRefs: "OpenStax Calculus",
    examHints: "limits, derivatives, integrals, applications, series",
    keywords: ["calculus", "derivative", "integral", "limit"],
    focusPlaceholder: "e.g. Optimization, related rates",
    difficultyLevel: 4,
  },
  {
    id: "statistics",
    label: "Statistics",
    contentArea: "Probability & statistics",
    textbookRefs: "OpenStax Intro Statistics",
    examHints: "distributions, hypothesis testing, regression, probability",
    keywords: ["statistics", "probability", "hypothesis", "regression"],
    focusPlaceholder: "e.g. Confidence intervals",
    difficultyLevel: 3,
  },
  {
    id: "trigonometry",
    label: "Trigonometry",
    contentArea: "Trigonometry",
    textbookRefs: "OpenStax Precalculus",
    examHints: "identities, graphs, inverse trig, applications",
    keywords: ["trigonometry", "sine", "cosine", "identity"],
    focusPlaceholder: "e.g. Unit circle, identities",
    difficultyLevel: 3,
  },
  {
    id: "geometry",
    label: "Geometry",
    contentArea: "Euclidean geometry",
    textbookRefs: "OpenStax Geometry",
    examHints: "proofs, circles, triangles, coordinate geometry, area/volume",
    keywords: ["geometry", "triangle", "circle", "proof"],
    focusPlaceholder: "e.g. Similar triangles",
    difficultyLevel: 2,
  },
];
