import type { AnatomyProcedure } from "./types";

export const CARDIAC_PROCEDURES: AnatomyProcedure[] = [
  {
    id: "cabg",
    name: "Coronary artery bypass grafting (CABG)",
    aliases: ["CABG", "Bypass surgery"],
    structureIds: ["heart", "heart-coronary-arteries", "heart-left-ventricle"],
    subregionIds: ["heart-coronary-arteries", "heart-left-ventricle"],
    approach: "open",
    urgency: "urgent",
    indication: "Left main disease, triple-vessel disease, or failed PCI with ongoing ischemia",
    examPearl: "LIMA to LAD is the gold-standard graft with best long-term patency.",
    complications: ["Stroke", "Mediastinitis", "Atrial fibrillation", "Graft occlusion"],
    highYield: true,
  },
  {
    id: "pci",
    name: "Percutaneous coronary intervention (PCI)",
    aliases: ["Angioplasty", "Stent placement"],
    structureIds: ["heart", "heart-coronary-arteries"],
    subregionIds: ["heart-coronary-arteries"],
    approach: "endovascular",
    urgency: "emergent",
    indication: "STEMI within reperfusion window; stable/unstable angina with suitable anatomy",
    examPearl: "Door-to-balloon time <90 min for STEMI — primary PCI preferred over fibrinolysis when available.",
    complications: ["In-stent thrombosis", "Coronary dissection", "Contrast nephropathy", "Bleeding at access site"],
    highYield: true,
  },
  {
    id: "aortic-valve-replacement",
    name: "Aortic valve replacement (AVR)",
    structureIds: ["heart", "heart-aortic-valve"],
    subregionIds: ["heart-aortic-valve"],
    approach: "open",
    urgency: "elective",
    indication: "Severe symptomatic aortic stenosis or regurgitation",
    examPearl: "Severe AS: valve area <1.0 cm², mean gradient >40 mmHg, or symptomatic with low flow.",
    complications: ["Complete heart block", "Paravalvular leak", "Stroke", "Prosthetic valve endocarditis"],
    highYield: true,
  },
  {
    id: "mitral-valve-repair",
    name: "Mitral valve repair or replacement",
    structureIds: ["heart", "heart-mitral-valve"],
    subregionIds: ["heart-mitral-valve"],
    approach: "open",
    urgency: "elective",
    indication: "Severe mitral regurgitation (symptomatic or LV dysfunction) or mitral stenosis refractory to medical therapy",
    examPearl: "Repair preferred over replacement when feasible — preserves subvalvular apparatus.",
    complications: ["Residual MR", "Atrial fibrillation", "Anticoagulation-related bleeding if mechanical valve"],
    highYield: true,
  },
  {
    id: "tavr",
    name: "Transcatheter aortic valve replacement (TAVR)",
    structureIds: ["heart", "heart-aortic-valve"],
    subregionIds: ["heart-aortic-valve"],
    approach: "endovascular",
    urgency: "elective",
    indication: "Severe aortic stenosis in patients at high/prohibitive surgical risk",
    examPearl: "TAVR vs SAVR decision weighs frailty, anatomy, and lifetime management of bioprosthesis.",
    complications: ["Vascular access injury", "Complete heart block (pacemaker)", "Paravalvular leak", "Stroke"],
    highYield: true,
  },
  {
    id: "pacemaker-icd",
    name: "Pacemaker / ICD implantation",
    structureIds: ["heart", "heart-left-ventricle"],
    approach: "percutaneous",
    urgency: "urgent",
    indication: "Symptomatic bradycardia, heart block, or primary/secondary prevention of sudden cardiac death",
    examPearl: "ICD for EF ≤35% on optimal therapy (ischemic cardiomyopathy) — not the same as pacemaker alone.",
    complications: ["Lead dislodgement", "Pneumothorax", "Device infection", "Inappropriate shocks (ICD)"],
    highYield: true,
  },
  {
    id: "cardiac-cath",
    name: "Left heart catheterization",
    aliases: ["Diagnostic cath", "Coronary angiography"],
    structureIds: ["heart", "heart-coronary-arteries", "aorta"],
    approach: "endovascular",
    urgency: "urgent",
    indication: "ACS workup, pre-operative risk stratification, or unexplained heart failure",
    examPearl: "Right heart cath measures PCWP and cardiac output — key for cardiogenic vs non-cardiogenic shock.",
    complications: ["Access site hematoma", "Coronary dissection", "Contrast reaction", "Arrhythmia"],
    highYield: true,
  },
];
