import type { AnatomyProcedure } from "./types";

export const GI_PROCEDURES: AnatomyProcedure[] = [
  {
    id: "lap-chole",
    name: "Laparoscopic cholecystectomy",
    structureIds: ["gallbladder", "gallbladder-cystic-duct", "liver"],
    subregionIds: ["gallbladder-cystic-duct"],
    approach: "laparoscopic",
    urgency: "urgent",
    indication: "Symptomatic cholelithiasis, acute cholecystitis, biliary dyskinesia",
    examPearl: "Critical view of safety (two structures only) before clipping cystic duct/artery — prevents CBD injury.",
    complications: ["CBD injury", "Bile leak", "Retained common duct stone", "Post-cholecystectomy syndrome"],
    highYield: true,
  },
  {
    id: "open-chole",
    name: "Open cholecystectomy",
    structureIds: ["gallbladder"],
    approach: "open",
    urgency: "urgent",
    indication: "Gallbladder perforation, gangrene, or failed laparoscopic approach in unstable patient",
    examPearl: "Conversion to open does not imply surgical error — safety first in difficult inflammation.",
    complications: ["Wound infection", "CBD injury", "Prolonged ileus"],
    highYield: false,
  },
  {
    id: "ercp-sphincterotomy",
    name: "ERCP with sphincterotomy",
    structureIds: ["duodenum", "pancreas", "gallbladder", "liver"],
    subregionIds: ["pancreas-head", "gallbladder-cystic-duct", "liver-portal-hilum"],
    approach: "endoscopic",
    urgency: "urgent",
    indication: "Choledocholithiasis with cholangitis, biliary pancreatitis, or obstructive jaundice",
    examPearl: "Charcot triad (fever, jaundice, RUQ pain) + hypotension/confusion = Reynolds pentad → emergent decompression.",
    complications: ["Post-ERCP pancreatitis", "Bleeding", "Perforation", "Cholangitis if drainage fails"],
    highYield: true,
  },
  {
    id: "appendectomy",
    name: "Appendectomy (laparoscopic or open)",
    structureIds: ["appendix", "colon"],
    approach: "laparoscopic",
    urgency: "urgent",
    indication: "Acute appendicitis; interval appendectomy after abscess drainage in select cases",
    examPearl: "McBurney point tenderness; perforated appendicitis needs source control + antibiotics.",
    complications: ["Abscess", "Wound infection", "Small bowel obstruction (adhesions)", "Stump appendicitis"],
    highYield: true,
  },
  {
    id: "whipple",
    name: "Pancreaticoduodenectomy (Whipple)",
    structureIds: ["pancreas", "duodenum", "stomach", "gallbladder"],
    subregionIds: ["pancreas-head"],
    approach: "open",
    urgency: "elective",
    indication: "Pancreatic head malignancy, ampullary cancer, selected cholangiocarcinomas",
    examPearl: "Painless jaundice + weight loss + palpable gallbladder (Courvoisier) → pancreatic head cancer until proven otherwise.",
    complications: ["Pancreatic fistula", "Delayed gastric emptying", "Diabetes/exocrine insufficiency", "Anastomotic leak"],
    highYield: true,
  },
  {
    id: "distal-pancreatectomy",
    name: "Distal pancreatectomy",
    structureIds: ["pancreas", "spleen"],
    subregionIds: ["pancreas-tail"],
    approach: "open",
    urgency: "elective",
    indication: "Tail/neck pancreatic tumors, chronic pancreatitis of the tail, trauma",
    examPearl: "Splenic preservation depends on vessel involvement — tail lesions often require splenectomy.",
    complications: ["Pancreatic leak", "Splenic infarction", "Post-splenectomy infection risk"],
    highYield: true,
  },
  {
    id: "hepatectomy",
    name: "Partial hepatectomy",
    structureIds: ["liver"],
    subregionIds: ["liver-right-lobe", "liver-portal-hilum"],
    approach: "open",
    urgency: "elective",
    indication: "Hepatocellular carcinoma, colorectal metastases, benign tumors in resectable location",
    examPearl: "Future liver remnant must be adequate — portal vein embolization can hypertrophy the remnant pre-op.",
    complications: ["Bile leak", "Liver failure", "Hemorrhage", "Ascites"],
    highYield: true,
  },
  {
    id: "liver-transplant",
    name: "Orthotopic liver transplantation",
    structureIds: ["liver"],
    subregionIds: ["liver-portal-hilum"],
    approach: "open",
    urgency: "urgent",
    indication: "Decompensated cirrhosis, acute liver failure, selected HCC within Milan criteria",
    examPearl: "MELD score prioritizes allocation — acute liver failure (acetaminophen) may bypass MELD.",
    complications: ["Rejection", "Biliary stricture", "Infection (immunosuppression)", "Hepatic artery thrombosis"],
    highYield: true,
  },
  {
    id: "colectomy",
    name: "Colectomy (segmental or total)",
    structureIds: ["colon", "small-intestine"],
    approach: "open",
    urgency: "urgent",
    indication: "Colon cancer, volvulus, ischemic colitis, fulminant IBD, diverticular perforation",
    examPearl: "Right hemicolectomy for cecal/ascending cancers; low anterior resection vs abdominoperineal resection for rectal cancer.",
    complications: ["Anastomotic leak", "Ileus", "Wound infection", "Temporary diverting ileostomy complications"],
    highYield: true,
  },
  {
    id: "partial-gastrectomy",
    name: "Partial gastrectomy",
    structureIds: ["stomach", "duodenum"],
    approach: "open",
    urgency: "elective",
    indication: "Gastric cancer, refractory peptic ulcer disease, GIST",
    examPearl: "Billroth I vs II reconstruction — post-gastrectomy dumping syndrome and B12 deficiency are long-term issues.",
    complications: ["Dumping syndrome", "Afferent loop syndrome", "Marginal ulcer", "Anastomotic leak"],
    highYield: true,
  },
  {
    id: "splenectomy",
    name: "Splenectomy",
    structureIds: ["spleen"],
    approach: "open",
    urgency: "urgent",
    indication: "Traumatic rupture, ITP refractory to medical therapy, hereditary spherocytosis, hypersplenism",
    examPearl: "Post-splenectomy patients need encapsulated organism vaccines (pneumococcus, meningococcus, Hib).",
    complications: ["Overwhelming post-splenectomy infection (OPSI)", "Pancreatic tail injury", "Thrombocytosis"],
    highYield: true,
  },
];
