import type { AnatomyProcedure } from "./types";

export const THORACIC_GU_PROCEDURES: AnatomyProcedure[] = [
  {
    id: "lobectomy",
    name: "Pulmonary lobectomy",
    structureIds: ["lungs"],
    subregionIds: ["lung-right-upper", "lung-right-lower", "lung-left-upper"],
    approach: "open",
    urgency: "elective",
    indication: "Early-stage lung cancer, benign lobar disease, trauma in selected cases",
    examPearl: "VATS lobectomy is standard for early NSCLC — same oncologic principles as open thoracotomy.",
    complications: ["Bronchopleural fistula", "Persistent air leak", "Post-pneumonectomy pulmonary edema"],
    highYield: true,
  },
  {
    id: "vats-wedge",
    name: "VATS wedge resection",
    structureIds: ["lungs"],
    approach: "laparoscopic",
    urgency: "elective",
    indication: "Peripheral nodules, metastectomy, diagnostic biopsy in high-risk patients",
    examPearl: "Sublobar resection may be appropriate for small peripheral tumors or poor pulmonary reserve.",
    complications: ["Air leak", "Bleeding", "Conversion to thoracotomy"],
    highYield: true,
  },
  {
    id: "chest-tube",
    name: "Tube thoracostomy (chest tube)",
    structureIds: ["lungs", "diaphragm"],
    approach: "percutaneous",
    urgency: "emergent",
    indication: "Pneumothorax, hemothorax, large pleural effusion, empyema drainage",
    examPearl: "Insert above the rib to avoid neurovascular bundle — classic teaching: 4th–5th ICS, mid-axillary line.",
    complications: ["Lung laceration", "Infection/empyema", "Re-expansion pulmonary edema", "Incorrect placement"],
    highYield: true,
  },
  {
    id: "thoracentesis",
    name: "Thoracentesis",
    structureIds: ["lungs", "diaphragm"],
    approach: "percutaneous",
    urgency: "urgent",
    indication: "Diagnostic or therapeutic drainage of pleural effusion",
    examPearl: "Send fluid for Light criteria — exudate vs transudate guides workup (malignancy, infection, heart failure).",
    complications: ["Pneumothorax", "Re-expansion pulmonary edema", "Hemothorax (intercostal artery injury)"],
    highYield: true,
  },
  {
    id: "nephrectomy",
    name: "Radical nephrectomy",
    structureIds: ["kidneys", "adrenal-glands"],
    subregionIds: ["kidney-renal-pelvis"],
    approach: "open",
    urgency: "elective",
    indication: "Renal cell carcinoma, non-functioning kidney, living donor harvest",
    examPearl: "Classic triad (hematuria, flank pain, mass) is rare — incidental renal mass on imaging is common.",
    complications: ["Bleeding", "Injury to colon or spleen", "Chronic kidney disease if solitary kidney compromised"],
    highYield: true,
  },
  {
    id: "partial-nephrectomy",
    name: "Partial nephrectomy (nephron-sparing)",
    structureIds: ["kidneys"],
    approach: "open",
    urgency: "elective",
    indication: "Small renal masses, solitary kidney, bilateral tumors, hereditary RCC syndromes",
    examPearl: "Nephron-sparing preferred when oncologically equivalent — preserves renal function.",
    complications: ["Urinary leak/fistula", "Positive margins", "Acute kidney injury"],
    highYield: true,
  },
  {
    id: "turp",
    name: "Transurethral resection of the prostate (TURP)",
    structureIds: ["prostate", "bladder"],
    subregionIds: ["prostate-peripheral-zone"],
    approach: "endoscopic",
    urgency: "elective",
    indication: "Benign prostatic hyperplasia with obstructive or refractory urinary symptoms",
    examPearl: "TURP treats BPH, not prostate cancer — post-TURP syndrome (hyponatremia) from glycine irrigation is historic.",
    complications: ["Bleeding", "Retrograde ejaculation", "Urethral stricture", "TUR syndrome (rare with saline)"],
    highYield: true,
  },
  {
    id: "radical-prostatectomy",
    name: "Radical prostatectomy",
    structureIds: ["prostate", "bladder"],
    subregionIds: ["prostate-peripheral-zone"],
    approach: "robotic",
    urgency: "elective",
    indication: "Localized prostate adenocarcinoma in patients with long life expectancy",
    examPearl: "PSA screening controversies aside — localized disease offers curative surgery vs active surveillance by risk group.",
    complications: ["Erectile dysfunction", "Urinary incontinence", "Positive margins", "Lymphocele"],
    highYield: true,
  },
  {
    id: "turbt",
    name: "Transurethral resection of bladder tumor (TURBT)",
    structureIds: ["bladder"],
    approach: "endoscopic",
    urgency: "urgent",
    indication: "Bladder cancer diagnosis and staging; resection of non-muscle-invasive tumors",
    examPearl: "Painless gross hematuria is bladder cancer until proven otherwise — cytology and cystoscopy are key.",
    complications: ["Bladder perforation", "Bleeding", "TUR syndrome", "Seeding (rare)"],
    highYield: true,
  },
  {
    id: "thyroidectomy",
    name: "Total thyroidectomy",
    structureIds: ["thyroid"],
    subregionIds: ["thyroid-isthmus"],
    approach: "open",
    urgency: "elective",
    indication: "Thyroid cancer, Graves disease, large goiter with compression, bilateral nodules",
    examPearl: "Watch for recurrent laryngeal nerve injury (hoarseness) and hypocalcemia from parathyroid devascularization.",
    complications: ["Hypoparathyroidism/hypocalcemia", "RLN injury", "Hematoma with airway compromise", "Hypothyroidism"],
    highYield: true,
  },
  {
    id: "hemithyroidectomy",
    name: "Thyroid lobectomy (hemithyroidectomy)",
    structureIds: ["thyroid"],
    approach: "open",
    urgency: "elective",
    indication: "Indeterminate thyroid nodule, toxic adenoma, low-risk unilateral cancer",
    examPearl: "If malignancy found on final pathology, completion thyroidectomy may be needed — counsel pre-op.",
    complications: ["RLN injury", "Bleeding", "Hypothyroidism (less than total thyroidectomy)"],
    highYield: true,
  },
  {
    id: "aortic-repair-open",
    name: "Open aortic repair",
    structureIds: ["aorta", "heart"],
    approach: "open",
    urgency: "emergent",
    indication: "Type A aortic dissection, ruptured abdominal aortic aneurysm, symptomatic ascending aneurysm",
    examPearl: "Type A dissection = surgery; Type B uncomplicated = medical (β-blocker) unless malperfusion/end-organ ischemia.",
    complications: ["Stroke", "Paraplegia (spinal ischemia)", "Renal failure", "Bleeding"],
    highYield: true,
  },
  {
    id: "evar",
    name: "Endovascular aneurysm repair (EVAR)",
    structureIds: ["aorta"],
    approach: "endovascular",
    urgency: "urgent",
    indication: "Infrarenal abdominal aortic aneurysm with suitable anatomy",
    examPearl: "EVAR requires lifelong surveillance imaging for endoleak — not all aneurysms have favorable neck anatomy.",
    complications: ["Endoleak", "Graft migration", "Access site complications", "Conversion to open repair"],
    highYield: true,
  },
  {
    id: "carotid-endarterectomy",
    name: "Carotid endarterectomy (CEA)",
    structureIds: ["carotid-artery"],
    approach: "open",
    urgency: "elective",
    indication: "Symptomatic high-grade carotid stenosis; selected asymptomatic severe stenosis",
    examPearl: "CEA vs carotid stenting — CEA preferred in many symptomatic patients; perioperative stroke risk is the key metric.",
    complications: ["Perioperative stroke/TIA", "Cranial nerve injury (hypoglossal, vagus)", "Neck hematoma with airway compromise"],
    highYield: true,
  },
];
