import type { AnatomyProcedure } from "./types";

export const NEURO_MSK_PROCEDURES: AnatomyProcedure[] = [
  {
    id: "craniotomy",
    name: "Craniotomy",
    structureIds: ["skull", "brain"],
    approach: "open",
    urgency: "emergent",
    indication: "Evacuation of epidural/subdural hematoma, resection of accessible brain tumor, decompressive surgery",
    examPearl: "Epidural hematoma = lucid interval + lens-shaped bleed — neurosurgical emergency.",
    complications: ["Seizures", "Infection", "Neurologic deficit", "CSF leak"],
    highYield: true,
  },
  {
    id: "burr-hole-evacuation",
    name: "Burr hole evacuation",
    structureIds: ["skull", "brain"],
    approach: "open",
    urgency: "emergent",
    indication: "Subdural hematoma in deteriorating patient when formal craniotomy delayed",
    examPearl: "Subdural = crescent-shaped bleed crossing sutures — bridging vein injury, often elderly/alcohol.",
    complications: ["Incomplete evacuation", "Recurrence", "Brain injury from rapid decompression"],
    highYield: true,
  },
  {
    id: "evd-vp-shunt",
    name: "External ventricular drain / VP shunt",
    structureIds: ["skull", "brain"],
    approach: "open",
    urgency: "emergent",
    indication: "Hydrocephalus, elevated ICP with ventricular enlargement, normal-pressure hydrocephalus (shunt)",
    examPearl: "EVD allows ICP monitoring and CSF drainage — infection risk rises with duration.",
    complications: ["Infection/ventriculitis", "Hemorrhage", "Shunt malfunction/obstruction", "Over-drainage"],
    highYield: true,
  },
  {
    id: "mechanical-thrombectomy",
    name: "Mechanical thrombectomy (endovascular)",
    structureIds: ["brain", "carotid-artery"],
    approach: "endovascular",
    urgency: "emergent",
    indication: "Large-vessel ischemic stroke within extended window with salvageable penumbra",
    examPearl: "tPA exclusions for hemorrhage — thrombectomy adds benefit for proximal occlusion (MCA, ICA) when available.",
    complications: ["Hemorrhagic transformation", "Vessel perforation", "Access site complications"],
    highYield: true,
  },
  {
    id: "orif-long-bone",
    name: "Open reduction and internal fixation (ORIF)",
    structureIds: ["femur", "humerus", "tibia", "clavicle"],
    approach: "open",
    urgency: "urgent",
    indication: "Displaced fractures, open fractures, unstable pelvic/acetabular injuries",
    examPearl: "Open fracture = antibiotics + tetanus + urgent debridement — Gustilo classification guides management.",
    complications: ["Nonunion/malunion", "Infection", "Hardware failure", "Compartment syndrome (tibia/femur)"],
    highYield: true,
  },
  {
    id: "hip-hemiarthroplasty",
    name: "Hip hemiarthroplasty",
    structureIds: ["femur"],
    approach: "open",
    urgency: "urgent",
    indication: "Displaced femoral neck fracture in elderly/low-demand patients",
    examPearl: "Shortened externally rotated leg after fall — femoral neck fracture risks AVN; ORIF in young, arthroplasty in elderly.",
    complications: ["Dislocation", "Periprosthetic fracture", "DVT/PE", "Leg length discrepancy"],
    highYield: true,
  },
  {
    id: "fasciotomy",
    name: "Compartment fasciotomy",
    structureIds: ["tibia", "femur", "biceps-brachii"],
    approach: "open",
    urgency: "emergent",
    indication: "Acute compartment syndrome — pain out of proportion, pain with passive stretch, tense compartment",
    examPearl: "Do not delay fasciotomy for compartment pressure if clinical picture is classic — irreversible ischemia in hours.",
    complications: ["Infection", "Chronic pain", "Nerve injury", "Need for repeat debridement"],
    highYield: true,
  },
  {
    id: "amputation-trauma",
    name: "Traumatic amputation / limb salvage decision",
    structureIds: ["femur", "tibia", "humerus"],
    approach: "open",
    urgency: "emergent",
    indication: "Mangled extremity when limb salvage not viable — life over limb in exsanguinating trauma",
    examPearl: "Mangled Extremity Severity Score (MESS) aids decision-making but clinical judgment dominates.",
    complications: ["Phantom limb pain", "Stump infection", "Psychologic trauma", "Revision surgery"],
    highYield: false,
  },
];
