import type { AnatomyProcedure } from "./types";

export const EXTENDED_PROCEDURES: AnatomyProcedure[] = [
  {
    id: "colonoscopy",
    name: "Colonoscopy with polypectomy",
    structureIds: ["colon"],
    subregionIds: ["colon-sigmoid"],
    approach: "endoscopic",
    urgency: "elective",
    indication: "Colorectal cancer screening, surveillance, diagnostic evaluation of GI bleeding",
    examPearl: "Screening starts at age 45 — remove adenomatous polyps to interrupt the adenoma-carcinoma sequence.",
    complications: ["Perforation", "Bleeding post-polypectomy", "Incomplete prep", "Missed lesions"],
    highYield: true,
  },
  {
    id: "low-anterior-resection",
    name: "Low anterior resection (rectal cancer)",
    structureIds: ["colon", "small-intestine"],
    subregionIds: ["colon-sigmoid"],
    approach: "open",
    urgency: "elective",
    indication: "Mid/low rectal adenocarcinoma after neoadjuvant therapy when sphincter preservation feasible",
    examPearl: "Temporary diverting ileostomy protects low anastomosis — leak is a surgical emergency.",
    complications: ["Anastomotic leak", "Low anterior resection syndrome", "Temporary ileostomy complications"],
    highYield: true,
  },
  {
    id: "tracheostomy",
    name: "Tracheostomy",
    structureIds: ["trachea"],
    subregionIds: ["trachea-carina"],
    approach: "open",
    urgency: "urgent",
    indication: "Prolonged mechanical ventilation, upper airway obstruction, secretions management",
    examPearl: "Percutaneous vs open tracheostomy — avoid high placement injuring cricoid; cuff management prevents stenosis.",
    complications: ["Bleeding", "Subcutaneous emphysema", "Tracheal stenosis", "Accidental decannulation"],
    highYield: true,
  },
  {
    id: "bronchoscopy",
    name: "Flexible bronchoscopy",
    structureIds: ["lungs", "trachea"],
    subregionIds: ["trachea-carina"],
    approach: "endoscopic",
    urgency: "urgent",
    indication: "Hemoptysis workup, foreign body, BAL for infection, staging/endobronchial lesion biopsy",
    examPearl: "Carina is the landmark dividing right vs left main bronchus — right is more vertical for aspiration.",
    complications: ["Hypoxemia", "Bleeding", "Pneumothorax (transbronchial biopsy)", "Laryngospasm"],
    highYield: true,
  },
  {
    id: "cystoscopy",
    name: "Cystoscopy",
    structureIds: ["bladder"],
    subregionIds: ["bladder-trigone"],
    approach: "endoscopic",
    urgency: "urgent",
    indication: "Gross hematuria, bladder cancer surveillance, ureteral stent placement",
    examPearl: "Painless gross hematuria in older adults → cystoscopy and upper tract imaging for urothelial malignancy.",
    complications: ["UTI", "Bleeding", "Bladder perforation", "Urinary retention"],
    highYield: true,
  },
  {
    id: "nephrostomy",
    name: "Percutaneous nephrostomy",
    structureIds: ["kidneys"],
    subregionIds: ["kidney-renal-pelvis"],
    approach: "percutaneous",
    urgency: "urgent",
    indication: "Obstructive uropathy with infection (pyonephrosis), ureteral obstruction when retrograde access fails",
    examPearl: "Infected obstructed kidney is urologic emergency — drain before systemic sepsis worsens.",
    complications: ["Bleeding", "Sepsis", "Colonic injury (rare)", "Tube dislodgement"],
    highYield: true,
  },
  {
    id: "parathyroidectomy",
    name: "Parathyroidectomy",
    structureIds: ["thyroid"],
    subregionIds: ["thyroid-isthmus"],
    approach: "open",
    urgency: "elective",
    indication: "Primary hyperparathyroidism (single adenoma vs multigland disease), refractory secondary HPT in renal failure",
    examPearl: "Stones, bones, groans, moans — hypercalcemia from PTH excess; localize adenoma pre-op when possible.",
    complications: ["Hypocalcemia (hungry bone)", "RLN injury", "Persistent/recurrent HPT", "Bleeding"],
    highYield: true,
  },
  {
    id: "laminectomy-fusion",
    name: "Laminectomy / spinal fusion",
    structureIds: ["vertebral-column", "spinal-cord"],
    subregionIds: ["spinal-cord-cervical"],
    approach: "open",
    urgency: "elective",
    indication: "Spinal stenosis with neurogenic claudication, unstable fracture, tumor decompression",
    examPearl: "Cauda equina syndrome (saddle anesthesia, bladder dysfunction) → emergent decompression — not elective MRI queue.",
    complications: ["Dural tear/CSF leak", "Hardware failure", "Adjacent segment disease", "Infection"],
    highYield: true,
  },
  {
    id: "total-hip-arthroplasty",
    name: "Total hip arthroplasty (THA)",
    structureIds: ["femur"],
    subregionIds: ["femur-neck"],
    approach: "open",
    urgency: "elective",
    indication: "End-stage hip osteoarthritis, avascular necrosis, some femoral neck fractures in active patients",
    examPearl: "Posterior approach hip precautions — avoid hip flexion >90° and internal rotation early post-op.",
    complications: ["Dislocation", "Periprosthetic fracture", "DVT/PE", "Leg length inequality"],
    highYield: true,
  },
  {
    id: "tips",
    name: "Transjugular intrahepatic portosystemic shunt (TIPS)",
    structureIds: ["liver"],
    subregionIds: ["liver-portal-hilum"],
    approach: "endovascular",
    urgency: "urgent",
    indication: "Refractory variceal bleeding, refractory ascites from portal hypertension",
    examPearl: "TIPS reduces portal pressure but can precipitate hepatic encephalopathy — not first-line for all ascites.",
    complications: ["Encephalopathy", "Shunt stenosis/thrombosis", "Hemorrhage", "Contrast nephropathy"],
    highYield: true,
  },
  {
    id: "thoracotomy",
    name: "Emergency thoracotomy",
    structureIds: ["heart", "lungs", "aorta"],
    subregionIds: ["aorta-ascending"],
    approach: "open",
    urgency: "emergent",
    indication: "Penetrating chest trauma with signs of life, massive hemothorax, cardiac tamponade in OR",
    examPearl: "ED thoracotomy survival is highest with penetrating trauma and recent signs of life — not blunt arrest.",
    complications: ["Death", "Coronary/air embolism", "Incomplete hemorrhage control", "Survivor neurologic injury"],
    highYield: true,
  },
  {
    id: "peg-tube",
    name: "Percutaneous endoscopic gastrostomy (PEG)",
    structureIds: ["stomach"],
    subregionIds: ["stomach-pylorus"],
    approach: "endoscopic",
    urgency: "elective",
    indication: "Long-term enteral access when oral intake inadequate (stroke, head and neck cancer, dementia)",
    examPearl: "PEG vs NG tube — PEG for anticipated need >4 weeks; assess goals of care in advanced dementia.",
    complications: ["Site infection", "Buried bumper syndrome", "Aspiration (still possible)", "Peritonitis if misplaced"],
    highYield: true,
  },
  {
    id: "diagnostic-laparoscopy",
    name: "Diagnostic laparoscopy",
    structureIds: ["liver", "spleen", "appendix", "gallbladder"],
    approach: "laparoscopic",
    urgency: "urgent",
    indication: "Uncertain acute abdomen, trauma evaluation, staging of intra-abdominal malignancy",
    examPearl: "Minimally invasive first look — converts to open if hemorrhage or adhesions preclude safe laparoscopy.",
    complications: ["Vascular injury at Veress/trocar entry", "Missed injury", "CO2 embolism (rare)"],
    highYield: false,
  },
];
