import type { DrugEnrichment } from "./types";

/** Concise mechanisms for anatomy-explorer / Top 500 drugs used in curated disease threads. */
export const DRUG_MECHANISM_OVERLAYS: Record<string, Pick<DrugEnrichment, "mechanism">> = {
  acetaminophen: { mechanism: "Central COX inhibition (weak anti-inflammatory)." },
  acetazolamide: { mechanism: "Inhibits CA → bicarbonaturia and diuresis." },
  albuterol: { mechanism: "β2 agonism → bronchial smooth muscle relaxation." },
  alendronate: { mechanism: "Inhibits osteoclast farnesyl pyrophosphate synthase." },
  allopurinol: { mechanism: "Blocks xanthine oxidase → ↓ uric acid." },
  amlodipine: { mechanism: "L-type Ca²⁺ channel block in vascular smooth muscle → vasodilation." },
  amoxicillin: { mechanism: "β-lactam inhibits peptidoglycan cross-linking." },
  apixaban: { mechanism: "Direct factor Xa inhibition → ↓ thrombin generation." },
  aspirin: { mechanism: "Irreversible COX-1 inhibition → ↓ thromboxane A2 → ↓ platelet aggregation." },
  atorvastatin: { mechanism: "HMG-CoA reductase inhibition → ↓ LDL and plaque inflammation." },
  azathioprine: { mechanism: "Purine antimetabolite → ↓ lymphocyte proliferation." },
  azithromycin: { mechanism: "Macrolide binds 50S → inhibits bacterial protein synthesis." },
  baclofen: { mechanism: "GABA-B agonist → ↓ excitatory transmission." },
  bethanechol: { mechanism: "Muscarinic agonist → detrusor contraction." },
  carvedilol: { mechanism: "β1/β2 + α1 blockade → ↓ afterload and sympathetic tone." },
  cefuroxime: { mechanism: "β-lactam cell-wall inhibition." },
  ciprofloxacin: { mechanism: "DNA gyrase/topoisomerase inhibition." },
  cisplatin: { mechanism: "DNA cross-linking → apoptosis." },
  clopidogrel: { mechanism: "Prodrug P2Y12 ADP-receptor blockade on platelets." },
  dexamethasone: { mechanism: "Glucocorticoid receptor agonism." },
  doxazosin: { mechanism: "α1 antagonist → vasodilation." },
  elbasvir: { mechanism: "NS5A inhibitor (with grazoprevir regimens)." },
  enoxaparin: { mechanism: "Accelerates antithrombin inhibition of factor Xa (and IIa)." },
  enzalutamide: { mechanism: "AR signaling inhibitor." },
  esmolol: { mechanism: "Selective β1 blockade (short t½)." },
  fluorouracil: { mechanism: "Thymidylate synthase inhibition." },
  "fluticasone-salmeterol": { mechanism: "ICS anti-inflammatory + LABA sustained β2 bronchodilation." },
  "folic-acid": { mechanism: "Essential cofactor for one-carbon metabolism." },
  fosphenytoin: { mechanism: "Converted to phenytoin → Na⁺ channel blockade." },
  furosemide: { mechanism: "Inhibits NKCC2 in thick ascending limb → natriuresis and diuresis." },
  gabapentin: { mechanism: "α2δ Ca channel ligand → ↓ excitatory release." },
  gemcitabine: { mechanism: "Nucleoside analog → DNA synthesis inhibition." },
  gentamicin: { mechanism: "30S misreading → bactericidal effect." },
  glipizide: { mechanism: "Sulfonylurea closes β-cell KATP channels → insulin release." },
  glucagon: { mechanism: "Raises glucose via hepatic glycogenolysis." },
  "heparin-unfractionated": { mechanism: "ATIII potentiation → inhibits Xa and thrombin; short half-life/reversible." },
  hydralazine: { mechanism: "Direct arteriolar smooth muscle relaxation." },
  hydrochlorothiazide: { mechanism: "Inhibits NCC in distal convoluted tubule → natriuresis." },
  hydrocortisone: { mechanism: "Glucocorticoid (± mineralocorticoid) receptor agonist." },
  ibuprofen: { mechanism: "COX inhibition → ↓ prostaglandins." },
  infliximab: { mechanism: "Monoclonal TNF-α neutralization." },
  "insulin-glargine": { mechanism: "Basal insulin analog forming subcutaneous depot with near peakless profile." },
  "insulin-regular": { mechanism: "Binds insulin receptor → GLUT4 translocation and anabolic metabolism." },
  ipratropium: { mechanism: "Muscarinic (M3) antagonism → ↓ bronchoconstriction." },
  ketamine: { mechanism: "NMDA receptor antagonism." },
  ketoconazole: { mechanism: "Inhibits adrenal steroidogenesis enzymes." },
  labetalol: { mechanism: "α1 + β blockade." },
  lactulose: { mechanism: "Osmotic cathartic + colonic acidification." },
  leuprolide: { mechanism: "Pituitary GnRH receptor downregulation after flare." },
  levetiracetam: { mechanism: "Binds SV2A → modulates neurotransmitter release." },
  levofloxacin: { mechanism: "Fluoroquinolone inhibits DNA gyrase/topoisomerase IV." },
  levothyroxine: { mechanism: "Synthetic T4; deiodinated to T3 → nuclear thyroid receptor activation." },
  lidocaine: { mechanism: "Voltage-gated Na⁺ channel block." },
  liothyronine: { mechanism: "Synthetic T3 binds thyroid receptors directly (short half-life)." },
  lisinopril: { mechanism: "ACE inhibition → ↓ angiotensin II and aldosterone; ↑ bradykinin." },
  lorazepam: { mechanism: "GABA-A positive allosteric modulator → neuronal hyperpolarization." },
  mannitol: { mechanism: "Osmotic diuresis / brain water shift." },
  mesalamine: { mechanism: "Local anti-inflammatory in gut mucosa." },
  methylprednisolone: { mechanism: "Glucocorticoid receptor agonism." },
  metoclopramide: { mechanism: "D2 antagonism + 5-HT4 agonism." },
  metoprolol: { mechanism: "Selective β1 blockade → ↓ HR, contractility demand, and arrhythmia risk." },
  metronidazole: { mechanism: "Nitroimidazole DNA damage under anaerobiosis." },
  mitomycin: { mechanism: "DNA cross-linking alkylator." },
  morphine: { mechanism: "μ-opioid receptor agonism." },
  moxifloxacin: { mechanism: "DNA gyrase inhibition." },
  nafcillin: { mechanism: "β-lactamase-stable cell-wall inhibition." },
  nifedipine: { mechanism: "Vascular L-type Ca²⁺ blockade." },
  nitrofurantoin: { mechanism: "Bacterial enzyme-activated nitroreductase damage to DNA/proteins." },
  octreotide: { mechanism: "Inhibits splanchnic vasodilators / hormone release." },
  omeprazole: { mechanism: "Irreversible H+/K+-ATPase block in parietal cells." },
  ondansetron: { mechanism: "5-HT3 receptor antagonism." },
  oxacillin: { mechanism: "Cell-wall inhibition (penicillinase-stable)." },
  pantoprazole: { mechanism: "Proton pump inhibition → ↓ gastric acid." },
  phenylephrine: { mechanism: "α1 agonism → vasoconstriction." },
  phenytoin: { mechanism: "Voltage-gated Na⁺ channel blockade prolongs inactivated state." },
  "piperacillin-tazobactam": { mechanism: "Cell-wall inhibition + BLI protection." },
  prednisone: { mechanism: "Synthetic glucocorticoid receptor agonist." },
  pregabalin: { mechanism: "α2δ Ca channel ligand." },
  propranolol: { mechanism: "Nonselective β-blockade + partial inhibition of T4→T3 conversion." },
  spironolactone: { mechanism: "Aldosterone receptor antagonist in collecting duct and myocardium." },
  sucralfate: { mechanism: "Forms protective paste over ulcer beds." },
  "sulfamethoxazole-trimethoprim": { mechanism: "Sequential folate synthesis blockade." },
  tamsulosin: { mechanism: "α1A antagonism → prostate/bladder neck smooth muscle relaxation." },
  "tenofovir-disoproxil": { mechanism: "Nucleotide reverse transcriptase inhibition." },
  trastuzumab: { mechanism: "Anti-HER2 monoclonal antibody." },
  vancomycin: { mechanism: "Binds D-Ala-D-Ala → blocks cell-wall synthesis." },
  warfarin: { mechanism: "Vitamin K antagonist → ↓ factors II, VII, IX, X." },
};

