import { defineExamTopics } from "./topic-factory";
import { sigCodeAbbreviationTopic } from "./sig-code-abbreviations";

export const NPTE_PT_HIGH_YIELD_TOPICS = defineExamTopics("npte-pt", [
  {
    slug: "musculoskeletal",
    category: "Musculoskeletal (~28%)",
    title: "Musculoskeletal System",
    overview: "Rotator cuff, ACL rehab, low back pain, manual therapy, and post-op TKA/THA progression.",
    summary:
      "MSK is the largest NPTE-PT domain. Items test examination clusters, special tests, exercise prescription, manual therapy indications, and post-operative protocols for shoulder, spine, hip, and knee.",
    keyConcepts: ["Rotator cuff pathology", "Lumbar radiculopathy", "ACL rehab phases", "TKA precautions", "Manual therapy"],
    mustKnowFacts: ["Empty can vs full can for supraspinatus", "TKA: avoid excessive knee flexion early per protocol"],
    pearls: ["Red flags in low back pain require medical referral before PT progression."],
    pitfalls: ["Aggressive stretching in acute disc herniation", "Ignoring post-op weight-bearing restrictions"],
    practiceTopicSlug: "musculoskeletal",
  },
  {
    slug: "neuromuscular-nervous",
    category: "Neuromuscular (~24%)",
    title: "Neuromuscular & Nervous Systems",
    overview: "Stroke, SCI, TBI, Parkinson, gait training, and balance interventions.",
    summary:
      "Neuromuscular content emphasizes motor recovery principles, neuroplasticity-driven repetition, gait and balance progressions, wheelchair mobility, and lesion-level implications for SCI.",
    keyConcepts: ["Stroke rehab", "SCI levels", "TBI stages", "Parkinson cues", "Balance training"],
    mustKnowFacts: ["SCI ASIA impairment scale guides prognosis", "External cues help bradykinesia in Parkinson disease"],
    pearls: ["High repetitions with task-specific practice drive neuroplasticity."],
    pitfalls: ["Overlooking autonomic dysreflexia in SCI", "Treating all gait deviations the same"],
    practiceTopicSlug: "neuromuscular-nervous",
  },
  {
    slug: "cardiovascular-pulmonary",
    category: "Cardiopulmonary (10%)",
    title: "Cardiovascular & Pulmonary Systems",
    overview: "COPD, CHF, post-MI rehab, oxygen titration, and airway clearance.",
    summary:
      "Cardiopulmonary items test exercise prescription in chronic lung and heart disease, pulse oximetry targets, energy conservation, breathing techniques, and safe progression after cardiac events.",
    keyConcepts: ["COPD exercise", "CHF activity guidelines", "Post-MI rehab", "Oxygen titration", "Airway clearance"],
    mustKnowFacts: ["COPD retainers: avoid hyperoxia", "RPE scales useful when SpO₂ monitoring limited"],
    pearls: ["Pursed-lip breathing reduces dynamic hyperinflation in COPD."],
    pitfalls: ["High-intensity exercise in unstable angina", "Skipping bronchodilator timing before airway clearance"],
    practiceTopicSlug: "cardiovascular-pulmonary",
  },
  {
    slug: "integumentary",
    category: "Integumentary (4%)",
    title: "Integumentary System",
    overview: "Pressure injury staging, wound care, and burn rehabilitation.",
    summary: "Integumentary content covers pressure injury prevention, positioning, wound bed preparation, and mobility considerations with open wounds or burns.",
    keyConcepts: ["Pressure injury staging", "Offloading", "Wound care principles", "Burn contracture prevention"],
    mustKnowFacts: ["Stage 1 = non-blanchable erythema intact skin", "Reposition at least every 2 hours in bed-bound patients"],
    pearls: ["Shear forces at the sacrum are reduced with proper bed elevation."],
    pitfalls: ["Massaging blanchable erythema", "Ambulation without offloading heel ulcers"],
    practiceTopicSlug: "integumentary",
  },
  {
    slug: "therapeutic-modalities",
    category: "Therapeutic Modalities (2%)",
    title: "Therapeutic Modalities",
    overview: "Ultrasound, TENS, NMES, cryotherapy, and heat — parameters and contraindications.",
    summary: "Modality items test appropriate parameter selection, tissue depth, treatment duration, and contraindications including pregnancy, malignancy, and impaired sensation.",
    keyConcepts: ["US parameters", "TENS modes", "NMES indications", "Cryotherapy", "Superficial vs deep heat"],
    mustKnowFacts: ["US contraindicated over malignancy, pregnancy, acute infection", "NMES for muscle re-education requires adequate innervation"],
    pearls: ["Continuous US for chronic conditions; pulsed for acute inflammation."],
    pitfalls: ["Heat over acute inflammation", "TENS pads over anterior neck/carotid"],
    practiceTopicSlug: "therapeutic-modalities",
  },
  {
    slug: "safety-protection",
    category: "Safety & Protection (2.4%)",
    title: "Safety & Protection",
    overview: "Falls prevention, body mechanics, infection control, and bloodborne pathogen precautions.",
    summary: "Safety content emphasizes fall risk assessment, safe transfers, standard precautions, and ergonomic lifting for clinicians and patients.",
    keyConcepts: ["Fall risk", "Transfer techniques", "BBP", "Infection control", "Body mechanics"],
    mustKnowFacts: ["Wide base of support and hip hinge reduce clinician injury", "Hand hygiene is first-line infection prevention"],
    pearls: ["Timed Up and Go >12 seconds suggests elevated fall risk."],
    pitfalls: ["Pulling from under patient's arms during transfer", "Reusing gloves between patients"],
    practiceTopicSlug: "safety-protection",
  },
  {
    slug: "equipment-devices",
    category: "Equipment & Devices (2.2%)",
    title: "Equipment, Devices & Technologies",
    overview: "Wheelchairs, ambulatory aids, prosthetics, and orthotics selection.",
    summary: "Equipment items test proper assistive device fitting, wheelchair propulsion, prosthetic gait training, and orthotic indications.",
    keyConcepts: ["Walker vs cane", "Wheelchair fit", "Prosthetic gait", "AFO indications"],
    mustKnowFacts: ["Cane used on contralateral side to involved LE", "Seat width = hip width + 2 inches"],
    pearls: ["Forearm crutches require adequate UE strength and coordination."],
    pitfalls: ["Cane on same side as weak leg", "Wheelchair seat too deep causing sacral pressure"],
    practiceTopicSlug: "equipment-devices",
  },
  {
    slug: "professional-responsibilities",
    category: "Professional Practice (1.8%)",
    title: "Professional Responsibilities",
    overview: "Ethics, documentation, supervision, and scope of practice.",
    summary: "Professional practice items test informed consent, referral when outside scope, accurate documentation, and supervision requirements for support personnel.",
    keyConcepts: ["Informed consent", "Referral", "Documentation", "Supervision", "Scope"],
    mustKnowFacts: ["PTs must refer when findings suggest conditions outside PT scope", "Co-signatures per state practice act for PTA services"],
    pearls: ["Objective, measurable goals support medical necessity and reimbursement."],
    pitfalls: ["Practicing outside state licensure", "Vague documentation without functional measures"],
    practiceTopicSlug: "professional-responsibilities",
  },
  {
    slug: "system-interactions",
    category: "System Interactions (~5%)",
    title: "Pediatrics, Geriatrics & Acute Care",
    overview: "CP, torticollis, falls prevention, ICU mobilization, oncology fatigue, and lifespan modifiers.",
    summary:
      "System interactions content spans pediatric developmental conditions, geriatric fall risk, acute care/ICU early mobility, and oncology-related deconditioning — often tested as cross-cutting vignettes.",
    keyConcepts: ["Cerebral palsy", "Torticollis", "Falls prevention", "ICU mobilization", "Oncology fatigue"],
    mustKnowFacts: ["TUG >12 seconds suggests elevated fall risk", "Infant torticollis needs early stretching, not delayed treatment"],
    pearls: ["ICU mobility requires team coordination and line/tube precautions."],
    pitfalls: ["Treating pediatric CP with passive-only care", "Deferring all ICU mobility regardless of stability"],
    practiceTopicSlug: "system-interactions",
  },
  {
    slug: "genitourinary",
    category: "Genitourinary (~2%)",
    title: "Pelvic Floor & Women's Health",
    overview: "Urinary incontinence, pelvic floor training, and pregnancy-related pain.",
    summary: "GU content tests stress vs urge incontinence, supervised pelvic floor muscle training, and pregnancy-related musculoskeletal pain management.",
    keyConcepts: ["Stress incontinence", "Pelvic floor training", "Pregnancy pain", "Post-prostatectomy rehab"],
    mustKnowFacts: ["PFMT is first-line for stress urinary incontinence", "Oxford scale grades pelvic floor strength"],
    pearls: ["Functional integration of pelvic floor contractions with daily activities improves outcomes."],
    pitfalls: ["High-impact exercise before pelvic floor training in postpartum stress incontinence"],
    practiceTopicSlug: "genitourinary",
  },
  {
    slug: "lymphatic",
    category: "Lymphatic (~3%)",
    title: "Lymphedema Management",
    overview: "Complete decongestive therapy, compression, and oncology-related lymphedema.",
    summary: "Lymphatic items test CDT components — manual lymph drainage, compression bandaging/garments, skin care, and therapeutic exercise.",
    keyConcepts: ["CDT", "Compression", "MLD", "Oncology lymphedema"],
    mustKnowFacts: ["CDT combines MLD, compression, skin care, and exercise", "Monitor for infection in lymphedematous limbs"],
    pearls: ["Compression is essential — exercise alone without compression is insufficient for lymphedema."],
    pitfalls: ["Heat application over infected or congested limb", "Aggressive resistance without compression garment"],
    practiceTopicSlug: "lymphatic",
  },
  {
    slug: "research-evidence",
    category: "Research & EBP (~2%)",
    title: "Evidence-Based Practice",
    overview: "Sensitivity/specificity, outcome measures, MCID, and RCT appraisal.",
    summary: "Research content distinguishes statistical vs clinical significance, interprets diagnostic test properties, and applies MCID to outcome measure changes.",
    keyConcepts: ["Sensitivity", "Specificity", "MCID", "RCT appraisal", "Likelihood ratios"],
    mustKnowFacts: ["p < 0.05 does not guarantee clinical importance — compare to MCID", "High sensitivity helps rule out disease"],
    pearls: ["Apply MCID when interpreting outcome measure changes in clinical trials."],
    pitfalls: ["Equating statistical significance with patient-meaningful improvement"],
    practiceTopicSlug: "research-evidence",
  },
  sigCodeAbbreviationTopic("npte-pt"),
]);
