import { defineExamTopics } from "./topic-factory";

export const PANCE_HIGH_YIELD_TOPICS = defineExamTopics("pance", [
  {
    slug: "cardiovascular",
    category: "Cardiovascular (11%)",
    title: "Cardiovascular System",
    overview: "ACS, heart failure, arrhythmias, hypertension, valvular disease, and shock recognition.",
    summary:
      "Cardiovascular content (~11% of PANCE) spans chest pain workup, ECG interpretation, acute coronary syndromes, heart failure management, arrhythmia selection, hypertensive emergencies, and hemodynamic shock. Items emphasize next-best diagnostic step and first-line therapy.",
    keyConcepts: ["ACS pathways", "Heart failure GDMT", "Arrhythmia management", "Hypertensive emergency", "Shock differentiation"],
    mustKnowFacts: ["STEMI requires reperfusion within guideline windows", "HFrEF four-pillar therapy"],
    pearls: ["Atypical MI presentations are common in older adults and diabetics."],
    pitfalls: ["Missing posterior MI on standard 12-lead", "Beta-blockers in acute decompensated HF"],
    practiceTopicSlug: "cardiovascular",
  },
  {
    slug: "pulmonary",
    category: "Pulmonary (9%)",
    title: "Pulmonary System",
    overview: "COPD, asthma, pneumonia, PE, pleural disease, and oxygen therapy.",
    summary:
      "Pulmonary items test dyspnea evaluation, COPD/asthma exacerbation management, CAP/HAP antibiotic selection, PE risk stratification and anticoagulation, pleural effusion workup, and safe oxygen delivery.",
    keyConcepts: ["COPD exacerbation", "Asthma step therapy", "PE workup", "Pneumonia severity", "Oxygen titration"],
    mustKnowFacts: ["Wells score guides PE pretest probability", "COPD: bronchodilator first, steroids when indicated"],
    pearls: ["Silent hypoxia can occur without distress — check SpO₂ early."],
    pitfalls: ["Over-oxygenating COPD patients", "Missing massive PE hemodynamic instability"],
    practiceTopicSlug: "pulmonary",
  },
  {
    slug: "gastrointestinal",
    category: "GI & Nutrition (8%)",
    title: "Gastrointestinal / Nutrition",
    overview: "GERD, pancreatitis, hepatitis, IBD, GI bleeding, and malnutrition.",
    summary:
      "GI content covers upper and lower GI bleeding algorithms, acute pancreatitis severity, liver enzyme patterns, IBD flares, biliary disease, and nutrition assessment in hospitalized patients.",
    keyConcepts: ["GI bleed localization", "Pancreatitis Ranson/BISAP", "Hepatitis serologies", "IBD maintenance", "Malnutrition screening"],
    mustKnowFacts: ["Upper GI bleed: PPI + endoscopy timing", "Acute pancreatitis: aggressive IV fluids early"],
    pearls: ["Coffee-ground emesis suggests upper GI source."],
    pitfalls: ["Missing variceal bleed in cirrhosis", "Delaying ERCP in ascending cholangitis"],
    practiceTopicSlug: "gastrointestinal",
  },
  {
    slug: "musculoskeletal",
    category: "Musculoskeletal (8%)",
    title: "Musculoskeletal System",
    overview: "Fractures, arthritis, back pain, compartment syndrome, and gout.",
    summary:
      "MSK vignettes include acute fracture management, septic vs inflammatory arthritis, red-flag back pain, compartment syndrome after trauma, gout/pseudogout crystals, and common overuse injuries.",
    keyConcepts: ["Septic arthritis", "Compartment syndrome", "Red-flag back pain", "Gout diagnosis", "Fracture stabilization"],
    mustKnowFacts: ["Septic joint: aspirate before antibiotics when feasible", "Compartment syndrome: pain out of proportion + pallor/pulselessness late"],
    pearls: ["Monoarticular hot joint is septic until proven otherwise."],
    pitfalls: ["Missing cauda equina red flags", "Treating gout flare with new urate-lowering without prophylaxis"],
    practiceTopicSlug: "musculoskeletal",
  },
  {
    slug: "infectious-diseases",
    category: "Infectious Diseases (7%)",
    title: "Infectious Diseases",
    overview: "Sepsis, HIV, TB, meningitis, skin infections, and antibiotic selection.",
    summary:
      "ID items emphasize sepsis bundle timing, empiric antibiotic selection by syndrome, HIV initial workup and OI prophylaxis, TB screening and treatment, meningitis empiric coverage, and SSTI management.",
    keyConcepts: ["Sepsis resuscitation", "Empiric antibiotics", "HIV initial evaluation", "Meningitis coverage", "MRSA risk factors"],
    mustKnowFacts: ["Sepsis: blood cultures before antibiotics when possible", "Neonatal meningitis coverage differs from adult"],
    pearls: ["Petechial rash + fever → consider meningococcemia."],
    pitfalls: ["Vancomycin monotherapy for CAP without MRSA risk", "Missing TB in chronic cough with weight loss"],
    practiceTopicSlug: "infectious-diseases",
  },
  {
    slug: "neurologic",
    category: "Neurologic (7%)",
    title: "Neurologic System",
    overview: "Stroke, seizure, headache, MS, and peripheral neuropathy.",
    summary:
      "Neurology content spans acute stroke tPA/thrombectomy windows, seizure first-break workup, thunderclap vs tension headache, MS relapse vs mimic, and diabetic/peripheral neuropathy patterns.",
    keyConcepts: ["Stroke tPA eligibility", "Status epilepticus", "Headache red flags", "MS diagnosis", "Neuropathy workup"],
    mustKnowFacts: ["tPA window and contraindications", "Thunderclap headache → exclude SAH"],
    pearls: ["ABCD² helps TIA risk stratification."],
    pitfalls: ["Missing posterior circulation stroke", "Attributing all neuropathy to diabetes without workup"],
    practiceTopicSlug: "neurologic",
  },
  {
    slug: "psychiatry",
    category: "Psychiatry & Behavioral (7%)",
    title: "Psychiatry / Behavioral Science",
    overview: "Depression, anxiety, psychosis, substance use, and suicide risk.",
    summary:
      "Behavioral health items test MDD vs bipolar screening, SSRI selection and monitoring, anxiety disorder hierarchy, first-break psychosis workup, alcohol/benzodiazepine withdrawal, and suicide risk assessment.",
    keyConcepts: ["Suicide risk assessment", "Antidepressant selection", "Psychosis workup", "Substance withdrawal", "Capacity evaluation"],
    mustKnowFacts: ["SSRI activation in young adults — close follow-up", "Alcohol withdrawal: CIWA-guided benzodiazepines"],
    pearls: ["Always ask about firearms and plan when suicidal ideation is present."],
    pitfalls: ["SSRI monotherapy in bipolar depression", "Missing delirium mimicking primary psychosis"],
    practiceTopicSlug: "psychiatry",
  },
  {
    slug: "reproductive",
    category: "Reproductive (7%)",
    title: "Reproductive System",
    overview: "Pregnancy complications, STIs, contraception, and gynecologic emergencies.",
    summary:
      "Reproductive content includes first-trimester bleeding differential, preeclampsia/eclampsia management, ectopic pregnancy, PID treatment, contraception counseling, and menopause symptoms.",
    keyConcepts: ["Ectopic pregnancy", "Preeclampsia severity", "PID regimens", "Contraception selection", "STI screening"],
    mustKnowFacts: ["Rhogam for Rh-negative bleeding in pregnancy", "Magnesium for eclampsia seizure prophylaxis"],
    pearls: ["Beta-hCG discriminatory zone helps ectopic evaluation."],
    pitfalls: ["Missing ruptured ectopic", "Tetracyclines in pregnancy"],
    practiceTopicSlug: "reproductive",
  },
  {
    slug: "endocrine",
    category: "Endocrine (6%)",
    title: "Endocrine System",
    overview: "Diabetes, thyroid, adrenal, DKA, and hypoglycemia.",
    summary:
      "Endocrine items cover DKA/HHS management, insulin regimens, hypoglycemia treatment, hyper/hypothyroidism, adrenal insufficiency crisis, and calcium disorders linked to parathyroid disease.",
    keyConcepts: ["DKA protocol", "Thyroid storm", "Adrenal crisis", "Diabetes pharmacotherapy", "Hypoglycemia rules"],
    mustKnowFacts: ["DKA: fluids + insulin; potassium before insulin if low", "Myxedema coma needs thyroid replacement + steroids"],
    pearls: ["Check glucose before treating altered mental status."],
    pitfalls: ["Stopping insulin in DKA too early", "Missing adrenal crisis in chronic steroid use"],
    practiceTopicSlug: "endocrine",
  },
  {
    slug: "eent",
    category: "EENT (6%)",
    title: "Eyes, Ears, Nose & Throat",
    overview: "Red eye, hearing loss, sinusitis, pharyngitis, and vertigo.",
    summary:
      "EENT vignettes include acute angle-closure glaucoma, retinal detachment red flags, otitis media vs externa, BPPV vs central vertigo, strep pharyngitis criteria, and epistaxis management.",
    keyConcepts: ["Red eye emergencies", "Hearing loss workup", "Vertigo differentiation", "Strep testing", "Sinusitis duration"],
    mustKnowFacts: ["Painful red eye + fixed pupil → angle closure", "Centor criteria guide strep testing"],
    pearls: ["Dix-Hallpike confirms BPPV."],
    pitfalls: ["Missing orbital cellulitis", "Antibiotics for viral pharyngitis"],
    practiceTopicSlug: "eent",
  },
  {
    slug: "hematologic",
    category: "Hematologic (5%)",
    title: "Hematologic System",
    overview: "Anemia, coagulopathy, thrombocytopenia, and leukemia workup.",
    summary:
      "Hematology content spans microcytic vs macrocytic anemia workup, DIC recognition, ITP vs TTP, anticoagulant reversal basics, and when to refer for bone marrow evaluation.",
    keyConcepts: ["Anemia classification", "Coagulopathy panels", "ITP management", "Transfusion triggers", "Leukocytosis workup"],
    mustKnowFacts: ["Iron studies before iron replacement", "TTP: schistocytes + low ADAMTS13 — plasmapheresis"],
    pearls: ["Reticulocyte count separates production vs loss."],
    pitfalls: ["Oral iron with active GI bleed without endoscopy plan", "Missing HIT on heparin"],
    practiceTopicSlug: "hematologic",
  },
  {
    slug: "renal",
    category: "Renal (5%)",
    title: "Renal System",
    overview: "AKI, CKD, electrolytes, acid-base, and dialysis indications.",
    summary:
      "Renal items test prerenal vs intrinsic vs postrenal AKI, hyperkalemia ECG changes and treatment, hyponatremia correction rate, metabolic acidosis differentials, and dialysis initiation criteria.",
    keyConcepts: ["AKI staging", "Hyperkalemia treatment", "Hyponatremia correction", "Acid-base interpretation", "Dialysis indications"],
    mustKnowFacts: ["Hyperkalemia: calcium first if ECG changes", "Correct Na slowly to avoid osmotic demyelination"],
    pearls: ["FeNa helps prerenal vs ATN when on diuretics use FeUrea."],
    pitfalls: ["Normal saline in hypervolemic hyponatremia", "Missing postrenal obstruction"],
    practiceTopicSlug: "renal",
  },
  {
    slug: "dermatologic",
    category: "Dermatologic (4%)",
    title: "Dermatologic System",
    overview: "Rash patterns, cellulitis, melanoma screening, and drug eruptions.",
    summary:
      "Dermatology vignettes include cellulitis vs necrotizing infection, psoriasis vs eczema, drug rash with eosinophilia, melanoma ABCDE criteria, and shingles antiviral timing.",
    keyConcepts: ["Cellulitis vs abscess", "Psoriasis therapy", "Drug eruption", "Melanoma screening", "Herpes zoster"],
    mustKnowFacts: ["Antivirals within 72h of rash onset for zoster", "Necrotizing fasciitis: surgical emergency"],
    pearls: ["Unilateral dermatomal rash suggests zoster."],
    pitfalls: ["Missing Stevens-Johnson from new medication", "Biologics without TB screening"],
    practiceTopicSlug: "dermatologic",
  },
  {
    slug: "genitourinary",
    category: "Genitourinary (4%)",
    title: "Genitourinary System",
    overview: "UTI, BPH, nephrolithiasis, and urologic emergencies.",
    summary:
      "GU content covers uncomplicated vs complicated UTI antibiotics, acute urinary retention, BPH medical vs surgical therapy, kidney stone analgesia and imaging, and testicular torsion time sensitivity.",
    keyConcepts: ["UTI classification", "BPH management", "Nephrolithiasis", "Testicular torsion", "Acute retention"],
    mustKnowFacts: ["Torsion: surgical detorsion within 6 hours", "Flank pain + hematuria → stone until proven otherwise"],
    pearls: ["Prehn sign is unreliable — Doppler if torsion suspected."],
    pitfalls: ["Missing epididymitis vs torsion", "Fluoroquinolones first-line for uncomplicated cystitis in young women"],
    practiceTopicSlug: "genitourinary",
  },
  {
    slug: "professional-practice",
    category: "Professional Practice (6%)",
    title: "Professional Practice",
    overview: "Ethics, informed consent, scope of practice, patient safety, and documentation.",
    summary:
      "Professional practice items test informed consent elements, capacity vs competence, mandatory reporting, error disclosure, scope of practice boundaries, HIPAA basics, and quality improvement concepts.",
    keyConcepts: ["Informed consent", "Capacity assessment", "Mandatory reporting", "Error disclosure", "Scope of practice"],
    mustKnowFacts: ["Consent requires understanding, voluntariness, and disclosure", "Impaired colleague reporting duties vary by state"],
    pearls: ["Document shared decision-making, not just the signature."],
    pitfalls: ["Assuming spouse can consent for competent adult", "Continuing beyond scope without collaboration"],
    practiceTopicSlug: "professional-practice",
  },
]);
