import { defineExamTopics } from "./topic-factory";

/** Additional NCLEX high-yield cards — health promo, pharm depth, risk reduction, NGN. */
export const NCLEX_EXTENDED_TOPICS = defineExamTopics("nclex", [
  {
    slug: "disaster-triage",
    category: "Management of Care",
    title: "Disaster Triage & Mass Casualty",
    overview: "START triage tags, RPM assessment, and ethical resource allocation during mass casualty incidents.",
    summary:
      "Mass casualty incidents (MCIs) require rapid sorting when resources cannot meet demand. The START triage system uses Respirations, Perfusion, and Motor status to assign tags: Immediate (red), Delayed (yellow), Minimal (green), and Expectant (black).\n\nAdults who are apneic after a simple airway maneuver may be tagged expectant in START when resources are scarce — the goal is greatest good for the greatest number. Walking wounded are tagged green and directed to minor treatment. RN roles shift to triage officer and coordination rather than prolonged bedside care.",
    keyConcepts: [
      "START: RPM — respirations, perfusion (cap refill/mental status), motor (follow commands)",
      "Red = immediate life-threatening but salvageable injuries",
      "Yellow = serious injuries that can wait for treatment",
      "Green = ambulatory minor injuries",
      "Black = deceased or expectant (non-survivable given resources)",
      "Reverse triage for evacuations when infrastructure fails",
    ],
    mustKnowFacts: [
      "During MCI, tag and move — do not provide prolonged ICU-level care at the scene",
      "Decontamination before treatment in radiation/chemical events when feasible",
    ],
    pearls: ["Document triage tag color and time on each patient"],
    pitfalls: ["Treating the nearest patient first regardless of survivability"],
    practiceTopicSlug: "management-of-care",
  },
  {
    slug: "quality-improvement",
    category: "Management of Care",
    title: "Quality Improvement & Incident Reporting",
    overview: "Root cause analysis, sentinel events, near-miss reporting, and nursing role in patient safety systems.",
    summary:
      "Quality improvement (QI) is a continuous process to reduce errors and harm. Nurses report incidents, near misses, and sentinel events without punitive culture when systems fail. Root cause analysis (RCA) asks why an event occurred at the system level — not who to blame.\n\nStandardized handoffs, barcode scanning, and double-checks for high-alert meds are QI interventions tested on NCLEX as error-prevention strategies.",
    keyConcepts: [
      "Incident report documents facts objectively — not blame",
      "Near-miss reporting prevents future harm",
      "Root cause analysis: system-focused investigation",
      "Sentinel event: unexpected death or serious injury",
      "Nursing role: advocate, document, report unsafe assignments",
    ],
    mustKnowFacts: ["Refuse unsafe assignments and chain-of-command escalate"],
    pearls: ["Barcode med administration reduces wrong-patient errors"],
    pitfalls: ["Completing incident report with opinion or blame language"],
    practiceTopicSlug: "management-of-care",
  },
  {
    slug: "immunization-schedules",
    category: "Health Promotion",
    title: "Immunization Schedules & Contraindications",
    overview: "CDC schedule milestones, live vs inactivated vaccines, pregnancy rules, and post-exposure prophylaxis.",
    summary:
      "Immunization is a cornerstone of health promotion on NCLEX. Live attenuated vaccines (MMR, varicella, LAIV, rotavirus) are contraindicated in pregnancy and severe immunocompromise. Inactivated vaccines are generally safer in immunosuppressed patients though response may be reduced.\n\nDocument lot number, site, and Vaccine Information Statement (VIS). Infant series at 2, 4, 6 months includes DTaP, IPV, Hib, PCV13, and rotavirus. Tdap is recommended each pregnancy at 27–36 weeks for pertussis protection in the newborn.",
    keyConcepts: [
      "Live vaccines: MMR, varicella — avoid in pregnancy and severe immunosuppression",
      "Inactivated vaccines: Tdap, IPV, injected flu — broader safety profile",
      "HBV post-exposure: HBIG + vaccine series for non-immune HCW after needlestick",
      "Storage: maintain cold chain; check expiration",
      "Report anaphylaxis; epinephrine available at vaccination sites",
    ],
    mustKnowFacts: ["Never give MMR to pregnant patient — verify immunity, vaccinate postpartum if needed"],
    pearls: ["Egg allergy is not automatic flu vaccine contraindication per current guidance"],
    pitfalls: ["Administering live vaccines during active chemotherapy without specialist plan"],
    practiceTopicSlug: "health-promotion",
  },
  {
    slug: "prenatal-labor-monitoring",
    category: "Health Promotion",
    title: "Prenatal Care & Fetal Monitoring",
    overview: "Prenatal assessment, preeclampsia screening, FHR patterns, and intrapartum decelerations.",
    summary:
      "Prenatal nursing focuses on BP trends, proteinuria, fundal height, glucose screening, and fetal heart rate monitoring. Preeclampsia presents with BP elevation, proteinuria, headache, visual changes, RUQ pain, and hyperreflexia.\n\nFHR baseline 110–160 with moderate variability is reassuring. Late decelerations suggest uteroplacental insufficiency — reposition, O₂, IV fluids, notify provider. Variable decelerations suggest cord compression — maternal position change.",
    keyConcepts: [
      "Preeclampsia: BP ↑, proteinuria, headache, vision changes, RUQ pain, clonus",
      "FHR Category III = ominous — immediate evaluation",
      "Late decels = uteroplacental insufficiency",
      "Variable decels = cord compression",
      "Magnesium sulfate for severe preeclampsia — monitor DTRs and RR",
    ],
    mustKnowFacts: ["Late decelerations require intervention — not benign"],
    pearls: ["Count fetal kicks in third trimester"],
    pitfalls: ["Dismissing headache as normal pregnancy discomfort without BP check"],
    practiceTopicSlug: "maternal-child",
  },
  {
    slug: "newborn-assessment",
    category: "Health Promotion",
    title: "Newborn Assessment & APGAR",
    overview: "Transition to extrauterine life, APGAR scoring, reflexes, and early bonding/safety.",
    summary:
      "Newborn priority is airway, warmth, drying, and stimulation. APGAR at 1 and 5 minutes assesses Appearance, Pulse, Grimace, Activity, Respiration — scores 7–10 generally reassuring.\n\nVitamin K and erythromycin eye prophylaxis given per protocol. Assess for respiratory distress, cyanosis, and feeding readiness. Safe sleep teaching: supine, firm surface, no loose bedding.",
    keyConcepts: [
      "APGAR 1 and 5 min — not used to decide resuscitation initiation alone",
      "Vitamin K IM prevents hemorrhagic disease of newborn",
      "Erythromycin eye ointment prevents ophthalmia neonatorum",
      "Safe sleep: supine, alone, firm crib",
      "Bonding and breastfeeding support early",
    ],
    mustKnowFacts: ["Resuscitation decisions based on HR and resp effort — not APGAR alone"],
    pearls: ["Morо and rooting reflexes present normally"],
    pitfalls: ["Placing newborn prone for sleep"],
    practiceTopicSlug: "maternal-child",
  },
  {
    slug: "developmental-milestones",
    category: "Health Promotion",
    title: "Growth & Developmental Milestones",
    overview: "Erikson and Piaget pearls, Denver Developmental screening, and age-appropriate communication.",
    summary:
      "Health promotion items test developmental milestones and psychosocial stages. Erikson stages include trust vs mistrust (infancy), autonomy vs shame (toddler), initiative vs guilt (preschool). Piaget: sensorimotor, preoperational, concrete operational.\n\nRed flags: no babbling by 12 months, no words by 16 months, loss of acquired skills. Always use age-appropriate explanations and include caregivers in teaching.",
    keyConcepts: [
      "Infant: social smile ~2 months, sits ~6 months, walks ~12 months",
      "Toddler: autonomy — offer choices, set limits",
      "Preschool: magical thinking — simple concrete explanations",
      "Adolescent: identity formation — confidential sensitive topics when appropriate",
      "Older adult: integrity vs despair — respect life review",
    ],
    mustKnowFacts: ["Regression or loss of milestones warrants referral"],
    pearls: ["Denver II screens fine and gross motor, language, personal-social"],
    pitfalls: ["Expecting abstract reasoning in preschooler"],
    practiceTopicSlug: "health-promotion",
  },
  {
    slug: "dosage-calculations",
    category: "Reduction of Risk Potential",
    title: "Dosage Calculations & IV Drip Rates",
    overview: "Weight-based dosing, D/H×Q formula, mL/hr, reconstitution, and high-alert concentration checks.",
    summary:
      "Dosage calculation items are pass/fail on NCLEX. Convert pounds to kg first (÷ 2.2). Use Desired/Having × Quantity for mL. Drip rate mL/hr = total volume ÷ hours.\n\nVerify insulin U-100 vs U-500 concentration. Independent double-check heparin and insulin drips. Round per policy — oral liquids often to tenths.",
    keyConcepts: [
      "lb ÷ 2.2 = kg for weight-based dosing",
      "D/H × Q = mL to administer",
      "mL/hr = volume ÷ hours for pump",
      "Reconstitution changes concentration — label final mg/mL",
      "Insulin and heparin are high-alert — double-check",
    ],
    mustKnowFacts: ["Never use lb directly in mg/kg formula without conversion"],
    pearls: ["Unit cancellation catches most trap answers"],
    pitfalls: ["Confusing mg with mL on syringe"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "critical-lab-values",
    category: "Reduction of Risk Potential",
    title: "Critical Lab Values & Diagnostics",
    overview: "Potassium, sodium, glucose, troponin, INR, CBC critical values and nursing notification actions.",
    summary:
      "Reduction of Risk Potential tests interpretation of critical labs and diagnostic trends. Critical hyperkalemia causes peaked T waves — cardiac monitor and emergency treatment per order. Critical INR on warfarin — hold and assess bleeding.\n\nTroponin trend supports ACS diagnosis. Neutropenia after chemo — fever is emergency. Always correlate labs with clinical assessment.",
    keyConcepts: [
      "Critical K⁺: ECG changes, hold contributing meds, treat per order",
      "Critical glucose <70: 15-15 rule",
      "Troponin trend with chest pain = ACS workup",
      "Critical INR: hold warfarin, bleeding assessment",
      "ANC low: neutropenic precautions, fever protocol",
    ],
    mustKnowFacts: ["Notify provider for critical values per institutional protocol — document"],
    pearls: ["Trend beats single isolated value"],
    pitfalls: ["Rapid sodium correction in chronic hyponatremia"],
    practiceTopicSlug: "reduction-risk",
  },
  {
    slug: "pre-post-procedure",
    category: "Reduction of Risk Potential",
    title: "Pre & Post-Procedure Care",
    overview: "NPO guidelines, informed consent, contrast precautions, and post-procedure complication monitoring.",
    summary:
      "Pre-procedure nursing ensures informed consent, NPO status, medication holds (metformin, anticoagulants per orders), allergies, and baseline vitals. Post-procedure monitor airway, bleeding, vitals, and procedure-specific complications.\n\nAfter angiography: assess insertion site, distal pulses, neurovascular checks. After colonoscopy: monitor for perforation/bleeding signs. Contrast: hydration and creatinine monitoring.",
    keyConcepts: [
      "NPO per protocol — typically solids 6–8 h, clear liquids 2 h (institution varies)",
      "Verify consent and allergies before transport",
      "Hold anticoagulants/metformin per surgeon/radiology orders",
      "Post-procedure: ABC, vitals, site, pain, specific complication signs",
      "Contrast nephropathy prevention: IV fluids per protocol",
    ],
    mustKnowFacts: ["Check insertion site and distal circulation after vascular procedures"],
    pearls: ["Signed consent must be in chart before elective procedures"],
    pitfalls: ["Sending patient to test without verifying NPO or consent"],
    practiceTopicSlug: "reduction-risk",
  },
  {
    slug: "chemotherapy-toxicity",
    category: "Reduction of Risk Potential",
    title: "Chemotherapy & Neutropenic Precautions",
    overview: "Chemo side effects, nadir timing, neutropenic fever, and protective isolation principles.",
    summary:
      "Chemotherapy nursing emphasizes infection prevention during nadir, emesis control, mucositis care, and extravasation management. Neutropenic fever (single oral temp ≥100.4°F or sustained ≥100°F) is an oncologic emergency — cultures and broad-spectrum antibiotics per protocol.\n\nAvoid live vaccines during treatment. No rectal temps or enemas in neutropenia. Hand hygiene and visitor illness screening.",
    keyConcepts: [
      "Neutropenic fever = emergency — notify immediately",
      "Nadir typically 7–14 days post-cycle depending on agent",
      "Avoid crowds, raw foods, sick contacts when ANC low",
      "Extravasation: stop infusion, elevate, notify — vesicant protocols",
      "Chemo PPE for nurses preparing/administering",
    ],
    mustKnowFacts: ["Never give live vaccines during active chemotherapy without oncology guidance"],
    pearls: ["ANC threshold for precautions often <500 — follow protocol"],
    pitfalls: ["Delaying fever workup waiting for morning labs in neutropenic patient"],
    practiceTopicSlug: "reduction-risk",
  },
  {
    slug: "gi-emergencies",
    category: "Physiological Adaptation",
    title: "GI Bleed, Pancreatitis & Liver Failure",
    overview: "Upper/lower GI bleeding, NG decompression, pancreatitis NPO/fluids, and hepatic encephalopathy.",
    summary:
      "GI emergencies require hemodynamic monitoring and NPO status. Upper GI bleed: hematemesis, melena — IV access, type & cross, PPI per order. Pancreatitis: severe epigastric pain, NPO, aggressive IV fluids, monitor glucose and calcium.\n\nHepatic encephalopathy: confusion, asterixis — lactulose per order, safety precautions, reduce ammonia-producing foods/meds.",
    keyConcepts: [
      "GI bleed: orthostatic vitals, Hgb trend, NPO, notify",
      "Pancreatitis: NPO, fluids, pain control — monitor complications",
      "Encephalopathy: lactulose, avoid sedatives, fall precautions",
      "Bowel obstruction: NG suction, strict NPO, electrolyte monitoring",
      "C. diff: contact precautions — do not miss infectious cause of diarrhea",
    ],
    mustKnowFacts: ["Coffee-ground emesis suggests upper GI bleed"],
    pearls: ["Lactulose titrated to 2–3 soft stools/day"],
    pitfalls: ["Feeding patient with suspected obstruction"],
    practiceTopicSlug: "med-surg",
  },
  {
    slug: "heme-oncology",
    category: "Physiological Adaptation",
    title: "Hematology & Oncology Emergencies",
    overview: "Anemia, thrombocytopenia, leukemia signs, sickle cell crisis, and transfusion basics.",
    summary:
      "Heme/onc NCLEX items include anemia symptoms (fatigue, tachycardia, pallor), thrombocytopenia bleeding precautions (no IM, soft toothbrush), and sickle cell vaso-occlusive crisis (pain, hydration, O₂).\n\nTumor lysis syndrome after chemo: rising K⁺, uric acid, phosphate — hydration, allopurinol/rasburicase per order. DIC: prolonged bleeding with clots — monitor labs and bleeding.",
    keyConcepts: [
      "Thrombocytopenia: bleeding precautions, platelet transfusion per order",
      "Sickle cell crisis: pain management, hydration, O₂ if hypoxic",
      "Tumor lysis: hydrate, monitor electrolytes after chemo initiation",
      "Neutropenia + fever = emergency",
      "Anemia: assess perfusion before attributing fatigue to anemia alone",
    ],
    mustKnowFacts: ["No aspirin/NSAIDs in thrombocytopenia unless ordered — bleeding risk"],
    pearls: ["Sickle cell: avoid dehydration and extreme temperature"],
    pitfalls: ["IM injection with platelets <50,000 unless emergent"],
    practiceTopicSlug: "med-surg",
  },
  {
    slug: "burns-trauma",
    category: "Physiological Adaptation",
    title: "Burns & Trauma Resuscitation",
    overview: "Burn depth, fluid resuscitation monitoring, compartment syndrome, and fracture priorities.",
    summary:
      "Burn nursing uses TBSA (rule of nines), fluid resuscitation formulas (Parkland), and urine output goals (~0.5–1 mL/kg/hr). Full-thickness burns may need escharotomy. Inhalation injury: suspect with facial burns and soot — monitor airway.\n\nCompartment syndrome: pain out of proportion, pallor, pulselessness, paresthesia — emergency fasciotomy. Long bone fracture: neurovascular checks distal to injury.",
    keyConcepts: [
      "Rule of nines for TBSA in adults",
      "Parkland formula guides fluid — monitor UOP",
      "Inhalation injury: early airway concern — intubation may be needed",
      "Compartment syndrome 6 P's — notify immediately",
      "Spinal precautions until cleared after trauma",
    ],
    mustKnowFacts: ["Cool thermal burn briefly — do not ice — then cover with clean dry dressing"],
    pearls: ["Circumferential burn may compromise circulation — monitor distal pulses"],
    pitfalls: ["Underestimating fluid needs in large TBSA burns"],
    practiceTopicSlug: "med-surg",
  },
  {
    slug: "anticoagulation-nursing",
    category: "Pharmacological Therapies",
    title: "Anticoagulation Nursing Care",
    overview: "Warfarin INR, heparin/LMWH monitoring, DOAC safety, HIT recognition, and reversal basics.",
    summary:
      "Anticoagulant nursing centers on bleeding surveillance and appropriate monitoring. Warfarin: INR goal typically 2–3; teach consistent vitamin K intake and bleeding signs. Heparin: aPTT and platelets for HIT. DOACs: renal dosing, no routine INR, bleeding precautions.\n\nProtamine reverses heparin — not warfarin. Vitamin K/PCC for major warfarin bleeding per order.",
    keyConcepts: [
      "Warfarin: INR monitoring, bleeding teaching, drug/food interactions",
      "Heparin/LMWH: aPTT or anti-Xa; platelet drop → HIT suspicion",
      "DOACs: apixaban, rivaroxaban, dabigatran — renal function matters",
      "Fall precautions for all anticoagulated patients",
      "Reversal agents are drug-specific",
    ],
    mustKnowFacts: ["HIT: stop heparin, do not re-expose"],
    pearls: ["No IM injections when avoidable on anticoagulation"],
    pitfalls: ["Using protamine for warfarin overdose"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "cardiovascular-meds-nursing",
    category: "Pharmacological Therapies",
    title: "Cardiovascular Medications",
    overview: "Antihypertensives, nitrates, diuretics, digoxin, statins — nursing checks before and after administration.",
    summary:
      "CV pharm NCLEX focuses on nursing surveillance: BP before nitroglycerin, apical pulse before digoxin, potassium with diuretics, and never stopping beta-blockers abruptly post-MI.\n\nACE inhibitors may cause cough and hyperkalemia. Statins: muscle pain and rhabdomyolysis risk. Diuretics: orthostatic hypotension and electrolyte loss.",
    keyConcepts: [
      "Nitroglycerin: check BP; hold if SBP <90",
      "Digoxin: apical pulse 1 min; hold HR <60 per order",
      "Beta-blockers: hold low HR/BP; taper — no abrupt stop",
      "ACE/ARB: monitor K⁺ and creatinine",
      "Loop diuretics: K⁺ loss, daily weights in HF",
    ],
    mustKnowFacts: ["Hypokalemia increases digoxin toxicity"],
    pearls: ["Right-sided HF: cautious diuresis"],
    pitfalls: ["Giving nitroglycerin without BP check"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "antibiotics-nursing",
    category: "Pharmacological Therapies",
    title: "Anti-infectives & Stewardship",
    overview: "Culture timing, C. diff precautions, vancomycin monitoring, and allergy assessment.",
    summary:
      "Anti-infective nursing prioritizes cultures before antibiotics when feasible without delaying sepsis care, monitoring for C. diff on broad-spectrum agents, and slow vancomycin infusion to prevent red man syndrome.\n\nFinish prescribed courses. Contact precautions and hand washing for C. diff — alcohol gel insufficient for spores.",
    keyConcepts: [
      "Blood cultures before antibiotics in sepsis when possible",
      "C. diff: contact precautions, oral vancomycin/fidaxomicin for CDI",
      "Vancomycin: trough levels, slow infusion",
      "Assess penicillin allergy type before charting",
      "Monitor renal function with aminoglycosides and vancomycin",
    ],
    mustKnowFacts: ["Stop/slow vancomycin for red man syndrome during infusion"],
    pearls: ["Teach patients not to share antibiotics"],
    pitfalls: ["Alcohol hand gel only after C. diff care"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "psychotropics-nursing",
    category: "Pharmacological Therapies",
    title: "Psychotropic Medications",
    overview: "SSRIs, antipsychotics, lithium, benzodiazepines, MAOIs — adverse effects and monitoring.",
    summary:
      "Psychotropic nursing links meds to monitoring: serotonin syndrome with serotonergic combos, EPS with antipsychotics, lithium toxicity signs, MAOI tyramine diet, and benzodiazepine respiratory depression with opioids.\n\nClozapine requires ANC monitoring. Never stop lithium abruptly. Black box on antidepressants requires monitoring not withholding without plan.",
    keyConcepts: [
      "Serotonin syndrome: agitation, hyperthermia, clonus — stop serotonergic drugs",
      "EPS: dystonia, akathisia — report early",
      "Lithium: tremor, polyuria — toxicity: ataxia, confusion",
      "MAOI: tyramine hypertensive crisis",
      "BZD + opioid = respiratory depression",
    ],
    mustKnowFacts: ["Lithium toxicity worsened by dehydration and NSAIDs"],
    pearls: ["Therapeutic communication before teaching if acutely suicidal"],
    pitfalls: ["Tyramine foods on MAOI without teaching"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "drug-interactions-antidotes",
    category: "Pharmacological Therapies",
    title: "Interactions, Overdose & Antidotes",
    overview: "Naloxone, vitamin K, Digibind, NAC, protamine — matching antidote to toxin on NCLEX.",
    summary:
      "High-acuity pharm items test antidote matching and first actions. Opioid overdose: naloxone titrated to respirations. Acetaminophen overdose: N-acetylcysteine time-sensitive. Digoxin toxicity with life-threatening arrhythmia: Digibind.\n\nSerotonin syndrome: stop offending agents. Heparin overdose: protamine.",
    keyConcepts: [
      "Opioid: naloxone + airway",
      "Warfarin major bleed: vitamin K ± PCC/FFP",
      "Digoxin life-threatening: Digibind",
      "Acetaminophen: NAC — poison control",
      "Heparin: protamine sulfate",
    ],
    mustKnowFacts: ["Titrate naloxone — avoid huge bolus withdrawal in dependent patients"],
    pearls: ["Naloxone shorter duration than many opioids — re-sedation risk"],
    pitfalls: ["Delaying NAC for acetaminophen waiting for liver failure signs"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "iv-fluids-blood-products",
    category: "Pharmacological Therapies",
    title: "IV Fluids & Blood Products",
    overview: "Crystalloids vs colloids nursing judgment, transfusion reactions, and KCl safety.",
    summary:
      "IV fluid nursing matches type to need — isotonic crystalloids for hypovolemia; caution in HF/renal failure. Transfusion: two-nurse verify, vitals q15 min first hour, stop for any reaction.\n\nNever IV push potassium. Febrile/hemolytic transfusion reactions: stop blood first, keep line open with NS.",
    keyConcepts: [
      "NS/LR for volume expansion — monitor overload in HF",
      "Transfusion reaction: stop blood first",
      "Two-nurse ID and product verification",
      "KCl: never IV push; max rate/concentration per policy",
      "PRBCs for symptomatic anemia per order",
    ],
    mustKnowFacts: ["First action transfusion reaction = stop the transfusion"],
    pearls: ["Stay with patient first 15 minutes of transfusion"],
    pitfalls: ["Continuing transfusion with acute hemolytic symptoms"],
    practiceTopicSlug: "pharmacology-nursing",
  },
  {
    slug: "sata-mastery",
    category: "NCLEX NGN Strategy",
    title: "SATA Mastery & Partial Credit",
    overview: "Select-all-that-apply strategy — independent true/false evaluation per option.",
    summary:
      "SATA items require evaluating each option independently — not as a group. Read stem constraints carefully: ALL appropriate vs FIRST action changes approach.\n\nMultiple correct answers are expected. Use ABC and scope of practice to eliminate clearly wrong options. Avoid under-selecting from doubt.",
    keyConcepts: [
      "Each option = true/false standalone",
      "Read FIRST/MOST/ALL keywords",
      "Multiple correct is normal",
      "Eliminate scope violations quickly",
      "Do not cluster-guess related sounding options",
    ],
    mustKnowFacts: ["SATA partial credit — do not leave option unchecked if true"],
    pearls: ["Cover options, predict answers, then compare"],
    pitfalls: ["Applying FIRST prioritization to ALL-that-apply stems incorrectly"],
    practiceTopicSlug: "management-of-care",
  },
  {
    slug: "bow-tie-ngn",
    category: "NCLEX NGN Strategy",
    title: "Bow-Tie & Trend Analysis",
    overview: "CJMM bow-tie items — actions, conditions to monitor, and complications for one clinical problem.",
    summary:
      "Bow-tie NGN items anchor a central clinical problem with actions on one side and monitoring/complications on the other. Trend analysis compares labs/vitals over time — direction matters more than a single snapshot.\n\nUse Clinical Judgment Measurement Model: recognize cues, analyze, prioritize hypotheses, generate solutions, evaluate outcomes.",
    keyConcepts: [
      "Center = focal problem (sepsis, DKA, PPH)",
      "Left wing = nursing actions",
      "Right wing = monitor + complications",
      "Trend worsening triggers escalation",
      "CJMM structures complex judgment",
    ],
    mustKnowFacts: ["Re-prioritize when trend shows decompensation"],
    pearls: ["UOP trend is key renal perfusion indicator post-op"],
    pitfalls: ["Picking actions unrelated to center problem"],
    practiceTopicSlug: "physiological-adaptation",
  },
  {
    slug: "case-study-ngn",
    category: "NCLEX NGN Strategy",
    title: "Unfolding Case Study Sets",
    overview: "Six-item NGN case studies — consistency, escalation, and evaluation across one patient timeline.",
    summary:
      "Unfolding case studies present six linked items on one patient. Preview allergies, isolation, and baseline status before item 1. Later items assume earlier actions were taken.\n\nWhen new abnormal data appear mid-case, re-prioritize — do not anchor on item 1 if patient decompensated. Final items often test evaluation and discharge teaching.",
    keyConcepts: [
      "Read full case header first",
      "Track allergies, isolation, devices",
      "Consistency across items unless status changes",
      "Escalate when vitals/labs worsen",
      "Evaluation items test reassessment after intervention",
    ],
    mustKnowFacts: ["Worsening vitals in item 5 override stable plan from item 2"],
    pearls: ["Mental note: what changed since last item?"],
    pitfalls: ["Treating each item as unrelated MCQ"],
    practiceTopicSlug: "management-of-care",
  },
]);
