import { defineReviewModuleTopic } from "@/lib/edtech/review-modules/build-topic";
import {
  ACS_MODULE,
  ANTIBIOTICS_STEWARDSHIP_MODULE,
  ANTICOAGULATION_MODULE,
  DELEGATION_MODULE,
  DIABETES_PHARMACOTHERAPY_MODULE,
  HEART_FAILURE_MODULE,
  INFECTION_CONTROL_NCLEX_MODULE,
  INFECTIOUS_DISEASE_USMLE_MODULE,
  SEPSIS_MODULE,
  CONTROLLED_SUBSTANCES_MODULE,
  CONTROLLED_SUBSTANCES_PANCE_MODULE,
  COPD_EXACERBATION_MODULE,
  AANP_ASSESS_MODULE,
  AANP_DIAGNOSE_MODULE,
  AANP_PLAN_MODULE,
  AANP_EVALUATE_MODULE,
  AANP_GERIATRICS_MODULE,
  AANP_PEDIATRICS_MODULE,
  MSK_REHABILITATION_MODULE,
  STROKE_REHABILITATION_MODULE,
  CARDIOPULMONARY_REHAB_MODULE,
  THERAPEUTIC_MODALITIES_NPTE_MODULE,
  NPTE_VESTIBULAR_BALANCE_MODULE,
  NPTE_PEDS_GERIATRICS_MODULE,
  NPTE_SAFETY_RED_FLAGS_MODULE,
  ENDOCRINE_EMERGENCIES_MODULE,
  RENAL_ELECTROLYTES_MODULE,
  STROKE_NEURO_MODULE,
  PATHOLOGY_NEOPLASIA_STEP1_MODULE,
  PHARMACOLOGY_MOA_STEP1_MODULE,
  BIOSTATISTICS_USMLE_STEP3_MODULE,
  CCS_CASE_MANAGEMENT_USMLE_MODULE,
  MEDICAL_ETHICS_USMLE_STEP3_MODULE,
  FLUIDS_ELECTROLYTES_NCLEX_MODULE,
  LEGAL_ETHICAL_NCLEX_MODULE,
  MATERNAL_NEWBORN_MODULE,
  PEDIATRICS_NCLEX_MODULE,
  PHARM_HIGH_ALERT_MODULE,
  PRIORITIZATION_WORKSHOP_MODULE,
  PSYCH_THERAPEUTIC_MODULE,
  CARDIOVASCULAR_NCLEX_MODULE,
  RESPIRATORY_NCLEX_MODULE,
  DIABETES_NCLEX_MODULE,
  RENAL_NCLEX_MODULE,
  NEUROLOGIC_NCLEX_MODULE,
  PAIN_OPIOIDS_NCLEX_MODULE,
  ANTICOAGULATION_NCLEX_MODULE,
  ANTIBIOTICS_NCLEX_MODULE,
  CARDIOVASCULAR_MEDS_NCLEX_MODULE,
  DOSAGE_CALC_NCLEX_MODULE,
  DRUG_INTERACTIONS_ANTIDOTES_NCLEX_MODULE,
  IV_FLUIDS_BLOOD_NCLEX_MODULE,
  PSYCHOTROPICS_NCLEX_MODULE,
  SATA_MASTERY_NCLEX_MODULE,
  BOW_TIE_NCLEX_MODULE,
  CASE_STUDY_NCLEX_MODULE,
  DISASTER_TRIAGE_NCLEX_MODULE,
  CRITICAL_LABS_NCLEX_MODULE,
  IMMUNIZATION_NCLEX_MODULE,
  PRENATAL_LABOR_NCLEX_MODULE,
  GI_EMERGENCIES_NCLEX_MODULE,
  NAPLEX_CALCULATIONS_MODULE,
  NAPLEX_ASTHMA_COPD_MODULE,
  NAPLEX_PSYCHOTROPICS_MODULE,
  NAPLEX_RENAL_CKD_MODULE,
  NAPLEX_TOXICOLOGY_MODULE,
  NAPLEX_GERIATRICS_MODULE,
  NAPLEX_TDM_MODULE,
  NAPLEX_GI_PHARMACOTHERAPY_MODULE,
  PHYSIOLOGY_SYSTEMS_STEP1_MODULE,
  BIOCHEMISTRY_METABOLISM_STEP1_MODULE,
  MICROBIOLOGY_IMMUNOLOGY_STEP1_MODULE,
  ANATOMY_EMBRYOLOGY_STEP1_MODULE,
  CARDIOVASCULAR_USMLE_MODULE,
  PULMONARY_USMLE_MODULE,
  GASTROENTEROLOGY_USMLE_MODULE,
  HEMATOLOGY_ONCOLOGY_USMLE_MODULE,
  RHEUMATOLOGY_USMLE_MODULE,
  OBSTETRICS_USMLE_MODULE,
  PEDIATRICS_USMLE_MODULE,
  PSYCHIATRY_USMLE_MODULE,
  EMERGENCY_TOXICOLOGY_USMLE_MODULE,
  DERMATOLOGY_ALLERGIC_USMLE_MODULE,
  ETHICS_BIOSTATS_USMLE_MODULE,
  PHARMACEUTICAL_ADS_ABSTRACTS_STEP3_MODULE,
  NEXT_BEST_STEP_STEP3_MODULE,
  CCS_MONITORING_ESCALATION_STEP3_MODULE,
  AMBULATORY_CHRONIC_CARE_STEP3_MODULE,
} from "@/lib/edtech/review-modules/content";
import type { HighYieldTopic } from "@/types/edtech";

/** Flagship textbook-style review modules — one or two per exam, sorted first. */
export const REVIEW_MODULE_TOPICS: HighYieldTopic[] = [
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "heart-failure-gdmt",
    title: "Heart Failure: Guideline-Directed Medical Therapy",
    overview:
      "Master the four pillars of HFrEF therapy, diuretic strategy, and when to start each agent — a core NAPLEX pharmacotherapy module.",
    practiceTopicSlug: "cardiovascular-rx",
    reviewModule: HEART_FAILURE_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "anticoagulation-reversal",
    title: "Anticoagulation & Reversal",
    overview:
      "Select warfarin vs DOACs, prevent HIT catastrophes, and match the correct reversal agent to the anticoagulant on board.",
    practiceTopicSlug: "pharmacology",
    reviewModule: ANTICOAGULATION_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "insulin-diabetes-management",
    title: "Diabetes Pharmacotherapy",
    overview:
      "Insulin kinetics, metformin renal rules, SGLT2i/GLP-1 agents, hypoglycemia treatment, sick-day management, and U-500 safety for NAPLEX.",
    practiceTopicSlug: "endocrine-rx",
    reviewModule: DIABETES_PHARMACOTHERAPY_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "antibiotics-stewardship",
    title: "Antibiotics & Antimicrobial Stewardship",
    overview:
      "Spectrum ladders, MRSA/Pseudomonas coverage, CAP and UTI regimens, C. diff therapy, HIV prophylaxis, and stewardship pearls for NAPLEX.",
    practiceTopicSlug: "infectious-disease-rx",
    reviewModule: ANTIBIOTICS_STEWARDSHIP_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "controlled-substances",
    title: "Controlled Substances & DEA Regulations",
    overview:
      "CSA schedules, CII refill rules, recordkeeping, transfers, and partial fills — core pharmacy law for NAPLEX and jurisprudence review.",
    practiceTopicSlug: "pharmacy-law",
    reviewModule: CONTROLLED_SUBSTANCES_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "calculations-workshop",
    title: "Pharmaceutical Calculations Workshop",
    overview:
      "IV drip rates, D/H×Q, alligation, CrCl, reconstitution, and high-alert concentration checks — board-style math mastery.",
    practiceTopicSlug: "compounding-calculations",
    reviewModule: NAPLEX_CALCULATIONS_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "asthma-copd-inhalers",
    title: "Asthma, COPD & Inhaler Therapy",
    overview:
      "GINA/GOLD step therapy, inhaler device counseling, CAP regimens, and COPD exacerbation management for NAPLEX.",
    practiceTopicSlug: "pharmacology",
    reviewModule: NAPLEX_ASTHMA_COPD_MODULE,
    sortOrder: 6,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "psychotropics-monitoring",
    title: "Psychotropics & CNS Pharmacotherapy",
    overview:
      "Antidepressant selection, antipsychotic monitoring, lithium/valproate levels, serotonin syndrome, and clozapine REMS.",
    practiceTopicSlug: "cns-rx",
    reviewModule: NAPLEX_PSYCHOTROPICS_MODULE,
    sortOrder: 7,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "renal-ckd-pharmacotherapy",
    title: "Renal Disease & CKD Pharmacotherapy",
    overview:
      "CrCl dosing, DOAC adjustments, dialysis supplemental dosing, CKD complications, and ACEi/ARB in proteinuric disease.",
    practiceTopicSlug: "compounding-calculations",
    reviewModule: NAPLEX_RENAL_CKD_MODULE,
    sortOrder: 8,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "toxicology-antidotes",
    title: "Toxicology & Antidote Management",
    overview:
      "Acetaminophen/NAC, opioid reversal, digoxin Fab, toxic alcohols, and high-yield antidote matching for NAPLEX.",
    practiceTopicSlug: "pharmacology",
    reviewModule: NAPLEX_TOXICOLOGY_MODULE,
    sortOrder: 9,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "geriatrics-beers",
    title: "Geriatrics & Beers Criteria",
    overview:
      "Potentially inappropriate medications in older adults, anticholinergic burden, deprescribing, and MTM for polypharmacy.",
    practiceTopicSlug: "patient-counseling",
    reviewModule: NAPLEX_GERIATRICS_MODULE,
    sortOrder: 10,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "tdm-monitoring",
    title: "Therapeutic Drug Monitoring",
    overview:
      "Vancomycin AUC/MIC, aminoglycoside nomograms, digoxin/lithium/phenytoin levels, and methotrexate weekly safety.",
    practiceTopicSlug: "pharmacology",
    reviewModule: NAPLEX_TDM_MODULE,
    sortOrder: 11,
  }),
  defineReviewModuleTopic({
    examSlug: "naplex",
    slug: "gi-pharmacotherapy",
    title: "GI Pharmacotherapy & Liver Disease",
    overview:
      "GERD/PPI counseling, H. pylori regimens, IBD biologics, hepatic encephalopathy, ascites, and opioid-induced constipation.",
    practiceTopicSlug: "pharmacology",
    reviewModule: NAPLEX_GI_PHARMACOTHERAPY_MODULE,
    sortOrder: 12,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "infection-control",
    title: "Infection Control & PPE",
    overview:
      "Standard and transmission-based precautions — the foundation of safe nursing practice on every unit.",
    practiceTopicSlug: "safety-infection",
    reviewModule: INFECTION_CONTROL_NCLEX_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "sepsis-shock",
    title: "Sepsis & Shock Prioritization",
    overview:
      "Recognize sepsis early, prioritize the sepsis bundle, and distinguish shock types for safe NCLEX clinical judgment.",
    practiceTopicSlug: "physiological-adaptation",
    reviewModule: SEPSIS_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "delegation",
    title: "Delegation & Scope of Practice",
    overview:
      "Assign tasks safely using the five rights while the RN retains accountability — a core NCLEX management module.",
    practiceTopicSlug: "management-of-care",
    reviewModule: DELEGATION_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "prioritization",
    title: "Prioritization & Triage Workshop",
    overview:
      "Master see-first triage with ABC framing, assignment parsing, and NCLEX trap elimination.",
    practiceTopicSlug: "management-of-care",
    reviewModule: PRIORITIZATION_WORKSHOP_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "postpartum",
    title: "Maternal-Newborn Emergencies",
    overview:
      "PPH, preeclampsia, FHR patterns, and newborn transition — high-acuity L&D judgment.",
    practiceTopicSlug: "maternal-child",
    reviewModule: MATERNAL_NEWBORN_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "medication-safety",
    title: "Pharm: High-Alert & Calculations",
    overview:
      "Insulin, heparin, opioids, electrolyte replacements, and safe dosage calculation.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: PHARM_HIGH_ALERT_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "psychiatric",
    title: "Psych & Therapeutic Communication",
    overview:
      "Suicide precautions, de-escalation, therapeutic responses, and psych medication monitoring.",
    practiceTopicSlug: "psychosocial",
    reviewModule: PSYCH_THERAPEUTIC_MODULE,
    sortOrder: 6,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "electrolytes",
    title: "Fluids, Electrolytes & Renal",
    overview:
      "K⁺/Na⁺/Ca²⁺/Mg²⁺ patterns, acid-base context, and safe replacement nursing actions.",
    practiceTopicSlug: "physiological-adaptation",
    reviewModule: FLUIDS_ELECTROLYTES_NCLEX_MODULE,
    sortOrder: 7,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "pediatrics",
    title: "Pediatric Growth, Safety & Immunizations",
    overview:
      "Age-specific vitals, dehydration, immunization rules, and mandatory reporting.",
    practiceTopicSlug: "pediatrics-nursing",
    reviewModule: PEDIATRICS_NCLEX_MODULE,
    sortOrder: 8,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "legal-ethical",
    title: "Legal, Ethical & Advocacy",
    overview:
      "Informed consent, mandatory reporting, HIPAA, and refusing unsafe assignments.",
    practiceTopicSlug: "management-of-care",
    reviewModule: LEGAL_ETHICAL_NCLEX_MODULE,
    sortOrder: 9,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "cardiovascular",
    title: "Cardiovascular Emergencies",
    overview:
      "ACS protocols, heart failure monitoring, anticoagulant safety, and dysrhythmia nursing priorities.",
    practiceTopicSlug: "med-surg",
    reviewModule: CARDIOVASCULAR_NCLEX_MODULE,
    sortOrder: 10,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "respiratory",
    title: "Respiratory & Oxygen Therapy",
    overview:
      "COPD O₂ targets, asthma escalation, PE suspicion, chest tubes, and post-op lung expansion.",
    practiceTopicSlug: "med-surg",
    reviewModule: RESPIRATORY_NCLEX_MODULE,
    sortOrder: 11,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "diabetes",
    title: "Diabetes Management",
    overview:
      "Hypoglycemia 15-15 rule, DKA/HHS sequencing, insulin safety, sick-day rules, and foot care.",
    practiceTopicSlug: "med-surg",
    reviewModule: DIABETES_NCLEX_MODULE,
    sortOrder: 12,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "renal",
    title: "Renal & Fluid Balance",
    overview:
      "AKI recognition, dialysis access care, daily weights, hyperkalemia response, and contrast precautions.",
    practiceTopicSlug: "med-surg",
    reviewModule: RENAL_NCLEX_MODULE,
    sortOrder: 13,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "neurologic",
    title: "Neurologic Assessment & Stroke",
    overview:
      "Stroke timelines, seizure safety, increased ICP, spinal precautions, and autonomic dysreflexia.",
    practiceTopicSlug: "med-surg",
    reviewModule: NEUROLOGIC_NCLEX_MODULE,
    sortOrder: 14,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "pain-opioids",
    title: "Pain Management & Opioid Safety",
    overview:
      "Multimodal analgesia, PCA rules, respiratory depression response, naloxone, and bowel prophylaxis.",
    practiceTopicSlug: "basic-care-comfort",
    reviewModule: PAIN_OPIOIDS_NCLEX_MODULE,
    sortOrder: 15,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "anticoagulation-nursing",
    title: "Anticoagulation Nursing Care",
    overview: "Warfarin INR, heparin/LMWH, DOAC safety, HIT, and reversal nursing priorities.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: ANTICOAGULATION_NCLEX_MODULE,
    sortOrder: 16,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "cardiovascular-meds-nursing",
    title: "Cardiovascular Medications",
    overview: "Nitro BP checks, digoxin pulse, diuretic K⁺, beta-blocker hold rules, and statin monitoring.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: CARDIOVASCULAR_MEDS_NCLEX_MODULE,
    sortOrder: 17,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "antibiotics-nursing",
    title: "Anti-infectives & Stewardship",
    overview: "Culture timing, C. diff precautions, vancomycin infusion, and allergy assessment.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: ANTIBIOTICS_NCLEX_MODULE,
    sortOrder: 18,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "psychotropics-nursing",
    title: "Psychotropic Medications",
    overview: "SSRIs, antipsychotics, lithium, benzodiazepines, MAOIs — monitoring and adverse effects.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: PSYCHOTROPICS_NCLEX_MODULE,
    sortOrder: 19,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "drug-interactions-antidotes",
    title: "Interactions, Overdose & Antidotes",
    overview: "Naloxone, vitamin K, Digibind, NAC, protamine — antidote matching for NCLEX.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: DRUG_INTERACTIONS_ANTIDOTES_NCLEX_MODULE,
    sortOrder: 20,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "iv-fluids-blood-products",
    title: "IV Fluids & Blood Products",
    overview: "Crystalloid selection, transfusion reactions, two-nurse verify, and KCl safety.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: IV_FLUIDS_BLOOD_NCLEX_MODULE,
    sortOrder: 21,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "dosage-calculations",
    title: "Dosage Calculations & IV Drip Rates",
    overview: "Weight-based dosing, D/H×Q, mL/hr, reconstitution, and insulin/heparin concentration checks.",
    practiceTopicSlug: "pharmacology-nursing",
    reviewModule: DOSAGE_CALC_NCLEX_MODULE,
    sortOrder: 22,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "disaster-triage",
    title: "Disaster Triage & Mass Casualty",
    overview: "START triage, RPM assessment, and ethical resource allocation during MCIs.",
    practiceTopicSlug: "management-of-care",
    reviewModule: DISASTER_TRIAGE_NCLEX_MODULE,
    sortOrder: 23,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "critical-lab-values",
    title: "Critical Lab Values & Diagnostics",
    overview: "K⁺, Na⁺, glucose, troponin, INR, ANC — notify, monitor, and treat per order.",
    practiceTopicSlug: "reduction-risk",
    reviewModule: CRITICAL_LABS_NCLEX_MODULE,
    sortOrder: 24,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "immunization-schedules",
    title: "Immunization Schedules & Contraindications",
    overview: "Live vs inactivated vaccines, pregnancy rules, CDC milestones, and PEP timelines.",
    practiceTopicSlug: "health-promotion",
    reviewModule: IMMUNIZATION_NCLEX_MODULE,
    sortOrder: 25,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "prenatal-labor-monitoring",
    title: "Prenatal Care & Fetal Monitoring",
    overview: "Preeclampsia screening, FHR patterns, and intrapartum deceleration actions.",
    practiceTopicSlug: "maternal-child",
    reviewModule: PRENATAL_LABOR_NCLEX_MODULE,
    sortOrder: 26,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "gi-emergencies",
    title: "GI Bleed, Pancreatitis & Liver Failure",
    overview: "GI hemorrhage, NG decompression, pancreatitis NPO/fluids, hepatic encephalopathy.",
    practiceTopicSlug: "med-surg",
    reviewModule: GI_EMERGENCIES_NCLEX_MODULE,
    sortOrder: 27,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "sata-mastery",
    title: "SATA Mastery & Partial Credit",
    overview: "Select-all-that-apply — independent true/false evaluation per option.",
    practiceTopicSlug: "management-of-care",
    reviewModule: SATA_MASTERY_NCLEX_MODULE,
    sortOrder: 28,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "bow-tie-ngn",
    title: "Bow-Tie & Trend Analysis",
    overview: "CJMM bow-tie items — actions, monitoring, and complications for one clinical problem.",
    practiceTopicSlug: "physiological-adaptation",
    reviewModule: BOW_TIE_NCLEX_MODULE,
    sortOrder: 29,
  }),
  defineReviewModuleTopic({
    examSlug: "nclex",
    slug: "case-study-ngn",
    title: "Unfolding Case Study Sets",
    overview: "Six-item NGN case studies — consistency, escalation, and evaluation.",
    practiceTopicSlug: "management-of-care",
    reviewModule: CASE_STUDY_NCLEX_MODULE,
    sortOrder: 30,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "acute-coronary-syndrome",
    title: "Acute Coronary Syndrome Management",
    overview:
      "From ECG to reperfusion: STEMI vs NSTEMI pathways, antithrombotics, and complication recognition for Step 2 CK.",
    practiceTopicSlug: "cardiology",
    reviewModule: ACS_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "infectious-disease",
    title: "Infectious Disease: Sepsis, HIV & Antimicrobials",
    overview:
      "CAP and meningitis empiric regimens, MRSA selection, the daptomycin pneumonia trap, C. diff therapy, HIV OI prophylaxis, vancomycin AUC monitoring, and febrile neutropenia for Step 2 CK.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: INFECTIOUS_DISEASE_USMLE_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "endocrine-dm",
    title: "Endocrine Emergencies: DKA, HHS, Thyroid & Adrenal",
    overview:
      "DKA/HHS sequencing, thyroid storm and myxedema coma, and adrenal crisis — the time-critical 'next best step' endocrine module for Step 2 CK.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: ENDOCRINE_EMERGENCIES_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "renal-electrolytes",
    title: "Renal: AKI, Dialysis & Electrolyte Emergencies",
    overview:
      "AKI categorization (FeNa, BUN:Cr), dialysis indications (AEIOU), and the hyperkalemia and hyponatremia algorithms for Step 2 CK.",
    practiceTopicSlug: "nephrology",
    reviewModule: RENAL_ELECTROLYTES_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "neurology-stroke",
    title: "Neurology: Stroke, SAH & Status Epilepticus",
    overview:
      "Ischemic vs hemorrhagic stroke pathways, subarachnoid hemorrhage workup, and status epilepticus escalation for Step 2 CK.",
    practiceTopicSlug: "neurology",
    reviewModule: STROKE_NEURO_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "pathology-neoplasia",
    title: "Pathology: Inflammation, Neoplasia & Hemodynamics",
    overview:
      "Granulomatous inflammation, malignant transformation hallmarks, and shock/edema mechanisms for Step 1.",
    practiceTopicSlug: "pathology",
    reviewModule: PATHOLOGY_NEOPLASIA_STEP1_MODULE,
    sortOrder: 10,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "pharmacology-moa",
    title: "Pharmacology: MOA, PK & Autonomic Drugs",
    overview:
      "Receptor pharmacology, CYP interactions, autonomic toxidromes, and classic antidote pairings for Step 1.",
    practiceTopicSlug: "pharmacology",
    reviewModule: PHARMACOLOGY_MOA_STEP1_MODULE,
    sortOrder: 11,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "biostatistics-epidemiology",
    title: "Biostatistics & Epidemiology",
    overview:
      "Sensitivity, NNT, bias, and trial appraisal for Step 3 abstract and drug-ad items.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: BIOSTATISTICS_USMLE_STEP3_MODULE,
    sortOrder: 20,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "medical-ethics-legal",
    title: "Medical Ethics & Legal Medicine",
    overview:
      "Capacity, consent, confidentiality, and surrogate decision-making for Step 3.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: MEDICAL_ETHICS_USMLE_STEP3_MODULE,
    sortOrder: 21,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "ccs-case-management",
    title: "CCS Case Management & Monitoring",
    overview:
      "Stabilize → diagnose → treat → monitor loops for Step 3 CCS-style items.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: CCS_CASE_MANAGEMENT_USMLE_MODULE,
    sortOrder: 22,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "pharmaceutical-ads-abstracts",
    title: "Pharmaceutical Ads & Medical Abstracts",
    overview:
      "Critically appraise drug advertisements and journal abstracts — NNT, surrogate endpoints, and study design traps for Step 3.",
    practiceTopicSlug: "pharmacology",
    reviewModule: PHARMACEUTICAL_ADS_ABSTRACTS_STEP3_MODULE,
    sortOrder: 23,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "next-best-step",
    title: "Next Best Step — Step 3 Decision Framework",
    overview:
      "Prioritize the single immediate action in management vignettes — stabilize first, then diagnose and treat.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: NEXT_BEST_STEP_STEP3_MODULE,
    sortOrder: 24,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "ccs-monitoring-escalation",
    title: "CCS Monitoring, Escalation & Disposition",
    overview:
      "Timed reassessment, ICU escalation, and safe discharge criteria for Step 3 CCS-style cases.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: CCS_MONITORING_ESCALATION_STEP3_MODULE,
    sortOrder: 25,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "ccs-initial-workup",
    title: "CCS Initial Workup & Stabilization",
    overview:
      "First CCS time block — ABCs, targeted diagnostics, and avoid shotgun ordering.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: CCS_CASE_MANAGEMENT_USMLE_MODULE,
    sortOrder: 26,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "ambulatory-chronic-care",
    title: "Ambulatory Chronic Disease Management",
    overview:
      "Outpatient diabetes, HTN, lipids, prevention, and high-value care for Step 3.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: AMBULATORY_CHRONIC_CARE_STEP3_MODULE,
    sortOrder: 27,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "nnt-arr",
    title: "NNT, ARR & Trial Statistics Deep Dive",
    overview:
      "Calculate and interpret NNT/NNH from trial data — embedded in Step 3 abstract items.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: BIOSTATISTICS_USMLE_STEP3_MODULE,
    sortOrder: 28,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "physiology-systems",
    title: "Physiology: Cardiac, Renal, Respiratory & Acid-Base",
    overview:
      "Pressure-volume loops, nephron segments, V/Q matching, and acid-base interpretation — integrated Step 1 physiology module.",
    practiceTopicSlug: "physiology",
    reviewModule: PHYSIOLOGY_SYSTEMS_STEP1_MODULE,
    sortOrder: 12,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "biochemistry-metabolism",
    title: "Biochemistry: Metabolic Pathways & Nutrition",
    overview:
      "Glycolysis, urea cycle, inborn errors, lysosomal storage, and vitamin deficiencies — mechanism-to-phenotype Step 1 module.",
    practiceTopicSlug: "biochemistry",
    reviewModule: BIOCHEMISTRY_METABOLISM_STEP1_MODULE,
    sortOrder: 13,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "microbiology-immunology",
    title: "Microbiology & Immunology: Bugs, Drugs & Host Defense",
    overview:
      "Gram algorithm, HBV serology, hypersensitivity types, and primary immunodeficiencies — Step 1 micro/immuno module.",
    practiceTopicSlug: "microbiology",
    reviewModule: MICROBIOLOGY_IMMUNOLOGY_STEP1_MODULE,
    sortOrder: 14,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "anatomy-embryology",
    title: "Anatomy & Embryology: Landmarks & Malformations",
    overview:
      "Cranial nerves, inguinal hernias, pharyngeal arches, and congenital defects — spatial Step 1 anatomy module.",
    practiceTopicSlug: "anatomy",
    reviewModule: ANATOMY_EMBRYOLOGY_STEP1_MODULE,
    sortOrder: 15,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "cardiovascular",
    title: "Cardiovascular: ACS, HF & Valvular Disease",
    overview:
      "STEMI pathways, HFrEF GDMT, valvular urgency, tamponade, and arrhythmia essentials — Step 2 CK cardiovascular module.",
    practiceTopicSlug: "cardiology",
    reviewModule: CARDIOVASCULAR_USMLE_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "pulmonary",
    title: "Pulmonary: COPD, Asthma, PE & Pleural Disease",
    overview:
      "COPD exacerbation, BiPAP criteria, PE workup, asthma step-up, and Light criteria — Step 2 CK pulmonary module.",
    practiceTopicSlug: "pulmonology",
    reviewModule: PULMONARY_USMLE_MODULE,
    sortOrder: 6,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "gastroenterology",
    title: "Gastroenterology: GI Bleed, Liver & IBD",
    overview:
      "Variceal bleed protocol, cirrhosis complications, pancreatitis, IBD, and C diff — Step 2 CK GI module.",
    practiceTopicSlug: "gastroenterology",
    reviewModule: GASTROENTEROLOGY_USMLE_MODULE,
    sortOrder: 7,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "hematology-oncology",
    title: "Hematology & Oncology: Anemia, Clotting & Emergencies",
    overview:
      "Anemia workup, TTP vs ITP, APL with ATRA, tumor lysis, and oncologic emergencies — Step 2 CK heme/onc module.",
    practiceTopicSlug: "hematology",
    reviewModule: HEMATOLOGY_ONCOLOGY_USMLE_MODULE,
    sortOrder: 8,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "rheumatology",
    title: "Rheumatology: RA, SLE, Gout & Vasculitis",
    overview:
      "RA vs OA, SLE flares, crystal arthropathies, GCA, and ANCA vasculitis — Step 2 CK rheumatology module.",
    practiceTopicSlug: "rheumatology",
    reviewModule: RHEUMATOLOGY_USMLE_MODULE,
    sortOrder: 9,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "obstetrics",
    title: "Obstetrics: Preeclampsia, Labor & OB Emergencies",
    overview:
      "Hypertensive disorders, third-trimester bleeding, ectopic pregnancy, and postpartum hemorrhage — Step 2 CK OB module.",
    practiceTopicSlug: "obstetrics",
    reviewModule: OBSTETRICS_USMLE_MODULE,
    sortOrder: 10,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "pediatrics",
    title: "Pediatrics: Milestones, Infections & Congenital Disease",
    overview:
      "Febrile infant workup, Kawasaki, bronchiolitis, vaccines, and child abuse red flags — Step 2 CK pediatrics module.",
    practiceTopicSlug: "pediatrics",
    reviewModule: PEDIATRICS_USMLE_MODULE,
    sortOrder: 11,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "psychiatry",
    title: "Psychiatry: Mood, Psychosis & Substance Use",
    overview:
      "Depression, bipolar, schizophrenia, serotonin syndrome vs NMS, and withdrawal — Step 2 CK psychiatry module.",
    practiceTopicSlug: "psychiatry",
    reviewModule: PSYCHIATRY_USMLE_MODULE,
    sortOrder: 12,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "emergency-toxicology",
    title: "Emergency Medicine & Toxicology",
    overview:
      "ATLS, toxidromes, antidote pairing, acetaminophen nomogram, and TCA overdose — Step 2 CK emergency module.",
    practiceTopicSlug: "emergency-medicine",
    reviewModule: EMERGENCY_TOXICOLOGY_USMLE_MODULE,
    sortOrder: 13,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "dermatology-allergic",
    title: "Dermatology & Allergy: Rashes, Anaphylaxis & Drug Eruptions",
    overview:
      "Anaphylaxis protocol, SJS/TEN, cellulitis vs nec fasc, psoriasis, and Lyme — Step 2 CK derm/allergy module.",
    practiceTopicSlug: "dermatology",
    reviewModule: DERMATOLOGY_ALLERGIC_USMLE_MODULE,
    sortOrder: 14,
  }),
  defineReviewModuleTopic({
    examSlug: "usmle",
    slug: "ethics-biostats",
    title: "Ethics & Biostatistics Cross-Cutting",
    overview:
      "Capacity, consent, Tarasoff, NNT/ARR, and study design appraisal — cross-step ethics and biostatistics module.",
    practiceTopicSlug: "internal-medicine",
    reviewModule: ETHICS_BIOSTATS_USMLE_MODULE,
    sortOrder: 24,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "acute-coronary-syndrome",
    title: "Acute Coronary Syndrome Management",
    overview:
      "From ECG to reperfusion: STEMI vs NSTEMI pathways, antithrombotics, and complication recognition for PANCE.",
    practiceTopicSlug: "cardiovascular",
    reviewModule: ACS_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "infectious-disease",
    title: "Infectious Disease: CAP, MRSA & Antimicrobials",
    overview:
      "CAP empiric regimens, MRSA selection, C. diff therapy, and HIV prophylaxis pearls for PANCE pharmacotherapy and clinical intervention tasks.",
    practiceTopicSlug: "infectious-diseases",
    reviewModule: INFECTIOUS_DISEASE_USMLE_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "controlled-substances-pance",
    title: "Controlled Substances & Prescribing Law",
    overview:
      "CSA schedules, CII validity, PDMP/EPCS, opioid risk mitigation, and HIPAA — prescriber-focused jurisprudence for PANCE professional practice items.",
    practiceTopicSlug: "professional-practice",
    reviewModule: CONTROLLED_SUBSTANCES_PANCE_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "insulin-diabetes-management",
    title: "Diabetes Management",
    overview:
      "A1c targets, metformin, insulin, SGLT2i/GLP-1 benefits, DKA, and hypoglycemia — high-yield endocrine pharmacotherapy for PANCE.",
    practiceTopicSlug: "endocrine",
    reviewModule: DIABETES_PHARMACOTHERAPY_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "copd-exacerbation",
    title: "COPD Exacerbation Management",
    overview:
      "Bronchodilators, steroids, antibiotics, oxygen targets, and NIPPV — GOLD-aligned pulmonary care for PANCE.",
    practiceTopicSlug: "pulmonary",
    reviewModule: COPD_EXACERBATION_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "pance",
    slug: "sepsis-shock",
    title: "Sepsis & Shock Management",
    overview:
      "Recognize sepsis early, execute the hour-1 bundle, and distinguish shock types — high-yield for PANCE infectious disease and critical care vignettes.",
    practiceTopicSlug: "infectious-diseases",
    reviewModule: SEPSIS_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "acute-coronary-syndrome",
    title: "Acute Coronary Syndrome Management",
    overview:
      "From ECG to reperfusion: STEMI vs NSTEMI pathways for AANP FNP cardiovascular Plan and Evaluate items.",
    practiceTopicSlug: "cardiovascular",
    reviewModule: ACS_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "infectious-disease",
    title: "Infectious Disease: CAP, MRSA & Antimicrobials",
    overview:
      "CAP empiric regimens, MRSA selection, and antibiotic stewardship for AANP FNP primary care.",
    practiceTopicSlug: "infectious-disease",
    reviewModule: INFECTIOUS_DISEASE_USMLE_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "sepsis-shock",
    title: "Sepsis & Shock Management",
    overview:
      "Recognize sepsis early and execute the hour-1 bundle — high-yield for AANP FNP geriatric and infectious disease vignettes.",
    practiceTopicSlug: "infectious-disease",
    reviewModule: SEPSIS_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "insulin-diabetes-management",
    title: "Diabetes Pharmacotherapy",
    overview:
      "Insulin, metformin, GLP-1/SGLT2 agents, and monitoring for AANP FNP Plan and Evaluate domains.",
    practiceTopicSlug: "endocrine",
    reviewModule: DIABETES_PHARMACOTHERAPY_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-assess-domain",
    title: "Health Assessment & Diagnostics",
    overview:
      "Domain I deep dive — screening, next-best test selection, and lifespan assessment for the AANP FNP exam.",
    practiceTopicSlug: "assess",
    reviewModule: AANP_ASSESS_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-diagnose-domain",
    title: "Diagnosis & Clinical Reasoning",
    overview:
      "Domain II deep dive — differential diagnosis, discriminating findings, and primary diagnosis selection.",
    practiceTopicSlug: "diagnose",
    reviewModule: AANP_DIAGNOSE_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-plan-domain",
    title: "Therapeutics & Care Planning",
    overview:
      "Domain III deep dive — first-line therapy, counseling, prevention, and referrals within NP scope.",
    practiceTopicSlug: "plan",
    reviewModule: AANP_PLAN_MODULE,
    sortOrder: 6,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-evaluate-domain",
    title: "Outcomes & Follow-Up",
    overview:
      "Domain IV deep dive — monitoring response, adverse effects, adherence, and care plan modification.",
    practiceTopicSlug: "evaluate",
    reviewModule: AANP_EVALUATE_MODULE,
    sortOrder: 7,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-geriatrics-high-yield",
    title: "Older Adult Care",
    overview:
      "Beers Criteria, delirium, falls, polypharmacy, and atypical presentations — highest lifespan weight on the exam.",
    practiceTopicSlug: "geriatrics",
    reviewModule: AANP_GERIATRICS_MODULE,
    sortOrder: 8,
  }),
  defineReviewModuleTopic({
    examSlug: "aanp-fnp",
    slug: "aanp-pediatrics-high-yield",
    title: "Pediatric Primary Care",
    overview:
      "Immunizations, febrile infant algorithms, milestones, and adolescent confidentiality.",
    practiceTopicSlug: "pediatrics",
    reviewModule: AANP_PEDIATRICS_MODULE,
    sortOrder: 9,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "msk-rehabilitation",
    title: "Musculoskeletal Rehabilitation",
    overview:
      "Rotator cuff, spine, post-op ortho, manual therapy, and outcome measures — highest-yield MSK domain on NPTE-PT.",
    practiceTopicSlug: "musculoskeletal",
    reviewModule: MSK_REHABILITATION_MODULE,
    sortOrder: 0,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "stroke-rehabilitation",
    title: "Neuromuscular Rehabilitation",
    overview:
      "Stroke, SCI, TBI, Parkinson, gait, and balance — core neuromuscular content for NPTE-PT.",
    practiceTopicSlug: "neuromuscular-nervous",
    reviewModule: STROKE_REHABILITATION_MODULE,
    sortOrder: 1,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "cardiopulmonary-rehab",
    title: "Cardiopulmonary Rehabilitation",
    overview:
      "COPD, CHF, post-MI rehab, oxygen titration, and airway clearance for NPTE-PT.",
    practiceTopicSlug: "cardiovascular-pulmonary",
    reviewModule: CARDIOPULMONARY_REHAB_MODULE,
    sortOrder: 2,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "therapeutic-modalities",
    title: "Therapeutic Modalities",
    overview:
      "Ultrasound, TENS, NMES, cryotherapy, and heat — parameters and contraindications.",
    practiceTopicSlug: "therapeutic-modalities",
    reviewModule: THERAPEUTIC_MODALITIES_NPTE_MODULE,
    sortOrder: 3,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "npte-vestibular-balance",
    title: "Vestibular & Balance Disorders",
    overview:
      "BPPV repositioning, gaze stabilization, and peripheral vs central vertigo — high-yield neuromuscular extension.",
    practiceTopicSlug: "neuromuscular-nervous",
    reviewModule: NPTE_VESTIBULAR_BALANCE_MODULE,
    sortOrder: 4,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "npte-peds-geriatrics",
    title: "Pediatrics & Geriatrics",
    overview:
      "CP, torticollis, falls prevention, frailty, and lifespan modifiers across NPTE-PT systems.",
    practiceTopicSlug: "system-interactions",
    reviewModule: NPTE_PEDS_GERIATRICS_MODULE,
    sortOrder: 5,
  }),
  defineReviewModuleTopic({
    examSlug: "npte-pt",
    slug: "npte-safety-red-flags",
    title: "Safety & Red Flags",
    overview:
      "When to refer, exercise contraindications, infection control, and fall risk — heavily tested cross-cutting content.",
    practiceTopicSlug: "safety-protection",
    reviewModule: NPTE_SAFETY_RED_FLAGS_MODULE,
    sortOrder: 6,
  }),
];

export function mergeReviewModules(topics: HighYieldTopic[], examSlug: HighYieldTopic["examSlug"]): HighYieldTopic[] {
  const modules = REVIEW_MODULE_TOPICS.filter((t) => t.examSlug === examSlug);
  if (modules.length === 0) return topics;

  const bySlug = new Map(topics.map((t) => [t.slug, t]));

  for (const mod of modules) {
    const existing = bySlug.get(mod.slug);
    bySlug.set(
      mod.slug,
      existing
        ? {
            ...existing,
            category: mod.category,
            title: mod.title,
            overview: mod.overview,
            reviewModule: existing.reviewModule ?? mod.reviewModule,
            relatedStructureIds:
              existing.relatedStructureIds?.length
                ? existing.relatedStructureIds
                : mod.relatedStructureIds,
            summary: existing.summary || mod.summary,
            keyConcepts: existing.keyConcepts.length ? existing.keyConcepts : mod.keyConcepts,
            mustKnowFacts: existing.mustKnowFacts.length ? existing.mustKnowFacts : mod.mustKnowFacts,
            pearls: existing.pearls.length ? existing.pearls : mod.pearls,
            pitfalls: existing.pitfalls.length ? existing.pitfalls : mod.pitfalls,
          }
        : mod
    );
  }

  const moduleSlugs = new Set(modules.map((m) => m.slug));
  const ordered = [
    ...modules.map((m) => bySlug.get(m.slug)!),
    ...topics.filter((t) => !moduleSlugs.has(t.slug)),
  ];

  return ordered.map((t, i) => ({ ...t, sortOrder: i + 1 }));
}
