import type { SubjectArea } from "../types";

export const NURSING_SUBJECTS: SubjectArea[] = [
{
      id: "management-of-care",
      label: "Management of Care",
      contentArea: "NCLEX — Safe & Effective Care (Management of Care)",
      textbookRefs: "Open RN Nursing Leadership, NCLEX test plan",
      examHints: "prioritization, delegation, advocacy, informed consent, continuity of care",
      keywords: ["prioritize", "delegate", "advocacy", "assignment", "management"],
      focusPlaceholder: "e.g. Delegation to LPN",
    },
    {
      id: "safety-infection",
      label: "Safety & Infection Control",
      contentArea: "NCLEX — Safety and Infection Control",
      textbookRefs: "Open RN, CDC infection prevention",
      examHints: "standard precautions, isolation, needle safety, fall prevention, restraints",
      keywords: ["infection", "isolation", "precautions", "safety", "fall", "PPE"],
      focusPlaceholder: "e.g. Contact precautions",
    },
    {
      id: "health-promotion",
      label: "Health Promotion",
      contentArea: "NCLEX — Health Promotion & Maintenance",
      textbookRefs: "Open RN Health Promotion",
      examHints: "screening, vaccines, lifestyle, development, aging, teaching",
      keywords: ["health promotion", "screening", "vaccine", "wellness", "education"],
      focusPlaceholder: "e.g. Adult immunizations",
    },
    {
      id: "psychosocial",
      label: "Psychosocial Integrity",
      contentArea: "NCLEX — Psychosocial Integrity",
      textbookRefs: "Open RN Mental Health Nursing",
      examHints: "therapeutic communication, abuse, grief, cultural competence, coping",
      keywords: ["psychosocial", "mental health", "abuse", "communication", "grief"],
      focusPlaceholder: "e.g. Therapeutic communication",
    },
    {
      id: "pharmacology-nursing",
      label: "Pharmacological Therapies",
      contentArea: "NCLEX — Pharmacological & Parenteral Therapies",
      textbookRefs: "Open RN Pharmacology",
      examHints: "medication rights, insulin, anticoagulants, pain meds, adverse reactions",
      keywords: ["medication", "pharmacology", "insulin", "dose", "adverse", "IV"],
      focusPlaceholder: "e.g. Insulin administration",
    },
    {
      id: "basic-care-comfort",
      label: "Basic Care & Comfort",
      contentArea: "NCLEX — Basic Care and Comfort",
      textbookRefs: "Open RN Fundamentals",
      examHints: "nutrition, elimination, sleep, mobility, pain, assistive devices",
      keywords: ["comfort", "nutrition", "elimination", "mobility", "pain", "hygiene"],
      focusPlaceholder: "e.g. Pressure injury prevention",
    },
    {
      id: "reduction-risk",
      label: "Reduction of Risk Potential",
      contentArea: "NCLEX — Reduction of Risk Potential",
      textbookRefs: "Open RN Medical-Surgical",
      examHints: "diagnostic tests, pre/post-op, complications, vital sign trends, labs",
      keywords: ["risk", "diagnostic", "preoperative", "postoperative", "complication"],
      focusPlaceholder: "e.g. Post-op complications",
    },
    {
      id: "physiological-adaptation",
      label: "Physiological Adaptation",
      contentArea: "NCLEX — Physiological Adaptation",
      textbookRefs: "Open RN Med-Surg, pathophysiology OER",
      examHints: "heart failure, shock, respiratory failure, fluid overload, sepsis",
      keywords: ["heart failure", "shock", "sepsis", "respiratory", "fluid", "adaptation"],
      focusPlaceholder: "e.g. Heart failure exacerbation",
    },
    {
      id: "fundamentals",
      label: "Nursing Fundamentals",
      contentArea: "Foundational nursing practice",
      textbookRefs: "Open RN Nursing Fundamentals",
      examHints: "assessment, vital signs, documentation, ethics, care planning",
      keywords: ["fundamentals", "assessment", "vital signs", "documentation", "ethics"],
      focusPlaceholder: "e.g. Head-to-toe assessment",
    },
    {
      id: "med-surg",
      label: "Medical-Surgical Nursing",
      contentArea: "Adult health",
      textbookRefs: "Open RN Medical-Surgical Nursing",
      examHints: "chronic disease, post-op, diabetes, COPD, renal failure, wound care",
      keywords: ["medical-surgical", "postoperative", "chronic", "wound", "diabetes"],
      focusPlaceholder: "e.g. Post-op abdominal surgery",
    },
    {
      id: "maternal-child",
      label: "Maternal & Child Health",
      contentArea: "Maternal-newborn / women's health",
      textbookRefs: "Open RN Maternal-Newborn",
      examHints: "prenatal care, labor stages, postpartum, newborn assessment, contraception",
      keywords: ["maternal", "newborn", "labor", "pregnancy", "postpartum", "lactation"],
      focusPlaceholder: "e.g. Postpartum hemorrhage",
    },
    {
      id: "pediatrics-nursing",
      label: "Pediatric Nursing",
      contentArea: "Child health",
      textbookRefs: "Open RN Pediatrics",
      examHints: "growth charts, immunizations, dehydration, asthma in children, fever",
      keywords: ["pediatric", "child", "immunization", "growth", "dehydration"],
      focusPlaceholder: "e.g. Febrile infant assessment",
    },
];
